### ISSUE TITLE
Failover模式无效果

### ISSUE THREAD

**Issue by ywolf** [smallnest/rpcx#100]
测试发现随机到存活的server即正常，但随机到非存活的server就直接报错退出没有重新选择。

![image](https://cloud.githubusercontent.com/assets/6976516/23788111/1aeca21c-05b0-11e7-9d3f-c7948099c4c3.png)

使用例子测试也是如此

**Comment by smallnest** [comment]
请添加相关的信息：

使用的自带例子名称或者你自己的代码。
测试步骤

**Comment by ywolf** [comment]
client:
https://raw.githubusercontent.com/smallnest/rpcx/master/_examples/multi_server/client_failover.go

server:
https://raw.githubusercontent.com/smallnest/rpcx/master/_examples/multi_server/server.go

还有就是client 多import了个fmt， 少import了log。

步骤：
运行 server
后运行clinet
有时候成功1次退出或者直接报错退出。

**Comment by ywolf** [comment]
抱歉，发现问题了，是我自己二次增加的代码导致的。
