### ISSUE TITLE
show a alert for dangerous actions such as deactiveService

### ISSUE THREAD

**Issue by 1046102779** [smallnest/rpcx#102]
you may use script or rpcx-ui tools to avoid many errors, such as the connection is closed,  the connection is shut down and etc .

shell script for etcd eg:

curl http://127.0.0.1:2379/v2/keys/{projectName}/prod/rpcx/{server}/tcp@127.0.0.1:30005 -XPUT -d value='state=inactive'

thus the client can remove the current invalid connection and it solved many errors

**Comment by smallnest** [comment]
do you mean https://github.com/smallnest/rpcx-ui/blob/master/etcd_service.go#L87?

**Comment by 1046102779** [comment]
https://github.com/smallnest/rpcx-ui/blob/master/etcd_service.go#L65

**Comment by smallnest** [comment]
need a confirm alert before execute those actions?

**Comment by smallnest** [comment]
fixed
