### ISSUE TITLE
Linux-64编译失败 DataDog/zstd 

### ISSUE THREAD

**Issue by ywolf** [smallnest/rpcx#103]
Please answer these questions before submitting your issue. Thanks!
如果您要提交一个关于这个项目的bug, 在提交这个bug之前，请填写下面的信息。谢谢。

### What operating system and processor architecture are you using (`go env`)?
程序运行环境的基本信息，你可以使用`go env`获得。

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\go\test
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build5598534
22=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
```

### What did you do?
测试步骤。
引用了一下包
"github.com/smallnest/rpcx"
"github.com/smallnest/rpcx/clientselector"
"github.com/smallnest/rpcx/codec"
LiteIDE 选择cross-linux64 进行编译

If possible, provide a recipe for reproducing the error.
如果程序可以复现，请提供可以复现bug的方法。

A complete runnable program is good.
最好能提供一个可运行的程序用来复现这个issue。

### What did you expect to see?
期望结果。
编译通过

### What did you see instead?
实际运行结果。

windows 正常通过，选择linux-64编译就出错
go build github.com/DataDog/zstd: no buildable Go source files in E:\go\test\src\github.com\DataDog\zstd

**Comment by smallnest** [comment]
试试下面的 命令
GOOS=linux GOARCH=amd64 go get -u github.com/DataDog/zstd

我在我机器上可以编译。

如果还不成功，建议到zstd去提个issue。
https://github.com/DataDog/zstd

**Comment by ywolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6976516/23885153/5ff98e0c-08ac-11e7-9a55-8dcd30bccbb0.png)

我 win7 win10 测试可均不可，您是什么环境呢

**Comment by smallnest** [comment]
可能你机器上没装gcc

**Comment by ywolf** [comment]
测试了 cygwin 和TDM-GCC 都一样的结果呢

**Comment by smallnest** [comment]
zstd已经提交了相关的issue

https://github.com/DataDog/zstd/issues/14

所以关闭这个issue
