### ISSUE TITLE
Prometheus monitoring plugin

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#104]
add Prometheus monitoring plugin.

Just like https://github.com/grpc-ecosystem/go-grpc-prometheus

**Comment by lwhhhh** [comment]
期待 !

**Comment by smallnest** [comment]
supported

**Comment by ltt1987** [comment]
@smallnest 未能在最新版本中找到prometheus的支持，请问是被移除了吗？

**Comment by smallnest** [comment]
是的，移除了。使用的较少，先前还有prometheus依赖库版本的问题。
你可以基于先前的实现自己实现一个：
<img width="573" alt="image" src="https://user-images.githubusercontent.com/865763/168735458-d6d16548-4f2a-40a4-a06f-85c9d7db5e61.png">
