### ISSUE TITLE
无法运行  signal: killed

### ISSUE THREAD

**Issue by hetian9288** [smallnest/rpcx#109]
安装方式： go get -v -u github.com/smallnest/rpcx
安装完成后提示有未安装的包，全部手动安装了，解决完所有未安装包问题后 程序依然无法运行；
提示：signal: killed 
没有其他的错误提示；

测试代码：https://github.com/rpcx-ecosystem/rpcx-examples2

运行环境 mac系统

> GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hetian9288/go:/Users/hetian9288/develop/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l8/4xd_ltxx55scsd202b9r1jn40000gn/T/go-build877300583=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by smallnest** [comment]
go 1.8的bug,升级你的Go环境，

https://github.com/golang/go/issues/19734

**Comment by hetian9288** [comment]
ok ，可以了 🙏🙏🙏
