### ISSUE TITLE
v2.0 compatablity with other languages?

### ISSUE THREAD

**Issue by tomByrer** [smallnest/rpcx#110]
Does this mean I need to stick with rpcx1.3 to use NodeJS clients (eg [GRPC](http://www.grpc.io/about/#osp))?

> Since rpcx 2.0, we replace underlying Go official rpc transport with customized rpc transport.  If you want to use underlying Go official rpc transport, please use rpcx 1.3.

Thanks for all your hard work!

**Comment by smallnest** [comment]
How do you use NodeJS clients to call rpcx 1.3?
If you use jsonrpc or jsonrpc2, you can still use rpcx 2.0 with jsonrpc clients.

I am working to implement the [agent](https://github.com/rpcx-ecosystem/agent) that is a agent to access rpcx services.
So you can use other languages (suuported by grpc) to acess rpcx.

**Comment by tomByrer** [comment]
I have not started to use rpcx yet.  I am deciding if I want to use this or [Dgraph](https://github.com/dgraph-io/dgraph), which is a database with GRPC combined.
