### ISSUE TITLE
can't find clientselector.ServerPair

### ISSUE THREAD

**Issue by xuanjiang1985** [smallnest/rpcx#112]
Hi, here is error
# command-line-arguments
./client3.go:21: undefined: clientselector.ServerPair
./client3.go:22: undefined: clientselector.ServerPair
./client3.go:24: undefined: clientselector.ServerPair

and i tried to test your example code below:
server1 := clientselector.ServerPair{Network: "tcp", Address: "127.0.0.1:8972"}
server2 := clientselector.ServerPair{Network: "tcp", Address: "127.0.0.1:8973"}

servers := []clientselector.ServerPair{server1, server2}

**Comment by smallnest** [comment]
I think your exampe is from README.md and it is old that can't work. See the newest examples https://github.com/rpcx-ecosystem/rpcx-examples2
