### ISSUE TITLE
想请教一下和go-micro相比，性能上有点多大的差异呢？

### ISSUE THREAD

**Issue by antxyz** [smallnest/rpcx#120]
最近在看RPC这方面的东西，对rpcx很感兴趣，而micro提供了api-gateway功能，现在取舍不定。但就RPC方面，不知道您做过和go-mirco的性能对比没有

**Comment by smallnest** [comment]
micro 基于grpc，所以性能最多和grpc相当。 实际测试rpcx性能几乎是grpc的两倍
