### ISSUE TITLE
CURL请求RPCX服务端口触发异常退出(编码库:gencode)

### ISSUE THREAD

**Issue by hankji** [smallnest/rpcx#125]
使用rpcx开启了服务端口:7051
服务端使用的编码:
....
server = rpcx.NewServer()
server.ServerCodecFunc = codec.NewGencodeServerCodec
....

此时curl http://localhost:7051/

程序异常信息:
panic: runtime error: index out of range

goroutine 22 [running]:
adindex/vendor/github.com/rpcx-ecosystem/net-rpc-gencode2.(*RequestHeader).Unmarshal(0xc4203c0600, 0xc4203d9000, 0x47, 0x400, 0x400, 0xc4203d9000, 0x47)
	/Users/hank/Documents/projects/src/adindex/vendor/github.com/rpcx-ecosystem/net-rpc-gencode2/rpc.schema.gen.go:172 +0x303
adindex/vendor/github.com/rpcx-ecosystem/net-rpc-gencode2.(*gencodeDecoder).Decode(0xc420120e70, 0x49e0be0, 0xc4203c0600, 0x0, 0x0)
	/Users/hank/Documents/projects/src/adindex/vendor/github.com/rpcx-ecosystem/net-rpc-gencode2/codec.go:38 +0xe1

**Comment by smallnest** [comment]
cocec应该提供容错机制， 不止于因为客户端的错误数据或者恶意攻击而panic

**Comment by smallnest** [comment]
Fixed
