### ISSUE TITLE
请问下目前支持服务隔离和熔断么

### ISSUE THREAD

**Issue by stelin** [smallnest/rpcx#126]
看下了使用文档，感觉很不错，功能很强大。目前发现服务隔离和熔断机制感觉还没怎么完善，有后续计划么

**Comment by stelin** [comment]
目前很期待rpcx

**Comment by smallnest** [comment]
服务隔离指的是？可以通过元数据的group来指定client访问特定组的服务。


熔断机制还没有加，目前是通过注册中心的心跳来检查服务的存活。这一特性在仔细分析后可以考虑加入，我新起一个issue纪录一下

**Comment by stelin** [comment]
比如A服务，需要调用三个服务B,C,D，假如B服务出问题或B服务的调用突然剧烈猛增，此时调用B服务消耗本机大量资源，导致调用C，D服务不能正常使用。类似Java中说的，针对不同的服务调用做线程隔离，服务之前做调用资源隔离。

**Comment by smallnest** [comment]
这不是你client调用需要处理的么，不同的服务调用你可以在不同的goroutine,本身tpc框架不负责这些事情

**Comment by stelin** [comment]
恩，明白了，可以这样处理，谢谢了。
