### ISSUE TITLE
增加熔断机制

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#127]
### 熔断器模式介绍

0. https://martinfowler.com/bliki/CircuitBreaker.html
1. http://www.cnblogs.com/yangecnu/p/Introduce-Circuit-Breaker-Pattern.html
2. https://segmentfault.com/a/1190000005988895
3. https://docs.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker
4. https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern
5. http://microservices.io/patterns/reliability/circuit-breaker.html

### 相关的库

1. https://github.com/Netflix/Hystrix/wiki/How-it-Works
2. https://github.com/rubyist/circuitbreaker
3. https://github.com/sony/gobreaker
4.  https://github.com/dahernan/goHystrix

**Comment by stelin** [comment]
nice

**Comment by smallnest** [comment]
added
