### ISSUE TITLE
rpcx集成到beego

### ISSUE THREAD

**Issue by stelin** [smallnest/rpcx#129]
可以把rpcx集成到beego框架里面么，beego本身会启动一个http server,启动的同时再启动一个rpcx server。相当于同时监听两个端口一个http server和tcp rpc server，类似swoole机制

**Comment by smallnest** [comment]
不会做集成，因为这是不同目的的两种框架，没有交集。如果你的项目中需要用到这两个框架，诚如你所说，你启动两个两个框架即可，也算是应用自己做的集成吧。

就像淘宝的Tengine和dubbo一样，nginx和grpc一样，
