### ISSUE TITLE
请问什么时候支持thrfit？

### ISSUE THREAD

**Issue by qiankunli** [smallnest/rpcx#130]

**Comment by smallnest** [comment]
目前没有特别的需求，有实际的应用场景？

**Comment by qiankunli** [comment]
主要我司都是采用thrift协议做rpc，java环境有一整套服务治理等，如果要推广go的使用，必须先支持这些。

**Comment by smallnest** [comment]
即使支持了thrift编码，也不能和其他thrift互联互通，只是利用thrift编码在rpcx之间调用，估计也不会在贵司这样的环境中推广开来。

目前rpcx不支持跨语言的调用， 虽然Leo提供了php的客户端，但是其它语言都不支持。

**Comment by qiankunli** [comment]
您这个协议原理上，我还没有仔细了解，不都是收发二进制么？哪些因素限制了不支持呢？

**Comment by smallnest** [comment]
rpcx会定义自己的header和payload, 所以和thrift服务的协议不是兼容的，其它语言的客户端需要按照rpcx的协议解析

**Comment by smallnest** [comment]
Thereis no plan to  support thrift
