### ISSUE TITLE
服务重启导致DirectClientSelector的连接数暴增

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#133]
@上海-ha666  在QQ群提到：

server端启动
客户端连接，总共请求1000次，间隔10毫秒，在请求的过程中，server关闭一次，然后server打开
在这种情况下，连接数暴增
server停止时间越长，连接数越多

![a068645702b1169b00beec11e4fcec1c-2](https://user-images.githubusercontent.com/865763/28050915-4bd1fa92-6633-11e7-901e-1aaf0e01d1c3.png)

http://git.oschina.net/ha666/ha666web/blob/master/src/ha666_client/client.go

**Comment by ha666** [comment]
`package main

import (
	"fmt"
	"github.com/astaxie/beego/logs"
	"github.com/smallnest/rpcx"
	"golang.org/x/net/context"
	_ "ha666_client/initial"
	"rpc_models/arith"
	"rpc_models/interface_names"
	"runtime"
	"sync"
	"time"
)

var client *rpcx.Client

func init() {
	s := &rpcx.DirectClientSelector{Network: "tcp", Address: "192.168.51.86:8888", DialTimeout: 5 * time.Second}
	client = rpcx.NewClient(s)
	client.FailMode = rpcx.Failtry
	client.Retries = 3
	client.Timeout = time.Hour * 720
	err := client.Auth("1234567890", "Bearer")
	if err != nil {
		logs.Error("can't add auth %v", err)
	}
}

func testArith_T3(current int) {
	args := &arith.Args{current, current}
	var reply arith.Reply
	err := client.Call(context.Background(), interface_names.Arith_T3, args, &reply)
	if err != nil {
		logs.Error("error for Arith:%d*%d,%v", args.A, args.B, err)
	} else {
		logs.Info("【T3】%d*%d,%v", args.A, args.B, reply.C)
	}
}

func testArith_T5(current int) {
	args := &arith.Args{current, current}
	var reply arith.Reply
	err := client.Call(context.Background(), interface_names.Arith_T5, args, &reply)
	if err != nil {
		logs.Error("error for Arith:%d*%d,%v", args.A, args.B, err)
	} else {
		logs.Info("【T5】%d*%d,%v", args.A, args.B, reply.C)
	}
}

func testArith_T10(current int) {
	args := &arith.Args{current, current}
	var reply arith.Reply
	err := client.Call(context.Background(), interface_names.Arith_T10, args, &reply)
	if err != nil {
		logs.Error("error for Arith:%d*%d,%v", args.A, args.B, err)
	} else {
		logs.Info("【T10】%d*%d,%v", args.A, args.B, reply.C)
	}
}

func main() {
	logs.Info("开始执行")
	runtime.GOMAXPROCS(runtime.NumCPU())
	var wg sync.WaitGroup
	wg.Add(1000)
	for index := 0; index < 1000; index++ {
		time.Sleep(time.Millisecond * 10)
		switch index % 10 {
		case 0, 1, 2, 3, 4:
			go testArith_T3(index)
		case 5, 6, 7:
			go testArith_T5(index)
		default:
			go testArith_T10(index)
		}
	}
	wg.Wait()
	fmt.Println("完成")
	time.Sleep(1000000)
}
`

**Comment by smallnest** [comment]
http://git.oschina.net/ha666/ha666web/tree/master/src

**Comment by smallnest** [comment]
MACOSX测试问题已修复。

据@上海-ha666说，windows环境下问题依然存在，issue持续观察。

**Comment by ha666** [comment]
经过测试，新版本已经完全解决了连接数暴涨的问题。
