### ISSUE TITLE
频繁出现，server io timeout后，client hang住直到超时

### ISSUE THREAD

**Issue by zyanho** [smallnest/rpcx#136]
env如下：
go 1.8.3、rpcx 最新master、使用tcp或者最新quic、使用rpcx/pool
server是单独进程，client初始化后，在一个fasthttp的http服务里面按需调用
server、client、http timeout都是120s

client使用的是NewMultiClientSelector 直连没使用注册中心
pool使用的是github.com/smallnest/pool
select是rpcx.RandomSelect

server，client使用了
compressionPlugin := plugin.NewCompressionPlugin(rpcx.CompressSnappy)

复现步骤

1、启动server
2、启动fasthttp，实例化client_pool
3、请求多次httpurl，调用client_pool，请求server，然后response，确保client_pool创建过client
4、停止任何请求，任何动作，等待server返回 server.go:550: INFO : [rpc: rpc: server cannot decode request: read tcp 127.0.0.1:8972->127.0.0.1:56132: i/o timeout]
5、client也得到返回 client.go:186: INFO : [rpc: client protocol error: read tcp 127.0.0.1:59597->127.0.0.1:8972: i/o timeout]，如果此时client会自动重连，重现失败，重复步骤3
6、server再次超时后，client再请求，hang住了，直到超时或者EOF
7、再次请求，client才会自动重连

**Comment by zyanho** [comment]
另外如果多个client同时请求的时候，还有个严重的panic，会随机出现

client.go:306: INFO : client has been shutdown
client.go:306: INFO : client has been shutdown
client.go:454: WARN : reconnected to server: tcp@127.0.0.1:8972
client.go:454: WARN : reconnected to server: tcp@127.0.0.1:8972
client.go:186: INFO : [rpc: client protocol error: read tcp 127.0.0.1:55574->127.0.0.1:8972: use of closed network connection]
fatal error: sync: unlock of unlocked mutex
client.go:192: ERROR: failed to call: read tcp 127.0.0.1:55574->127.0.0.1:8972: use of closed network connection

**Comment by smallnest** [comment]
相应的Call变成了孤立的， 没有地方去调用它的Done,即使是连接断掉。

**Comment by smallnest** [comment]
Server端测试代码：

```go
package main

import (
	"context"

	"time"

	"github.com/smallnest/rpcx"
	"github.com/smallnest/rpcx/plugin"
)

type Args struct {
	A int
	B int
}

type Reply struct {
	C int
}

type Arith int

func (t *Arith) Mul(ctx context.Context, args *Args, reply *Reply) error {
	reply.C = args.A * args.B
	return nil
}

type Arith2 int

func (t *Arith2) Mul(args *Args, reply *Reply) error {
	reply.C = args.A * args.B * 10
	return nil
}

func main() {
	server1 := rpcx.NewServer()
	compressionPlugin := plugin.NewCompressionPlugin(rpcx.CompressSnappy)
	server1.PluginContainer.Add(compressionPlugin)
	server1.Timeout = 5 * time.Second

	server1.RegisterName("Arith", new(Arith))
	server1.Start("tcp", "127.0.0.1:8972")

	server2 := rpcx.NewServer()
	server2.PluginContainer.Add(compressionPlugin)
	server2.RegisterName("Arith", new(Arith2))
	server2.Serve("tcp", "127.0.0.1:8973")
}
```

**Comment by smallnest** [comment]
客户端测试代码:

```go
package main

import (
	"context"
	"time"

	"github.com/apex/log"
	"github.com/smallnest/rpcx"
	"github.com/smallnest/rpcx/clientselector"
	"github.com/smallnest/rpcx/plugin"
)

type Args struct {
	A int
	B int
}

type Reply struct {
	C int
}

func main() {
	server1 := &clientselector.ServerPeer{Network: "tcp", Address: "127.0.0.1:8972"}
	server2 := &clientselector.ServerPeer{Network: "tcp", Address: "127.0.0.1:8973"}

	servers := []*clientselector.ServerPeer{server1, server2}

	s := clientselector.NewMultiClientSelector(servers, rpcx.RoundRobin, 10*time.Second)
	s.SelectMode = rpcx.RandomSelect
	client := rpcx.NewClient(s)
	client.Timeout = 6 * time.Second

	compressionPlugin := plugin.NewCompressionPlugin(rpcx.CompressSnappy)
	client.PluginContainer.Add(compressionPlugin)

	for i := 0; i < 10; i++ {
		callServer(client)
		time.Sleep(6 * time.Second)
	}

	client.Close()
}

func callServer(client *rpcx.Client) {
	args := &Args{7, 8}
	var reply Reply
	err := client.Call(context.Background(), "Arith.Mul", args, &reply)
	if err != nil {
		log.Infof("error for Arith: %d*%d, %v", args.A, args.B, err)
	} else {
		log.Infof("Arith: %d*%d=%d", args.A, args.B, reply.C)
	}
}
```

一段时间之后client就hang住了。

**Comment by smallnest** [comment]
相关测试信息：

1.  用上面的代码可重现
client hang在core.Client.Call方法中
2. 与CompressionPlugin无关
注释掉这个插件,bug依然可以重现
3. 和服务器超时设置无关

**Comment by zyanho** [comment]
设置rpcx.Reconnect = nil不会出现hang住的问题，但是会出现另外一种情况，当timeout或者其他问题出现，会出现某一次请求返回报错，再次请求才会正常，目前做法是遇到以下的错误，client重新发起一次请求。

client protocol error: NetworkIdleTimeout: No recent network activity
failed to call: connection is shut down
PublicReset: Received
PeerGoingAway:
write: broken pipe
writing response

**Comment by smallnest** [comment]
2.1中不再支持reconnect
