### ISSUE TITLE
使用consul注册服务，无法查询到所有consul agent上的服务

### ISSUE THREAD

**Issue by juexun** [smallnest/rpcx#137]
github.com/smallnest/rpcx/clientselector/consul_selector.go

func (s *ConsulClientSelector) pullServers() {
	agent := s.client.Agent()
	ass, err := agent.Services()  // 此处有坑

	if err != nil {
		return
	}

       ....
}

**Comment by smallnest** [comment]
3.0中解决了这个问题。 2.0中不再支持consul
