### ISSUE TITLE
github.com/rpcx-ecosystem/colfer/rpc/rpc.go:9:2: use of internal package not allowed

### ISSUE THREAD

**Issue by 0i** [smallnest/rpcx#139]
github.com/rpcx-ecosystem/colfer/rpc/rpc.go:9:2: use of internal package not allowed

**Comment by 0i** [comment]
首先非常感谢作者的共享，我还是非常看到这个项目的。
但是经过我这边的亲自尝试使用，反馈一下我这边一些问题。

第一：经过尝试使用，bug 实在太多了！！！
第二：整个文档没有看到详细的安装文档，然后包管理做的确实很烂，安装异常异常痛苦。
第三：如何使用第三方序列化工具，也没有详细的说明(虽然这个本身不困难)。

感觉整个介绍，都是在如何吹嘘性能如何好，使用如何多方便。但是真正的如何使用，如何安装，如何集成第三方序列化工具的文档几乎没有。
导致第一眼看上去非常兴奋，但是使用之后就会发现诸多问题。
另外整个源代码也是特别臃肿，希望作者有时间可以做一些重构。

以上只是一些个人建议，希望作者不要介意。

**Comment by smallnest** [comment]
There are more details about this issue. Please search your issue and google it such as 
https://golangtc.com/t/55fa6bc6b09ecc7a4200009f

**Comment by 0i** [comment]
sorry，我用的glide这个go package管理工具，下载下来的代码，github.com/rpcx-ecosystem/colfer/blob/master/rpc/rpc.go中，并不是import 的 github.com/rpcx-ecosystem/colfer/rpc/internal，而是 pascaldekloe/colfer/rpc/internal，我这边在使用glide add package的时候并不是选择的release版本，很奇怪为什么会出现这个问题，目前还在更进一步跟进中。
golang的包管理确实一直是一个很头疼的问题，希望官方在2.x版本中能够优雅的解决下这个问题。
