### ISSUE TITLE
plugin newmetrics missing

### ISSUE THREAD

**Issue by omani** [smallnest/rpcx#142]
hi all,

could you please stop writing in chinese? so we can understand the issues.

I got this problem here when running an example:
```
~/gocode/src/github.com/rpcx-ecosystem/rpcx-examples2/etcd_registry (master) $ go run server.go 
# command-line-arguments
./server.go:50: undefined: plugin.NewMetricsPlugin
```

I see that the metrics plugin was commented out. but since the commit message is in chinese language (or whatever it is) I can't understand why and what to do here.

any hints?

**Comment by smallnest** [comment]
Sorry for that. I will use english for comments and issues.

MetricsPlugin has some issues. It changes seq in requests and clients may be hangs for new coming clients. So please don't use MetricsPlugin temporarily

**Comment by smallnest** [comment]
I have re-implemented metrics and you can try it.

**Comment by omani** [comment]
thanks.
