### ISSUE TITLE
how to check client connection is health

### ISSUE THREAD

**Issue by imiskolee** [smallnest/rpcx#149]
i define a rpcx.Client of a global variable(it like sql.Open()).

a global client to handle a service all request is right ?

and we need to check client is health ?

**Comment by smallnest** [comment]
a rpcx.Client can be used for **one** service, and it can used in multiple goroutines concurrently.
If you use etcd, zookeeper or consul,  rpcx.Client can handle unavailable servers, remove them  and only use avaliable servers. So you don't need check client is health.
