### ISSUE TITLE
看了几个例子挺简单的，但是安装太难了。

### ISSUE THREAD

**Issue by xuanjiang1985** [smallnest/rpcx#152]
翻墙都不能全部下载下所有依赖包。
我用国外服务安装了，再把依赖包下载到本地电脑，还是不行。是否能提供简单的压缩文件
# github.com/lucas-clemente/quic-go
../github.com/lucas-clemente/quic-go/interface.go:14: syntax error: unexpected = in type declaration
../github.com/lucas-clemente/quic-go/interface.go:17: syntax error: unexpected = in type declaration
../github.com/lucas-clemente/quic-go/interface.go:20: syntax error: unexpected = in type declaration
# github.com/coreos/etcd/clientv3
../github.com/coreos/etcd/clientv3/client.go:327: cannot use c.tokenCred (type *authTokenCredential) as type credentials.PerRPCCredentials in argument to grpc.WithPerRPCCredentials:

**Comment by lmsreborn** [comment]
@xuanjiang1985 I have the same problem. Maybe you should change your Go version to 1.9. Those two repos are using Go 1.9 features like type alias.

**Comment by smallnest** [comment]
3.0  将简化rpcx实现， 只使用必需的依赖。

**Comment by smallnest** [comment]
3.0 已经简化，可以i 查看3.0的分支
