### ISSUE TITLE
core.Client关闭时没有清理MultiClientSelector中clientAndServer

### ISSUE THREAD

**Issue by fangguanya** [smallnest/rpcx#156]
根据'RPCX'中文文档中的例子使用MultiClientSelector试验了下'客户端自动选择多服务'时,发现前1-2个call能成功, 但是后面的总是 failed to call: connection is shut down.
看代码后,觉得应该是client.Close后,设置了状态,但是没有从SeverPeer当中把自身引用清除导致,

**Comment by smallnest** [comment]
把你的例子贴出来

**Comment by fangguanya** [comment]
`func main(){
	s := &rpcx.DirectClientSelector{
		Network:"tcp",
		Address:"127.0.0.1:1234",
		DialTimeout:time.Second * 10,}

	// sync
	client := rpcx.NewClient(s)
	args := &rpcx2.Args{7,9}
	var reply rpcx2.Reply
	err := client.Call(context.Background(),"Arith.Mul",args,&reply)
	if err != nil {
		fmt.Println("ERROR:",err)
	}
	fmt.Println("sync result:",reply.C)

	// async
	divCall := client.Go(context.Background(), "Arith.Mul", args, &reply, nil)
	resCall := <-divCall.Done
	if resCall.Error != nil {
		fmt.Println("Async ERROR:",resCall.Error)
	}
	fmt.Println("async result:",reply.C)


	// multi selector
	server1 := &clientselector.ServerPeer{Network:"tcp",Address:"127.0.0.1:1234"}
	server2 := &clientselector.ServerPeer{Network:"tcp",Address:"127.0.0.1:2222"}
	servers := []*clientselector.ServerPeer{server1,server2}
	s1 := clientselector.NewMultiClientSelector(servers, rpcx.RandomSelect, 2 * time.Second)
	for i := 0;i < 10 ;i ++{
		callServer(s1)
	}
}
func callServer(s rpcx.ClientSelector){
	client := rpcx.NewClient(s)
	args := &rpcx2.Args{7,9}
	var reply rpcx2.Reply
	err := client.Call(context.Background(),"Arith.Mul",args,&reply)
	if err != nil {
		fmt.Println("call server error:",err)
	}
	fmt.Println("call server result:",reply.C)
	client.Close()
}`

**Comment by fangguanya** [comment]
@smallnest 
[rpcx.zip](https://github.com/smallnest/rpcx/files/1382825/rpcx.zip)上传了压缩文件啦.
执行后输出:
sync result: 63
async result: 63
call server result: 63
2017/10/13 21:52:38 client.go:362: ERROR: failed to ReadResponseHeader: EOF
2017/10/13 21:52:38 client.go:192: ERROR: failed to call: connection is shut down
2017/10/13 21:52:38 client.go:362: ERROR: failed to ReadResponseHeader: read tcp 127.0.0.1:6766->127.0.0.1:1234: use of closed network connection
2017/10/13 21:52:38 client.go:192: ERROR: failed to call: connection is shut down
2017/10/13 21:52:38 client.go:362: ERROR: failed to ReadResponseHeader: EOF
2017/10/13 21:52:38 client.go:192: ERROR: failed to call: connection is shut down
2017/10/13 21:52:38 client.go:192: ERROR: failed to call: connection is shut down
2017/10/13 21:52:38 client.go:362: ERROR: failed to ReadResponseHeader: EOF
2017/10/13 21:52:38 client.go:192: ERROR: failed to call: connection is shut down
2017/10/13 21:52:38 client.go:362: ERROR: failed to ReadResponseHeader: EOF
2017/10/13 21:52:38 client.go:192: ERROR: failed to call: connection is shut down
2017/10/13 21:52:38 client.go:192: ERROR: failed to call: connection is shut down
2017/10/13 21:52:38 client.go:362: ERROR: failed to ReadResponseHeader: EOF
2017/10/13 21:52:38 client.go:192: ERROR: failed to call: connection is shut down
2017/10/13 21:52:38 client.go:362: ERROR: failed to ReadResponseHeader: EOF
2017/10/13 21:52:38 client.go:192: ERROR: failed to call: connection is shut down
call server error: connection is shut down
call server result: 0
call server error: connection is shut down
call server result: 0
call server error: connection is shut down
call server result: 0
call server error: connection is shut down
call server result: 0
call server error: connection is shut down
call server result: 0
call server error: connection is shut down
call server result: 0
call server error: connection is shut down
call server result: 0
call server error: connection is shut down
call server result: 0
call server error: connection is shut down
call server result: 0

**Comment by smallnest** [comment]
```go
func callServer(s rpcx.ClientSelector) {
	client := rpcx.NewClient(s)
	args := &rpcx2.Args{7, 9}
	var reply rpcx2.Reply
	err := client.Call(context.Background(), "Arith.Mul", args, &reply)
	if err != nil {
		fmt.Println("call server error:", err)
	}
	fmt.Println("call server result:", reply.C)
	client.Close()
}
```
client放在全局， 或者clientselector放在在方法内。
