### ISSUE TITLE
使用Etcd3做服务发现时存在连接未关闭的问题

### ISSUE THREAD

**Issue by joy-chenjh** [smallnest/rpcx#157]
**Please answer these questions before submitting your issue. Thanks!**

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/chenjianhui/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xp/3bsc2jdd26zgr94b99bgxx180000gn/T/go-build931620161=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

使用Etcd3做服务发现时, 发现存在连接句柄关闭的问题.

测试验证方法:
使用
github.com/rpcx-ecosystem/rpcx-examples2/etcdv3_registry中的server,client代码.
修改client在循环中增加sleep.
    for i := 0; i < 10; i++ {
        err := client.Call(context.Background(), *n+".Mul", args, &reply)
        if err != nil {
            log.Infof("error for "+*n+": %d*%d, %v", args.A, args.B, err)
        } else {
            log.Infof(*n+": %d*%d=%d", args.A, args.B, reply.C)
        }
        **log.Info("sleep", time.Minute)
        time.Sleep(time.Minute)**
    }

client运行日志如下:
2017/10/17 11:49:48 client.go:42: INFO : Arith: 7*8=56
2017/10/17 11:49:48 client.go:44: INFO : [sleep 1m0s]
2017/10/17 11:50:33 etcdv3_selector.go:121: INFO : PUT "/rpcx/Arith/tcp@127.0.0.1:8972":"m=devops&tps=0&weight=1"
2017/10/17 11:50:48 client.go:42: INFO : Arith: 7*8=56
2017/10/17 11:50:48 client.go:44: INFO : [sleep 1m0s]
2017/10/17 11:51:48 client.go:42: INFO : Arith: 7*8=56
2017/10/17 11:51:48 client.go:44: INFO : [sleep 1m0s]
2017/10/17 11:52:32 etcdv3_selector.go:121: INFO : PUT "/rpcx/Arith/tcp@127.0.0.1:8972":"m=devops&tps=0&weight=1"
2017/10/17 11:52:48 client.go:42: INFO : Arith: 7*8=56
2017/10/17 11:52:48 client.go:44: INFO : [sleep 1m0s]
2017/10/17 11:53:48 client.go:42: INFO : Arith: 7*8=56
2017/10/17 11:53:48 client.go:44: INFO : [sleep 1m0s]
^C

查看网络连接:
$ netstat -na |grep 8972
tcp4       0      0  127.0.0.1.8972         127.0.0.1.63869        ESTABLISHED
tcp4       0      0  127.0.0.1.63869        127.0.0.1.8972         ESTABLISHED
tcp4       0      0  127.0.0.1.8972         127.0.0.1.63857        ESTABLISHED
tcp4       0      0  127.0.0.1.63857        127.0.0.1.8972         ESTABLISHED
tcp4       0      0  127.0.0.1.8972         127.0.0.1.63847        ESTABLISHED
tcp4       0      0  127.0.0.1.63847        127.0.0.1.8972         ESTABLISHED
tcp4       0      0  127.0.0.1.8972         *.*                    LISTEN

分析是 watch中从连接map clientAndServer中删除了对应的Key, 但是没有关闭连接.
func (s *EtcdV3ClientSelector) watch() {
	watcher := s.KeysAPI.Watch(context.Background(), s.BasePath, clientv3.WithPrefix())
	for wresp := range watcher {
		for _, ev := range wresp.Events {
			log.Infof("%s %q:%q\n", ev.Type, ev.Kv.Key, ev.Kv.Value)
			s.pullServers()
			removedServer := strings.TrimPrefix(string(ev.Kv.Key), s.BasePath)
			s.clientRWMutex.Lock()
			delete(s.clientAndServer, removedServer)
			s.clientRWMutex.Unlock()
		}
	}
}
此处是否可以同时优化一下. 区分Events的事件进行处理.

**Comment by smallnest** [comment]
这个是故意设计的，注册中心中如果发现一个服务不存在了， 那么client已经建立的连接需不需要主动关闭:


1. 如果真的服务宕机， 我觉得client应该能读取到io.EOF,然后关闭这个连接， 所以这种情况是不需要的。

2. 但是如果想服务还存在，就是不想让它提供服务 (服务暂时退休)， 但是手工从注册中心注销掉， 这种情况下连接需要断掉，否则已有的client还会调用服务

3. 服务和注册中心网络分区，这种情况下虽然注册中心中已经没有了这个服务，但是服务还是可用的，在这种情况下，不应该关闭连接。

针对这些情况，我觉得可以扩展一下，提供一个标志， 让使用者决定注册中心中如果服务不存在，要不要主动关闭连接

**Comment by joy-chenjh** [comment]
提代一个扩展标志最好, 可以让使用者自主选择.   

验证的场景是没有设置client的Timeout时长. 如果设置了,目前也能有效的关闭连接. 但是TimeOut的时长如果设置得过短, 则会出现很多的重连.  过长, 又会在一定的时长时出现连接不能立即关闭的问题.


2017/10/17 14:27:42 client.go:43: INFO : Arith: 7*8=56
2017/10/17 14:27:42 client.go:45: INFO : [sleep 1m0s]
2017/10/17 14:27:52 client.go:362: WARN : failed to ReadResponseHeader: read tcp 127.0.0.1:49203->127.0.0.1:8972: i/o timeout
2017/10/17 14:27:52 client.go:191: INFO : [rpc: client protocol error: read tcp 127.0.0.1:49203->127.0.0.1:8972: i/o timeout]
2017/10/17 14:28:42 client.go:192: WARN : failed to call: connection is shut down
2017/10/17 14:28:42 client.go:41: INFO : error for Arith: 7*8, connection is shut down
2017/10/17 14:28:42 client.go:45: INFO : [sleep 1m0s]
2017/10/17 14:29:37 etcdv3_selector.go:121: INFO : PUT "/rpcx/Arith/tcp@127.0.0.1:8972":"m=devops&tps=0&weight=1"
2017/10/17 14:29:42 client.go:43: INFO : Arith: 7*8=56
2017/10/17 14:29:42 client.go:45: INFO : [sleep 1m0s]
2017/10/17 14:29:52 client.go:362: WARN : failed to ReadResponseHeader: read tcp 127.0.0.1:49232->127.0.0.1:8972: i/o timeout
2017/10/17 14:29:52 client.go:191: INFO : [rpc: client protocol error: read tcp 127.0.0.1:49232->127.0.0.1:8972: i/o timeout]
2017/10/17 14:30:42 client.go:192: WARN : failed to call: connection is shut down
2017/10/17 14:30:42 client.go:41: INFO : error for Arith: 7*8, connection is shut down
2017/10/17 14:30:42 client.go:45: INFO : [sleep 1m0s]
2017/10/17 14:31:37 etcdv3_selector.go:121: INFO : PUT "/rpcx/Arith/tcp@127.0.0.1:8972":"m=devops&tps=0&weight=1"
2017/10/17 14:31:42 client.go:43: INFO : Arith: 7*8=56
2017/10/17 14:31:42 client.go:45: INFO : [sleep 1m0s]
2017/10/17 14:31:52 client.go:362: WARN : failed to ReadResponseHeader: read tcp 127.0.0.1:49245->127.0.0.1:8972: i/o timeout
2017/10/17 14:31:52 client.go:191: INFO : [rpc: client protocol error: read tcp 127.0.0.1:49245->127.0.0.1:8972: i/o timeout]
2017/10/17 14:32:42 client.go:192: WARN : failed to call: connection is shut down
2017/10/17 14:32:42 client.go:41: INFO : error for Arith: 7*8, connection is shut down
2017/10/17 14:32:42 client.go:45: INFO : [sleep 1m0s]
2017/10/17 14:33:37 etcdv3_selector.go:121: INFO : PUT "/rpcx/Arith/tcp@127.0.0.1:8972":"m=devops&tps=0&weight=1"
2017/10/17 14:33:42 client.go:43: INFO : Arith: 7*8=56
2017/10/17 14:33:42 client.go:45: INFO : [sleep 1m0s]
2017/10/17 14:33:52 client.go:362: WARN : failed to ReadResponseHeader: read tcp 127.0.0.1:49274->127.0.0.1:8972: i/o timeout
2017/10/17 14:33:52 client.go:191: INFO : [rpc: client protocol error: read tcp 127.0.0.1:49274->127.0.0.1:8972: i/o timeout]
2017/10/17 14:34:42 client.go:192: WARN : failed to call: connection is shut down
2017/10/17 14:34:42 client.go:41: INFO : error for Arith: 7*8, connection is shut down
2017/10/17 14:34:42 client.go:45: INFO : [sleep 1m0s]
2017/10/17 14:35:37 etcdv3_selector.go:121: INFO : PUT "/rpcx/Arith/tcp@127.0.0.1:8972":"m=devops&tps=0&weight=1"
2017/10/17 14:35:42 client.go:43: INFO : Arith: 7*8=56
2017/10/17 14:35:42 client.go:45: INFO : [sleep 1m0s]

**Comment by smallnest** [comment]
#cc5ba60 应该解决了这个问题，超时的时候连接关闭
