### ISSUE TITLE
使用EtcdV3做服务发现时不支持EtcdV3 使用用户名和密码.

### ISSUE THREAD

**Issue by joy-chenjh** [smallnest/rpcx#158]
为保证生产环境的安全性, Etcd 配置了访问账号和密码. 在NewEtcdV3ClientSelector 初始化时没有参数配置EtcdV3的账号和密码. 

是否可以将EtcdV3的配置 clientv3.Config 通过入参传入.

**Comment by smallnest** [comment]
supported in 3.0
