### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by leepengg** [smallnest/rpcx#162]
goroutine 44 [runnable]:
github.com/coreos/etcd/client.v2KeysURL(0xc4201542a0, 0x4, 0x0, 0x0, 0x0, 0xc4201542a7, 0x11, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/keys.go:479 +0x3f
github.com/coreos/etcd/client.(*getAction).HTTPRequest(0xc42014a870, 0xc4201542a0, 0x4, 0x0, 0x0, 0x0, 0xc4201542a7, 0x11, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/keys.go:502 +0x8c
github.com/coreos/etcd/client.(*simpleHTTPClient).Do(0xc420158500, 0xd72900, 0xc420012090, 0xd6c2c0, 0xc42014a870, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:525 +0xc2
github.com/coreos/etcd/client.(*redirectFollowingHTTPClient).Do(0xc420148560, 0xd72900, 0xc420012090, 0xd6c2c0, 0xc42014a870, 0xc4201542a7, 0x11, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:636 +0xb2
github.com/coreos/etcd/client.(*httpClusterClient).Do(0xc42014e900, 0xd72900, 0xc420012090, 0xd6c2c0, 0xc42014a870, 0xc4201542e0, 0x1, 0xa8dd0d, 0x1, 0x9faa01, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:365 +0x36c
github.com/coreos/etcd/client.(*httpKeysAPI).Get(0xc420148520, 0xd72900, 0xc420012090, 0xc4201542e1, 0x11, 0xc420152278, 0xd74840, 0xc42014e900, 0x0)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/keys.go:422 +0xe1
github.com/docker/libkv/store/etcd.(*Etcd).List(0xc420146370, 0xa95990, 0x11, 0x11, 0xd75d40, 0xc420146370, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:407 +0xe1
github.com/smallnest/rpcx/client.NewEtcdDiscovery(0xa95990, 0x11, 0xc420146360, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:36 +0x2a4
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:65 +0xa8
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 45 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 46 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 47 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 48 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 65 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 66 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 67 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 68 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 69 [runnable]:
math/rand.New(...)
        /usr/local/go/src/math/rand/rand.go:65
github.com/coreos/etcd/client.New(0xc4201301b0, 0x1, 0x1, 0xd6fe40, 0xda6620, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:215 +0xe6
github.com/docker/libkv/store/etcd.New(0xc420130190, 0x1, 0x1, 0x0, 0xc4201402f8, 0xf0ceb90349fea201, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:83 +0x186
github.com/docker/libkv.NewStore(0xa8e4d9, 0x4, 0xc420130190, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/libkv.go:31 +0xa0
github.com/smallnest/rpcx/client.NewEtcdDiscovery(0xa95990, 0x11, 0xc420130190, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:27 +0xcf
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:65 +0xa8
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 70 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 71 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 72 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 73 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 74 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 75 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 76 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 77 [runnable]:
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 78 [runnable]:
math/rand.New(...)
        /usr/local/go/src/math/rand/rand.go:65
github.com/coreos/etcd/client.New(0xc4201ae2e0, 0x1, 0x1, 0xd6fe40, 0xda6620, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:215 +0xe6
github.com/docker/libkv/store/etcd.New(0xc4201ae2c0, 0x1, 0x1, 0x0, 0xc4201402f8, 0xf0ceb90349fea201, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:83 +0x186
github.com/docker/libkv.NewStore(0xa8e4d9, 0x4, 0xc4201ae2c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/libkv.go:31 +0xa0
github.com/smallnest/rpcx/client.NewEtcdDiscovery(0xa95990, 0x11, 0xc4201ae2c0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:27 +0xcf
main.callRPC(0xc4201ae2a0, 0xc420182130, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:65 +0xa8
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 26 [runnable]:
github.com/smallnest/rpcx/client.EtcdDiscovery.watch(0xa95990, 0x11, 0xd75d40, 0xc420146370, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:64
created by github.com/smallnest/rpcx/client.NewEtcdDiscovery
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:34 +0x270

**Comment by smallnest** [comment]
最开始出问题的堆栈还是没看到

**Comment by leepengg** [comment]
server
2017/10/24 16:02:22 client.go:90: INFO : d = : 174238
2017/10/24 16:02:22 client.go:86: INFO : hello = hellofrom server
2017/10/24 16:02:22 client.go:90: INFO : d = : 186035
2017/10/24 16:02:22 client.go:59: INFO : total time d = 9037690
root@iZ2ze0lxdukyo8d11hlo5eZ:~# ./etec3_client 1 10 10
fatal error: concurrent map writes

goroutine 68 [running]:
runtime.throw(0xa97d01, 0x15)
        /usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc420040c10 sp=0xc420040bf0 pc=0x42a385
runtime.mapassign_faststr(0x9bc5a0, 0xc420073080, 0xa8e4d9, 0x4, 0x0)
        /usr/local/go/src/runtime/hashmap_fast.go:685 +0x4da fp=0xc420040c90 sp=0xc420040c10 pc=0x40cc5a
github.com/docker/libkv.AddStore(...)
        /Users/peng/go_workspace/src/github.com/docker/libkv/libkv.go:39
github.com/docker/libkv/store/etcd.Register(...)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:50
github.com/smallnest/rpcx/client.NewEtcdDiscovery(0xa95990, 0x11, 0xc420130430, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:26 +0x63 fp=0xc420040df8 sp=0xc420040c90 pc=0x90f823
main.callRPC(0xc420130410, 0xc42014c360, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:66 +0xa8 fp=0xc420040fc8 sp=0xc420040df8 pc=0x91a178
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420040fd0 sp=0xc420040fc8 pc=0x457e01
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42014c36c)
        /usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc42014c360)
        /usr/local/go/src/sync/waitgroup.go:131 +0x72
main.main()
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:55 +0x36c

goroutine 28 [runnable]:
github.com/coreos/etcd/client.v2KeysURL(0xc4200144e0, 0x4, 0x0, 0x0, 0x0, 0xc4200144e7, 0x11, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/keys.go:479 +0x3f
github.com/coreos/etcd/client.(*getAction).HTTPRequest(0xc420122330, 0xc4200144e0, 0x4, 0x0, 0x0, 0x0, 0xc4200144e7, 0x11, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/keys.go:502 +0x8c
github.com/coreos/etcd/client.(*simpleHTTPClient).Do(0xc4200830e0, 0xd72900, 0xc420012090, 0xd6c2c0, 0xc420122330, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:525 +0xc2
github.com/coreos/etcd/client.(*redirectFollowingHTTPClient).Do(0xc4200d8ac0, 0xd72900, 0xc420012090, 0xd6c2c0, 0xc420122330, 0xc4200144e7, 0x11, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:636 +0xb2
github.com/coreos/etcd/client.(*httpClusterClient).Do(0xc4200549c0, 0xd72900, 0xc420012090, 0xd6c2c0, 0xc420122330, 0xc420014520, 0x1, 0xa8dd0d, 0x1, 0x9faa01, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:365 +0x36c
github.com/coreos/etcd/client.(*httpKeysAPI).Get(0xc4200d8a80, 0xd72900, 0xc420012090, 0xc420014521, 0x11, 0xc420012738, 0xd74840, 0xc4200549c0, 0x0)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/keys.go:422 +0xe1
github.com/docker/libkv/store/etcd.(*Etcd).List(0xc420049c50, 0xa95990, 0x11, 0x11, 0xd75d40, 0xc420049c50, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:407 +0xe1
github.com/smallnest/rpcx/client.NewEtcdDiscovery(0xa95990, 0x11, 0xc420049c40, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:36 +0x2a4
main.callRPC(0xc420130410, 0xc42014c360, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:66 +0xa8
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 18 [select]:
github.com/coreos/etcd/client.(*httpClusterClient).AutoSync(0xc42015a180, 0xd72900, 0xc420012090, 0x45d964b800, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:478 +0x192
github.com/docker/libkv/store/etcd.New.func1(0xd74840, 0xc42015a180)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:93 +0x58
created by github.com/docker/libkv/store/etcd.New
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:91 +0x310

goroutine 19 [chan receive]:
github.com/smallnest/rpcx/client.EtcdDiscovery.watch(0xa95990, 0x11, 0xd75d40, 0xc420130290, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:71 +0x42f
created by github.com/smallnest/rpcx/client.NewEtcdDiscovery
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:34 +0x270

goroutine 26 [runnable]:
github.com/smallnest/rpcx/client.(*xClient).watch(0xc42016e5a0, 0xc42015a900)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/xclient.go:118
created by github.com/smallnest/rpcx/client.NewXClient
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/xclient.go:85 +0x3b3

goroutine 33 [select]:
github.com/coreos/etcd/client.(*simpleHTTPClient).Do(0xc42019e000, 0xd72900, 0xc420012090, 0xd6c2c0, 0xc42013c2d0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:564 +0x31d
github.com/coreos/etcd/client.(*redirectFollowingHTTPClient).Do(0xc420144060, 0xd72900, 0xc420012090, 0xd6c2c0, 0xc42013c2d0, 0xc420150107, 0x11, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:636 +0xb2
github.com/coreos/etcd/client.(*httpClusterClient).Do(0xc42015a180, 0xd72900, 0xc420012090, 0xd6c2c0, 0xc42013c2d0, 0xc420198060, 0x1, 0xa8dd0d, 0x1, 0x9faa01, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:365 +0x36c
github.com/coreos/etcd/client.(*httpKeysAPI).Get(0xc420134300, 0xd72900, 0xc420012090, 0xc420198061, 0x11, 0xc420146028, 0xc420026e50, 0x909477, 0xc420130290)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/keys.go:422 +0xe1
github.com/docker/libkv/store/etcd.(*Etcd).List(0xc420130290, 0xa95990, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:407 +0xe1
github.com/docker/libkv/store/etcd.(*Etcd).WatchTree.func1(0xc42019a000, 0xc420130290, 0xa95990, 0x11, 0x0, 0xd6c300, 0xc420148080)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:280 +0x79
created by github.com/docker/libkv/store/etcd.(*Etcd).WatchTree
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:276 +0x12f

goroutine 27 [runnable]:
main.callRPC(0xc420130410, 0xc42014c360, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 11 [runnable]:
github.com/docker/libkv/store/etcd.New.func1(0xd74840, 0xc4200549c0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:91
created by github.com/docker/libkv/store/etcd.New
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:91 +0x310

goroutine 37 [IO wait]:
internal/poll.runtime_pollWait(0x7fa3bdd1ef70, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420154498, 0x72, 0xffffffffffffff00, 0xd6e880, 0xd6a3d8)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420154498, 0xc4201b0000, 0x1000, 0x1000)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420154480, 0xc4201b0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc420154480, 0xc4201b0000, 0x1000, 0x1000, 0x42c04b, 0xc420041a40, 0x454230)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420140018, 0xc4201b0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc42016e240, 0xc4201b0000, 0x1000, 0x1000, 0xc420150180, 0xc42019a4d8, 0x452420)
        /usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc42019c6c0)
        /usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc42019c6c0, 0x1, 0x0, 0x0, 0x0, 0xc42019a3c0, 0x0)
        /usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc42016e240)
        /usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 34 [select]:
net/http.(*persistConn).roundTrip(0xc4201a8000, 0xc42013c3f0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1970 +0x608
net/http.(*Transport).RoundTrip(0xda6620, 0xc4201a6000, 0x457e01, 0xa95990, 0x0)
        /usr/local/go/src/net/http/transport.go:413 +0x992
github.com/coreos/etcd/client.(*simpleHTTPClient).Do.func1(0xc42019e000, 0xc4201a6000, 0xc42019c0c0)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:556 +0x41
created by github.com/coreos/etcd/client.(*simpleHTTPClient).Do
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:555 +0x200

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0x7fa3bdd1eeb0, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420120298, 0x72, 0xffffffffffffff00, 0xd6e880, 0xd6a3d8)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420120298, 0xc42008f000, 0x1000, 0x1000)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420120280, 0xc42008f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc420120280, 0xc42008f000, 0x1000, 0x1000, 0x42c04b, 0xc420045a40, 0x454230)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000c4a8, 0xc42008f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc42008d320, 0xc42008f000, 0x1000, 0x1000, 0xc420014440, 0xc42001c5f8, 0x452420)
        /usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc420054900)
        /usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc420054900, 0x1, 0x0, 0x0, 0x0, 0xc42001c4e0, 0x0)
        /usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc42008d320)
        /usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 49 [runnable]:
internal/poll.runtime_pollWait(0x7fa3bdd1edf0, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42014a318, 0x72, 0xffffffffffffff00, 0xd6e880, 0xd6a3d8)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42014a318, 0xc4201bc000, 0x1000, 0x1000)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42014a300, 0xc4201bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc42014a300, 0xc4201bc000, 0x1000, 0x1000, 0xa19a40, 0x1, 0xc42015e180)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc4201ba000, 0xc4201bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc4201a8000, 0xc4201bc000, 0x1000, 0x1000, 0x0, 0x0, 0xc420042b68)
        /usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc4201ac060)
        /usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc4201ac060, 0x1, 0xc4201763c0, 0xc4201b2480, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc4201a8000)
        /usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 38 [select]:
net/http.(*persistConn).writeLoop(0xc42016e240)
        /usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1187 +0xa53

goroutine 50 [select]:
net/http.(*persistConn).writeLoop(0xc4201a8000)
        /usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1187 +0xa53

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc42008d320)
        /usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1187 +0xa53

goroutine 29 [runnable]:
main.callRPC(0xc420130410, 0xc42014c360, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 30 [runnable]:
math/rand.New(...)
        /usr/local/go/src/math/rand/rand.go:65
github.com/coreos/etcd/client.New(0xc4201c0090, 0x1, 0x1, 0xd6fe40, 0xda6620, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/peng/go_workspace/src/github.com/coreos/etcd/client/client.go:215 +0xe6
github.com/docker/libkv/store/etcd.New(0xc4201c0070, 0x1, 0x1, 0x0, 0xc4201562f8, 0x35f3413f5124bf01, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:83 +0x186
github.com/docker/libkv.NewStore(0xa8e4d9, 0x4, 0xc4201c0070, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/libkv.go:31 +0xa0
github.com/smallnest/rpcx/client.NewEtcdDiscovery(0xa95990, 0x11, 0xc4201c0070, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:27 +0xcf
main.callRPC(0xc420130410, 0xc42014c360, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:66 +0xa8
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 31 [runnable]:
main.callRPC(0xc420130410, 0xc42014c360, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 32 [runnable]:
main.callRPC(0xc420130410, 0xc42014c360, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 65 [runnable]:
github.com/docker/libkv/store.CreateEndpoints(0xc42013e200, 0x1, 0x1, 0xa8e559, 0x4, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/helpers.go:8 +0x1e1
github.com/docker/libkv/store/etcd.New(0xc42013e200, 0x1, 0x1, 0x0, 0xc4201562f8, 0x35f3413f5124bf01, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/store/etcd/etcd.go:63 +0x8f
github.com/docker/libkv.NewStore(0xa8e4d9, 0x4, 0xc42013e200, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/docker/libkv/libkv.go:31 +0xa0
github.com/smallnest/rpcx/client.NewEtcdDiscovery(0xa95990, 0x11, 0xc42013e200, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:27 +0xcf
main.callRPC(0xc420130410, 0xc42014c360, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:66 +0xa8
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 66 [runnable]:
main.callRPC(0xc420130410, 0xc42014c360, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 67 [runnable]:
main.callRPC(0xc420130410, 0xc42014c360, 0xa)
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:64
created by main.main
        /Users/peng/go_workspace/src/rpcx-examples3/registry/etcd/client/client.go:52 +0x342

goroutine 12 [runnable]:
github.com/smallnest/rpcx/client.EtcdDiscovery.watch(0xa95990, 0x11, 0xd75d40, 0xc420049c50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:64
created by github.com/smallnest/rpcx/client.NewEtcdDiscovery
        /Users/peng/go_workspace/src/github.com/smallnest/rpcx/client/etcd_discovery.go:34 +0x270

**Comment by smallnest** [comment]
使用最新的代码，基于etcd的例子，没重新这个问题

**Comment by smallnest** [comment]
fixed
