### ISSUE TITLE
Can you update the example of serverPlugin??

### ISSUE THREAD

**Issue by hirorogithub** [smallnest/rpcx#166]
Thx your nice code of rpcx,i am so interested in using rpcx ,but i found that the example may be outdate to your code?
For example ,some args are changed in serverPlugin of etcd ,or can you give me a doc guding me how to use rpcx? 
thx a lot :)

**Comment by smallnest** [comment]
see https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/registry

**Comment by hirorogithub** [comment]
yes i have saw the example ,but for example ,the define of serverPlugin.EtcdRegisterPlugin is 
`type EtcdRegisterPlugin struct {
	// service address, for example, tcp@127.0.0.1:8972, quic@127.0.0.1:1234
	ServiceAddress string
	// etcd addresses
	EtcdServers []string
	// base path for rpcx server, for example com/example/rpcx
	BasePath string
	Metrics  metrics.Registry
	// Registered services
	Services       []string
	metasLock      sync.RWMutex
	metas          map[string]string
	UpdateInterval time.Duration

	Options *store.Config
	KV      store.Store
}`

but the example only offer args like `r := &serverplugin.EtcdRegisterPlugin{
		ServiceAddress: "tcp@" + *addr,
		EtcdServers:    []string{*etcdAddr},
		BasePath:       *basePath,
		Metrics:        metrics.NewRegistry(),
		UpdateInterval: time.Minute,
	}`

**Comment by smallnest** [comment]
See the other two 	args： Options and KV.  Options is a type of libkv.Option and you can see details in libkv project.

KV may be should be changed to `kv` and doesn't be exported Users.

**Comment by hirorogithub** [comment]
thx a lot for your help
