### ISSUE TITLE
need Chinese document

### ISSUE THREAD

**Issue by waterloopwm** [smallnest/rpcx#168]
现在开着google翻译看英文文档,毕竟是翻译,怕有些理解不准,希望作者补上中文文档

**Comment by smallnest** [comment]
The Chinese document is writting:

https://www.gitbook.com/book/smallnest/go-rpc-programming-guide/details

**Comment by yuan520521** [comment]
发的这个链接 第三部分【特性】第四部分【插件开发】 下没有文档

**Comment by smallnest** [comment]
zk,etcd,consul都是第三方的软件，rpcx 只是支持使用他们实现服务发现  @wangwei123

**Comment by lubaoyilang** [comment]
希望可以 补全 中文文档，怕英文理解不准，项目上 不敢上+1

**Comment by smallnest** [comment]
implemented. http://doc.rpcx.site
