### ISSUE TITLE
关于rpc的几个疑问

### ISSUE THREAD

**Issue by g4zhuj** [smallnest/rpcx#17]
1.etcd注册部分目前使用的是定时拉取，其实可以使用watch.
2.client没有加锁，也就是client无法保证线程安全？
3.go原生rpc里的call没有超时，且上层无法感知连接的可用状态，之前我们遇到过网络环境不好时，连接已经不可用，call没有返回，导致大量线程阻塞，大概10多分钟后所有call集体返回超时．针对这种情况该rpc框架也是基于go原生rpc搭建，针对这个问题是否会有所考虑？

**Comment by smallnest** [comment]
谢谢你的comments.
1. 的确是个问题，我考虑改成watch实现，类似zookeeper
2. client是故意这样设计的。每个goroutine可以考虑创建单独的一个client，当然这会带来两个问题：
- 连接数很多
- client数太多
但是可以通过一个client pool来避免。
这么设计的好处代码简单，不需要特别的并发控制
3. 我会调研相关的实现。 连接状态可以通过检查底层的Conn来实现，需要暴露友好的借口。 超时操作可以考虑go 1.7中的 context。这个问题我专门提交一个bug.

多谢你的意见和建议。

**Comment by g4zhuj** [comment]
连接状态检测和超时这个问题因为受原生rpc的限制，貌似不太好解决。
1. 针对链接可用监测，我觉得可以server端注册一个简单类似心跳rpc，client端定时调用，如client端调用超时则直接关掉链接，但是因为主动关闭方是client，所以server端仍然会存在连接端句柄。
2.超时的确可以采用context来进行资源的快速回收。超时监测可以用Go来实现，但如果超时直接返回的话会导致client里等待队列内存泄漏。

**Comment by smallnest** [comment]
implement timeout feature base on net.Comm deadline.
add etcd client watcher

**Comment by smallnest** [comment]
澄清一个误解。
Client其实是可以并发使用的,可以查看rpc.Client的实现，利用使用mutex进行了控制：

```go
func (client *Client) send(call *Call) {
	client.reqMutex.Lock()
	defer client.reqMutex.Unlock()

	// Register this call.
	client.mutex.Lock()
	if client.shutdown || client.closing {
		call.Error = ErrShutdown
		client.mutex.Unlock()
		call.done()
		return
	}
	seq := client.seq
	client.seq++
	client.pending[seq] = call
	client.mutex.Unlock()

	// Encode and send the request.
	client.request.Seq = seq
	client.request.ServiceMethod = call.ServiceMethod
	err := client.codec.WriteRequest(&client.request, call.Args)
	if err != nil {
		client.mutex.Lock()
		call = client.pending[seq]
		delete(client.pending, seq)
		client.mutex.Unlock()
		if call != nil {
			call.Error = err
			call.done()
		}
	}
}
```
