### ISSUE TITLE
services status change does not take effect

### ISSUE THREAD

**Issue by monklee** [smallnest/rpcx#172]
1. in "**func NewEtcdDiscoveryStore**" , 
   "**go d.watch()**" should move after "**d.RetriesAfterWatchFailed = -1**", 
    otherwise "**RetriesAfterWatchFailed**" will always be 0,  
    we can never enter into "**for d.RetriesAfterWatchFailed == -1 || retry > 0 {**".
    same thing for "**NewZookeeperDiscoveryWithStore**" and "**NewConsulDiscoveryStore**"

2. in "**func (c *xClient) watch**", 
    "**c.selector.UpdateServer(servers)**" should be added before "**c.mu.Unlock()**",
    otherwise client can never select the new services map

**Comment by smallnest** [comment]
Thanks a lot for the great found".  fixed
