### ISSUE TITLE
一个结构中 有API接口限制吗？

### ISSUE THREAD

**Issue by normandie199** [smallnest/rpcx#173]
rpcx: failed to handle request: internal error: runtime error: invalid memory address or nil pointer dereference
![image](https://user-images.githubusercontent.com/13691976/32718691-d284d31c-c898-11e7-8898-692241fe15a7.png)

**Comment by smallnest** [comment]
attach your codes otherwise we cann't know what issue you met.

**Comment by normandie199** [comment]
![image](https://user-images.githubusercontent.com/13691976/32721346-266eca16-c8a1-11e7-9e3c-b32fb6bc6f4b.png)

**Comment by normandie199** [comment]
![image](https://user-images.githubusercontent.com/13691976/32721372-36ef2bc4-c8a1-11e7-9169-441a9f6f773f.png)

**Comment by normandie199** [comment]
有群吗  ？  我加下！

**Comment by normandie199** [comment]
![image](https://user-images.githubusercontent.com/13691976/32721410-5c1c8f36-c8a1-11e7-96c7-811f290675de.png)

**Comment by smallnest** [comment]
See Readme.

没看到你的的关键的client和service的实现， 不过从第一个log看起来你的service的的某个方法中可能某个变量没有初始化。

**Comment by normandie199** [comment]
我贴下

**Comment by normandie199** [comment]
![image](https://user-images.githubusercontent.com/13691976/32722239-3d2466d2-c8a4-11e7-85cd-80900b5eab43.png)

**Comment by normandie199** [comment]
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/13691976/32722280-5c4ef66c-c8a4-11e7-8fc7-46c9af0d861b.png">

**Comment by normandie199** [comment]
我其他的接口都可以！   就这个API不行，我还没有时间看rpcx的底层代码，是不是底层的functional map 没有搞好？？

**Comment by smallnest** [comment]
看看`AddTopHundred`中的`fmt.Println(..........)`那一句打印出来了吗? 加些log看看在哪个地方报的错。
我怀疑是`libpurge. AddTopHundred `抛的错， 内部有变量未初始化

**Comment by normandie199** [comment]
![image](https://user-images.githubusercontent.com/13691976/32722606-610e3432-c8a5-11e7-9e5b-7a57a6d3f31a.png)

**Comment by normandie199** [comment]
![image](https://user-images.githubusercontent.com/13691976/32722631-76164004-c8a5-11e7-810a-4be94c8bf758.png)

**Comment by normandie199** [comment]
程序没有core！

**Comment by smallnest** [comment]
第一句 `internal error .......`表明是service 实现的问题。在你的`AddTopOneHunred`加上`recover`看看错误在哪里。

**Comment by smallnest** [comment]
查看模拟你这种情况的例子：

https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/nil_panic
