### ISSUE TITLE
关于SelectMode的 问题

### ISSUE THREAD

**Issue by joy-chenjh** [smallnest/rpcx#174]
**1.NewXClient 中的client.selector 初始化顺序问题.**  

client.selector 是在 client.selector = newSelector(selectMode, servers)中初始化的. 但是在go client.watch(ch) 可能会先运行到c.selector.UpdateServer(servers) 会导致panic 

2017/11/15 10:15:40 net listen [:9099] ok
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1664dbb]

goroutine 53 [running]:
github.com/smallnest/rpcx/client.(*xClient).watch(0xc4202a6240, 0xc42029e180)
	xxxxxx/src/github.com/smallnest/rpcx/client/xclient.go:133 +0x12b
created by github.com/smallnest/rpcx/client.NewXClient
	xxxxxx/src/github.com/smallnest/rpcx/client/xclient.go:84 +0x390

```go 
func NewXClient(servicePath string, failMode FailMode, selectMode SelectMode, discovery ServiceDiscovery, option Option) XClient {
	client := &xClient{
		failMode:     failMode,
		selectMode:   selectMode,
		discovery:    discovery,
		servicePath:  servicePath,
		cachedClient: make(map[string]RPCClient),
		option:       option,
	}

	ch := client.discovery.WatchService()
	if ch != nil {
		go client.watch(ch)
	}

	servers := make(map[string]string)
	pairs := discovery.GetServices()
	for _, p := range pairs {
		servers[p.Key] = p.Value
	}
	client.servers = servers
	if selectMode != Closest && selectMode != SelectByUser {
		client.selector = newSelector(selectMode, servers)
	}

	client.Plugins = &pluginContainer{}
	return client
}
```

**2. selectMode中的 SelectByUser模式中初始化问题**  

由于在NewXClient中的go client.watch(ch) 中会直接使用selector.  没有办法进行初始化.

**3. selectMode中的 Closest模式应该是已经不支持了.**

**Comment by smallnest** [comment]
fixed. thanks
