### ISSUE TITLE
 error is %!(EXTRA *errors.errorString=breaker open)

### ISSUE THREAD

**Issue by leepengg** [smallnest/rpcx#179]
client 配置：

optionD := new(store.Config)
	optionD.ConnectionTimeout = 15 * time.Second
	d := client.NewEtcdDiscovery(*basePath, common.UserServiceName, []string{*etcdAddr}, optionD)

	option := client.DefaultOption
	option.SerializeType = protocol.ProtoBuffer
	client := client.NewXClient(common.UserServiceName, client.Failtry, client.RandomSelect, d, option)
	defer client.Close()

同一个client连续调用后出现 breaker open 错误

**Comment by smallnest** [comment]
这是熔断器模式， see #127.

当一个节点在一定时间内总是返回错误会暂时标记它为不可用。

如果不想使用熔断器模式，将Option中的Breaker置为nil
