### ISSUE TITLE
undefined: serverplugin.ConsulRegisterPlugin

### ISSUE THREAD

**Issue by yukui** [smallnest/rpcx#181]
https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/registry/consul
使用这个示例中出现：
  ./server.go:33:8: undefined: serverplugin.ConsulRegisterPlugin  

另外请问consul在rpcx中怎么使用，有相关示例代码么？

**Comment by smallnest** [comment]
see thre readme and documents for using plugins such as zk, etcd, consul, ping

**Comment by yukui** [comment]
Sorry, 执行命令是  go run -tags consul server.go ，没加tags参数

**Comment by ha666** [comment]
![1](https://user-images.githubusercontent.com/4374328/61573657-f5865e00-aae4-11e9-8b9b-c97a2afd6d8e.jpg)
![2](https://user-images.githubusercontent.com/4374328/61573661-fc14d580-aae4-11e9-8241-363fb3b6dfd8.jpg)
![3](https://user-images.githubusercontent.com/4374328/61573663-ff0fc600-aae4-11e9-96cc-73d1d908cb66.jpg)
