### ISSUE TITLE
can call rpcx via http without rpcx gateway

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#183]
currently You can call rpcx services via http protocol by rpcx-gateway. Next step we will add  raw http support in rpcx server.

**Comment by wangwanttt** [comment]
rpcx-gateway  中的  
case "consul":
		return client.NewConsulDiscovery(*basePath, "Login", []string{regAddr}, nil), nil
应该配什么参数啊，我配好后，http访问出错 socket hang up
