### ISSUE TITLE
rpcx.Register: type Arith has no exported methods of suitable type

### ISSUE THREAD

**Issue by widon1104** [smallnest/rpcx#184]
widon@widon-desktop:~/go/src/RpcxTest/server$ ./server 
2017/12/05 11:40:25 service.go:137: INFO : methodErrorhas wrong number of ins:3
2017/12/05 11:40:25 service.go:137: INFO : methodMulhas wrong number of ins:3
2017/12/05 11:40:25 service.go:115: **ERROR: rpcx.Register: type Arith has no exported methods of suitable type**

//代码如下，运行时报错，这是为什么啊？
```
package  main

import "github.com/smallnest/rpcx/server"

type Args struct {
	A int `msg:"a"`
	B int `msg:"b"`
}
type Reply struct {
	C int `msg:"c"`
}

type Arith int

func (t *Arith) Mul(args *Args, reply *Reply) error {
	reply.C = args.A * args.B
	return nil
}
func (t *Arith) Error(args *Args, reply *Reply) error {
	panic("ERROR")
	return nil
}
func main() {
	server := server.NewServer()
	server.RegisterName("Arith", new(Arith), "")
	server.Serve("tcp", "127.0.0.1:8972")
}

```

**Comment by smallnest** [comment]
see the readme, run examples in rpcx-examples. Your code is for rpcx 2.0
