### ISSUE TITLE
使用consul进行服务发现错误

### ISSUE THREAD

**Issue by juexun** [smallnest/rpcx#185]
基于consul的方式下，xClient.watch中UpdateSelector会导致 Server的格式出错，从而导致客户端调用失败

错误信息如下：
2017/12/08 16:39:27 connection.go:75: ERROR: failed to dial server: dial rpcx_test/Arith/tcp: unknown network rpcx_test/Arith/tcp

重现方式：
修改client.go

多次调用Call，第一次能执行成功，二三次之后就会开始报错，如上
```
for { 
		err := xclient.Call(context.Background(), "Mul", args, reply)
		if err != nil {
			log.Fatalf("failed to call: %v", err)
		}

		log.Printf("%d * %d = %d", args.A, args.B, reply.C)

		time.Sleep(5*time.Second)
	}
```

**Comment by smallnest** [comment]
fixed. 

Must trim basepath for consul descovery
