### ISSUE TITLE
xClient.Close() 没有关闭 discovery 线程，导致 service watch channel 满

### ISSUE THREAD

**Issue by juexun** [smallnest/rpcx#186]
运行一段时间后，会提示错误如下：

2017/12/12 22:48:05 consul_discovery.go:133: WARN : chan is full and new change has ben dropped
2017/12/12 22:48:14 consul_discovery.go:133: WARN : chan is full and new change has ben dropped
2017/12/12 22:48:15 consul_discovery.go:133: WARN : chan is full and new change has ben dropped
2017/12/12 22:48:18 consul_discovery.go:133: WARN : chan is full and new change has ben dropped
2017/12/12 22:48:19 consul_discovery.go:133: WARN : chan is full and new change has ben dropped
2017/12/12 22:48:19 consul_discovery.go:133: WARN : chan is full and new change has ben dropped
2017/12/12 22:48:24 consul_discovery.go:133: WARN : chan is full and new change has ben dropped

**Comment by smallnest** [comment]
fixed, thansk

**Comment by tentree** [comment]
> fixed, thansk

代码好像并没有起作用，还是会出现调用后watch的连接没有清理的状况。
![image](https://user-images.githubusercontent.com/46660079/52632150-aa479e00-2efb-11e9-899d-f4e188492bf6.png)

**Comment by tentree** [comment]
> > fixed, thansk
> 
> 代码好像并没有起作用，还是会出现调用后watch的连接没有清理的状况。
> ![image](https://user-images.githubusercontent.com/46660079/52632150-aa479e00-2efb-11e9-899d-f4e188492bf6.png)

已经找到替代方案了，使用https://github.com/rpcx-ecosystem/rpcx-examples3/blob/master/registry/consul_pool/client/client.go中的方式即可。
