### ISSUE TITLE
Too many files open (consul discovery)

### ISSUE THREAD

**Issue by alidehghan** [smallnest/rpcx#187]
Hello,

 I tested rpcx with Consul discovery for over 500 concurrent requests and it encountered  "too many files open" error. **"consul_discovery.go:126: WARN : chan is closed and will rewatch"** is shown. It seems that a close operation over a socket has been missed. Might you please investigate this situation?

Many thanks in advance

**Comment by smallnest** [comment]
Did create over 500 concurent xclients? Did you increase your `open files limit` with `ulimit -n` for concurrent test? 

"consul_discovery.go:126: WARN : chan is closed and will rewatch"  is an warn that the watch connection to consul is closed. I suspected your `open files limit` was too small. You can check with `ulimit -a`.

**Comment by alidehghan** [comment]
I guess I found the root cause of problem in my case. I am creating a new XClient for each rpc call and close it via defer, while even after closing, the channel used for watching is active and sending requests to consul. I tried to cache the client through putting a single instance of XClient within `var` section, but when calling it at `client.Go(getContext(), serviceMethod, req, res, nil)`, server addresses could not be fetched from consul.

**Comment by smallnest** [comment]
did you set your basepath in client? 
basepath must be same to the defined in services. For your case, it should be `Services`

**Comment by alidehghan** [comment]
Yes, I did. Actually my code is like this: 
`registry := client.NewConsulDiscovery("/Services", "User", []string{*consulAddr}, nil)
rpcxXClient := client.NewXClient("User", client.Failtry, client.RoundRobin, registry, cfg)
return &Endpoint{rpcx:&rpcxXClient}`.

The strange thing is that when I use this `rpcxXClient` directly (no calling from other functions) it perfectly runs (and resolves services address from consul), but when I put it in a variable and pass through a struct to other functions to be called, it fails.

**Comment by alidehghan** [comment]
I changed my code into this:

`userServiceClientPool = sync.Pool{New: func() interface{} {
		clientCfg := xClient.DefaultOption
		clientCfg.SerializeType = protocol.ProtoBuffer
		clientCfg.TLSConfig = tlsConfig
		r := xClient.NewConsulDiscovery(microServiceBaseUrl, microServiceUsersUrl, []string{*consulAddr}, nil)
		c := xClient.NewXClient(microServiceUsersUrl, xClient.Failtry, xClient.RoundRobin, r, clientCfg)

		c.Auth(microserviceAuth)
		return c
	}}
`

in this case, when I get a new instance from pool `client:=userServiceClientPool.Get()`, it works, but when I return the client into pool through userServiceClientPool.Put(client), consulDiscovery could not find the services and encounters previously mentioned error *`failed to dial server: dial Services/User/tcp: unknown network Services/User/tcp`*.

May you please provide a sample for using XClient within memory pool (like sync.Pool) using consul to use between threads and goroutines?

Thanks in advance

**Comment by alidehghan** [comment]
I noticed the problem, I will open a new issue with more relevant topic.
