### ISSUE TITLE
Bug in updating servers in Selector module

### ISSUE THREAD

**Issue by alidehghan** [smallnest/rpcx#188]
After digging XClient, I noticed a probably bug which occurs in `watch` function in `xclient` file. To be exact, at the line 123. When a client is created for the first time with any selector (in my case, RoundRobin), `client.servers` is correctly filled with this template (`tcp@ip:port`), and after successfully dialing the address, `watch` function is called to update the server addresses. In this function, addresses of servers is given as `BaseUrl/MethodName/tcp@ip:port` which makes the next consecutive calls (dialing) encounters error. Could you please take a look at the code and correct that? or inform me when I am making mistake.

Thanks

**Comment by smallnest** [comment]
see example: https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/registry/consul_pool
I can't reproduce your issue.

I think the commit has fixed your issue and you should update rpcx lib.

https://github.com/smallnest/rpcx/commit/901bdef54248fd556868f80e97fd75fe28292f8f

**Comment by smallnest** [comment]
see my example, if you can provide reproducable code, may I can find whether there is any issue.

When services are changed in consul, for example, add more nodes for this service **Services/User**, ConsulDiscovery can get those info and it also trims the prefix **Services/User**, so the dialing uses `tcp@127.0.0.1:8888`, not `Services/User/tcp@127.0.0.1:8888`.

To say briefly， ConsulDiscovery can handle prefix.

**Comment by alidehghan** [comment]
Actually, `splitNetworkAndAddress` can't split the string correctly.  In my case, server parameter is `Services/User/tcp@127.0.0.1:8888` and first returning output of this function is **Services/User/tcp** whereas should be **tcp**. I changed the code (for testing) as follows and problem solved. 

```go 
func splitNetworkAndAddress(server string) (string, string) {
	ss := strings.SplitN(server, "@", 2)
	return "tcp", ss[1]
	/*if len(ss) == 1 {
		return "tcp", server
	}

	return ss[0], ss[1]
	*/
}```

**Comment by smallnest** [comment]
I think you misunderstood it.

See https://github.com/smallnest/rpcx/blob/master/client/consul_discovery.go#L67 

What you got is `tcp@127.0.0.1:8888`, not `Services/User/tcp@127.0.0.1:8888`

**Comment by alidehghan** [comment]
Thank you
