### ISSUE TITLE
is there any way for nodejs to use rpcx?

### ISSUE THREAD

**Issue by VarDking** [smallnest/rpcx#197]

**Comment by smallnest** [comment]
If you talk about clients, the answer is **YES**.

There are three approaches to write node.js clients (or clients in other programming languages).

- [rpcx-gateway](https://github.com/rpcx-ecosystem/rpcx-gateway): you can check [examples](https://github.com/rpcx-ecosystem/rpcx-gateway/tree/master/examples) to learn how to write clients. Clients send http requests to rpcx-gateway and rpcx-gateway redirects requests to rpcx services. **recommend**

- http invoke: you can send http requests like rpcx-gateway to rpcx services directly.

- raw rpcx protocol: you can write a node.js rpcx protocol to communicate rpcx services. You can learn protocol in rpcx documents.
