### ISSUE TITLE
Does rpcx support game development?

### ISSUE THREAD

**Issue by ckcfcc** [smallnest/rpcx#207]
大概阅读了下文档，请教以下几个问题，主要想在网游中使用。

1、客户端是否可以通过一个连接持续调用各种不同的服务，而不用每次调用都重连？
2、当一个客户端连接上时，客户端发送一个订阅请求后，某个服务是否能主动的，持续的发送需要的内容到客户端？
3、如果支持1，那么有没有目前的负载测试？

谢谢

**Comment by smallnest** [comment]
支持。
1. 一个应用(进程)只需创建一个OneClient实例即可，see https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/oneclient.

2. rpcx支持双向的通讯，一旦客户端调用一次之后，服务器可以不断地发送指令， 如 https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/bidirectional

3. benchmark代码参看 https://github.com/rpcx-ecosystem/rpcx-benchmark,  同步调用的情况下比grpc快50%左右， 异步的调用情况没测，肯定更快。
