### ISSUE TITLE
set value in context in plugin functions

### ISSUE THREAD

**Issue by ssrlxl** [smallnest/rpcx#208]
我的需求是想在插件PreReadRequest函数，通过context.WithValue(ctx, "mgo", "xxxx")给context带上参数，但是目前的实现，不容许我回传新的ctx

这个是基于什么考虑呢，再不改代码的情况下，有没有其他方法呢

**Comment by smallnest** [comment]
`context.WithValue(ctx, "mgo", "xxxx")`是新生成一个新的context,它的scope只在PreReadRequest函数内，无法更改原`ctx`

**Comment by ssrlxl** [comment]
我的意思是能不能把PreReadRequest这个接口改一下，容许我把最新的ctx传给底层接口

**Comment by smallnest** [comment]
try `ctx.getValue(share.ReqMetaDataKey)`

**Comment by smallnest** [comment]
目前没有办法。未来可以考虑把PreReadRequest的第一个接口换成`*context.Context`, 不过一般`context.Context`很少有这样的操作。

**Comment by smallnest** [comment]
你可以实现下面的接口,这个接口会在服务方法执行之前调用：
```
type PostReadRequestPlugin interface {
    PostReadRequest(ctx context.Context, r *protocol.Message, e error) error
}
```

通过它的context得到一个map值:
```
reqMeta := ctx.Value(share.ReqMetaDataKey).(map[string]string)
```
