### ISSUE TITLE
How to use rpcx like grpc Interceptor

### ISSUE THREAD

**Issue by guoyoujin** [smallnest/rpcx#209]
How to use `grpc` Interceptor

`grpc` for example 
```
grpc.NewServer(Interceptor)
```
How should `rpcx` use interceptors?

**Comment by guoyoujin** [comment]
看了你给的文档你指的是这个[https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/trace](https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/trace)吗？
具体如何使用呢？看`examples3`里面的`trace`例子没看明白如何使用。比如自定义实现一个`app_id,app_token`的验证，就类似java的拦截器，在发起请求前进行一些操作（比如数据加密），在接收请求后预处理数据（比如数据解密），具体类似下面的`grpc middleware插`件
[https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/trace](https://github.com/grpc-ecosystem/go-grpc-middleware)

**Comment by smallnest** [comment]
1. 如果只是身份认证，rpcx提供了Auth接口，你可以接入你的oauth2或者jws
https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/auth

2. 你可以用metadata传递额外的信息
https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/metadata
这个例子是在服务中读取metadata。如果你想实现通用的拦截，可以实现下面的接口

```go
type PostReadRequestPlugin interface {
    PostReadRequest(ctx context.Context, r *protocol.Message, e error) error
}
```
通过 `reqMeta := ctx.Value(share.ReqMetaDataKey).(map[string]string)` 读取客户端传递的metadata

3. 如果你的信息是在参数里， 你实现`PostReadRequestPlugin `接口即可。

**Comment by smallnest** [comment]
参考trace实现： https://github.com/smallnest/rpcx/blob/master/serverplugin/trace.go

定义一个struct, 实现`PostReadRequest`方法：

```go
func (p *TracePlugin) PostReadRequest(ctx context.Context, r *protocol.Message, e error) error {
	tr := trace.New("rpcx.Server", "ReadRequest")
	defer tr.Finish()
	tr.LazyPrintf("read request %s.%s, seq: %d", r.ServicePath, r.ServiceMethod, r.Seq())
	return nil
}
```
你可以在这个方法中做你的拦截操作，如果返回error，则直接返回给clienty error, 否则会继续调用服务

把你的这个plugin加入到server的plugin容器中即生效。

```go
       s := server.NewServer()
	traceP := &serverplugin.TracePlugin{}
	s.Plugins.Add(traceP)
```

**Comment by smallnest** [comment]
你更新一下代码， 我刚刚fix. 

先前的代码没有处理插件的error,直接抛弃了

**Comment by guoyoujin** [comment]
好的，谢谢啦
