### ISSUE TITLE
服务集群的权重问题

### ISSUE THREAD

**Issue by g4zhuj** [smallnest/rpcx#21]
刚看了之前提的问题, 解决的很棒!

目前框架内分配内服务的分配策略有随机,轮训,以及一致性hash.其实这里还缺少按权重分配策略,如加权轮训,加权随机,以及加权一致性hash.权重可通过服务定期向zookeeper等上报,client获取到权重后进行加权分配.
这样解决相同服务部署多个在不同服务器上时,主机硬件配置不一致,主机之间负载不均衡等情况下的负载均衡问题.

**Comment by smallnest** [comment]
谢谢你的建议，我会考虑加上，或者提供一个接口。 
另外还提供基于路由的选择，在同一个数据中心的client/server的权重更高。

如果你有什么建议，非常欢迎提出来，谢谢。

**Comment by smallnest** [comment]
implemented smooth weight roundrobin just like Nginx.
currently set the weight when  register a service. 

Will explore weight updating  api and update services' weight on web GUI.
