### ISSUE TITLE
rpcx server解析请求时解析请求大小出bug导致内存剧增

### ISSUE THREAD

**Issue by histalk** [smallnest/rpcx#210]
查看服务器内存，偶然发现内存剧增1.8G，通过go tool pprof 发现如下：
![rpcx](https://user-images.githubusercontent.com/24246018/38924323-40a3a2a4-432f-11e8-94a9-87be5f582aa6.PNG)

![rpcx2](https://user-images.githubusercontent.com/24246018/38924473-a0771df0-432f-11e8-95ed-04780d8a365d.PNG)

问题出在 data := make([]byte, int(l)) 瞬间消耗大量内存；

该问题只出现过一次，无法再次重现，对int(l)数值的异常排查无果，目前先通过
`protocol.MaxMessageLength = 10 * 1024 * 1024 //限制每个rpc请求大小不超过10M`
进行抑制

**Comment by smallnest** [comment]
客户端也是rpcx?  有恶意攻击？

**Comment by histalk** [comment]
客户端也是rpcx，没有发现恶意攻击的迹象，请求频率峰值不超过每秒30个，请求大小小于1KB；运行64位系统下的docker容器;
服务器启动到现在处理了7万个请求，时长两个星期，只重现了一次，目前尚未重启，内存仍未被释放，估计还在pool中
```
Linux version 3.10.0-514.6.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Thu Feb 23 03:04:39 UTC 2017
```
使用了自己写的codec；
```golang
type RpcBean []byte

type PkgCodec struct {
}

func (c *PkgCodec) Encode(i interface{}) ([]byte, error) {
	if data, ok := i.(*RpcBean); ok {
		return *data, nil
	}
	return nil, fmt.Errorf("%T is not a []byte", i)
}

func (c *PkgCodec) Decode(data []byte, i interface{}) error {
	*i.(*RpcBean) = RpcBean(data)
	return nil
}
```

**Comment by histalk** [comment]
非常感谢。
没有被垃圾回收只是业务逻辑导致；

**Comment by zch1221** [comment]
![1702024379125](https://github.com/smallnest/rpcx/assets/31136805/ebd7e96f-9cc9-4672-81db-8c1af26178c8)
