### ISSUE TITLE
请问作者 这里面的 心跳 描述的很少

### ISSUE THREAD

**Issue by shachao888** [smallnest/rpcx#214]
请问作者 clicent这里面的 心跳 描述的很少。要是在client  设置了这个一个心跳，是不是就是等于有了一个链接，还是 有了一个连接池？ 我设置了一个心跳，能应对并发么？

**Comment by smallnest** [comment]
单个xclient总是使用**一个**连接来和某个特定的服务器通讯。因为协议是异步的，所以不必担心性能的问题。 如果设置了heartbeat， xclient会自动定时的发送心跳以保持这个连接是活着的。

如果你担心性能不够，你可以创建xclient pool,当然我不认为这是必要的。

**Comment by shachao888** [comment]
我设置一个全局的 client 链接 并保持心跳，我在使用 xclients.Call 的时候 报  WARN : failed to dial server: dial tcp 127.0.0.0:8972: i/o timeout 请问 这是什么问题呢？

**Comment by shachao888** [comment]
那这个大概是一个什么问题呢？困扰了很久了

**Comment by smallnest** [comment]
错误信息已经告诉你了： 

> 127.0.0.0:8972

client连接这个服务器端口连不上，根据相关技术检查相关端口

**Comment by smallnest** [comment]
假定问题是部署的问题，应该和服务器启动顺序或者网络环境相关，和rpcx本身没关，所以关闭了此issue。

如果有其它问题， 提交相关的测试代码和测试步骤以便分析。
