### ISSUE TITLE
Compression issue

### ISSUE THREAD

**Issue by ssh777** [smallnest/rpcx#215]
Decoder always raises an error "msgpack: invalid code=1f decoding map length" in case of using []byte field inside *args struct for XClients with CompressType Gzip

**Comment by ssh777** [comment]
thx, we will expect this example. especcially for 3.x version

**Comment by smallnest** [comment]
the example has been added:

https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/compress

**Comment by ssh777** [comment]
thx a lot!
