### ISSUE TITLE
undefined: serverplugin.EtcdRegisterPlugin

### ISSUE THREAD

**Issue by mini-bix** [smallnest/rpcx#217]
安装好后无法得到serverplugin.EtcdRegisterPlugin，依赖包已经安装好，还需要做什么操作呢

**Comment by smallnest** [comment]
see tags introduction in readme

**Comment by w01fb0ss** [comment]
我也遇到了同样的问题，，，，

**Comment by airplayx** [comment]
go run -tags=etcd main.go
