### ISSUE TITLE
when does rpcx can use etcdv3?

### ISSUE THREAD

**Issue by blessswei** [smallnest/rpcx#219]

**Comment by smallnest** [comment]
rpcx support etcdv3.

rpcx uses libkv to access etcd and libkv supports etcdv2 and etcdv3.

**Comment by blessswei** [comment]
Thank you for your answer. But I have read etcd package of libkv and not
found the support to etcdv3.

The following is a fragment from libkv:


   - Etcd versions >= 2.0 because it uses the new coreos/etcd/client, this
   might change in the future as the support for APIv3 comes along and adds
   more capabilities.



2018-05-12 20:10 GMT+08:00 smallnest <notifications@github.com>:

**Comment by smallnest** [comment]
It uses apiv2 but It supports etcdv3
