### ISSUE TITLE
什么时候支持多种语言，尤其是对于ios/android

### ISSUE THREAD

**Issue by arden** [smallnest/rpcx#22]
什么时候支持多种语言，尤其是对于ios/android ?

**Comment by smallnest** [comment]
rpcx不适合跨语言开发。
对于ios/android 可以考虑 http api + 特定的序列化框架,这样容易实现跨语言(xml,json, protobuf或者其它)。Go有相当多的高性能的web框架， 比如 https://github.com/smallnest/go-web-framework-benchmark 项目中列出的。

**Comment by smallnest** [comment]
implemented JSON-RPC and JSON-RPC2.
so ios/android can call services of rpcx with JSON-RPC2 spec
