### ISSUE TITLE
请问 client 连接断开之后 server 端对应的调用如何终止？

### ISSUE THREAD

**Issue by wangzhuzhen** [smallnest/rpcx#223]
我用 rpcx 写了个简单的流处理的服务，client 端提交相关参数到 server 端，server 端根据提供的参数连接到 kafka，读取指定 topic 的数据，然后进行处理。

我这边希望达到的一个特定场景是客户端程序kill掉之后，服务端对应的处理流程发现 client 连接断开后就不再去读取 kafka的数据、不再进行处理了。

我对 RPC 原理细节了解不多，不知道这个场景是否有实现示例

**Comment by smallnest** [comment]
服务端提供start,status,stop方法， 客户端退出的时候调用stop方法

**Comment by wangzhuzhen** [comment]
@smallnest 

你好，上次按照你的指导之后，解决了问题。

我现在有个新的问题，请你指导一下：

client 端提交相关参数到 server 端，server 端根据提供的参数连接到 kafka，读取指定 topic 的数据，然后进行处理。整个过程类似于流处理，但是server 端处理后的结果并不需要返回给client 端。如果 client 端和 server 端都是以 docker 容器的方式部署，这样在 docker stop 停止 client 端的容器之后，实际上客户端由于捕获不到类似 kill -9 这种操作的信号，导致 server 端不能发现 client 端已经被 kill 掉，这样 server 端也就接收不到 stop 方法，仍在处理。

是否有参数或者什么方式能让 server 端自动识别对应的 client 已经断开？
