### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by mini-bix** [smallnest/rpcx#227]
fatal error: concurrent map writes

goroutine 100 [running]:
runtime.throw(0xeddcd0, 0x15)
        /usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc423d9ae40 sp=0xc423d9ae20 pc=0x42b9c5
runtime.mapassign(0xd6e2a0, 0xc422e09890, 0xc42323eeb0, 0xd039a0)
        /usr/local/go/src/runtime/hashmap.go:535 +0x643 fp=0xc423d9aed8 sp=0xc423d9ae40 pc=0x409103
reflect.mapassign(0xd6e2a0, 0xc422e09890, 0xc42323eeb0, 0xc422e098c0)
        /usr/local/go/src/runtime/hashmap.go:1228 +0x3f fp=0xc423d9af08 sp=0xc423d9aed8 pc=0x40b20f
reflect.Value.SetMapIndex(0xd6e2a0, 0xc42165c760, 0x195, 0xd11720, 0xc42323eeb0, 0x98, 0xdd6060, 0xc422e098c0, 0x199)
        /usr/local/go/src/reflect/value.go:1499 +0x1f6 fp=0xc423d9af78 sp=0xc423d9af08 pc=0x4bc996
encoding/json.(*decodeState).object(0xc422b46120, 0xd6e2a0, 0xc42165c760, 0x195)
        /usr/local/go/src/encoding/json/decode.go:773 +0xa94 fp=0xc423d9b1c8 sp=0xc423d9af78 pc=0x6e3e04
encoding/json.(*decodeState).value(0xc422b46120, 0xd6e2a0, 0xc42165c760, 0x195)
        /usr/local/go/src/encoding/json/decode.go:405 +0x2e4 fp=0xc423d9b248 sp=0xc423d9b1c8 pc=0x6e2044
encoding/json.(*decodeState).object(0xc422b46120, 0xe19240, 0xc42165c708, 0x199)
        /usr/local/go/src/encoding/json/decode.go:736 +0x1284 fp=0xc423d9b498 sp=0xc423d9b248 pc=0x6e45f4
encoding/json.(*decodeState).value(0xc422b46120, 0xe19240, 0xc42165c708, 0x199)
        /usr/local/go/src/encoding/json/decode.go:405 +0x2e4 fp=0xc423d9b518 sp=0xc423d9b498 pc=0x6e2044
encoding/json.(*decodeState).object(0xc422b46120, 0xcccc80, 0xc4216853c0, 0x196)
        /usr/local/go/src/encoding/json/decode.go:736 +0x1284 fp=0xc423d9b768 sp=0xc423d9b518 pc=0x6e45f4
encoding/json.(*decodeState).value(0xc422b46120, 0xcccc80, 0xc4216853c0, 0x196)
        /usr/local/go/src/encoding/json/decode.go:405 +0x2e4 fp=0xc423d9b7e8 sp=0xc423d9b768 pc=0x6e2044
encoding/json.(*decodeState).array(0xc422b46120, 0xcfa060, 0xc42498b9c8, 0x197)
        /usr/local/go/src/encoding/json/decode.go:558 +0x1d6 fp=0xc423d9b908 sp=0xc423d9b7e8 pc=0x6e2986
encoding/json.(*decodeState).value(0xc422b46120, 0xcfa060, 0xc42498b9c8, 0x197)
        /usr/local/go/src/encoding/json/decode.go:402 +0x277 fp=0xc423d9b988 sp=0xc423d9b908 pc=0x6e1fd7
encoding/json.(*decodeState).object(0xc422b46120, 0xcce840, 0xc42498b9c0, 0x16)
        /usr/local/go/src/encoding/json/decode.go:736 +0x1284 fp=0xc423d9bbd8 sp=0xc423d9b988 pc=0x6e45f4
encoding/json.(*decodeState).value(0xc422b46120, 0xcce840, 0xc42498b9c0, 0x16)
        /usr/local/go/src/encoding/json/decode.go:405 +0x2e4 fp=0xc423d9bc58 sp=0xc423d9bbd8 pc=0x6e2044
encoding/json.(*decodeState).unmarshal(0xc422b46120, 0xcce840, 0xc42498b9c0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/decode.go:187 +0x20e fp=0xc423d9bcd0 sp=0xc423d9bc58 pc=0x6e14ce
encoding/json.Unmarshal(0xc424500821, 0x200, 0x710, 0xcce840, 0xc42498b9c0, 0x1, 0x68782fc22030b720)
        /usr/local/go/src/encoding/json/decode.go:107 +0x148 fp=0xc423d9bd18 sp=0xc423d9bcd0 pc=0x6e0e98
_/Users/zrq/server/src/utils/rpcx-master/codec.JSONCodec.Decode(0xc424500821, 0x200, 0x710, 0xcce840, 0xc42498b9c0, 0x13cf380, 0xc42008cd20)
        /Users/zrq/server/src/utils/rpcx-master/codec/codec.go:51 +0x53 fp=0xc423d9bd60 sp=0xc423d9bd18 pc=0x8cb543
_/Users/zrq/server/src/utils/rpcx-master/codec.(*JSONCodec).Decode(0x13fb8c0, 0xc424500821, 0x200, 0x710, 0xcce840, 0xc42498b9c0, 0x0, 0x0)
        <autogenerated>:1 +0x66 fp=0xc423d9bda8 sp=0xc423d9bd60 pc=0x8cc336
_/Users/zrq/server/src/utils/rpcx-master/client.(*Client).input(0xc423a93040)
        /Users/zrq/server/src/utils/rpcx-master/client/client.go:536 +0x5ef fp=0xc423d9bfd8 sp=0xc423d9bda8 pc=0xb4b9bf
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc423d9bfe0 sp=0xc423d9bfd8 pc=0x45c181
created by _/Users/zrq/server/src/utils/rpcx-master/client.(*Client).Connect
        /Users/zrq/server/src/utils/rpcx-master/client/connection.go:56 +0x22d

**Comment by smallnest** [comment]
看起来你函数的返回值有个字段是map类型的，并且你这个返回值在多个goroutine调用。检查你的逻辑避免这个值被并发访问
