### ISSUE TITLE
add traceid plugin

### ISSUE THREAD

**Issue by goodjava** [smallnest/rpcx#232]
client->server1->server2->server3   这个调用顺序下,server1 能拿到唯一的traceId,后续的server也可以拿到,方便问题排查,性能分析

**Comment by fastcgi** [comment]
其实这个问题，只要开放 一个  `SetLogger()` 就可以了，目前 `rpcx`的 `logger` 全部都是写死用内部的。

例如 
https://github.com/smallnest/rpcx/blob/bd147a4ffc486503ec54f7ebb74da862e723eb37/server/server.go#L230

`log.Errorf("rpcx: Accept error: %v; retrying in %v", e, tempDelay)`

**微服务一般都会用上 ELK 之类的日志收集，格式一般也就是 json 或者 xml 了**， 建议开放 `Logger` 接口，可以让我们启动服务的时候， 通过 `options` 指定我们自己实现了你的接口的 日志。这样子才真正解决了问题。

加一个 `traceID` 没有从根本上解决这个问题。

**Comment by fastcgi** [comment]
## 如果仅仅只是要一个 `TraceID`，通过`Context`即可解决了

```go
       // ContextKey defines key type in context.
        type ContextKey string
        m := make(map[ContextKey]string)
	m[WeChatAppIDKey] = opt.WeChatAppID
	m[WeChatSecretKey] = opt.WeChatSecret
	m[RequestIDKey] = opt.RequestID
        //  ........  这里还可以放  instanceID 之类的
	return context.WithValue(context.Background(), share.ReqMetaDataKey, m)
```

然后在 提供服务的方法里面获取`rpcx`的上下文中的追溯信息即可，


```go
func (m *Wechat) AccessToken(ctx context.Context, nilData *rpc.NilData, reply *rpc.String) error {
	m := ctx.Value(share.ReqMetaDataKey).(map[ContextKey]string)
	// ...  这里 就可以随意选择一个 日志库来处理  日志追踪了
}
```

**Comment by smallnest** [comment]
rpcx的log是可插拔的， see  https://github.com/smallnest/rpcx/blob/2191cb993b0dc1ca15d1dc859c11fcf49dbb3100/log/logger.go#L34

**Comment by fastcgi** [comment]
@smallnest 感谢指出问题。 抱歉，没有仔细去看，其实已经提供了这个方法。😶

`TraceID` 上面说的用 上下文来传递，应该就 ok 了吧？

**Comment by smallnest** [comment]
是的。

opentracing也是类似的方式

**Comment by smallnest** [comment]
change its implementation in 5.0. Must support opentracing

**Comment by smallnest** [comment]
Supported tracers:

- many tracer: https://opentracing.io/docs/supported-tracers/
- zipkin: https://github.com/openzipkin-contrib/zipkin-go-opentracing
- jaeger: https://github.com/jaegertracing/jaeger-client-go

**Comment by smallnest** [comment]
supported OpenTracing API.

The example is at https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/opentracing

**Comment by smallnest** [comment]
@wu-sheng can you add [rpcx][http://rpcx.site] into the **OT Supported Frameworks List** ?

**Comment by smallnest** [comment]
support opencensus too.
