### ISSUE TITLE
目前最新版的rpcx，请问如何实现服务端的超时限制？

### ISSUE THREAD

**Issue by shhnwangjian** [smallnest/rpcx#235]
针对客户端连接，服务端的超时限制关闭这些连接，请问这个有样例吗？

**Comment by smallnest** [comment]
https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/timeout

https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/timeout2

**Comment by shhnwangjian** [comment]
你好，我看过这2个样例，这是客户端针对服务端的超时机制。
我的意思是服务端对客户端连接，超过一定时间就强制关闭客户端连接。这个样例我没找到。请问是不是没有这个功能？

**Comment by smallnest** [comment]
服务器端设置读写超时

https://github.com/smallnest/rpcx/blob/master/server/option.go#L28
+ 
https://github.com/smallnest/rpcx/blob/master/server/server.go#L92

**Comment by shhnwangjian** [comment]
好的，谢谢
