### ISSUE TITLE
我按照教程安装了 zookeeper ，还是找不到serverplugin.ZooKeeperRegisterPlugin，如何解决

### ISSUE THREAD

**Issue by lifh1234** [smallnest/rpcx#236]
如下：
go get -u -v -tags "reuseport quic kcp zookeeper etcd consul ping" github.com/smallnest/rpcx/...
安装之后，引入不了serverplugin.ZooKeeperRegisterPlugin，求解

**Comment by smallnest** [comment]
了解一下go的build tag。
 IDE需要配置build tag, 编译的时候也需要带build tag
