### ISSUE TITLE
rpcx-examples3 can not be compile

### ISSUE THREAD

**Issue by zhuxiujia** [smallnest/rpcx#238]
in project rpcx-examples3, file consul.go have "// +build consul " ,have this code Unable to import project ，"'consul.go' doesn't match to target system.File will be ignored by build tool."
but if you delete code "// +build consul" ,it work

**Comment by smallnest** [comment]
see readme, set go build tags in your IDE. And use build tags when you build/import/install projects.

https://github.com/smallnest/rpcx/wiki/BuildTags
