### ISSUE TITLE
如何在server端启动时向服务传递一些配置？How to pass some parameters to service when the server start?

### ISSUE THREAD

**Issue by kidnet** [smallnest/rpcx#241]
如何从配置文件中读取一些配置参数，传递给服务，比如：log文件的路径。

How to read parameters then pass to service, EX: path of log file.

**Comment by smallnest** [comment]
log是可以插拔的， 调用rpcx/log.SetLogger换成你自己的log实现。

其它配置可以参考NewServer, 有一些自定义的参数函数，你也可以开发自己的。

**Comment by kidnet** [comment]
defaultlogger已经实现，只不过defaultlogger默认是标准输出了，这个可以开放出来么？这样就不用再实现一遍了。
