### ISSUE TITLE
无限出现chan is closed and will rewatch？

### ISSUE THREAD

**Issue by waroyhz** [smallnest/rpcx#243]
在测试时出现无限chan is closed and will rewatch的情况，重启后就正常，可能是什么原因？谢谢。
![_ _20180807201508](https://user-images.githubusercontent.com/29970865/43775288-be80293a-9a7e-11e8-8685-92624de10a4c.png)

**Comment by waroyhz** [comment]
![_deepin-terminal_20180807201822](https://user-images.githubusercontent.com/29970865/43775394-204995b6-9a7f-11e8-880a-9b39d8f446f2.png)
![_deepin-terminal_20180807201834](https://user-images.githubusercontent.com/29970865/43775395-208309ea-9a7f-11e8-93e3-1891e5baeda3.png)

**Comment by smallnest** [comment]
redis有问题，检查你的redis

**Comment by waroyhz** [comment]
我并没有配置redis，是etcd连接不上，不过重新启动客户端后就正常连上了。

**Comment by LockGit** [comment]
same problem in etcdv3 , should add rewatch times config ?

**Comment by smallnest** [comment]
should check your etcd. When rpcx found ectd is not alive, it must reconnect.

**Comment by LockGit** [comment]
@smallnest
But reconnecting too often, causing the cpu to exceed the load ，System crash！
I think should add reconnect sleep time .

**Comment by smallnest** [comment]
see https://github.com/smallnest/rpcx/blob/master/client/etcdv3_discovery.go#L157

There are sleep and retry limits

**Comment by LockGit** [comment]
Actually, have lot's of chan is closed and will rewatch error print and system load 100%,  but etcd is healthy.
May be other question. thx
