### ISSUE TITLE
xclient使用context.WithTimeout时，Failfast以外的模式无法返回超时错误

### ISSUE THREAD

**Issue by yangst90** [smallnest/rpcx#244]
diff --git a/src/github.com/smallnest/rpcx/client/xclient.go b/src/github.com/smallnest/rpcx/client/xclient.go
index 33b969e..00ed208 100644
--- a/src/github.com/smallnest/rpcx/client/xclient.go
+++ b/src/github.com/smallnest/rpcx/client/xclient.go
@@ -374,6 +374,7 @@ func (c *xClient) Call(ctx context.Context, serviceMethod string, args interface
 	switch c.failMode {
 	case Failtry:
 		retries := c.option.Retries
+		var e error
 		for retries > 0 {
 			retries--
 
@@ -388,11 +389,15 @@ func (c *xClient) Call(ctx context.Context, serviceMethod string, args interface
 			}
 
 			c.removeClient(k, client)
-			client, err = c.getCachedClient(k)
+			client, e = c.getCachedClient(k)
+		}
+		if err == nil {
+			return e
 		}
 		return err
 	case Failover:
 		retries := c.option.Retries
+		var e error
 		for retries > 0 {
 			retries--
 
@@ -408,9 +413,11 @@ func (c *xClient) Call(ctx context.Context, serviceMethod string, args interface
 
 			c.removeClient(k, client)
 			//select another server
-			k, client, err = c.selectClient(ctx, c.servicePath, serviceMethod, args)
+			k, client, e = c.selectClient(ctx, c.servicePath, serviceMethod, args)
+		}
+		if err == nil {
+			return e
 		}
-
 		return err
 	case Failbackup:
 		ctx, cancelFn := context.WithCancel(ctx)

**Comment by smallnest** [comment]
fixed. thanks for the found and fix.
