### ISSUE TITLE
有没有好的限流方案，目前发现服务端处理能力有限的情况下会导致请求堆积

### ISSUE THREAD

**Issue by yangst90** [smallnest/rpcx#246]
比如客户端限制每秒的请求数， 如果超出后不再发送请求到server.

**Comment by smallnest** [comment]
rpcx client端本身没有out-of-box的限流， 但是可以用 `github.com/juju/ratelimit` 做限流来实现，至少有两种方式：

- xclient.Call之前调用限流库看是否可以发送
- 实现一个client插件，在`DoPreCall`检查限流
