### ISSUE TITLE
关于Client/Server Stub 的问题

### ISSUE THREAD

**Issue by mupengX** [smallnest/rpcx#247]
RPCX既没有像gRPC、Thrift中的IDL，也不能像在Java中使用Dubbo那样Client与Server共享一个service interface的jar包，那Client该如何知道注册的服务名和方法名呢，Client和Server双方又该如何协商并维护服务及对应的方法列表呢？

**Comment by smallnest** [comment]
通过文档或者interface, 参数和方法定义在接口中。
