### ISSUE TITLE
Can not recognized function with “// +build etcd” tag.

### ISSUE THREAD

**Issue by Maxwell365** [smallnest/rpcx#249]
Hi, I met a problem that can not compile my program. My IDE hints me some function is not defined but they exist actually. Eventually, I found "// +build etcd" tag in file top. When I remove them the problem is gone away.  build tag look like "// +build linux"  used at the different platform. Do I want to know Why use the kind of tag?
我英语写作需要练习，: )  为了让遇到问题的外国友人也能看到这个问题所以献丑了，问题很简单，当有// +build etcd的tag时Ide就不识别里面的某些函数，现在我是手动去掉的，不知道为什么要用这种方式？有没有不需要手动删除就能使用的方式？

**Comment by smallnest** [comment]
see https://github.com/smallnest/rpcx/wiki/BuildTags
