### ISSUE TITLE
如何在plugin中进行IP拦截？

### ISSUE THREAD

**Issue by kidnet** [smallnest/rpcx#250]
想实现一个IP白名单，使用plugin中"PostConnAccept"接口必须要返回一个conn。如何能获取IP进行校验，然后直接返回错误断开连接？

**Comment by smallnest** [comment]
HandleConnAccept 中检查IP,不合法的IP直接返回conn, false，

**Comment by kidnet** [comment]
怎么能把拒绝连接的原因返回给clinet呢？现在拒绝连接如下：
`2018/08/17 22:40:12 client.go:577: ERROR: rpcx: client protocol error:read tcp 127.0.0.1:48688->127.0.0.1:8972: read: connection reset by peer
2018/08/17 22:40:12 client.go:577: ERROR: rpcx: client protocol error:read tcp 127.0.0.1:48690->127.0.0.1:8972: read: connection reset by peer
2018/08/17 22:40:12 client.go:577: ERROR: rpcx: client protocol error:read tcp 127.0.0.1:48692->127.0.0.1:8972: read: connection reset by peer
failed to call: read tcp 127.0.0.1:48692->127.0.0.1:8972: read: connection reset by peermsg: `

**Comment by smallnest** [comment]
目前没有办法
