### ISSUE TITLE
如何在服务中获取访问的IP

### ISSUE THREAD

**Issue by kidnet** [smallnest/rpcx#252]
可以在服务中获取client的IP么？要用于日志记录

**Comment by smallnest** [comment]
https://github.com/smallnest/rpcx/issues/42

**Comment by kidnet** [comment]
@smallnest 你好，按照提供的解决方法测试了下，但是ctx这个map里是空的。net.Conn没有被插入到map中。
`WARN: rpcx: failed to handle request: [service internal error]: interface conversion: interface is nil, not net.Conn`

**Comment by kidnet** [comment]
我的代码如下：
`type Cmd struct {
    Command string
    Args    []string
    Timeout int
    ctx map[string]interface{}
}

type Reply struct {
    Status int
    Msg    string
    Contant []byte
}

type Command string

func (c *Cmd) Value(key string) interface{} {
    if c.ctx != nil {
        return c.ctx[key]
    }
    return nil
}

func (c *Cmd) SetValue(key string, value interface{}) {
    if c.ctx == nil {
        c.ctx = make(map[string]interface{})
    }
    rlog.Debugf("key:%s", key)
    c.ctx[key] = value
}

func (c *Cmd) GetKey() string {
    k := reflect.ValueOf(c.ctx).MapKeys()
    strKeys := make([]string, len(k))
    for i := 0; i < len(k); i++ {
        strKeys[i] = k[i].String()
    }
    return strings.Join(strKeys, ",")
}

func (t *Command) Exec(ctx context.Context, cmd *Cmd, reply *Reply) error {
    reply.Status = ERROR
    reply.Msg = ""
    msg, err := cExec(cmd.Timeout, cmd.Command, cmd.Args)
    keys := cmd.GetKey()
    rlog.Debug(keys)
    conn := cmd.Value("conn").(net.Conn)
    remoteAddr := conn.RemoteAddr().String()
    rlog.Debug(remoteAddr)
    if err != nil {
        reply.Status = ERROR
        e := err.Error()
        reply.Msg = e
        return nil
    } else {
        reply.Status = SUCCESS
        reply.Msg = msg
        return nil
    }
}
`

**Comment by smallnest** [comment]
请使用master分支，这个特性是后加的。

例子：

https://github.com/rpcx-ecosystem/rpcx-examples3/blob/e40b258d883cfb748c63300bdbf5d85903087e25/bidirectional/server.go#L26

**Comment by kidnet** [comment]
可以了，谢谢
