### ISSUE TITLE
How to use function server.SendMessage?

### ISSUE THREAD

**Issue by youngbloood** [smallnest/rpcx#257]
If i want to use interface ```DoPreWriteRequest``` and ```DoPostWriteRequest```. I must invoke the ```server.SendMessage()``` with manual. But when i invoke the function and how to invoke it?

**Comment by youngbloood** [comment]
But just only function ```server.SendMessage``` invoke the interface ```DoPreWriteRequest``` and ```DoPostWriteRequest```. I am not found where invoke the two functions in server.serveConn(conn net.Conn) then viewed the code.

**Comment by smallnest** [comment]
Because they are only invoked when servers send notifications to clients. I guess you want 

```go
//PreReadRequestPlugin represents .
	PreReadRequestPlugin interface {
		PreReadRequest(ctx context.Context) error
	}

	//PostReadRequestPlugin represents .
	PostReadRequestPlugin interface {
		PostReadRequest(ctx context.Context, r *protocol.Message, e error) error
	}

	//PreWriteResponsePlugin represents .
	PreWriteResponsePlugin interface {
		PreWriteResponse(context.Context, *protocol.Message, *protocol.Message) error
	}

	//PostWriteResponsePlugin represents .
	PostWriteResponsePlugin interface {
		PostWriteResponse(context.Context, *protocol.Message, *protocol.Message, error) error
	}
```

**Comment by youngbloood** [comment]
I get it. But there are two questions:
1. Why not invoke the  interface ```DoPreWriteRequest``` and ```DoPostWriteRequest``` in [server.serveConn(conn net.Conn)](https://github.com/smallnest/rpcx/blob/fa882ccb86dbbf8351fddb8ac7f05e2cbae8d6de/server/server.go#L292)?  
2.Can you give a template about how to use ```server.SendMessage()``` and where use it then i want to send notifications to clients?
Thank you.

**Comment by smallnest** [comment]
https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/bidirectional
