### ISSUE TITLE
is there any bug on Broadcast

### ISSUE THREAD

**Issue by sniperdong** [smallnest/rpcx#258]
is there any bug on Broadcast , some times err will be overwrite by follow goroutine :

var err error
	l := len(clients)
	done := make(chan bool, l)
	for k, client := range clients {
		k := k
		client := client
		go func() {
			err = c.wrapCall(ctx, client, serviceMethod, args, reply)
			done <- (err == nil)
			if err != nil {
				c.removeClient(k, client)
			}
		}()
	}

	timeout := time.After(time.Minute)
check:
	for {
		select {
		case result := <-done:
			l--
			if l == 0 || !result { // all returns or some one returns an error
				break check
			}
		case <-timeout:
			break check
		}
	}

	return err

**Comment by smallnest** [comment]
Yes, it is a bug and I fixed it. thanks.

**Comment by sniperdong** [comment]
> Yes, it is a bug and I fixed it. thanks.

there are also problems once timeout between broadcast and fork.

**Comment by smallnest** [comment]
what problems, attach logs and erros

**Comment by sniperdong** [comment]
when all servers are not response within one  minute nil will be return, but there may be errors.

**Comment by sniperdong** [comment]
may be as follow:
`case <-timeout:`
`	errors.New("timeout")`
[https://github.com/sniperdong/rpcx/blob/master/client/xclient.go](url)

**Comment by smallnest** [comment]
good found, fixed.

**Comment by sniperdong** [comment]
thanks for your contributions. we were built easily a rpc system about 3billions calls per day (2 clients and 6 servers)
