### ISSUE TITLE
使用etcd注册中心时不能注册function as serivce 这样的服务

### ISSUE THREAD

**Issue by fmyxyz** [smallnest/rpcx#260]

**Comment by fmyxyz** [comment]
when use function as serivce way can't register in etcd . @smallnest

**Comment by smallnest** [comment]
I have found any issue. See the example https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/function/etcd

**Comment by fmyxyz** [comment]
https://github.com/smallnest/rpcx/issues/260#issuecomment-432068347

I have tried your example with my development environment:
go build server.go 
out:
`2018/10/23 13:53:46 server.go:168: INFO : server pid:35994
2018/10/23 13:54:47 etcd.go:239: ERROR: cannot create consul path /rpcx_test/a.fake.service/tcp@127.0.0.1:8972: Key not found in store
panic: [[Key not found in store]]
`
go build client.go
out:
`
2018/10/23 13:53:53 failed to call: can not found any server
2018/10/23 13:53:58 failed to call: can not found any server
2018/10/23 13:54:03 failed to call: can not found any server
2018/10/23 13:54:08 failed to call: can not found any server
2018/10/23 13:54:13 failed to call: can not found any server
2018/10/23 13:54:18 failed to call: can not found any server
2018/10/23 13:54:23 failed to call: can not found any server
2018/10/23 13:54:28 failed to call: can not found any server
2018/10/23 13:54:33 failed to call: can not found any server
2018/10/23 13:54:38 failed to call: can not found any server
2018/10/23 13:54:43 failed to call: can not found any server
2018/10/23 13:54:48 failed to call: can not found any server
2018/10/23 13:54:53 failed to call: can not found any server
`
and in etcd 
curl http://127.0.0.1:2379/v2/keys/
out:
`
{
  "action": "get",
  "node": {
    "dir": true,
    "nodes": [
      {
        "key": "/rpcx_test",
        "dir": true,
        "nodes": [
          {
            "key": "/rpcx_test/a.fake.service",
            "dir": true,
            "modifiedIndex": 54099,
            "createdIndex": 54099
          }
        ],
        "modifiedIndex": 54098,
        "createdIndex": 54098
      }
    ]
  }
}
`
-------------------------------
Could you help me find the problem? thinks.
And, I have found any implement for interface named RegisterFunctionPlugin in https://github.com/smallnest/rpcx/blob/master/serverplugin/etcd.go ,how it works?
