### ISSUE TITLE
JSONRPC2 support?

### ISSUE THREAD

**Issue by s3rj1k** [smallnest/rpcx#264]

**Comment by smallnest** [comment]
Currently rpcx doesn't support jsonrpc2, I hope I can implement it in rpcx 5.0

**Comment by eddiewang** [comment]
+1 for JSONRPC2 support

**Comment by damoonazarpazhooh** [comment]
+1 for JSONRPC2 support

**Comment by smallnest** [comment]
supported [JSONRPC 2.0](https://www.jsonrpc.org/specification).

Limitations

- Does not support Pipelined Requests/Responses.
- Does not support Batch Request.
- Must use named parameters.

If you want to use jsonrpc just like the standard libary or websocket, you can use:

- https://github.com/powerman/rpc-codec
- https://godoc.org/github.com/sourcegraph/jsonrpc2

**Comment by smallnest** [comment]
the example is at: https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/jsonrpc2
