### ISSUE TITLE
发现一个内存被改写的bug

### ISSUE THREAD

**Issue by ldseraph** [smallnest/rpcx#267]
并发调用 GO 接口 发现一个内存被改写的bug
场景：
A函数调用GO函数 B函数从channel接受数据

```go
tempChan := make(chan *client.Call, 10)
func A（）{
  for{
    oneClient.Go(context.Background(), "A", "B", a, r, tempChan)
  }
}
func B（）{
  for{
    temp := <-tempChan
  }
}

type Call struct {
	ServicePath   string            // The name of the service and method to call.
	ServiceMethod string            // The name of the service and method to call.
	Metadata      map[string]string //metadata
	ResMetadata   map[string]string
	Args          interface{} // The argument to the function (*struct).
	Reply         interface{} // The reply from the function (*struct).
	Error         error       // After completion, the error status.
	Done          chan *Call  // Strobes when call is complete.
	Raw           bool        // raw message or not
}
```
如果B函数没有及时接收消息 而client的input 连续接收到多个消息
则第二次的消息内容会覆盖掉第一次的内容

错误原因：
Call中string是通过SliceByteToString直接引用byte中的内存
func (m *Message) Decode(r io.Reader) 中如果没有重新make byte而是使用原先的data
则第二次的内容就会覆盖掉之前的内容

if cap(m.data) >= totalL { //reuse data
	m.data = m.data[:totalL]
} else {
	m.data = make([]byte, totalL)
}

**Comment by smallnest** [comment]
`tempChan` 中总是新的消息，不清楚你说的什么时候回覆盖?

https://github.com/smallnest/rpcx/blob/master/client/client.go#L523

**Comment by ldseraph** [comment]
并没有进入这个case
case call == nil:

我是这个情况下发现的
第一次进入
case res.MessageStatusType() == protocol.Error:
返回错误是正常的没有改写
B函数没有处理消息
input直接处理了第二个消息
err没有被修改
https://github.com/smallnest/rpcx/blob/1da5fc91dfb885a8649547c7426ec7733ae65188/client/client.go#L497
Decode中m.data没有重新make
导致覆盖第一次数据
B函数再处理第一条消息中的Error error 内容就被修改了

**Comment by smallnest** [comment]
如果是重用同一个msg,会有覆盖问题。 
目前看只有下面一行可能会有重用的问题。

https://github.com/smallnest/rpcx/blob/master/client/client.go#L530

**Comment by ldseraph** [comment]
是的 有两个成员有问题
call.Error
call.ResMetadata

**Comment by ldseraph** [comment]
测试流程很简单 一个server 一个client
server大部分时候会返回error
client就是那两个A和B函数
B函数收到消息后会判断返回值
经常判断error是乱码

**Comment by ldseraph** [comment]
go version go1.11.1 linux/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lidong/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lidong/workspace/project/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build869626845=/tmp/go-build -gno-record-gcc-switches"

**Comment by ldseraph** [comment]
还是有问题 因为根本问题在string上 string引用的内存并没有改变

**Comment by ldseraph** [comment]
要放到下个版本修复吗 那4.0版本准备什么时候release呢

**Comment by smallnest** [comment]
这一两天我就会修复

**Comment by smallnest** [comment]
没看到你说的情况，你可以把你的例子贴一下，或者发gist.

我下面的例子测试没看到乱码。


```go server.go
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"net"
	"net/http"
	_ "net/http/pprof"
	"time"

	example "github.com/rpcx-ecosystem/rpcx-examples3"
	"github.com/smallnest/rpcx/server"
)

var (
	addr = flag.String("addr", "localhost:8972", "server address")
)

var clientConn net.Conn
var connected = false

type Arith int

var i = 0

func (t *Arith) Mul(ctx context.Context, args *example.Args, reply *example.Reply) error {
	clientConn = ctx.Value(server.RemoteConnContextKey).(net.Conn)
	reply.C = args.A * args.B
	connected = true

	i++

	if i%3 != 0 {
		return errors.New("some error")
	}
	return nil
}

func main() {
	flag.Parse()

	ln, _ := net.Listen("tcp", ":9981")
	go http.Serve(ln, nil)

	s := server.NewServer()
	//s.RegisterName("Arith", new(example.Arith), "")
	s.Register(new(Arith), "")
	go s.Serve("tcp", *addr)

	for !connected {
		time.Sleep(time.Second)
	}

	fmt.Printf("start to send messages to %s\n", clientConn.RemoteAddr().String())
	for {
		if clientConn != nil {
			err := s.SendMessage(clientConn, "test_service_path", "test_service_method", nil, []byte("abcde"))
			if err != nil {
				fmt.Printf("failed to send messsage to %s: %v\n", clientConn.RemoteAddr().String(), err)
				clientConn = nil
			}
		}
		//time.Sleep(time.Second)
	}
}
```

客户端例子：

```go client.go
package main

import (
	"context"
	"flag"
	"fmt"

	example "github.com/rpcx-ecosystem/rpcx-examples3"
	"github.com/smallnest/rpcx/client"
	"github.com/smallnest/rpcx/protocol"
)

var (
	addr = flag.String("addr", "localhost:8972", "server address")
)

func main() {
	flag.Parse()

	ch := make(chan *protocol.Message)

	d := client.NewPeer2PeerDiscovery("tcp@"+*addr, "")
	xclient := client.NewBidirectionalXClient("Arith", client.Failtry, client.RandomSelect, d, client.DefaultOption, ch)
	defer xclient.Close()

	args := &example.Args{
		A: 10,
		B: 20,
	}

	go func() {
		for {
			reply := &example.Reply{}
			err := xclient.Call(context.Background(), "Mul", args, reply)
			if err != nil {
				// log.Fatalf("failed to call: %v", err)
			}
			//log.Printf("%d * %d = %d", args.A, args.B, reply.C)
		}

	}()

	for msg := range ch {
		fmt.Printf("receive msg from server: %s, %v\n", msg.Payload, msg.Metadata)
	}
}
```

**Comment by smallnest** [comment]
我按照你的场景测试了一下，无法复现。 你可以把你的测试程序贴一下以便分析。

我的测试程序：


服务器端:

```go
package main

import (
	"context"
	"errors"
	"flag"

	example "github.com/rpcx-ecosystem/rpcx-examples3"
	"github.com/smallnest/rpcx/server"
)

var (
	addr = flag.String("addr", "localhost:8972", "server address")
)

var i = 0

type Arith int

func (t *Arith) Mul(ctx context.Context, args *example.Args, reply *example.Reply) error {
	reply.C = args.A * args.B

	i++
	if i%3 != 0 {
		return errors.New("some error")
	}
	return nil
}

func main() {
	flag.Parse()

	s := server.NewServer()
	//s.RegisterName("Arith", new(example.Arith), "")
	s.Register(new(Arith), "")
	s.Serve("tcp", *addr)
}
```

客户端:

```go
package main

import (
	"context"
	"flag"
	"fmt"

	example "github.com/rpcx-ecosystem/rpcx-examples3"
	"github.com/smallnest/rpcx/client"
)

var (
	addr = flag.String("addr", "localhost:8972", "server address")
)

func main() {
	flag.Parse()

	d := client.NewPeer2PeerDiscovery("tcp@"+*addr, "")
	oneClient := client.NewOneClient(client.Failtry, client.RandomSelect, d, client.DefaultOption)
	defer oneClient.Close()

	args := &example.Args{
		A: 10,
		B: 20,
	}

	reply := &example.Reply{}
	tempChan := make(chan *client.Call, 1000)
	go func() {
		for {
			oneClient.Go(context.Background(), "Arith", "Mul", args, reply, tempChan)
			// time.Sleep(time.Second)
		}
	}()

	for {
		temp := <-tempChan
		fmt.Printf("%+v\n", temp.Error)
	}

}
```

运行结果。 Call.error有时候是nil, 有时候是服务器端返回的错，符合预期。


<img width="141" alt="image" src="https://user-images.githubusercontent.com/865763/48548896-2c2e2800-e909-11e8-8fe2-fafd5e6667e6.png">

**Comment by smallnest** [comment]
我大概明白你的意思了。你可能误用了`tempChan := make(chan *client.Call, 1000)`, 对于每次调用`oneClient.Go`, 你需要单独的一个*client.Call,如:


```go
	go func() {
		for {
			reply := &example.Reply{}
			done := make(chan *client.Call, 1000)
			oneClient.Go(context.Background(), "Arith", "Mul", args, reply, done)
			// time.Sleep(time.Second)
		}
	}()
```

`done`只负责本次调用，不能多次调用共享

**Comment by ldseraph** [comment]
多谢作者 明天我会试一下你的测试程序

> 我大概明白你的意思了。你可能误用了`tempChan := make(chan *client.Call, 1000)`, 对于每次调用`oneClient.Go`, 你需要单独的一个*client.Call,如:
> 
> ```go
> 	go func() {
> 		for {
> 			reply := &example.Reply{}
> 			done := make(chan *client.Call, 10)
> 			oneClient.Go(context.Background(), "Arith", "Mul", args, reply, done)
> 			<- done
> 
> 		}
> 	}()
> ```
> 
> `done`只负责本次调用，不能多次调用共享
我感觉如果每次调用都需要创建新的channel 那这个接口就少了很多灵活性 也不能算是真正的async接口了

**Comment by ldseraph** [comment]
更新完最新的commit，问题解决了

没更新前，你的测试程序确实复现不出来问题 
我今天尝试简化了一下我的程序，发现特意复现问题很困难。
我感觉把问题想的太简单了，client我用到了gocv，server我也用到了cgo和一些c lib，还有其他一些goroutine,看起来跟那个返回值都没关，但是确实有影响。
多谢作者支持，我先自己研究一下其他的库会不会影响到rpcx吧
