### ISSUE TITLE
Parsing meta tags from https://golang.org/x/net/ipv4?go-get=1 (status code 200)

### ISSUE THREAD

**Issue by forging2012** [smallnest/rpcx#268]
➜  rpcx git:(master) go get -u -v github.com/smallnest/rpcx/...

github.com/smallnest/rpcx (download)
github.com/edwingeng/doublejump (download)
github.com/dgryski/go-jump (download)
github.com/grandcat/zeroconf (download)
github.com/cenkalti/backoff (download)
github.com/miekg/dns (download)
Fetching https://golang.org/x/net/ipv4?go-get=1
Parsing meta tags from https://golang.org/x/net/ipv4?go-get=1 (status code 200)
get "golang.org/x/net/ipv4": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/ipv4?go-get=1
get "golang.org/x/net/ipv4": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://golang.org/x/net/bpf?go-get=1
Parsing meta tags from https://golang.org/x/net/bpf?go-get=1 (status code 200)
get "golang.org/x/net/bpf": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/bpf?go-get=1
get "golang.org/x/net/bpf": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/internal/iana?go-get=1
Parsing meta tags from https://golang.org/x/net/internal/iana?go-get=1 (status code 200)
get "golang.org/x/net/internal/iana": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/internal/iana?go-get=1
get "golang.org/x/net/internal/iana": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/internal/socket?go-get=1
Parsing meta tags from https://golang.org/x/net/internal/socket?go-get=1 (status code 200)
get "golang.org/x/net/internal/socket": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/internal/socket?go-get=1
get "golang.org/x/net/internal/socket": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/ipv6?go-get=1
Parsing meta tags from https://golang.org/x/net/ipv6?go-get=1 (status code 200)
get "golang.org/x/net/ipv6": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/ipv6?go-get=1
get "golang.org/x/net/ipv6": verifying non-authoritative meta tag
github.com/hashicorp/go-multierror (download)
github.com/hashicorp/errwrap (download)
github.com/rubyist/circuitbreaker (download)
github.com/cenk/backoff (download)
github.com/facebookgo/clock (download)
github.com/fatih/color (download)
git.apache.org/thrift.git (download)
github.com/gogo/protobuf (download)
github.com/golang/protobuf (download)
github.com/vmihailenco/msgpack (download)
github.com/valyala/fastrand (download)
github.com/julienschmidt/httprouter (download)
github.com/kavu/go_reuseport (download)
github.com/soheilhy/cmux (download)
Fetching https://golang.org/x/net/http2?go-get=1
Parsing meta tags from https://golang.org/x/net/http2?go-get=1 (status code 200)
get "golang.org/x/net/http2": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/http2?go-get=1
get "golang.org/x/net/http2": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/http/httpguts?go-get=1
Parsing meta tags from https://golang.org/x/net/http/httpguts?go-get=1 (status code 200)
get "golang.org/x/net/http/httpguts": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/http/httpguts?go-get=1
get "golang.org/x/net/http/httpguts": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/idna?go-get=1
Parsing meta tags from https://golang.org/x/net/idna?go-get=1 (status code 200)
get "golang.org/x/net/idna": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/idna?go-get=1
get "golang.org/x/net/idna": verifying non-authoritative meta tag
Fetching https://golang.org/x/text/secure/bidirule?go-get=1
Parsing meta tags from https://golang.org/x/text/secure/bidirule?go-get=1 (status code 200)
get "golang.org/x/text/secure/bidirule": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/secure/bidirule?go-get=1
get "golang.org/x/text/secure/bidirule": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
golang.org/x/text (download)
Fetching https://golang.org/x/text/transform?go-get=1
Parsing meta tags from https://golang.org/x/text/transform?go-get=1 (status code 200)
get "golang.org/x/text/transform": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
Fetching https://golang.org/x/text/unicode/bidi?go-get=1
Parsing meta tags from https://golang.org/x/text/unicode/bidi?go-get=1 (status code 200)
get "golang.org/x/text/unicode/bidi": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/unicode/bidi?go-get=1
get "golang.org/x/text/unicode/bidi": verifying non-authoritative meta tag
Fetching https://golang.org/x/text/unicode/norm?go-get=1
Parsing meta tags from https://golang.org/x/text/unicode/norm?go-get=1 (status code 200)
get "golang.org/x/text/unicode/norm": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/unicode/norm?go-get=1
get "golang.org/x/text/unicode/norm": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/http2/hpack?go-get=1
Parsing meta tags from https://golang.org/x/net/http2/hpack?go-get=1 (status code 200)
get "golang.org/x/net/http2/hpack": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/http2/hpack?go-get=1
get "golang.org/x/net/http2/hpack": verifying non-authoritative meta tag
github.com/juju/ratelimit (download)
github.com/rcrowley/go-metrics (download)
github.com/vrischmann/go-metrics-influxdb (download)
github.com/influxdata/influxdb (download)
github.com/influxdata/platform (download)
Fetching https://golang.org/x/net/trace?go-get=1
Parsing meta tags from https://golang.org/x/net/trace?go-get=1 (status code 200)
get "golang.org/x/net/trace": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/trace?go-get=1
get "golang.org/x/net/trace": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/internal/timeseries?go-get=1
Parsing meta tags from https://golang.org/x/net/internal/timeseries?go-get=1 (status code 200)
get "golang.org/x/net/internal/timeseries": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/internal/timeseries?go-get=1
get "golang.org/x/net/internal/timeseries": verifying non-authoritative meta tag

**Comment by smallnest** [comment]
whats your question?

**Comment by forging2012** [comment]
It is normal?
The outline when I run "go get -u -v github.com/smallnest/rpcx/..."

**Comment by smallnest** [comment]
it is normal for go module

**Comment by forging2012** [comment]
Thank you!
