### ISSUE TITLE
RPCX 双向通讯问题

### ISSUE THREAD

**Issue by dulumao** [smallnest/rpcx#275]
rpcx 通讯有没有什么特别好的方法，当 client 连接上server以后，server提供服务的同时，可以调用当前client的方法，而不需要client提供自己注册成server,说白了，只有client知道server是谁，只要client连接上以后，就能双向调用方法

**Comment by CaoMengLong** [comment]
How is this problem closed? Can RPCX pass in both directions?

**Comment by smallnest** [comment]
rpcx不支持这样的双向调用
