### ISSUE TITLE
关于startGateway的疑惑。

### ISSUE THREAD

**Issue by JungleYe** [smallnest/rpcx#276]
作者，你好！我想基于rpcx实现如下场景：整个后端有一个对外的Access服务，这个Access接收客户端（APP）的tcp长连接的请求（非rpcx的header + dataLen + spLen + sp + smLen + sm + metaL + meta + payloadLen + payload 协议），然后解析请求，并转换成普通的rpc请求，进行rpc调用之后返回响应！ 

我看现在的startGateway方法中已经实现了http请求转rpc请求，并响应结果！如果我要以tcp长连接的方式实现，是不是参考startHTTP1APIGateway？ 有没有可参考的基于rpcx的tcp gateway服务？

**Comment by smallnest** [comment]
参考gateway
