### ISSUE TITLE
多server通信问题

### ISSUE THREAD

**Issue by c17abab** [smallnest/rpcx#277]
场景：
一个client连接两个server A，B，其中一个server B的进程中断连接。client的数据全部发送至server A。
问题：
client每发送一个包到server A，都会额外发送一个syn包到server B进行重连操作，这里是否有配置可以调整client重连的时间间隔？
c端代码：
```
package main
import (
	"context"
	"flag"
	"log"
	"testlab/com"
	"time"

	"github.com/smallnest/rpcx/client"
)
var (
	addr1 = flag.String("addr1", "localhost:8889", "server1 address")
	addr2 = flag.String("addr2", "localhost:8888", "server2 address")
)

func main() {
	flag.Parse()
	d := client.NewMultipleServersDiscovery([]*client.KVPair{{Key: *addr1}, {Key: *addr2}})
	option := client.DefaultOption
	option.Retries = 10
	xclient := client.NewXClient("RPC", client.Failover, client.RandomSelect, d, option)
	defer xclient.Close()
	for ; ;  {
		for i := 0; i < 10; i++ {
			args := &com.Args{
				A: i,
			}
			reply := &com.Reply{
				Sum: 0,
			}
			if err := xclient.Call(context.Background(), "P", args, reply); err != nil {
				log.Println("send",i)
			}
			time.Sleep(time.Second * 2)
		}
	}
}
```
s端代码：
```
package main

import (
	"flag"
	"testlab/com"

	"github.com/smallnest/rpcx/server"
)

var (
	addr1 = flag.String("addr1", "localhost:8889", "server1 address")
)

func main() {
	flag.Parse()

	go createServer(*addr1)

	select {}
}

func createServer(addr string) {
	s := server.NewServer()
	s.RegisterName("RPC", new(com.RPC), "")
	s.Serve("tcp", addr)
}
```

**Comment by smallnest** [comment]
what's your question?

**Comment by c17abab** [comment]
场景：
一个client连接两个server A，B，其中一个server B的进程中断连接。client的数据全部发送至server A。
问题：
client每发送一个包到server A，都会额外发送一个syn包到server B进行重连操作，这里是否有配置可以调整client重连的时间间隔？
c端代码：
`package main
import (
	"context"
	"flag"
	"log"
	"testlab/com"
	"time"

	"github.com/smallnest/rpcx/client"
)
var (
	addr1 = flag.String("addr1", "localhost:8889", "server1 address")
	addr2 = flag.String("addr2", "localhost:8888", "server2 address")
)

func main() {
	flag.Parse()
	d := client.NewMultipleServersDiscovery([]*client.KVPair{{Key: *addr1}, {Key: *addr2}})
	option := client.DefaultOption
	option.Retries = 10
	xclient := client.NewXClient("RPC", client.Failover, client.RandomSelect, d, option)
	defer xclient.Close()
	for ; ;  {
		for i := 0; i < 10; i++ {
			args := &com.Args{
				A: i,
			}
			reply := &com.Reply{
				Sum: 0,
			}
			if err := xclient.Call(context.Background(), "P", args, reply); err != nil {
				log.Println("send",i)
			}
			time.Sleep(time.Second * 2)
		}
	}
}
`
s端代码：
`
package main

import (
	"flag"
	"testlab/com"

	"github.com/smallnest/rpcx/server"
)

var (
	addr1 = flag.String("addr1", "localhost:8889", "server1 address")
)

func main() {
	flag.Parse()

	go createServer(*addr1)

	select {}
}

func createServer(addr string) {
	s := server.NewServer()
	s.RegisterName("RPC", new(com.RPC), "")
	s.Serve("tcp", addr)
}
`

**Comment by smallnest** [comment]
1. 使用断路器

2. 使用服务配置框架， 如etcd, consul等，在服务停止一段时间后，这些框架会自动将其踢掉
