### ISSUE TITLE
Dependency loss

### ISSUE THREAD

**Issue by LuDell** [smallnest/rpcx#284]
1.github_com/cloudflare/sidh/sidh: Cannot detect VCS

2.golang_org/x/crypto/chacha20poly1305: Cannot detect VCS

3.golang_org/x/crypto/curve25519: Cannot detect VCS

How can I solve this problem?

**Comment by smallnest** [comment]
It looks you used glide. It is the issue of glide and you can search the similar problems in glide issues.

Glide is deprecated and rpcx uses go module for depenecy management.
