### ISSUE TITLE
is there any possibility we provide wireshark rpcx plugin？

### ISSUE THREAD

**Issue by zhxiaom5** [smallnest/rpcx#286]
is there any possibility we provide wireshark rpcx plugin？

**Comment by smallnest** [comment]
It is a good feature and welcome to contribute

**Comment by smallnest** [comment]
add a tcpdump tools that can capture rpcx data and outputs on console.

https://github.com/smallnest/rpcxdump

![](https://github.com/smallnest/rpcxdump/raw/master/snapshoot.png)
