### ISSUE TITLE
read and write timeouts on XClient

### ISSUE THREAD

**Issue by glycerine** [smallnest/rpcx#292]
This is a very nice rpc package.

One feature missing is a way to change the timeouts after creating an XClient. The interface doesn't provide me any way to change them for each individual Call(). This would be a very useful feature to add.

**Comment by smallnest** [comment]
I suggest you use context to control timeout for each call. The timeout values in option are used for all calls on one connection. If you change it dynamically, maybe it affects other calls

**Comment by glycerine** [comment]
That's reasonable. Thanks for suggesting it.
