### ISSUE TITLE
客户端打到10000次请求就卡

### ISSUE THREAD

**Issue by ansjsun** [smallnest/rpcx#293]
https://github.com/smallnest/rpcx/issues/5

但是不知道怎么解决我是按照 example的方式使用的

````
d := client.NewPeer2PeerDiscovery("tcp@"+serverAddress+":"+ cast.ToString(port), "")

oneClient := client.NewOneClient(client.Failtry, client.RandomSelect, d, client.DefaultOption)

````
全局只使用了一个client。

看到你有说连接池。但是也没看到相关例子

我的server是这么启动的

````
server := server.NewServer()

	this.server = server

	go server.Serve("tcp", fmt.Sprintf("%s:%d", this.serverAddress, this.port))

````

貌似必须 go 的方式才能异步吧。。。

您给掌掌眼。怎么搞

**Comment by smallnest** [comment]
需要测试代码，测试步骤和异常说明

**Comment by smallnest** [comment]
同时检查你的网络连接，大概率是网络环境配置的问题

**Comment by ansjsun** [comment]
我用的是 ab   -c 50  -n 10000 -p postdata.json  -T application/json 127.0.0.1:9001/ansj/ansj/_search
网络环境是本机

**Comment by ansjsun** [comment]
多线程调用client huang住

![image](https://user-images.githubusercontent.com/1221947/50736083-60301600-11f3-11e9-8bea-6b37d66d4a11.png)

是我用的不对吗？？

**Comment by smallnest** [comment]
client有问题，你的机器不可能启动999999999个goroutine的，考虑一下你的客户端的设计

**Comment by ansjsun** [comment]
需要自己做连接池吗？我golang 这块刚 接触。。 

这意思 client 是不支持并发执行的吗？我看到你例子说。 client是无状态的。我理解你client里面维护着连接池。。所以无论如何也不能卡住。。哪怕是等待。

99999999只是个极端特例。。改为10000也可能卡住。只不过没有99999999明显而已。。

**Comment by smallnest** [comment]
这个不属于rpcx的scope,请先了解一下go语言的并发编程，golang-nuts或者gocn.vip等网站，相关的go语言的书

**Comment by ansjsun** [comment]
再次感谢。我理解了就和java的 连接池一样。。。一个client 是一个长连接。。所以维护若干个client就可以。不能无限制创建。client 应该是不能并发使用的吧。。或者说，并发下会导致没有限制。还是需要一个池来控制总量。。

**Comment by njlkj** [comment]
> 再次感谢。我理解了就和java的 连接池一样。。。一个client 是一个长连接。。所以维护若干个client就可以。不能无限制创建。client 应该是不能并发使用的吧。。或者说，并发下会导致没有限制。还是需要一个池来控制总量。。

您是vearch开发者吗? vearch使用中,我也遇到相似问题了
goroutine 397222 [syscall]:
github.com/vearch/vearch/ps/engine/gammacb._Cfunc_SearchV2(0x7fd3580015b0, 0x7fca5c00a4c0, 0x0)
        _cgo_gotypes.go:727 +0x4e
github.com/vearch/vearch/ps/engine/gammacb.(*readerImpl).Search.func3(0xc000010550, 0x7fca5c00a4c0, 0x25e23e0)
        /env/app/go/src/github.com/vearch/vearch/ps/engine/gammacb/reader.go:586 +0x9b
github.com/vearch/vearch/ps/engine/gammacb.(*readerImpl).Search(0xc000010550, 0x180a340, 0xc00213f320, 0xc00364a180, 0x0)
        /env/app/go/src/github.com/vearch/vearch/ps/engine/gammacb/reader.go:586 +0x2ac
github.com/vearch/vearch/ps/storage/raftstore.(*Store).Search(0xc0009ad860, 0x180a340, 0xc00213f320, 0x1833400, 0xc00364a180, 0xc00227b880, 0xc00497b770, 0xc00364a180)
        /env/app/go/src/github.com/vearch/vearch/ps/storage/raftstore/store_read.go:53 +0xb2
github.com/vearch/vearch/ps.(*SearchHandler).Execute(0xc000b4caa8, 0xc000fd1000, 0xc000fd1040, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/ps/handler_document.go:399 +0xb8
github.com/vearch/vearch/util/server/rpc/handler.(*Chain).Execute(0xc000b5ed80, 0x180a340, 0xc00213f320, 0xc000fd1000, 0xc000fd1040, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/util/server/rpc/handler/chain.go:47 +0xe8
reflect.Value.call(0xc000b84400, 0xc00098a830, 0x13, 0x1578913, 0x4, 0xc00497bae8, 0x4, 0x4, 0xc00497baa0, 0x28, ...)
        /env/app/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xc000b84400, 0xc00098a830, 0x13, 0xc00497bae8, 0x4, 0x4, 0xc00497bba8, 0x10fce24, 0x12c6900)
        /env/app/go/src/reflect/value.go:308 +0xa4
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*service).call(0xc000b725f0, 0x180a340, 0xc00213f320, 0xc000b84480, 0x13ed1a0, 0xc000fd1000, 0x16, 0x12c6900, 0xc000fd1040, 0x16, ...)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/service.go:361 +0x215
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).handleRequest(0xc000b8a000, 0x180a340, 0xc00213f320, 0xc003793560, 0x0, 0x0, 0xc001613c80)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:529 +0x98c
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).serveConn.func2(0xc000b8a000, 0xc003793560, 0x1821fa0, 0xc000028460, 0xc00213f320)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:414 +0x1e8
created by github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).serveConn
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:396 +0x713
