### ISSUE TITLE
flow control/streaming a big file

### ISSUE THREAD

**Issue by glycerine** [smallnest/rpcx#294]
I'm enjoying rpcx very much.

If I could ask for advice--is it possible to send a large (several gigabyte) file streaming over rpcx?

Such a transfer would need to have some kind of flow control (possibly using TCP's flow control) to avoid having the fast sender overwhelm the slow receiver.

I know that gRPC has such a feature. Does rpcx support something comparable?

Thank you.

**Comment by smallnest** [comment]
Currently rpcx does not support large file streaming.But Ithink it is an interesting feature and we can consider we implemrnt it in next release.

**Comment by smallnest** [comment]
grpc discussion:

1. https://github.com/grpc/grpc-go/issues/414
2. https://www.reddit.com/r/golang/comments/7nx7ym/sending_files_via_grpc/
3. https://github.com/mattn/ft
4. https://github.com/glycerine/grpc-demo


There are some solutions to implement this feature:

1. just like ftp protocol: start a new connection to transfer files
2. implement plugins to split the file into pieces and assemble it in server

**Comment by glycerine** [comment]
I wrote 4 so that's certainly familiar. :-) There is also go-micro which claims to have a API for synchronous bidirectional streaming.

https://github.com/micro/go-micro

**Comment by smallnest** [comment]
implement it and the example is at https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/filetransfer.

**Comment by glycerine** [comment]
Nice. Does that work to send a file from server to client as well as from client to server?

**Comment by glycerine** [comment]
Ah. I see. It is using a separate port. So it won't participate in the same security scheme, and it won't be able to use server push through the established channel to go back through firewalls. It couldn't be used to provide a Netflix like service, for example.
