### ISSUE TITLE
官方例子修改args参数后出了问题

### ISSUE THREAD

**Issue by cw290746987** [smallnest/rpcx#306]
http://doc.rpcx.site/part1/server.html
http://doc.rpcx.site/part1/client.html
客户端和服务端的代码使用官方例子的。编译在windows10上运行的。
然后修改参数
args := &example.Args{
        A: 1,
        B: 1,
    }
客户端调用就会卡住，直到关闭客户端，服务端会收到这个请求。
如果A:10  B:20  那么正常返回。 很是疑惑
![image](https://user-images.githubusercontent.com/16933565/53296326-3769eb80-3848-11e9-8c3c-75187f7dce65.png)
![image](https://user-images.githubusercontent.com/16933565/53296347-94fe3800-3848-11e9-9ec5-e0f92ddc09d9.png)

**Comment by smallnest** [comment]
需要详细的信息。

单从这些信息上看不出哪里有问题，因为框架和你输入的参数没有关系，检查一下你是否修改了其它代码。

建议在相关的方法调用里加上log,或者通过pprof查看goroutine阻塞在哪里，进一步的通过tcpdump抓包看看。

**Comment by cw290746987** [comment]
我想也是跟参数应该没关系。我调试跟踪看最后发出的字节数都是一样的，都是int嘛。我会进一步调试。
另外真的没有改动，就粘贴的例子代码。使用的go1.10版本。

**Comment by smallnest** [comment]
曾经有人说windows console有问题，你可以问问群里的ha666。我相信这应该是运行环境的问题

**Comment by cw290746987** [comment]
我也相信是环境的问题，我在ubuntu下运行也是一样的结果。我可能需要尝试下安装新的go环境以及依赖库试试。
 
![image](https://user-images.githubusercontent.com/16933565/53297525-b0723e80-385a-11e9-8e4b-b8380d7598ce.png)
![image](https://user-images.githubusercontent.com/16933565/53297529-ba943d00-385a-11e9-847c-436b3204a11e.png)

**Comment by cw290746987** [comment]
> 曾经有人说windows console有问题，你可以问问群里的ha666。我相信这应该是运行环境的问题

还有群啊，可以告诉一下群号吗？

**Comment by km6** [comment]
![image](https://user-images.githubusercontent.com/24953345/53310632-95e6a680-38e8-11e9-9714-7ca326e8fd6b.png)
我也是同样的问题，改用http协议可以正常调用，这个问题已经纠结了好久

**Comment by smallnest** [comment]
这是一个bug，在实现jsonrpc2特性的时候引入的。

实现jsonrpc2时，增加了一个cmux.Matcher处理jsonrpc2.0的请求，但是这个matcher对于特定的rpcx tcp请求却会误以为是http jsonrpc,导致不能正确处理。

目前这个bug已修复，可以拉取最新的 rpcx的代码测试。
