### ISSUE TITLE
XClient.Call 的args和reply直接传[]byte数据？

### ISSUE THREAD

**Issue by JungleYe** [smallnest/rpcx#309]
我在rpcx实践中有这个问题：数据流向为 客户端->agent->rpc（pb格式）
agent接收客户端请求，并解析出后续需要发起rpc调用的服务名、方法名、Marshal之后的args（[]byte数据）。在agent转到rpc服务时，我需要把Marshal之后的args（即[]byte）unmarshal到args对象。然后再通过XClient.Call发起rpc调用！
`Call(ctx context.Context, serviceMethod string, args interface{}, reply interface{}) error`
上面做法带来的问题是：
1、agent上需要根据服务名和方法名反射unmarshal出args对象。并且添加了新的rpc服务后，agent也需要更新，很麻烦！

我的问题是：
在XClient中能否加一个api，类似于Call，但args和reply类型为[]byte

`BCall(ctx context.Context, serviceMethod string, args []byte, reply []byte, marshalType int32) error`

这样rpc客户端直接把二进制数据传递到rpc服务端，服务端框架层根据marshalType将args恢复成controller中需要的结构体对象！然后进行业务逻辑的处理……

请赐教！

**Comment by JungleYe** [comment]
补充一下：
1、client.send方法中已经指定了编码方式为 client.option.SerializeType。
2、client包中send和input方法分别处理了args的Encode和reply的Decode。
`data, err := codec.Encode(call.Args)`

`err = codec.Decode(data, call.Reply)`

**Comment by smallnest** [comment]
rpcx协议是包含req/res的元数据类型的， 服务端框架会自动根据服务定义的类型来反序列化。

你可以将Agent的Codes设置为 SerializeNone， https://github.com/smallnest/rpcx/blob/master/protocol/message.go#L83， 然后传递 `
args []byte, reply []byte`即可。 可以使用这种方案尝试一下。

**Comment by JungleYe** [comment]
我尝试了以下两种情况：
S1：
Client：
```
SerializeType:  protocol.SerializeNone,
reqBytes, _ := args.Marshal()
var replyBytes = make([]byte, 0)
err := xclient.Call(ctx, "Mul", reqBytes, replyBytes)

```
Server：
```
func (t *Arith) Mul(ctx context.Context, args *[]byte, reply *[]byte) error {
	fmt.Println("hello world")
	arg := &pbMoney.LoginRequest{}
	arg.Unmarshal(*args)
	fmt.Println(arg)

	return nil
}

```
在S1的情况下 rpc调用正常！

S2：
Client：同S1

Server：
```
func (t *Arith) Mul(ctx context.Context, args *pbUser.LoginRequest, reply *pbUser.LoginResponse) error {
	fmt.Println("hello world")
	reply.Uid = 456
	reply.Code = 0
	return nil
}

```
S2情况下就会报如下panic：

```
panic: reflect: call of reflect.Value.SetBytes on struct Value

goroutine 15 [running]:
reflect.flag.mustBe(0x199, 0x17)
	/usr/local/go/src/reflect/value.go:207 +0xb4
reflect.Value.SetBytes(0x8f6760, 0xc00005e7c0, 0x199, 0xc0000227f8, 0x8, 0x8)
	/usr/local/go/src/reflect/value.go:1393 +0x46
github.com/smallnest/rpcx/codec.ByteCodec.Decode(0xc0000227f8, 0x8, 0x8, 0x9088e0, 0xc00005e7c0, 0xcf0920, 0xc000082d20)
	/media/sf_bygo/src/github.com/smallnest/rpcx/codec/codec.go:40 +0xe6
github.com/smallnest/rpcx/server.(*Server).handleRequest(0xc0000795f0, 0x9a6c60, 0xc00000ca60, 0xc000062cc0, 0x0, 0x0, 0xc0000909c0)
	/media/sf_bygo/src/github.com/smallnest/rpcx/server/server.go:514 +0x296
github.com/smallnest/rpcx/server.(*Server).serveConn.func2(0xc0000795f0, 0xc000062cc0, 0x9a7e80, 0xc0000b4bb0, 0xc00000ca60)
	/media/sf_bygo/src/github.com/smallnest/rpcx/server/server.go:411 +0x1f9
created by github.com/smallnest/rpcx/server.(*Server).serveConn
	/media/sf_bygo/src/github.com/smallnest/rpcx/server/server.go:393 +0x6c4
exit status 2
```

是否有满足S2的client和server的API呢？也就是只省掉客户端对args的序列化和对reply的反序列化的操作？

**Comment by smallnest** [comment]
你这个需求是特殊的， rpcx目前不支持这种特性。但是你可以这样做一点点修改，满足你的需求。

- 在client端将SerializeType放在meta中，这样就能通知服务器采用哪种编码方式
- 在server端修改server.go#508行，使用从meta中读取到SerializeType，而不是rpcx协议中的SerializeType

这样客户端就能发送编码后的slice of byte, 而客户端能正确的进行反序列化

**Comment by smallnest** [comment]
这个我也可以增加一个插件，在消息Encode之前调用一下， 你实现一个插件的方法即可

**Comment by smallnest** [comment]
增加了一个插件接口 ClientBeforeEncodePlugin， 你可以实现`ClientBeforeEncode(*protocol.Message) bool` , 强制设置SerializeType为你的编码。

**Comment by JungleYe** [comment]
更新了代码之后，我实现了ClietnBeforeEncode接口：

type MyPlug struct{}
func (p *MyPlug)ClientBeforeEncode(myp *protocol.Message) bool{
	fmt.Println("come to DoClientBeforeEncode")
	myp.SetSerializeType(protocol.ProtoBuffer)	//设置自己的编解码方式
	return true
}

另外NewXClient中的配置为：SerializeType:  protocol.SerializeNone

实验结果：
1  reply为结构体对象时，rpc调用正常！
2  reply 定义为[]byte时就会报如下错误：
报错信息如下：
2019/02/28 21:20:00 client.go:682: ERROR: rpcx: client protocol error:[]uint8 is not a proto.Unmarshaler
2019/02/28 21:20:00 failed to call: []uint8 is not a proto.Unmarshaler
exit status 1

原因：L620中  err = codec.Decode(data, call.Reply)  此时的codec还是用了protocol.ProtoBuffer。

**Comment by JungleYe** [comment]
不成熟的想法：
client插件中添加一个接口：ClientBeforeDecodePlugin，客户端在收到响应数据之后，指定解码器来解析数据！

**Comment by smallnest** [comment]
added `ClientAfterDecodePlugin` plugin.

encode/decode是指protocol.Message, 而不是args/reply。 可以在发送消息之前或者收到消息之后进行一些自定义的修改。

这样应该可以满足你发送和接收都是slice of byte类型了。

**Comment by JungleYe** [comment]
嗯，验证OK了！插件化的使用和你的答复速度一样。niubility

**Comment by fitlivingmm** [comment]
@JungleYe 你好，想实现和你一样agent ,尝试了好多次，reply 还是不能正确的返回。请问能否提供参考解析的列子或者agent 整体的例子。

**Comment by fitlivingmm** [comment]
success 完整的案例如下，方便需要的人

`


	// ====== client
	type MyClientBeforeEncode struct{}
	func (p *MyClientBeforeEncode) ClientBeforeEncode(myp *protocol.Message) error {
		fmt.Println("====  encode")
		myp.SetSerializeType(protocol.ProtoBuffer)
		return nil
	}

	type MyClientAfterDecode struct{}

	func (p *MyClientAfterDecode) ClientAfterDecode(myp *protocol.Message) error {
		fmt.Println("====  decode")
		myp.SetSerializeType(protocol.SerializeNone)
		return nil
	}




	d, _ := client.NewPeer2PeerDiscovery("tcp@"+*addr, "")

	option := client.DefaultOption
	option.SerializeType = protocol.SerializeNone
	xclient := client.NewXClient("aaa", client.Failtry, client.RandomSelect, d, option)
	xclient.GetPlugins().Add(&MyClientBeforeEncode{})
	xclient.GetPlugins().Add(&MyClientAfterDecode{})





	request := &example.PlayerLoginAPI{
		Language: 1,
	}
	reqBytes, _ := request.Marshal()
	var replyBytes = make([]byte, 0)
	err := xclient.Call(context.Background(), "Test", reqBytes, &replyBytes)
	if err != nil {
		log.Printf("failed to call: %v", err)
	}
	log.Printf("replyBytes:%+v", replyBytes)



	// ====== server
 	func (t *Arith) Test(ctx context.Context, args *PlayerLoginAPI, reply *PlayerLoginReply) error{
		// error
		//reply = &PlayerLoginReply{
		//	Uid:      1,
		//	NickName: "aaa",
		//}

		// right
		*reply = PlayerLoginReply{
			Uid:      1,
			NickName: "aaa",
		}
		return nil
	}

`

**Comment by fitlivingmm** [comment]
@smallnest 你好， rpcx实践中有这个问题：数据流向为 客户端->agent->后台rpc（pb格式）依照上面配置是可以顺利请求和返回数据。现在有个新的需求，每次后台rpc新增一个servicepath ，agent 就需要重新new 一个client才可以调用，可以默认去掉servicepath 只需要通过method来注册调用api吗？

**Comment by smallnest** [comment]
根据微服务的实践，一旦api broken,你应该加版本号的，客户端选择要调用哪个版本的服务。 否则，客户端或者rpcx怎么知道你想调用新版的还是旧版的服务？

**Comment by fitlivingmm** [comment]
@smallnest 恩，新增api后，正常的实践是应该添加版本号。表达错误了。最终rpc 还是调用函数，能否有选择不采用servicepath前缀注册，现在rpcx client 限制在servicepath 其中，个人不成熟的想法，能否直接采用函数名称注册。函数的版本也可以通命名来区分。

**Comment by fitlivingmm** [comment]
@smallnest 恩，新增api后，正常的实践是应该添加版本号。表达错误了。有一个不成熟的想法，最终rpc 还是调用函数，能否在函数注册的采用这样的servicepath+method 格式，这样rpxc cient 调用就不用限制了servicepath里了。
etcd 注册结构是这样的
// rpc1
/rpcx_rpcxdemo/server/test/tcp@localhost:8973

// rpc2
/rpcx_rpcxdemo/server/test/tcp@localhost:8972
/rpcx_rpcxdemo/server/add/tcp@localhost:8972
