### ISSUE TITLE
thread not save bug

### ISSUE THREAD

**Issue by shikbupt** [smallnest/rpcx#310]
func (c *xClient) getCachedClient(k string) (RPCClient, error) {
	c.mu.RLock()
	breaker, ok := c.breakers.Load(k)
	if ok && !breaker.(Breaker).Ready() {
		c.mu.RUnlock()
		return nil, ErrBreakerOpen
	}
	client := c.cachedClient[k]
	if client != nil {
		if !client.IsClosing() && !client.IsShutdown() {
			c.mu.RUnlock()
			return client, nil
		}
		delete(c.cachedClient, k)
		client.Close()
	}
	c.mu.RUnlock()

delete(c.cachedClient, k) will cause concurrent map writes。when mutil goroutine have the same xclient and Call the service concurrently. Then delete will has chance to cause mutil goroutine write the  same map. the thread not safe.
the code should use c.mu.Lock not the c.mu.RLock().

**Comment by smallnest** [comment]
fixed
