### ISSUE TITLE
rpcx这种组件不应该执行os.Exit(0), 这样外面很多收尾的工作就无法做了.

### ISSUE THREAD

**Issue by yangxuanjia** [smallnest/rpcx#312]
rpcx这种组件不应该执行os.Exit(0), 这样外面很多收尾的工作就无法做了.
建议把os.Exit(0)去掉.

func (s *Server) startShutdownListener() {
	go func(s *Server) {
		log.Info("server pid:", os.Getpid())
		c := make(chan os.Signal, 1)
		signal.Notify(c, syscall.SIGTERM)
		si := <-c
		if si.String() == "terminated" {
			if nil != s.onShutdown && len(s.onShutdown) > 0 {
				for _, sd := range s.onShutdown {
					sd(s)
				}
			}
			// os.Exit(0)
		}
	}(s)
}

**Comment by smallnest** [comment]
是的。rpcx不应该负责程序退出。已修改。
