### ISSUE TITLE
Does it has client multiplex?

### ISSUE THREAD

**Issue by itgeniusshuai** [smallnest/rpcx#316]
I see the example, I must instantiate a new client object.Can it multiplex?

```
var d = client.NewPeer2PeerDiscovery("tcp@localhost:8972", "")
var xclient = client.NewXClient("GetService", client.Failtry, client.RandomSelect, d, client.DefaultOption)
func  callService()  {
	// #2
	var reply *[]byte
	err := xclient.Call(context.Background(), "Query", nil, &reply)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(string(*reply))
}

func  callService1()  {
	// #2
	var reply *[]byte
	err := xclient.Call(context.Background(), "Query2", nil, &reply)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(string(*reply))
}
```

When I call two services,xclient is global, can it has some problem?

**Comment by smallnest** [comment]
XClient and OneClient can be used concurrenctly. It is no problem.

It looks you use one service and call its two methods, you can use the shared XClient.

If you use multiple servics such as `service1`, `service2`, `service3`...., you can use OneClient.

Anyway, both they are called concurrenctly.
