### ISSUE TITLE
请教大佬一个问题，rpcx 如何跟kong api gateway搭配使用

### ISSUE THREAD

**Issue by scfobao** [smallnest/rpcx#318]
如题。谢谢

**Comment by smallnest** [comment]
rpcx推荐你使用本身的胖客户端的模式，这样相对http来说可以取得很高性能。

因为某种原因，如果你必须使用kong api gateway,你可以按照http方式访问rpcx services, 把rpcx services 部署成kong的服务。

有两种方式可以通过http方式访问rpcx services:

1. http invoke: http://doc.rpcx.site/part6/http_invoke.html
2. jsonrpc-2.0: https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/jsonrpc2

**Comment by scfobao** [comment]
@smallnest 好的。谢谢
