### ISSUE TITLE
数据类型在传输时候被修改

### ISSUE THREAD

**Issue by shileislslsl** [smallnest/rpcx#325]
我在rpc请求时候设定了通用的请求数据结构，其中包含一个interface{}，
但是在使用过程中发现客户端有时候接收到的interface{}类型为map，不能理解是什么bug，有时候是string。
![Screenshot from 2019-05-22 11-26-21](https://user-images.githubusercontent.com/24676420/58145410-8fb45c00-7c84-11e9-8672-ecde0e285354.png)
部分代码如下：
```
msg := public.Msg_S2C_TableIn{
			Id:     ack.TId,
			GameId: ack.GameId,
			KindId: ack.KindId,
			Ip:     ack.Ip}
		fmt.Println("put struct in return 772")
		sendMsg(constant.MsgTypeHouseTableIn, code, &msg, uid)

func sendMsg(head string, errCode int16, v interface{}, uid int64) {
	if head == "" {
		return
	}
	args := public.ServerMsgReq{
		UID:       uid,
		Data:      v,
		Head:      head,
		From:      "hall",
		ToServer:  "gate",
		NeedReply: false,
	}
	if head == "testhead" {
		fmt.Println("beforesend:", reflect.TypeOf(args.Data))
	}
	callRpc.CallGate(&args)
}

```

不知道是我使用姿势哪里有问题？

**Comment by smallnest** [comment]
这和rpcx或者哪个编码器无关。 和Go语言有关。

你可以想象一下， 你设置一个字段为interface{},  收到随便一个数据，你能把它解析成什么类型？

所以尽量不要设置字段为interface{}, 即使你使用再聪明的AI，程序也不能确定要解析成什么类型。
