### ISSUE TITLE
使用XClient.SendRaw在服务器端无法收到认证信息

### ISSUE THREAD

**Issue by kidnet** [smallnest/rpcx#329]
在使用XClient.SendRaw的时候，发现服务器端无法收到认证使用的token，使用Call可以正常获取到token。代码如下
`  w.xclient.Auth(w.token)`
`  ctx := context.WithValue(context.Background(), share.ReqMetaDataKey, make(map[string]string))`
`  m, payload, err := w.xclient.SendRaw(ctx, w.req)`

**Comment by smallnest** [comment]
fixed.
