### ISSUE TITLE
请问现在能否被用于生产环境？

### ISSUE THREAD

**Issue by henrylee2cn** [smallnest/rpcx#33]

**Comment by smallnest** [comment]
是的。目前rpcx的功能已经稳定，可以用于生产环境，建议采用ZooKeeper注册中心或者Etcd注册中心。

目前准备增加的一个功能是根据网络状况选择合适的路由，这个在将服务部署在多个数据中心的时候会有用。

非常欢迎你提供意见和建议，共同促进RPCX的增长。

**Comment by henrylee2cn** [comment]
ok，今天看了你的代码，感觉扩展地非常棒，感谢你的无私奉献！

**Comment by henrylee2cn** [comment]
同时我发现一个Authorization的编码固定为了gob，这样在跨语言使用时不方便，因此建议和全局的编码方式保持一致

**Comment by smallnest** [comment]
谢谢指出这个问题。这个不太好控制的是有各种的序列化库，将来还可能增加更多的序列化库，如果和序列化库保持一致代码不太好同步。 

其实Authorization的信息很少，直接拼装字符串也就可以了，没必要gob编码。考虑到跨语言的需求，我把它改成普通字符串好了

**Comment by henrylee2cn** [comment]
嗯，这里使用字符串足够了。
不过考虑到一些其他的插件，其实这里应该需要有个继承编码方式的参数，另外如果可以支持分组的话，那么插件定义在分组上，使用起来就会非常灵活了。
