### ISSUE TITLE
是否有成功或大规模高并发使用场景案例

### ISSUE THREAD

**Issue by CodeLazier** [smallnest/rpcx#330]
如题,rpcx功能丰富,满足了很多需求.设计也较为简洁流畅.就不知道是否有成功案例可以分享以利前期调研选型.避免过多踩坑.

**Comment by smallnest** [comment]
rpcx在很多初创企业和发展中的互联网企业中使用。 比如上海某海外游戏公司采用rpcx替换他们原先的java系统，为公司每月可节省50万港元的费用，机器使用少了，负载还降低了。

另一个优秀的rpcx使用者是电商网站 http://Paigogo.com, 它是一家原汁原味的日本代购网站，后台的微服务架构采用的是rpcx。

rpcx秉承的理念就是最简单的写法，实现最强大的功能，至少目前看来还没有出其右的Go rpc架构。

如果公司准备选型微服务框架，除了简单易开发、易维护、功能是否满足，性能是否强大以外，很大的一个考量就是公司的技术栈。

- 如果公司是纯java技术栈，采用dubbo比较好，java生态圈使用的比较多
- 如果是纯Go的技术栈,
  - 如果服务规模比较小，可以考虑标准库的rpc或者grpc, 暂时忽略服务治理的功能
  - 如果服务规模比较大，或者在可预见的将来比较大，建议使用rpcx
- 如果公司是混合技术栈，php, python, java, go等技术栈都有
  - 采用restful的api更方便
  - 如果服务规模比较小，可以考虑标准库的grpc, 暂时忽略服务治理的功能
  - 如果服务规模比较大，或者在可预见的将来比较大，建议使用rpcx,rpcx支持http调用和jsonrpc2.0调用,可以支持其它语言调用。方便公司向go技术栈过度

**Comment by CodeLazier** [comment]
谢谢!
