### ISSUE TITLE
哪里用到原生rpc 库net/rpc了？

### ISSUE THREAD

**Issue by harlanc** [smallnest/rpcx#332]
没有发现rpcx里面有net/rpc引用？

**Comment by pengshaomin** [comment]
4.0版本好像移除了，自己实现rpc

**Comment by harlanc** [comment]
是不是要更新下文档？
It is developed based on Go net/rpc and provides extra governance features.

**Comment by smallnest** [comment]
Then where is the this sentence from currenctly?

**Comment by harlanc** [comment]
wiki 首页

**Comment by smallnest** [comment]
移除了过时的wiki,所有的文档移到了 https://doc.rpcx.site

**Comment by harlanc** [comment]
赞
