### ISSUE TITLE
Serverplugin issue

### ISSUE THREAD

**Issue by w01fb0ss** [smallnest/rpcx#333]
![image](https://user-images.githubusercontent.com/44709004/60635936-1d1fca00-9e47-11e9-85bd-1fbe2bd2a3b4.png)
![image](https://user-images.githubusercontent.com/44709004/60635949-27da5f00-9e47-11e9-817e-cf502dbfc7b7.png)

[// +build etcd] should be changed to [// +build aix darwin dragonfly freebsd linux netbsd openbsd solaris]

**Comment by w01fb0ss** [comment]
Other plug-ins should also be changed to [// +build aix darwin dragonfly freebsd linux netbsd openbsd solaris]

**Comment by smallnest** [comment]
please learn go tags first
