### ISSUE TITLE
使用consul的疑问

### ISSUE THREAD

**Issue by caobingsheng** [smallnest/rpcx#337]
使用consul时，将producer信息put到consul的kv存储中了，但是consul是有专门的服务发现功能的，不知道rpcx中这样用会有什么影响？健康检查会生效吗？看过其他语言实现好像不是这样用的，仅仅是疑问

**Comment by smallnest** [comment]
rpcx使用 https://github.com/docker/libkv 作为zookeeper,etcd,consul的通用抽象层，它是基于kv的方式。

支持过期的特性，所以健康检查没有问题。
