### ISSUE TITLE
请教一下关于服务发现的疑问。

### ISSUE THREAD

**Issue by jiangrzh** [smallnest/rpcx#338]
rpcx使用zookeeper/etcd/consul作为注册中心时，如果使用NewXXXDiscoveryStore或者NewConsulDiscoveryTemplate等API查找的ServicePath不存在时，会直接抛出异常：
``` bash
consul_discovery.go:60: INFO : cannot get services of from registry: rpcx/Stations%!(EXTRA *errors.errorString=Key not found in store)
panic: Key not found in store
```

如果这样的情况放在agent或者gateway这样的服务进程中该怎么处理才好？
是否改为能被上层捕获的处理Error更合适?

**Comment by smallnest** [comment]
目前你可以通过`recover`捕获这个panic,后续会在函数的返回值中增加一个error

**Comment by jiangrzh** [comment]
受教，看了rpcx-gateway的代码，发现就是这么做的👍
