### ISSUE TITLE
请教一下关于服务发现中注册的服务地址

### ISSUE THREAD

**Issue by jiangrzh** [smallnest/rpcx#341]
如果服务以tcp://0.0.0.0:NNN 为监听地址，并注册到consul中。
客户端在consul拿到的服务地址就是0.0.0.0，然后就无法连接服务端了。

**Comment by smallnest** [comment]
解决方案一: 不要使用`0.0.0.0`地址，使用明确的地址，否则客户端没办法知道服务器的信息

解决方案二：配置consul插件的AdvertiseAddress字段，让服务使用这个IP注册到consul中

**Comment by smallnest** [comment]
相关issue #190
