### ISSUE TITLE
MutipleServersDiscovery结构体中Update方法没有开放接口导致没法调用

### ISSUE THREAD

**Issue by Lonenso** [smallnest/rpcx#343]
官方文档及源码中都提到了 MultipleServersDiscovery有Update方法用来更新servers。但看了源码发现ServiceDiscovery这个interface里没有Update方法

**Comment by smallnest** [comment]
type assert

d.(* MultipleServersDiscovery)

Update是`MultipleServersDiscovery `独有的方法，不是接口中的方法

**Comment by Lonenso** [comment]
是的，我看到是独有的方法了，请问如果要调用这个方法应该怎么做，因为我看到 MultipleServersDiscovery 里没有办法获取到跟xclient里同样chan。

**Comment by Lonenso** [comment]
谢谢，懂了
