### ISSUE TITLE
io: read/write on closed pipe

### ISSUE THREAD

**Issue by botemple** [smallnest/rpcx#344]
MicroService Err: io: read/write on closed pipe
github.com/xtaci/kcp-go.(*UDPSession).WriteBuffers
        /go/src/github.com/xtaci/kcp-go/sess.go:321
github.com/xtaci/kcp-go.(*UDPSession).Write
        /go/src/github.com/xtaci/kcp-go/sess.go:261
github.com/smallnest/rpcx/client.(*Client).send
        /go/src/github.com/smallnest/rpcx/client/client.go:533
github.com/smallnest/rpcx/client.(*Client).Go
        /go/src/github.com/smallnest/rpcx/client/client.go:236
github.com/smallnest/rpcx/client.(*xClient).Go
        /go/src/github.com/smallnest/rpcx/client/xclient.go:370
github.com/smallnest/rpcx/client.(*xClient).Call

We use fail backup and with timeout options, it always show the error like this.
Is it just because of timeout problem or might have some other option could tuning?

**Comment by smallnest** [comment]
You can  check whether you send your calls after timeout. It is normal if you send requests after timeout.

From code of kcp-go,  "read/write on closed pipe" happended because the session is closed
