### ISSUE TITLE
 rpcx: failed to handle request: The entry size is larger than 1/1024 of cache size

### ISSUE THREAD

**Issue by botemple** [smallnest/rpcx#345]
I encounter the problem as following:

 rpcx: failed to handle request: The entry size is larger than 1/1024 of cache size

What should I trace to debug it? is it because the request is too large? what's the size of the cache size. where is the setting for change the cache size?

**Comment by smallnest** [comment]
First, you can search "The entry size is larger than" in rpcx project. It is not error of rpcx.
Second, you can search the error by google. It is an error of freecache. It is an error of your implementation.

**Comment by botemple** [comment]
Thanks, finally I figure out the problem.forget to update in here.
The weird thing is that rpcx report free-cache's error . make me on the wrong track.
