### ISSUE TITLE
when using OpentracingPlugin, there will be a nil interface conversion in share.GetSpanContextFromContext

### ISSUE THREAD

**Issue by nuknal** [smallnest/rpcx#346]
The panic occurred in 

`DoPreCall`-->
`share.GetSpanContextFromContext{`
 `     reqMeta := ctx.Value(ReqMetaDataKey).(map[string]string)`
 `     ...}`

Because there wasn't a `ReqMetaDataKey` in context, and I don't think it's necessary to set  meta data like `map[string]string{}` when I have nothing to send to server in my code.

**Comment by smallnest** [comment]
fixed
