### ISSUE TITLE
In my service, I cannot get opentracing span by opentracing.SpanFromContext().

### ISSUE THREAD

**Issue by nuknal** [smallnest/rpcx#347]
I know that span is stored in tags of share.Context. Every time I need create a child span, I have to do this in every function of my service:
`if rpcxContext, ok := ctx.(*share.Context); ok {`
		`span1 := rpcxContext.Value(share.OpentracingSpanServerKey)`
`newCtx=opentracing.ContextWithSpan(...)`
`
	}
`
It is a little boring. Just store the span in value of context when handle request maybe a better way (or a conventional way of using opentracing in go)?
`res, err := s.handleRequest(newCtx, req)`

**Comment by smallnest** [comment]
I  am not sure what problem you have met?

For you service, ni you can get the span from context:

```
ctx.GetValue(share.OpentracingSpanServerKey)
```

If you want to write a plugin, you can refer to https://github.com/smallnest/rpcx/blob/master/serverplugin/opentracing.go

**Comment by smallnest** [comment]
You can write a plugin just like OpenTracingPlugin to handle span.
