### ISSUE TITLE
使用etcd作为注册中心，用docker部署服务，server 的地址如何设置？

### ISSUE THREAD

**Issue by scfobao** [smallnest/rpcx#349]
addr     = flag.String("addr", "localhost:8977", "server address")
	etcdAddr = flag.String("etcdAddr", "192.168.2.227:12379", "etcd address")
	basePath = flag.String("base", "/rpcx_test", "prefix path")

**Comment by smallnest** [comment]
服务端在配置Etc插件的时候设置对外的广播地址，这样服务端注册带etcd上的地址客户端就可以访问了。

https://github.com/smallnest/rpcx/blob/master/serverplugin/etcd.go#L29

**Comment by scfobao** [comment]
server上我配置成这样
addr     = flag.String("addr", ":8977", "server address")
etcdAddr = flag.String("etcdAddr", "192.168.2.227:12379", "etcd address")
basePath = flag.String("base", "/rpcx_test", "prefix path")

客户端和docker 部署的服务都在一台机器上时可以正常工作
但docker部署的服务在另一台机器上时，就不行了。
他们都在一个网络，可以相互访问的

**Comment by scfobao** [comment]
docker run -it -p 192.168.2.227:8990:8990 scfobao/server-test:1.0.2  可以了

**Comment by smallnest** [comment]
看看ectd中服务端注册的地址是多少，然后看看client获取到的地址是什么，查查日志，看看哪儿配置的不对
