### ISSUE TITLE
没有找到etcd v3的example呀

### ISSUE THREAD

**Issue by dean2021** [smallnest/rpcx#351]
> 支持

没有找到v3的实例呀，https://github.com/rpcx-ecosystem/rpcx-examples3

_Originally posted by @dean2021 in https://github.com/smallnest/rpcx/issues/350#issuecomment-523815742_

**Comment by dean2021** [comment]
作者方便留个联系方式吗？微信群什么的。  @smallnest

**Comment by smallnest** [comment]
qq2群 看readme
