### ISSUE TITLE
使用etcd时,用RegisterFunctionName的注册问题

### ISSUE THREAD

**Issue by CodeLazier** [smallnest/rpcx#353]
在etcd示例中有注册函数:
s.RegisterName("Arith", new(example.Arith), "")
但我换成RegisterFunctionName,如:
s.RegisterFunctionName("Arith","subPath",testFun,"")
其中:
func testFun(ctx context.Context, req *string, res *string) error {
	return nil
}
发现并不能成功往etcd中写入相应的路径和值.请问RegisterFunctionName不支持注册到etcd还是使用上的不对?

**Comment by smallnest** [comment]
注册register function有问题，etcd等注册中心无法找到服务，**已修复**。 

你可以跑example3/function/etcd的例子，或者你自己的例子验证。

**Comment by CodeLazier** [comment]
我这里验证正确.感谢!
