### ISSUE TITLE
Graceful shutdown of Client

### ISSUE THREAD

**Issue by nuknal** [smallnest/rpcx#354]
我注意到在client.Close()中，pending中的连接会被直接以err结束。

可否提供一个更加平滑的接口：在重启or升级某个调用了其它服务的实例时，client.Close()时能否对pending中的client进行阻塞等待，即调用的服务全部返回（或超时）之后再关闭掉rpcx client，这样在重启前的本实例请求都有响应。

**Comment by smallnest** [comment]
client无法保证服务器发生了什么，以及服务器什么时候返回，一旦发现服务器异常或者连接断了，最安全快速的方式返回error。

rpcx提供了retry和failover的各种姿势保证服务还可以继续调用，以便调用者还可以得到正确的响应
