### ISSUE TITLE
go 1.12  执行# go mod vendor  报错

### ISSUE THREAD

**Issue by happyhakka** [smallnest/rpcx#355]
go: downloading github.com/lucas-clemente/quic-go v0.12.0
verifying github.com/lucas-clemente/quic-go@v0.12.0: checksum mismatch
	downloaded: h1:TRbvZ6F++sofeGbh+Z2IIyIOhl8KyGnYuA06g2yrHdI=
	go.sum:     h1:dYHUyB50gEQlK3KqytmNySzuyzAcaQ3iuI2ZReAfVrE=

**Comment by smallnest** [comment]
quic-go和quic-conn目前有问题，等待官方修复

**Comment by smallnest** [comment]
我更新了一下quic-conn,使用定制的quic-conn, 因为官方的quic-conn没有及时更新，会报错。
可以尝试更新代码，使用最新的go.mod
