### ISSUE TITLE
同一个客户端连接不同服务端, tls配置中servername问题

### ISSUE THREAD

**Issue by Lonenso** [smallnest/rpcx#358]
想要实现tls的认证, 客户端使用multipleserver,去连接不同服务端, 这里servername会出现问题.
比如我传入a的tls配置,那就不可能连接到b.

请问一下有什么解决办法吗

**Comment by smallnest** [comment]
如果自定义的CA,那么所有的服务都使用统一的CA。 
如果公共的CA, 比如操作系统内置的CA,那么和其它的tls client一样。
如果不同的服务使用不同的CA,你得检查你的架构是不是有问题，如果你非要这样，那么自定义tlsconfig

**Comment by Lonenso** [comment]
> 如果自定义的CA,那么所有的服务都使用统一的CA。
> 如果公共的CA, 比如操作系统内置的CA,那么和其它的tls client一样。
> 如果不同的服务使用不同的CA,你得检查你的架构是不是有问题，如果你非要这样，那么自定义tlsconfig
你好, 感谢回复
这里指的是tls.Config 里的servername, 大概是验证证书CN, 所以不是指CA, 这里的CA我用的统一的.
再来是我发现的解决方法, 设置servername为""(空字符串), 会默认设置servername为对端的ip.
具体在tls/tls.go , DialWithDialer 141 行
