### ISSUE TITLE
XClient support concurrent access ?

### ISSUE THREAD

**Issue by ericdotwang** [smallnest/rpcx#362]
Does XClient support concurrent access?
I got some datarace issues.
WARNING: DATA RACE
Read at 0x00c0012f9289 by goroutine 412:
  github.com/smallnest/rpcx/client.(*Client).IsShutdown()
Previous write at 0x00c0012f9289 by goroutine 414:
  github.com/smallnest/rpcx/client.(*Client).input()

**Comment by smallnest** [comment]
XClient is **thread-safe** and support concurrent access.

But from your log, it looks the call is accessed by multiple goroutines. Please make sure you use independent Calls.

**Comment by ericdotwang** [comment]
i am sorry, i can't understand. What do you mean about "Please make sure you use independent Calls." ?

I want to call xclient.Go(...) or xlient.Call(...) by multiply goroutines.
But i got some datarace as following:
============================================
WARNING: DATA RACE
Read at 0x00c0006791b9 by goroutine 283:
  github.com/smallnest/rpcx/client.(*Client).heartbeat()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/client.go:714 +0x10c

Previous write at 0x00c0006791b9 by goroutine 281:
  ??()
      -:0 +0xffffffffffffffff
  bufio.(*Reader).Read()
      /usr/local/go/src/bufio/bufio.go:216 +0x78d
  io.ReadAtLeast()
      /usr/local/go/src/io/io.go:310 +0x95
  io.ReadFull()
      /usr/local/go/src/io/io.go:329 +0x72
  github.com/smallnest/rpcx/protocol.(*Message).Decode()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/protocol/message.go:405 +0x97
  github.com/smallnest/rpcx/client.(*Client).input()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/client.go:574 +0x226

Goroutine 283 (running) created at:
  github.com/smallnest/rpcx/client.(*Client).Connect()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/connection.go:66 +0x4fb
  github.com/smallnest/rpcx/client.(*xClient).getCachedClient()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/xclient.go:270 +0x46d
  github.com/smallnest/rpcx/client.(*xClient).selectClient()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/xclient.go:232 +0x1c0
  github.com/smallnest/rpcx/client.(*xClient).Go()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/xclient.go:366 +0x14e


WARNING: DATA RACE
Read at 0x00c0012f9289 by goroutine 412:
  github.com/smallnest/rpcx/client.(*Client).IsShutdown()
Previous write at 0x00c0012f9289 by goroutine 414:
  github.com/smallnest/rpcx/client.(*Client).input()

==================
WARNING: DATA RACE
Read at 0x00c0012f9289 by goroutine 412:
  github.com/smallnest/rpcx/client.(*Client).IsShutdown()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/client.go:198 +0x41
  github.com/smallnest/rpcx/client.(*xClient).getCachedClient()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/xclient.go:248 +0x964
  github.com/smallnest/rpcx/client.(*xClient).selectClient()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/xclient.go:232 +0x1c0
  github.com/smallnest/rpcx/client.(*xClient).Go()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/xclient.go:366 +0x14e


Previous write at 0x00c0012f9289 by goroutine 414:
  github.com/smallnest/rpcx/client.(*Client).input()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/client.go:672 +0x1a5e

Goroutine 412 (running) created at:
      /home/devel/goapp/CloudServ/src/xxx/dataserver/rpc/rpc_service.go:85 +0x1d6
  runtime.call64()
      /usr/local/go/src/runtime/asm_amd64.s:523 +0x3a
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:308 +0xc0
  github.com/smallnest/rpcx/server.(*service).call()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/server/service.go:361 +0x26d
  github.com/smallnest/rpcx/server.(*Server).handleRequest()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/server/server.go:529 +0xe38
  github.com/smallnest/rpcx/server.(*Server).serveConn.func2()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/server/server.go:414 +0x2b2

Goroutine 414 (finished) created at:
  github.com/smallnest/rpcx/client.(*Client).Connect()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/connection.go:63 +0x47e
  github.com/smallnest/rpcx/client.(*xClient).getCachedClient()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/xclient.go:270 +0x46d
  github.com/smallnest/rpcx/client.(*xClient).selectClient()
      /home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/xclient.go:232 +0x1c0
  github.com/smallnest/rpcx/client.(*xClient).Go()

==================

**Comment by smallnest** [comment]
You can paste your client code here.

I suspect you use a shared `done chan *Call` object for multiple goroutines when you use `xclient.Go`

**Comment by smallnest** [comment]
You can paste your client code here.

I suspect you used a shared `done chan *Call` object for multiple goroutines when you use `xclient.Go`

**Comment by ericdotwang** [comment]
init xclient:

option := client.DefaultOption
option.Heartbeat = true
option.HeartbeatInterval = 2 * time.Second
xclient := client.NewXClient(serviceName, client.Failtry, client.RandomSelect, d, option)


call:

xc.Go(context.Background(), method, args, &reply, nil)


thx.

**Comment by smallnest** [comment]
I got it. 

`/home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/client.go:198` and `/home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/client.go:714`
and `/home/devel/goapp/CloudServ/src/github.com/smallnest/rpcx/client/client.go:749` have `Data RACE` issues. 

for some cases I have not used lock to access shutdown for performance so it has  data race. But I think it won't affect your app. 

I will review it and consider adding  mutex.Lock for all accessing shutdown

**Comment by ericdotwang** [comment]
Thanks.
Yes, i just got some datarace warnings.

**Comment by smallnest** [comment]
fixed
