### ISSUE TITLE
Can you provide an example for Python？

### ISSUE THREAD

**Issue by WavesLi** [smallnest/rpcx#363]
I want use it in Python. Do you have a plan for it?

**Comment by smallnest** [comment]
No, there is no implementation for python in raw protocol.
But you can use python as clients to invoke rpcx services in Go/Rust/Java.

https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/jsonrpc2
https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/http_invoke
