### ISSUE TITLE
是不是可以在服务注册信息中增加版本号？

### ISSUE THREAD

**Issue by jiangrzh** [smallnest/rpcx#365]
在服务注册信息中增加版本号，然后针对版本设置服务不同版本的使能状态，就能实现不同的服务发布策略了。

**Comment by smallnest** [comment]
你可以在meta中设置额外的信息， 比如版本

**Comment by jiangrzh** [comment]
Meta也写进注册中心么？要实现使能得操作注册中心或Gateway一类的东西吧

**Comment by smallnest** [comment]
client使用注册中心才能访问服务端的信息，或者手工在客户端配置，或者服务自己实现一个getVersion方法。 有多种方式可以实现。

**Comment by jiangrzh** [comment]
恩恩，先动手试试

**Comment by jiangrzh** [comment]
感觉getVersion放到服务里面自己实现不怎么科学啊，难道不是rpcx作为服务治理的基础设施提供能力会更合适？
