### ISSUE TITLE
如何在客户端获取到自身的ip

### ISSUE THREAD

**Issue by Lonenso** [smallnest/rpcx#367]
多网卡情况下, 客户端有没有办法获取到与服务端连接时的客户端ip.
例如 客户端B有多网卡 e1, e2, e3, 连接A服务端的RPC服务.可能是e1 连, 可能是e2连

B有没有办法获取到此时去连接的网卡的ip地址, (排除 直接net.Dial A的ip地址这种方法)
另外使用的是xclient, 如果这个有影响的话

**Comment by smallnest** [comment]
没有办法。

因为B 可能连接Lan1的A1, Lan2的A2,Lan3的A3, 它可能会使用不同的lan的地址访问不同的服务节点，所以在这种情况下你没有办法说xclient使用的IP是哪一个， 因为它使用多个IP。

特殊的情况是A1、A2、A3......和xclient在同一个Lan中，那么xclient可能使用固定的IP, 但是特例的情况无法使用通用的数据结构表现出来。

xclient将来可以把`cachedClient`暴露出来，这样可以遍历RPCClient的Conn，得到每个连接所使用的本地地址

**Comment by smallnest** [comment]
或者你实现`ClientConnectedPlugin`插件，每次连接的时候会获得创建Conn,通过Conn得到本地的连接

**Comment by Lonenso** [comment]
> 或者你实现`ClientConnectedPlugin`插件，每次连接的时候会获得创建Conn,通过Conn得到本地的连接

你好, 请更新 rpcx-example plugin\client ClientConnected方法的返回类型 error.

**Comment by smallnest** [comment]
updated
