### ISSUE TITLE
golang.org\x\sys\windows\dll_windows.go:21:6: missing function body

### ISSUE THREAD

**Issue by nimoyao2** [smallnest/rpcx#369]
Hello ，author。
     I encounter the error what is golang.org\x\sys\windows\dll_windows.go:21:6: missing function body  when I run eample. The example is one of client in  rpcx-ecosystem/rpcx-examples3 . 
    I don't know if I import less stuff or others , I hope to get your help.

**Comment by smallnest** [comment]
I think it is your x/sys issue. delete it and re-install it. update golang

**Comment by nimoyao2** [comment]
thank you .I try the command go get +name , it is not successful . Therefore i get it by clone. is it ok?&nbsp; or can you tell me how to installl ,thank you



---Original---
