### ISSUE TITLE
rpcx sendraw response Error

### ISSUE THREAD

**Issue by zhaoqb** [smallnest/rpcx#371]
env: go 1.12.1
rpcx: github.com/smallnest/rpcx v0.0.0-20191008054500-6a4c1b1de0fa
使用client.sendraw, SerializeType：protobuf
响应的PB格式：
import "google/protobuf/any.proto";
// response
message Resp {
    int32  code         = 1; // 返回码
    uint64 req_time     = 2; // 请求时间
    uint64 time         = 3; // 当前服务器时间
    string msg          = 4;
    google.protobuf.Any  data   = 5;
}
********************
使用:
 go funcA() { client.Sendraw(....) }()
 go funcB() { client.Sendraw(....) }()
同时请求同一个servicepath和servicemethod，偶尔出现sendraw响应的payload错误（貌似内存被覆盖）。
在client/client.go 的input接收数据时：
if call.Raw {
    call.Metadata, call.Reply, _ = convertRes2Raw(res)
  log.Info("call payload: ", call.Reply, "args=", call.Args)
}  这里的call.Reply的内容是正确的，然后进入call.done(),将call对象发给call内部的channel，
在channel接收数据后
select {
.....
case call := <-done:
		err = call.Error
		m = call.Metadata
		if call.Reply != nil {
                       // 这里的call.Reply的数据（protobuf的marshal）偶尔出现问题，和上面client.input时接收的不一致
			log.Info("chan payload: ", **call.Reply**, "args=", call.Args)
			payload = call.Reply.([]byte)
		}
	}
}

求大神指导下

**Comment by zhaoqb** [comment]
以下是出现问题的 log call payload: 和 chan payload: 打印
2019/10/14 06:50:14.807 [RPCX.rpc] [I] call payload: [16 130 183 160 200 220 45 24 166 181 144 237 5 42 8 18 6 16 166 181 144 237 5] seq=18
2019/10/14 06:50:14.807 [RPCX.rpc] [I] call payload: [16 130 183 160 200 220 45 24 166 181 144 237 5 42 0] seq=17
2019/10/14 06:50:14.808 [Proxy.node] [E] bug: payload error="proto: wrong wireType = 2 for field ReqTime" serialtype=2
2019/10/14 06:50:14.808 [RPCX.rpc] [I] chan payload: [16 130 183 160 200 220 45 24 166 181 144 237 5 42 0 18 6 16 166 181 144 237 5] seq=18
2019/10/14 06:50:14.808 [RPCX.rpc] [I] chan payload: [16 130 183 160 200 220 45 24 166 181 144 237 5 42 0] seq=17

**Comment by smallnest** [comment]
你的rpcx的版本？

**Comment by zhaoqb** [comment]
go mod   github.com/smallnest/rpcx v0.0.0-20191008054500-6a4c1b1de0fa

**Comment by zhaoqb** [comment]
func TestSS(t *testing.T) {
	rep := getTicketLocal_test()
	if rep.Ticket == nil {
		panic("ticket invalid")
	}

	wg1.Add(2)
	nowt := utils.TimestampUint()

	option := client.DefaultOption
	option.SerializeType = protocol.ProtoBuffer
	
	d := client.NewEtcdDiscovery("/com/keywea/rpcx", "com.keywea.PlayerService", []string{"localhost:2379"}, nil)
	xclient := client.NewXClient("com.keywea.PlayerService", client.Failfast, client.RandomSelect, d, option)
	defer xclient.Close()

	args := &res.Resq{
		Ticket:  rep.Ticket,
		ReqTime: nowt,
		Biz:     3020,
	}
	d1, _ := args.Marshal()
	go request(xclient, 1, d1)

	args2 := &res.Resq{
		Ticket:  rep.Ticket,
		ReqTime: nowt,
		Biz:     3023,
	}
	d2, _ := args2.Marshal()
	go request(xclient, 2, d2)

	wg1.Wait()
}

**Comment by zhaoqb** [comment]
func request(c client.XClient, seqid uint64, body []byte) {
	rpcxReq := protocol.GetPooledMsg()
	rpcxReq.SetMessageType(protocol.Request)
	rpcxReq.SetSeq(seqid)
	rpcxReq.ServicePath = "com.keywea.PlayerService"
	rpcxReq.ServiceMethod = "Bizz"
	rpcxReq.SetSerializeType(protocol.ProtoBuffer)
	rpcxReq.Payload = body
	rpcxReq.SetOneway(false)
	defer protocol.FreeMsg(rpcxReq)

	rpcctx, cancelFn := context.WithTimeout(context.Background(), time.Duration(10*time.Second))
	_, payload, e := c.SendRaw(rpcctx, rpcxReq)
	cancelFn()
	if e != nil {
		fmt.Println(e)
	}

	fmt.Println("bug: playload len", len(payload))
	respp := &res.Resp{}
	epp := respp.Unmarshal(payload)
	if epp != nil {
		fmt.Println("bug: payload", epp)
	}
	wg1.Done()
}

**Comment by zhaoqb** [comment]
=== RUN   TestSS
2019/10/14 16:07:42 client.go:626: INFO : call payload: [16 206 217 144 237 5 24 206 217 144 237 5 42 8 18 6 16 206 217 144 237 5]args=2
2019/10/14 16:07:42 client.go:626: INFO : call payload: [16 206 217 144 237 5 24 206 217 144 237 5 42 0]args=1
2019/10/14 16:07:42 client.go:419: INFO : chan payload: [16 206 217 144 237 5 24 206 217 144 237 5 42 0]args=1
bug: playload len 14
2019/10/14 16:07:42 client.go:419: INFO : chan payload: [16 206 217 144 237 5 24 206 217 144 237 5 42 0 18 6 16 206 217 144 237 5]args=2
bug: playload len 22
bug: payload proto: wrong wireType = 2 for field ReqTime
--- PASS: TestSS (0.04s)

**Comment by smallnest** [comment]
fixed, 你拉取一下代码试试

**Comment by zhaoqb** [comment]
> fixed, 你拉取一下代码试试

好，谢谢大神

**Comment by JungleYe** [comment]
留记号：看来平常应该关注这里的bug fix；
