### ISSUE TITLE
求助！以HTTP方式公布Gateway会挂死？

### ISSUE THREAD

**Issue by jiangrzh** [smallnest/rpcx#373]
我们把一组服务通过rpcx-gateway方式公布出来，但发现压测会挂死
![image](https://user-images.githubusercontent.com/3725828/67172237-1cf30c80-f3ed-11e9-9b73-82611e425c27.png)

请求帮忙分析原因，目测只要通过http方式调用XClient或XClientPool就会这样。
但是绕过gateway，直接http压测服务，则没这个问题

**Comment by smallnest** [comment]
所以瓶颈在gateway上。 看看gateway的日志。

1. 单个请求发送的gateway上有没有问题
2. -n 1 压测 gateway有没有问题
3. 出问题的日志
4. 出问题时的gateway的pprof

通过多种方式检查gateway，看看瓶颈点在哪里

**Comment by jiangrzh** [comment]
看起来是gateway没有办法处理并发请求,并发数大于1就会重现

**Comment by jiangrzh** [comment]
gateway中定义了一个全局的xclient连接池，看起来是goroutine 之间争用连接池发生死锁了

**Comment by smallnest** [comment]
需要提供详细信息分析。

gateway中获取xclient是有锁保护的：

```go
	var xc client.XClient
	g.mu.Lock()
	xc, err = getXClient(g, servicePath)
	g.mu.Unlock()

```

**Comment by jiangrzh** [comment]
我们在原生的rpcx-gateway上测试也是这种状况：
同样发送8个请求，1个客户端并发的时候没有任何问题：
![image](https://user-images.githubusercontent.com/3725828/67182541-0f9c4900-f412-11e9-8511-e2d9c0eb7c76.png)

2个客户端并发的时候就不行了：
![image](https://user-images.githubusercontent.com/3725828/67182752-69047800-f412-11e9-9b27-963c29c4d164.png)

**Comment by jiangrzh** [comment]
刚给rpcx-gateway加了竞争检测，输出了如下日志，看起来是ConsulDiscovery产生的死锁？
![image](https://user-images.githubusercontent.com/3725828/67183091-3444f080-f413-11e9-80c9-b0b780966527.png)

**Comment by smallnest** [comment]
我更新了rpcx避免data race, 但是我的你的问题不是这个导致的。你查看pprof的各个goroutine的状态，看看两个并发情况下goroutine block在哪一行了

**Comment by jiangrzh** [comment]
更新了rpcx重新编译了gateway，然后crash了,报Locker未初始化

**Comment by smallnest** [comment]
我建议你加入 ![](https://github.com/smallnest/rpcx/blob/master/_documents/rpcx_dev_qq2.png) 讨论更快更方便

**Comment by jiangrzh** [comment]
how?

**Comment by smallnest** [comment]
更新一下rpcx避免刚才的Locker未初始化错误。

回到最初问题，并发访问的情况下为什么有“挂死”的情况。

原因可能并发访问的情况下goroutine设置了相同的`gateway.XMessageID`，导致重复ID的请求无法返回结果。

你可以尝试每个goroutine使用不同的MessageID, 或者使用全局的ID调用

**Comment by jiangrzh** [comment]
```
				for j := 0; j < m; j++ {
					t := time.Now().UnixNano()

					data := []byte(rpcxArgs)
					uri := fmt.Sprintf("http://%s", serverAddr)

					req, err := http.NewRequest("POST", uri, bytes.NewReader(data))
					if err != nil {
						log.Println("failed to create request: ", err)
						atomic.AddUint64(&trans, 1)
						wg.Done()
						continue
					}

					h := req.Header
					h.Set(gateway.XMessageID, strconv.Itoa(j))
```
盗用了您在rpcx-benchmark的代码，MessageID是个变量

**Comment by smallnest** [comment]
现在的gateway不再使用客户端传入的MessageID, 你设不设置MessageID都能通过。更新gateway试试

**Comment by jiangrzh** [comment]
测试通过，感谢！
