### ISSUE TITLE
xxx_discovery.go 的watch方法可能会产生CPU 100%问题

### ISSUE THREAD

**Issue by jkingben** [smallnest/rpcx#374]
在关闭其他服务模块情况下，watch方法一直打印 chan is closed and will rewatch，for循环没有阻断，执行太快了。一台机器跑多个服务时，可能会造成100%CPU，卡死。今天正好卡死了一次

**Comment by smallnest** [comment]
首先注册中心是基础服务，不应该宕机。
其次，如果不幸宕机了，client会半分钟尝试连一次，所以压力不应该很大
see https://github.com/smallnest/rpcx/blob/master/client/etcd_discovery.go#L154

所以你需要检查程序中哪里占cpu高

**Comment by jkingben** [comment]
我用的是etcd，不是etcd关闭，是NewXXXDiscovery依赖的服务模块关闭，会造成watch一直空转，见图，箭头处条件并不成立，所以在服务模块启动前，最外面的for会一直循环。
![image](https://user-images.githubusercontent.com/5220242/67954249-92e84680-fc2b-11e9-85b4-fb8ad8a07284.png)

**Comment by smallnest** [comment]
能否描述一下你的测试流程。

1. 开始调用时是否正常？是一开始调用的服务就不存在，还是运行了一段时间后服务端宕机产生的？
2. 客户端的配置？ 使用一个XClient还是池？
3. WatchTree使用的`d.basePath`是？

**Comment by smallnest** [comment]
你可以更新一下 rpcx以及库 https://github.com/smallnest/libkv-etcdv3-store

我怀疑是一开始没有在etcd创建一个服务节点，导致libkv-etcdv3-store初始返回一个空的数据导致

**Comment by jkingben** [comment]
服务一切正常。包也是最新

我用的etcdv3 创建服务A（EtcdV3RegisterPlugin）和 发现服务B（NewEtcdV3Discovery）。

B在启动后会调用A的方法，都没问题。这时把A关闭，打印一条：client.go:682: ERROR: rpcx: client protocol error:read tcp 192.168.28.81:5930->192.168.28.81:60000: wsarecv: An existing connection was forcibly closed by the remote host.   这条打印也没问题

大概再过个10 - 20秒样子开始进入空循环状态：chan is closed and will rewatch

很容易重现

**Comment by jkingben** [comment]
发现服务B用的是池：client.NewXClientPool(1, http.RpcRegName_CacheDataService, client.Failover, client.RoundRobin, nodes, client.DefaultOption)

**Comment by smallnest** [comment]
更新了一下rpcx以及它的依赖库  https://github.com/smallnest/libkv-etcdv3-store ,测试正常，你可以拉取最新的代码试试。

server.go:

```go server.go
package main

import (
	"flag"
	"log"
	"time"

	example "github.com/rpcx-ecosystem/rpcx-examples3"
	"github.com/smallnest/rpcx/server"
	"github.com/smallnest/rpcx/serverplugin"
)

var (
	addr     = flag.String("addr", "localhost:8972", "server address")
	etcdAddr = flag.String("etcdAddr", "localhost:2379", "etcd address")
	basePath = flag.String("base", "/rpcx_test_374", "prefix path")
)

func main() {
	flag.Parse()

	s := server.NewServer()
	addRegistryPlugin(s)

	s.RegisterName("Arith", new(example.Arith), "")
	err := s.Serve("tcp", *addr)
	if err != nil {
		panic(err)
	}
}

func addRegistryPlugin(s *server.Server) {

	r := &serverplugin.EtcdV3RegisterPlugin{
		ServiceAddress: "tcp@" + *addr,
		EtcdServers:    []string{*etcdAddr},
		BasePath:       *basePath,
		UpdateInterval: 10 * time.Second,
	}
	err := r.Start()
	if err != nil {
		log.Fatal(err)
	}
	s.Plugins.Add(r)
}
```

client.go
```go client.go
package main

import (
	"context"
	"flag"
	"log"
	"time"

	example "github.com/rpcx-ecosystem/rpcx-examples3"
	"github.com/smallnest/rpcx/client"
)

var (
	etcdAddr = flag.String("etcdAddr", "localhost:2379", "etcd address")
	basePath = flag.String("base", "/rpcx_test_374", "prefix path")
)

func main() {
	flag.Parse()

	d := client.NewEtcdV3Discovery(*basePath, "Arith", []string{*etcdAddr}, nil)

	pool := client.NewXClientPool(1, "Arith", client.Failover, client.RoundRobin, d, client.DefaultOption)
	defer pool.Close()

	args := &example.Args{
		A: 10,
		B: 20,
	}

	for {
		reply := &example.Reply{}
		err := pool.Get().Call(context.Background(), "Mul", args, reply)
		if err != nil {
			log.Printf("failed to call: %v\n", err)
			time.Sleep(5 * time.Second)
			continue
		}

		log.Printf("%d * %d = %d", args.A, args.B, reply.C)

		time.Sleep(30 * time.Second)
	}

}
```

**Comment by jkingben** [comment]
经测试，已经正常。感谢

**Comment by chiuan** [comment]
😵我今天刚换v3也遇到了。。。搞了一天。。还好上来看了一眼
