### ISSUE TITLE
Disable INFO Log

### ISSUE THREAD

**Issue by arigon** [smallnest/rpcx#375]
Hello

how can I disable this INFO log?

2019/11/01 15:17:06 server.go:358: INFO : client has closed this connection: 10.0.16.25:42698
2019/11/01 15:17:11 server.go:358: INFO : client has closed this connection: 10.0.16.25:42738
2019/11/01 15:17:16 server.go:358: INFO : client has closed this connection: 10.0.16.25:42770

Is there a way to handle the other Log-Messages?

**Comment by smallnest** [comment]
rpcx use rpcx/log/defaultLogger to output logs. You can your customized logger to replace the default logger.

https://github.com/smallnest/rpcx/blob/master/log/logger.go#L38
