### ISSUE TITLE
document unavailable

### ISSUE THREAD

**Issue by Zhwt** [smallnest/rpcx#376]
文档打不开了, 这俩网址访问都报 404 错误
Official site: http://en.doc.rpcx.io/
Gitbook: https://doc.rpcx.site/

**Comment by smallnest** [comment]
我这里都都可以访问，你可以清理清理缓存试试。

英文文档: https://en.doc.rpcx.io
中文文档：https://doc.rpcs.io 或者 https://cn.doc.rpcs.io

**Comment by Zhwt** [comment]
真是挺奇怪的事情, 直连可以打开, 走代理反而打不开, 而且除了报 404之外, 还会提示证书错误, 而且证书是颁发给 github.com 的, 已经清理了缓存包括 dns 缓存

**Comment by smallnest** [comment]
应该是我dns设置的问题

**Comment by Veitor** [comment]
果然，开了翻墙软件就访问不了中文文档。。关了就正常了

**Comment by smallnest** [comment]
中文文档直接访问 https://cn.doc.rpcx.io
