### ISSUE TITLE
How to restart rpcx gracefully？

### ISSUE THREAD

**Issue by tomener** [smallnest/rpcx#377]
服务端有更新，怎样不停服务重启

**Comment by chiuan** [comment]
不停服务重启？ 那怎么能保证你正确热更？

**Comment by tomener** [comment]
> 不停服务重启？ 那怎么能保证你正确热更？

你的意思是停服重启，等待客户端失败重试？

**Comment by smallnest** [comment]
不要期望热更新。

正确的做法是先将这个节点下线(从注册中心中注销)，然后再上线（重新注册）

**Comment by tomener** [comment]
> 不要期望热更新，（热更新过于复杂而且容易出错）
> 
> 正确的做法是先将这个节点下线(从注册中心中注销)，然后再上线（重新注册）

好的
