### ISSUE TITLE
实现ClientConnected(conn net.Conn) (net.Conn, error) 接口里面调用client的call会卡主

### ISSUE THREAD

**Issue by chiuan** [smallnest/rpcx#380]
我是监听服务有就发送一个心跳消息，然后ClientConnected(conn net.Conn) (net.Conn, error)了，我会执行一个连接成功的回调，然后在这个回调里面又给这个client执行一个call。然后就卡住了。

**Comment by smallnest** [comment]
这个插件里调用会有死锁。已修复，你可以拉取新代码试试

**Comment by smallnest** [comment]
另外一个解决方案就是 在插件里使用另外的XClient实例，不要共用外部的XClient实例

**Comment by chiuan** [comment]
> 另外一个解决方案就是 在插件里使用另外的XClient实例，不要共用外部的XClient实例

因为我游戏集群。。是同一个xclient发送的。这里的回调方法是给业务模块逻辑监听，可能会在连接上时候判断服务名称然后同时发送一些消息。。都是一个接口。如果区分的话有点绕了。

**Comment by smallnest** [comment]
现在在`ClientConnected`中你使用相同的XClient调用也应该没问题了，我测试通过。
