### ISSUE TITLE
go.sum mismatch

### ISSUE THREAD

**Issue by Lonenso** [smallnest/rpcx#384]
想测试rpcx代码, vendor后发现这样

go版本
go 1.13.1 /windows

![image](https://user-images.githubusercontent.com/22173979/68928212-8126a780-07c4-11ea-9d9d-2adad2107561.png)

![image](https://user-images.githubusercontent.com/22173979/68928402-f2665a80-07c4-11ea-8259-287e87636976.png)

**Comment by smallnest** [comment]
https://github.com/golang/go/issues/29278

历史bug导致本地缓存的thrift sum cache总是用错误的sum来下载。

`go clean -modcache` 后重新生成 go.sum.

生成了正确的sum.
