### ISSUE TITLE
support rust

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#389]
support to write rpcx services and clients in rust： https://github.com/smallnest/rpcx-rs

**Comment by davidxiaozhi** [comment]
@smallnest  如果在支持 C++ 那就更完美了

**Comment by davidxiaozhi** [comment]
c++ 在深度学习在线推理领域非常火,但是和其他生态结合跨语言的微服务就比较弱了

**Comment by smallnest** [comment]
非常欢迎公司和个人提供c/c++/python/c#的实现，或者是客户端的实现。我可以提供技术相关的支持

**Comment by xusworld** [comment]
> c++ 在深度学习在线推理领域非常火,但是和其他生态结合跨语言的微服务就比较弱了
rpcx-cpp , 我跟着
