### ISSUE TITLE
能否将 makeConnMap 公开

### ISSUE THREAD

**Issue by liuxingbaoyu** [smallnest/rpcx#392]
你好
我想实现双向调用，一方是外网，一方不是

内网为服务端，外网为客户端时
首先内网端建立一条连接，发送确认信息
然后外网端收到信息后，借助 makeConnMap 将连接返回给 rpcx
现在 makeConnMap 没有公开，能否将其公开，谢谢

**Comment by smallnest** [comment]
exported as ConnFactories
