### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by liuxingbaoyu** [smallnest/rpcx#393]
1.[这里](https://github.com/smallnest/rpcx/blob/3a499652de566b89db3a963dbd64e7c675f50954/server/server.go#L250-L260) 如果插件返回了包装过的 conn 会出现问题

2.当 reply 传入 nil 时，为 Oneway 模式
方法返回的错误以及更上层错误 例如 (WARN : rpcx: failed to handle request: rpcx: can't find service)
都不会回传，属于预期结果吗

**Comment by smallnest** [comment]
1. 是个bug
2. 是预期的结果， Oneway意味着不管成功失败client都不理

**Comment by smallnest** [comment]
1. 是个bug. fixed
