### ISSUE TITLE
Users can customize the failure of calls

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#396]
Users can customize processing the call of clients, for example, if clients fail to call a service, users can mark the node as temporary offline. Clients won't select this node in ashort time.

It looks like circuit breaker but clients can invoke the broken nodes in circuit breaker, just only return errors immediately. But this plugin marks the node offline and the node won't be selected.

**Comment by juzidong** [comment]
Wow, I'm looking forward to it！

**Comment by smallnest** [comment]
you can use client `DoWrapSelect` plugin to interrupt the Select method, for example, you can skip a node and reselect
