### ISSUE TITLE
使用consul 1.3以下版本时，引发consul服务发现频繁触发update，阻塞channel，`chan is full and new change has been dropped`, 服务发现更新失效

### ISSUE THREAD

**Issue by juzidong** [smallnest/rpcx#398]
consul 1.2、1.3版本每次心跳都会变更ModifyIndex，rpcx依据ModifyIndex变化判断是否需要更新，若集群机器较多，则频繁触发update，
// WatchService returns a nil chan.
func (d *ConsulDiscovery) WatchService() chan []*KVPair {
	d.mu.Lock()
	defer d.mu.Unlock()

	ch := make(chan []*KVPair, 10)
	d.chans = append(d.chans, ch)
	return ch
}
由于这里限制channel长度为10，很容易堆积满，造成后续变更丢弃：chan is full and new change has been dropped

测试consul 1.6心跳时不会更新ModifyIndex，未复现上述问题

**Comment by smallnest** [comment]
rpcx 使用 https://github.com/docker/libkv 作为consul的访问库。如果确实如你所说，那么就是libkv的确不能以这种访问consul 1.2、1.3的版本。 rpcx不会单独支持consul 1.2/1.3, 而是会使用libkv。

可以考虑给libkv 提个issue, 不过貌似libkv 不再维护了。
