### ISSUE TITLE
[BUG]使用redis作为注册中心 启动gateway注册的时候报错

### ISSUE THREAD

**Issue by pengshaomin** [smallnest/rpcx#405]
`
// NewRedisDiscoveryTemplate returns a new RedisDiscovery template.
func NewRedisDiscoveryTemplate(basePath string, etcdAddr []string, options *store.Config) ServiceDiscovery {
	if len(basePath) > 1 && strings.HasSuffix(basePath, "/") {
		basePath = basePath[:len(basePath)-1]
	}

	kv, err := valkeyrie.NewStore(store.ETCD, etcdAddr, options)
	if err != nil {
		log.Infof("cannot create store: %v", err)
		panic(err)
	}

	return &RedisDiscovery{basePath: basePath, kv: kv}
}`
此处是否设置错误 应该是store.REDIS

**Comment by pengshaomin** [comment]
提交到rpcxgateway

**Comment by smallnest** [comment]
fixed
