### ISSUE TITLE
Getway error duration Server Shutdown or Close

### ISSUE THREAD

**Issue by Pangbit** [smallnest/rpcx#407]
非常感谢开源这么好的项目，我是Go新手，刚开始使用rpcx，发现有些问题，如果提的不对，请多多包涵

我在执行rpcx.Server的Shutdown或Close时总是会记录并返回一个错误，在`gateway.go`如下位置

```go
func (s *Server) startHTTP1APIGateway(ln net.Listener) {
	...
	if err := s.gatewayHTTPServer.Serve(ln); err != nil {
		log.Errorf("error in gateway Serve: %s", err)
	}
}
```

官方htt包中注释说明，Serve方法总是会返回错误，且http.Server被Shutdwon或Close时，返回ErrServerClosed，原文如下
```go
// Serve always returns a non-nil error and closes l.
// After Shutdown or Close, the returned error is ErrServerClosed.
func (srv *Server) Serve(l net.Listener) error {
...
```

建议增加错误类型判断，不是ErrServerClosed才做错误处理
另外Go13增强了errors包，增加了fmt.Errorf("%w", err)的类型包装，和Is、As等错误类型判断方法，可否考虑采用？

**Comment by smallnest** [comment]
加上了判断ErrServerClosed。

目前不会`fmt.Errorf("%w", err)`，因为没有特别的需要。一旦使用也必须要求rpcx使用者的版本在1.13以上，要求太严格
