### ISSUE TITLE
close rpcx client cause crash

### ISSUE THREAD

**Issue by juexun** [smallnest/rpcx#41]
I create a rpcx client to send rpc to remote server with Call API, and close it with defer. If the remote server is not running, the rpc call failed. But the whole program crashed with "Handler crashed with error runtime error: invalid memory address or nil pointer dereference".

It is clearly that the crash is caused by the Close API. Because it didn't crash if I removed the Close API.

How can i fix it?
Thanks

**Comment by smallnest** [comment]
It is a bug and I have fixed it.
You can `go get -u github.com/smallnest/rpcx/...` to retest.
Thanks for committing this issue.

**Comment by juexun** [comment]
Thanks very much
