### ISSUE TITLE
与server不通后，每次Call都会引起Connect

### ISSUE THREAD

**Issue by yongjianchn** [smallnest/rpcx#411]
现象：跟server断开后，若干协程都在不断调用Call()，每次Call()都会尝试Connect。
期望：一般来说，第一次Call()发现client被shutdown之后，应该尝试Connect()并将client置为pending状态，直到Connect()成功或者超时后将状态再改为正常或shutdown。这样pending期间的所有Call()都不需要尝试Connect()。

不知道关于这块，您怎么看？

**Comment by smallnest** [comment]
这是一个值得优化的点。

目前client依赖注册中心来标记server是否不可用，如果注册中心中server被标记为不可用，那么调用Call的时候不会选择这个 server， 也就不会尝试Connect了。

你的这个问题估计你没有使用注册中心导致，下一步可以优化。

**Comment by yongjianchn** [comment]
明白，多谢。

**Comment by smallnest** [comment]
fixed
