### ISSUE TITLE
Server Shutdown or Close的报错

### ISSUE THREAD

**Issue by 15951836388** [smallnest/rpcx#414]
func main() {

	s := server.NewServer()
	r := client.InprocessClient
	s.Plugins.Add(r)

	s.RegisterName("Arith", new(example.Arith), "")

	go func() {
		s.Serve("tcp", "localhost:8972")
	}()
	time.Sleep(time.Second * 2)
	s.Close()

	for {
		select {}
	}
}
基本照着范例来的，报下面的错误
2020/02/14 12:34:12 gateway.go:78: ERROR: error in gateway Serve: mux: listener closed
另外请问 Shutdown 和 Close 分别什么情况用？

**Comment by smallnest** [comment]
`Close`是立即关闭服务，即使还有请求每处理完。
`Shutdown`是尝试处理完已接收的请求再关闭服务。

这个error是误报，应该是info信息。最新的rpcx已经修复。
