### ISSUE TITLE
add rpc request replay

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#417]
增加流量回放功能，把请求复制一份给流量回放系统，方便采集线上请求

**Comment by chiuan** [comment]
what's the time release V6.0

**Comment by smallnest** [comment]
in the end of this year but I think this feature will be add in some weeks.

**Comment by chiuan** [comment]
> in the end of this year but I think this feature will be add in some weeks.

cool support. always Star!

**Comment by yuanjize** [comment]
这个思路是什么，我有时间的话可以周末搞

**Comment by smallnest** [comment]
增加了TeePlugin插件，后续在例子项目中增加一个流量复制的例子

**Comment by smallnest** [comment]
例子: https://github.com/rpcxio/rpcx-examples/tree/master/tcpcopy
