### ISSUE TITLE
失败 go get -u -v -tags "reuseport quic kcp zookeeper etcd consul ping" github.com/smallnest/rpcx/...

### ISSUE THREAD

**Issue by dengzhaofun** [smallnest/rpcx#419]
https://github.com/etcd-io/etcd/issues/11563 应该跟这个问题有关,尽快解决下呗,不然无法使用.

# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
github.com/coreos/etcd/clientv3/balancer/picker
# github.com/coreos/etcd/clientv3/balancer/picker
../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
# github.com/lucas-clemente/quic-go/internal/handshake
../../pkg/mod/github.com/lucas-clemente/quic-go@v0.14.4/internal/handshake/crypto_setup.go:435:40: not enough arguments in call to h.conn.GetSessionTicket
        have ()
        want ([]byte)

**Comment by smallnest** [comment]
使用go module下载，否则依赖的库在更新中难免有冲突。

**Comment by smallnest** [comment]
removed etcd, grpc-go dependencies in go.mod

**Comment by smallnest** [comment]
另外我认为这是etcd的一个问题，需要etcd在它的go.mod修复它的依赖。 etcd已经不止一次的出现grpc的问题了

**Comment by smallnest** [comment]
解决了etcd和grpc的冲突，quic-conn和quic-go的冲突， go get -v github.com/smallnest/rpcx/... 应该没问题了
