### ISSUE TITLE
请问如何获取客户端的IP地址及端口？

### ISSUE THREAD

**Issue by phproot** [smallnest/rpcx#42]
有没有获取当前客户端IP及端口的方法呢？
找了半天还是没有发现相应的函数。

**Comment by smallnest** [comment]
refer to: https://github.com/golang/go/issues/4584

目前service没有办法获取客户端和端口，可以参照Golang的bug，而且看起来Go team不准备增加这个功能。

rpcx提供一个IPostConnAcceptPlugin接口，但是它只能处理链接的建立，比如实现rate-limiting,还不能为每个服务增加获取context/conn的功能。

我会持续调研，找到一个比较好解决的办法处理这个问题。

**Comment by smallnest** [comment]
implemented this feature to bypass golang #4584.

Your Args type should satisfy ArgsContext to get/set net.Conn.
```go
type ArgsContext interface {
	Conn() net.Conn
	SetConn(conn net.Conn)
}
```


There is a example to get remote ip address (client ip):
```go
package main

import (
	"fmt"
	"net"

	"github.com/smallnest/rpcx"
)

type Args struct {
	A    int `msg:"a"`
	B    int `msg:"b"`
	conn net.Conn
}

type Reply struct {
	C int `msg:"c"`
}

func (a *Args) Conn() net.Conn {
	return a.conn
}

func (a *Args) SetConn(c net.Conn) {
	a.conn = c
}

type Arith int

func (t *Arith) Mul(args *Args, reply *Reply) error {
	reply.C = args.A * args.B
	fmt.Printf("Client IP: %s \n", args.Conn().RemoteAddr().String())
	return nil
}

func main() {
	server := rpcx.NewServer()
	server.RegisterName("Arith", new(Arith))
	server.Serve("tcp", "127.0.0.1:8972")
}
```

**Comment by phproot** [comment]
非常感谢！

**Comment by smallnest** [comment]
https://github.com/smallnest/rpcx/tree/master/_examples/context
