### ISSUE TITLE
ETCDV3插件在某种场景下的问题

### ISSUE THREAD

**Issue by yeaze** [smallnest/rpcx#420]
问题描述：当etcd集群宕机或者当前因为网络故障暂时无法连接到etcd注册中心，待一段时间故障恢复之后，微服务无法自动注册回etcd，查看日志发现etcd返回报错：requested lease not found.

看了etcdv3插件的源码,了解了整个运行过程和报错原因大致如下：
`r := &serverplugin.EtcdRegisterPlugin{
        ServiceAddress: "tcp@" + *addr,
        EtcdServers:    []string{*etcdAddr},
        BasePath:       *basePath,
        Metrics:        metrics.NewRegistry(),
        UpdateInterval: time.Minute,
    }
    err := r.Start()
    if err != nil {
        log.Fatal(err)
    }
    s.Plugins.Add(r)`

1、当运行到r.Start()的时候，会去实例化一个etcdv3的客户端，同时预先申请一个租约为30s的leaseID，然后开启一个协程，调用KeepAlive方法使得租约一直不会过期。

2、接着开启一个定时器，定时器的时间间隔就是UpdateInterval所设定的值，每隔UpdateInterval这个时间间隔，程序会去etcd获取指定的key，如果key不存在，那就会重新将这个key设置回etcd。

3、现在假设网络故障，或者etcd集群宕机，只要故障时间超过30s（30s是第一步中预先申请的leaseID的有效期），然后因为故障的原因，KeepAlive方法就无法保持leaseID永不失效，30s之后leaseID过期失效。

4、现在etcd集群故障恢复，或者网络故障恢复。当定时器再次触发，尝试去etcd获取指定的key，发现不存在，于是重新写入指定的key到etcd，此时就会出现报错：requested lease not found.
出现这个问题是因为程序一开始申请的leaseID已经过期了，在etcd中就不存在了，但是微服务程序中依然还在使用这个leaseID，所以此处报错了。 那就意味着现在就算etcd集群或者网络故障恢复了，微服务也没法自动注册会etcd了，必须手动重启下微服务才能注册成功。当我有很多微服务的情况下，我就必须挨个挨个的去重启这些微服务。

当然，etcd集群作为基础设施理应不会轻易宕机的，但是短暂的网络故障还是有可能的，所以这里是否能优化下，感谢！

**Comment by smallnest** [comment]
可以在6.0中加强一下，如果发现注册中心没有了对应的信息，就重新注册一下， 其它注册中心zookeeper,consul应该也有同样的问题

**Comment by smallnest** [comment]
fixed
