### ISSUE TITLE
运行 demo 客户端出现 resolver.BuildOption

### ISSUE THREAD

**Issue by idcpj** [smallnest/rpcx#424]
```
addr := "127.0.0.1:8972"
	d := client.NewPeer2PeerDiscovery("tcp@"+addr, "")
	// #2
	xclient := client.NewXClient("Arith", client.Failtry, client.RandomSelect, d, client.DefaultOption)
	defer xclient.Close()

	// #3
	args := &Args{
		A: 10,
		B: 20,
	}

	// #4
	reply := &Reply{}

	// #5
	err := xclient.Call(context.Background(), "Mul", args, reply)
	if err != nil {
		log.Fatalf("failed to call: %v", err)
	}

	log.Printf("%d * %d = %d", args.A, args.B, reply.C)
```
```
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
D:\go\api\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
D:\go\api\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
D:\go\api\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
D:\go\api\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
```

**Comment by smallnest** [comment]
这是etcd的一个bug, 但是我不知道为什么这个bug一直没有改。

看那个issue相关的讨论，看看别人的一些临时解决办法

![image](https://user-images.githubusercontent.com/865763/75663902-927cbc80-5cac-11ea-8947-b094ec1d645f.png)

**Comment by smallnest** [comment]
修改你的测试程序的go.mod, etcd和grpc使用以下版本，应该临时解决问题，否则需要等待etcd修复这个bug。 建议到etcd这个issue中讨论。

```
module mymod

go 1.13

require (
	github.com/coreos/etcd v3.3.18+incompatible
	github.com/coreos/go-systemd v0.0.0-00010101000000-000000000000 // indirect
	github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f // indirect
	github.com/gogo/protobuf v1.3.1 // indirect
	github.com/google/uuid v1.1.1 // indirect
	go.uber.org/zap v1.13.0 // indirect
	google.golang.org/grpc v1.26.0
)

replace github.com/coreos/go-systemd => github.com/coreos/go-systemd/v22 v22.0.0
```

**Comment by smallnest** [comment]
go get google.golang.org/grpc@v1.26.0

**Comment by wolking** [comment]
> 假定你启用了Go Module
> 
> ```
> go get google.golang.org/grpc@v1.26.0
> ```
> 
> 然后
> 
> ```
> module mymod
> 
> go 1.13
> 
> require (
> 	github.com/coreos/etcd v3.3.18+incompatible
> 	google.golang.org/grpc v1.26.0
> )
> ```

你这方法不靠谱啊，改为google.golang.org/grpc v1.26.0后，serverplugin.ConsulRegisterPlugin就不可用了，例子全按照官方来的：
https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/registry/consul

**Comment by smallnest** [comment]
修复了etcd和grpc的冲突, quic-conn和quic-go的冲突。 可以go get -v github.com/smallnest/rpcx/...试试

**Comment by daleyshek** [comment]
同样错误，wsl go 1.14/win go 1.13都是同样的错误，指定最新的 122cece1047a 这个也不行。只能强制replace。
`require （
google.golang.org/grpc v1.27.0
)`
`replace google.golang.org/grpc v1.27.0 => google.golang.org/grpc v1.26.0`

**Comment by smallnest** [comment]
因为etcd module有问题，`etcd v3.3.18+incompatible`和`google.golang.org/grpc v1.27.0`有冲突，所以rpcx go.mod把grpc已经修改了为了`v1.26.0`， 所以你`go get -v github.com/smallnest/rpcx`应该没问题，travis-ci测试`go 1.13.*` 和`go tip`编译通过。

如果你的go.mod中有grpc v1.17.0, 所以也得需要手工降级为`v1.26.0`,除非等待etcd修复这个bug

**Comment by todother** [comment]
我已经把电脑上已经下载过的grpc删了，然后go mod里面也改成了1.26.0  但是1秒左右吧，goland就自动跳回1.27.0了。。。这怎么破。。还请指教。。
