### ISSUE TITLE
ConsulRegisterPlugin如何配置datacenter与token

### ISSUE THREAD

**Issue by wolking** [smallnest/rpcx#428]
如果consul开启了acl，datacenter也不是默认的dc1，要如何配置这个插件？

**Comment by smallnest** [comment]
贵司实际使用了consul的acl和datacenter?

consul推荐的使用方式是本机部署consul的agent, 然后本机服务访问这个agent。rpcx使用libkv,没有额外配置acl和数据中心的方法

**Comment by wolking** [comment]
> 贵司实际使用了consul的acl和datacenter?
> 
> consul推荐的使用方式是本机部署consul的agent, 然后本机服务访问这个agent。rpcx使用libkv,没有额外配置acl和数据中心的方法

我是按consul官方推荐k8s安装方式进行安装，https://www.consul.io/docs/platform/k8s/run.html
默认开启acl

**Comment by wolking** [comment]
未来会支持吗？

**Comment by smallnest** [comment]
因为你本机已经安装了一个consul agent,可以不通过acl访问。 非本地ip访问才会启用acl吧？




rpcx依赖libkv,但是目前看来libkv不会支持这种方式
