### ISSUE TITLE
Upgrading rpcx to v5

### ISSUE THREAD

**Issue by Chillance** [smallnest/rpcx#429]
Hey!

So, I'm trying to upgrade rpcx I'm using but I get this issue:
go get -v github.com/smallnest/rpcx/...
go: finding module for package github.com/tatsushid/go-fastping
go: found github.com/tatsushid/go-fastping in github.com/tatsushid/go-fastping v0.0.0-20160109021039-d7bb493dee3e
go: github.com/smallnest/rpcx upgrade => v0.0.0-20200305032620-0a8dc95b9e1c
go get: github.com/smallnest/rpcx@v0.0.0-20200305032620-0a8dc95b9e1c requires
        github.com/tjfoc/gmsm@v1.3.0: reading http://127.0.0.1:3456/github.com/tjfoc/gmsm/@v/v1.3.0.mod: 500 Internal Server Error

The 127.0.0.1 is because I'm running athens-proxy, but shouldn't matter I think. Something is off with getting the gmsm library it seems...

Thoughts?

Edit: Aha:
ERROR[12:17AM]: exit status 1: go: finding github.com/tjfoc/gmsm v1.3.0
verifying github.com/tjfoc/gmsm@v1.3.0: checksum mismatch
    downloaded: h1:qhgkrZru95jFP9NbVPknJvc9vgkMXhOEzkOASKdc0oQ= 
    sum.golang.org: h1:i7c6Za/IlgBvnGxYpfD7L3TGuaS+v6oGcgq+J9/ecEA=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.

Thanks!

**Comment by smallnest** [comment]
what's your go version. Go 1.11 calculated checksum is different with checksum by higher go version

**Comment by smallnest** [comment]
tagged v5.1.0 with github.com/tjfoc/gmsm@v1.3.0:i7c6Za/IlgBvnGxYpfD7L3TGuaS+v6oGcgq+J9/ecEA=

**Comment by Chillance** [comment]
go version go1.14 linux/amd64

**Comment by Chillance** [comment]
go get -v github.com/smallnest/rpcx/...@0a8dc95b9e1cf3521f2ee02eea9a93906257d480
go: finding module for package github.com/tatsushid/go-fastping
go: found github.com/tatsushid/go-fastping in github.com/tatsushid/go-fastping v0.0.0-20160109021039-d7bb493dee3e
go: github.com/smallnest/rpcx 0a8dc95b9e1cf3521f2ee02eea9a93906257d480 => v0.0.0-20200305032620-0a8dc95b9e1c
go get: github.com/smallnest/rpcx@v0.0.0-20200305032620-0a8dc95b9e1c requires
        github.com/tjfoc/gmsm@v1.3.0: reading http://127.0.0.1:3456/github.com/tjfoc/gmsm/@v/v1.3.0.mod: 500 Internal Server Error

**Comment by smallnest** [comment]
try `go get -v github.com/tjfoc/gmsm@v1.3.0`. I have test on my pc servers and have no error

**Comment by Chillance** [comment]
go get -v github.com/tjfoc/gmsm@v1.3.0
go get github.com/tjfoc/gmsm@v1.3.0: github.com/tjfoc/gmsm@v1.3.0: reading http://127.0.0.1:3456/github.com/tjfoc/gmsm/@v/v1.3.0.info: 500 Internal Server Error

**Comment by smallnest** [comment]
I think it is the problem of your proxy.

Actually, the lib exists: https://github.com/tjfoc/gmsm/tree/v1.3.0.

and go.dev can find it:
https://pkg.go.dev/mod/github.com/tjfoc/gmsm@v1.3.0

**Comment by Chillance** [comment]
Changed proxy and I get:
main.go:16:2: module github.com/smallnest/rpcx@latest found (v0.0.0-20200305032620-0a8dc95b9e1c), but does not contain package github.com/smallnest/rpcx

**Comment by Chillance** [comment]
It's only this module that doesnt work for some reason. Everything else seems to work fine. I don't get it.
