### ISSUE TITLE
connection pool support

### ISSUE THREAD

**Issue by UlricQin** [smallnest/rpcx#43]

**Comment by smallnest** [comment]
see https://github.com/smallnest/rpcx/blob/master/_examples/cache/client.go

**Comment by frankyzhu** [comment]
使用 sync.Pool 实现连接池是否妥当 ？每次 GC 前 Pool 里面的对象都会被清掉，这个代价太大了。

**Comment by smallnest** [comment]
有道理，我会修改一下这个例子

**Comment by smallnest** [comment]
我修改了这个对象池的例子，使用一个链表来实现对象池。

**Comment by frankyzhu** [comment]
例子里面还有 2 个小问题：

Get 操作这里，极端情况下，池子总是空的，就会不断 New 出新的对象。虽然最终池子不会溢出，但是实际创建的对象数已经大于 max 限制。

```go
        if p.size < 1 {
		return p.New()
	}
```

Put 操作这里，判断条件应该是 `p.size >= p.max`

```go
       if p.size > p.max {
		c.Close()
		return
	}
```

另外，如果要实现稍微实用一点的对象池，Get 超时和对象有效性判断等特性应该也需要加上。
不过这个可能不是 rpcx 的重点。

**Comment by smallnest** [comment]
Agree. 这个例子作为一个概念性的演示。连接池建议自己取实现或者采用成熟的对象池。
