### ISSUE TITLE
go get error. go1.13.8.  daw.amd64 

### ISSUE THREAD

**Issue by ruiboma** [smallnest/rpcx#430]
go: github.com/smallnest/rpcx@v0.0.0-20200305032620-0a8dc95b9e1c requires
	github.com/anacrolix/envpprof@v1.0.1: gzip: invalid header

**Comment by smallnest** [comment]
手工`go get -v github.com/anacrolix/envpprof@v1.0.1`分析一下。一般是防火墙等问题
