### ISSUE TITLE
go get etcdv3 报错

### ISSUE THREAD

**Issue by bojiuyunkai** [smallnest/rpcx#432]
初次go get -u -v github.com/smallnest/rpcx/...  报版本不兼容 
错误如下：
../../../go/pkg/mod/go.etcd.io/etcd@v3.3.18+incompatible/clientv3/client.go:30:2: module github.com/coreos/etcd@latest found (v3.3.18+incompatible), but does not contain package github.com/coreos/etcd/clientv3/balancer/resolver/endpoint

**Comment by smallnest** [comment]
etcd的bug https://github.com/etcd-io/etcd/issues/11563

一旦你使用`-u`, 会把etcd和grpc更新到`etcd v3.3.18+incompatible`和`grpc v1.27.0`。
这两个库有冲突，等待etcd fix 这个bug。

临时解决方案是:
1. 去掉`-u`, 拉取rpcx不会有冲突，因为rpcx go.mod 通过trick fix这个问题
2. 或者像rpcx一样，把grpc版本降级到`v1.26.0`

具体讨论可以到etcd issues中讨论

**Comment by smallnest** [comment]
手工更新一下etcd, 大机率是本地缓存等问题。 

因为rpcx这个go.mod在travis-ci环境中测试编译通过。

或者手工`go get -v go.etcd.io/etcd@v3.3.18`试试

**Comment by smallnest** [comment]
另外看看和这个issue是否有关系 https://github.com/smallnest/rpcx/issues/419

**Comment by bojiuyunkai** [comment]
试了下mac和linux centos都报错，删除mod缓存，重新下载，还是报错，怀疑rpcx go.mod文件引用etcdv3 v3.3.18 有问题。
