### ISSUE TITLE
安装完启动客户端报错，并没有用etcd注册

### ISSUE THREAD

**Issue by Angel-fund** [smallnest/rpcx#433]
/var/www/godev/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
/var/www/godev/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
/var/www/godev/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
/var/www/godev/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption

**Comment by kxy000** [comment]
嗯 按作者之前的解决办法 也没解决好，不知道为啥

**Comment by Angel-fund** [comment]
已解决
etcd依赖grpc v1.26.0，安装的时候默认安装了最新的grpc v1.27.0 了,替换成 v1.26.0就好了

go.mod 添加

replace google.golang.org/grpc => google.golang.org/grpc v1.26.0

**Comment by Ouyangan** [comment]
最新代码还是 v1.29.0 ,需要手动更新一下
