### ISSUE TITLE
xclient.call阻塞问题。interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by AirYang** [smallnest/rpcx#434]
xclient使用redis或者consul作为注册中心。
在注册中心中没有一个服务注册时，xclient.call会返回can not found any server。这是正常的。
但是这时候启动一个server加入到注册中心中。
再次调用xclient.call。xclient.call会返回interface conversion: interface {} is nil, not string。
然后第三次调用xclient.call。那xclient.call就会一直阻塞，不再返回结果。

**Comment by smallnest** [comment]
看看服务预先注册的时候，访问是否正常？

**Comment by AirYang** [comment]
访问正常，感觉这是RPCX client的BUG，似乎不支持注册中心动态的服务增加。

**Comment by smallnest** [comment]
动态服务的增加肯定是支持的

**Comment by AirYang** [comment]
那是否测试过，注册服务数量从0到1的过程。这个过程的BUG？

**Comment by smallnest** [comment]
see https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/registry/redis_lazyregister

**Comment by AirYang** [comment]
感觉这个问题，跟我部署到docker容器里面有关系。我用上面的代码就没有这个问题。

**Comment by AirYang** [comment]
是否有docker配置的案例参考？

**Comment by smallnest** [comment]
https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/docker
