### ISSUE TITLE
最新版编译etcd会出错

### ISSUE THREAD

**Issue by chennqqi** [smallnest/rpcx#435]
\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
是引用的etcd版本的问题吗

**Comment by solarhell** [comment]
锁一下grpc版本 1.26.0
可以看看最近的issue

**Comment by chennqqi** [comment]
老哥，问题在

https://github.com/smallnest/rpcx/blob/122cece1047a45d78df92d1d339b8ffca3ea32d3/go.mod#L8

这个地方引用的
```
github.com/smallnest/rpcx@v0.0.0-20200310110228-122cece1047a google.golang.org/genproto@v0.0.0-20200228133532-8c2c7df3a383
```
而
google.golang.org/genproto@v0.0.0-20200228133532-8c2c7df3a383 应用了grpc@v1.2.7
所以在我的项目的go.mod里是锁不住的。

go mod会使用整个系统中最小包的版本。1.2.7
我感觉你得改一下那一行

**Comment by chennqqi** [comment]
可以用go mod graph 把依赖关系打出来看看

**Comment by smallnest** [comment]
拉取最新的rpcx试试，更改了rpcx go.mod避免直接依赖etcd. 将etcd的问题放在libkv中解决

**Comment by chennqqi** [comment]
已经可以了

**Comment by pengshaomin** [comment]
github.com/smallnest/rpcx v0.0.0-20200322104434-654544af007f
最新版本还是这个问题
