### ISSUE TITLE
rpcx.Client.Call出现panic错误

### ISSUE THREAD

**Issue by AirYang** [smallnest/rpcx#436]
![image](https://user-images.githubusercontent.com/18303087/77246482-a475cd80-6c62-11ea-8c4e-d038aeebb9cd.png)
使用redis注册中心。
redis注册中心中包含一个已经注册的服务。
然后出现了这个问题。

**Comment by AirYang** [comment]
似乎是在一致性Hash路由方法出现的问题，

**Comment by AirYang** [comment]
替换成RandomSelect，就没有这个问题了。

**Comment by AirYang** [comment]
问题出现在
![image](https://user-images.githubusercontent.com/18303087/77246925-dbe67900-6c66-11ea-9cc1-48bd1267bee5.png)

**Comment by AirYang** [comment]
应该增加是nil值条件下的判断，不能直接转换成string

**Comment by smallnest** [comment]
fixed. thanks
