### ISSUE TITLE
RegisterOnShutdown 是什么情况下触发？

### ISSUE THREAD

**Issue by pengshaomin** [smallnest/rpcx#438]
注册了这个函数，发现程序退出也不会自动调用，临时使用了signal.Notify解决UnregisterAll问题

**Comment by smallnest** [comment]
![image](https://user-images.githubusercontent.com/865763/77390060-c2147580-6dcf-11ea-8942-444a0c352152.png)

https://github.com/smallnest/rpcx/blob/9063e1f0bdc38f40f8a949d98f92bd564c08c686/server/server.go#L175
