### ISSUE TITLE
go module tag version should be v0 or v1 , not v5

### ISSUE THREAD

**Issue by z9905080** [smallnest/rpcx#439]
I use go mod in my project,  but your tag version is v5
that's is a problem in my project to decide this framework version.

**Comment by smallnest** [comment]
why not > 1?

see https://github.com/golang/go/wiki/Modules

**Comment by smallnest** [comment]
sorry about it. Now I created v5.3.0 and it you can use ‘ import "github.com/smallnest/rpcx/v5" now

**Comment by z9905080** [comment]
thanks, I use it and run well now
