### ISSUE TITLE
json Decode int64会丢失

### ISSUE THREAD

**Issue by tangquan261** [smallnest/rpcx#444]
json编码器在解码的时候int64会出现丢失现象，Decode
codec := share.Codecs[req.SerializeType()]
if codec == nil {
		return nil
}
codec.Decode(data, &replyData)
codec.go 53行对json的解析
// Decode decodes an object from slice of bytes.
func (c JSONCodec) Decode(data []byte, i interface{}) error {
	return json.Unmarshal(data, i)
}

建议能改成userNumber的实现方式
var replyData = common.Reply{}
	d := json.NewDecoder(bytes.NewBuffer(reply.Payload))
	d.UseNumber()
	d.Decode(&replyData)

**Comment by smallnest** [comment]
added
