### ISSUE TITLE
cannot use "github.com/smallnest/rpcx/v5/protocol".SerializeType as type "github.com/smallnest/rpcx/protocol".SerializeType in assignment

### ISSUE THREAD

**Issue by xuyang3232** [smallnest/rpcx#445]
问题描述如下：
使用版本v.5.3.0，在go_mod中require path为
require github.com/smallnest/rpcx/v5 v5.3.0
程序调用的时候，import "github.com/smallnest/rpcx/v5/protocol"
在下面语句中：
option := client.DefaultOption
option.SerializeType = protocol.SerializeType(protocol.ProtoBuffer)
编译报错：
cannot use "github.com/smallnest/rpcx/v5/protocol".SerializeType("github.com/smallnest/rpcx/v5/protocol".ProtoBuffer) (type "github.com/smallnest/rpcx/v5/protocol".SerializeType) as type "github.com/smallnest/rpcx/protocol".SerializeType in assignment
从报错上看option.SerializeType定义是"github.com/smallnest/rpcx/v5/protocol".SerializeType，但是protocol.SerializeType却是"github.com/smallnest/rpcx/protocol".SerializeType，所以不匹配，那应该怎么调用才能成功呢？谢谢

**Comment by smallnest** [comment]
这确实是个问题。一旦使用了`v5`, rpcx代码中中就不得不所有的引用都得带`v5`。

go module这个设计很蛋疼，这让不使用go module的用户没有办法使用5.x的版本。

我去修改一下代码，重新打一个5.x的版本。 还是重申一下， go module的这个设计非常的蛋疼

**Comment by smallnest** [comment]
使用`require github.com/smallnest/rpcx/v5 v5.6.0`解决这个问题

**Comment by xuyang3232** [comment]
谢谢，已解决
