### ISSUE TITLE
Refactoring client plugin API 

### ISSUE THREAD

**Issue by Codebreaker101** [smallnest/rpcx#448]
I've been going trough `Client` and `XClient` interfaces and I think there are room to improve readability and extensibility. 

Currently, we have `Client` that has basic methods for sending and receiving messages. Then we have `XClient` that implements all of the plugins, discovery and more. There is no middle ground. What I would suggest can be put in a single sentence. Move some or all of the XClient features to client plugins, make plugins optional by wrapping client interface with desired methods and implementations.

That way users can _create his own XClient_ based on their need and it would keep the custom `XCLient` interface clean. 

Here's a `FileTransfer` client plugin with `SendFile` method as an example

``` go
package clientplugin

import (
	"context"
	"fmt"
	"io"
	"net"
	"os"
	"time"

	"github.com/juju/ratelimit"
	"github.com/smallnest/rpcx/client"
	"github.com/smallnest/rpcx/serverplugin"
)

const (
	fileTransferBufferSize = 1024
)

type FileTransfer interface {
	client.RPCClient

	SendFile(ctx context.Context, fileName string, rateInBytesPerSecond int64) error
}

type fileTransfer struct {
	*client.Client
}

func NewFileTransferPlugin(rpcxClient *client.Client) FileTransfer {
	ft := &fileTransfer{
		Client: rpcxClient,
	}
	if rpcxClient.Plugins == nil {
		rpcxClient.Plugins = client.NewPluginContainer()
	}
	rpcxClient.Plugins.Add(ft)
	return ft
}

func (ft *fileTransfer) SendFile(ctx context.Context, fileName string, rateInBytesPerSecond int64) error {

	file, err := os.Open(fileName)
	if err != nil {
		return err
	}

	fi, err := os.Stat(fileName)
	if err != nil {
		return err
	}

	args := serverplugin.FileTransferArgs{
		FileName: fi.Name(),
		FileSize: fi.Size(),
	}

	reply := &serverplugin.FileTransferReply{}

	err = ft.Call(ctx, serverplugin.SendFileServiceName, "TransferFile", args, reply)
	if err != nil {
		return err
	}

	conn, err := net.DialTimeout("tcp", reply.Addr, (10 * time.Second) /*c.option.ConnectTimeout*/) // alter client to support retrieveing of options
	if err != nil {
		return err
	}

	defer conn.Close()

	_, err = conn.Write(reply.Token)
	if err != nil {
		return err
	}

	var tb *ratelimit.Bucket

	if rateInBytesPerSecond > 0 {
		tb = ratelimit.NewBucketWithRate(float64(rateInBytesPerSecond), rateInBytesPerSecond)
	}

	sendBuffer := make([]byte, fileTransferBufferSize)
loop:
	for {
		select {
		case <-ctx.Done():
		default:
			if tb != nil {
				tb.Wait(fileTransferBufferSize)
			}
			n, err := file.Read(sendBuffer)
			if err != nil {
				if err == io.EOF {
					return nil
				}
				return err
			}
			if n == 0 {
				break loop
			}
			_, err = conn.Write(sendBuffer)
			if err != nil {
				if err == io.EOF {
					return nil
				}
				return err
			}
		}
	}

	return nil
}

```

Example usage 

``` go 
package clientplugin_test

import (
	"context"
	"fmt"
	"io/ioutil"
	"net"
	"testing"
	"time"

	"github.com/smallnest/rpcx/client"
	"github.com/smallnest/rpcx/clientplugin"
	"github.com/smallnest/rpcx/server"
	"github.com/smallnest/rpcx/serverplugin"
)

func TestFileTransfer(t *testing.T) {

	s := server.NewServer()
	p := serverplugin.NewFileTransfer("127.0.0.1:8973", saveFilehandler, nil, 1000)
	serverplugin.RegisterFileTransfer(s, p)

	go func() {
		err := s.Serve("tcp", "127.0.0.1:8972")
		if err != nil {
			panic(err)
		}
	}()

	time.Sleep(time.Second)

	c := client.NewClient(client.DefaultOption)
	c.Connect("tcp", "127.0.0.1:8972")
	defer c.Close()

	fileTransferClient := clientplugin.NewFileTransferPlugin(c)
	defer fileTransferClient.Close()

	if err := fileTransferClient.SendFile(context.Background(), "file.txt", 0); err != nil {
		panic(err)
	}

	time.Sleep(time.Second)
}

func saveFilehandler(conn net.Conn, args *serverplugin.FileTransferArgs) {
	fmt.Printf("received file name: %s, size: %d\n", args.FileName, args.FileSize)
	data, err := ioutil.ReadAll(conn)
	if err != nil {
		fmt.Printf("error read: %v\n", err)
		return
	}
	fmt.Printf("file content: %s\n", data)
}

```

**Comment by smallnest** [comment]
rpcx use `Client` as a core client and a simple rpc client. I hope it can keep the  same simple with rpc client in std lib. Basically I don't recommend use it directly even if you use a server node. If you has the case of using it, I think rpc of std lib and grpc are better than `client`.

`XClient` is a service-governance client and it is used to develop scalable and big system. It is a fat implementation which adds many service-governance logics.

If  you want to extend its functions, you can wrap `XClient` instead of `Client`. `Client` is really really designed to use in rpcx own initially.

So I think you'd better extend `XClient`:

```go
type FileTransfer interface {
	client.XClient

	SendFile(ctx context.Context, fileName string, rateInBytesPerSecond int64) error
}
```

**Comment by Codebreaker101** [comment]
Thank you for the response. 

What I was trying to say was that there is a discrepancy in what is considered a plugin on the server and plugin on the client side.

On the server side not all plugins in the `serverplugin` directory use the plugin API. For example `file_transfer.go`. It is just a regular service, it does not _plugin_ to the rpc request/response cycle and have it's methods called by the server plugin API. On the client side the the FileTransfer handler is integrated into `XClient` and not considered a plugin. 

To conclude, on the server side FileTransfer is a plugin, but on the client side it is not.

**Comment by smallnest** [comment]
refactor it and it becomes the  method of server not a plugin
