### ISSUE TITLE
Bug of tolerance regarding prehandleRequest plugin

### ISSUE THREAD

**Issue by Baby-Anran** [smallnest/rpcx#451]
I may find a bug that RPCX is supposed to process the error created by prehandleRequest plugin - 
 to send error to client directly.

**Comment by smallnest** [comment]
It is design for sending an error to clients  if `PreHandleRequestPlugin ` return an err

**Comment by Baby-Anran** [comment]
It may preHandleRequest method of rate limit plugin which doesn't work in my project.

**Comment by smallnest** [comment]
RateLimitingPlugin limits connection.
ReqRateLimitingPlugin limits rate of requests.
