### ISSUE TITLE
与etcdv3断开连接，进程cpu占用率高

### ISSUE THREAD

**Issue by xuyang3232** [smallnest/rpcx#452]
环境如下：
1.go版本1.14.1
2.xrpc版本：v5.6.0
3.etcd采用单点部署
4.采用etcdv3接口
5.服务器cpu是4核。
问题描述：
如果服务器进程在运行中，关闭etcd注册中心，或者与etcd断开连接。过了10秒左右，提示log如下：
2020/05/13 06:55:09 etcdv3.go:92: INFO : can't get data of node: /room/room/tcp@127.0.0.1:6575, because of Key not found in store
2020/05/13 06:55:09 etcdv3.go:100: ERROR: cannot re-create etcd path /room/room/tcp@127.0.0.1:6575: etcdserver: requested lease not found
然后每10秒打印一次。这时候进程cpu就会涨到17%左右。

用profile工具，打印出cpu消耗前10如下：
Showing nodes accounting for 29480ms, 98.07% of 30060ms total
Dropped 35 nodes (cum <= 150.30ms)
Showing top 10 nodes out of 12
      flat  flat%   sum%        cum   cum%
   11060ms 36.79% 36.79%    28000ms 93.15%  runtime.selectgo
    5660ms 18.83% 55.62%     5660ms 18.83%  runtime.lock
    5390ms 17.93% 73.55%     5400ms 17.96%  runtime.unlock
    1950ms  6.49% 80.04%     7600ms 25.28%  runtime.sellock
    1650ms  5.49% 85.53%     7040ms 23.42%  runtime.selunlock
    1440ms  4.79% 90.32%    29810ms 99.17%  github.com/smallnest/libkv-etcdv3-store.New.func1
     870ms  2.89% 93.21%      870ms  2.89%  runtime.fastrand
     690ms  2.30% 95.51%      690ms  2.30%  runtime.(*waitq).dequeue
     400ms  1.33% 96.84%     1270ms  4.22%  runtime.fastrandn
     370ms  1.23% 98.07%      370ms  1.23%  runtime.duffzero

如果过一会，启动etcd。cpu占用率还是不会降。log也还是继续打印。

**Comment by smallnest** [comment]
fixed. 需要更新`github.com/smallnest/libkv-etcdv3-store`到 `v1.1.3`版本

**Comment by xuyang3232** [comment]
请问我现在rpcx用的是v5.6.0，这个版本默认依赖的github.com/smallnest/libkv-etcdv3-store是v1.1.1版本，我应该怎么把它升到v1.1.3版本？直接修改v5.6.0版本下的go.mod好像不起作用。

**Comment by smallnest** [comment]
升级成 v5.7.1
