### ISSUE TITLE
官方网站反映有点慢https://doc.rpcx.io/，恳求把站点放回国内。。

### ISSUE THREAD

**Issue by 0102redirects** [smallnest/rpcx#454]

**Comment by smallnest** [comment]
放国内就需要备案，太麻烦.

文档项目在 https://github.com/smallnest/go-rpc-programming-guide，可以考虑gitbook自己生成

**Comment by smallnest** [comment]
出于备案的考虑，文档不会移动到国内，除非有好的解决方案
