### ISSUE TITLE
missing pointer check for callFunction

### ISSUE THREAD

**Issue by xhebox** [smallnest/rpcx#455]
I suppose that there should be a similar check for https://github.com/smallnest/rpcx/blob/9e5976a9d1d6f967c1a883805661f388ad854c92/server/server.go#L604
as in https://github.com/smallnest/rpcx/blob/9e5976a9d1d6f967c1a883805661f388ad854c92/server/server.go#L538-L542

**Comment by smallnest** [comment]
fixed. thanks
