### ISSUE TITLE
Can `rpcx` completely replace the `gorilla/rpc`?

### ISSUE THREAD

**Issue by ygj6** [smallnest/rpcx#456]
I have a project that uses `gorilla/rpc`. Now I want to renovate this project. But I found that the `gorilla/rpc` is very inactive. It seems to be abandoned. So I am looking for other rpc to replace it. Has `rpcx` implemented the same functions as `gorilla/rpc`? Can it completely replace the latter?

**Comment by smallnest** [comment]
For service side, it is Yes. Implementation of services are very similar. All of them are from rpc in std lib. That means you can convert your services into rpcx services easily.

![image](https://user-images.githubusercontent.com/865763/82173825-30be0d00-9901-11ea-8763-d98990e15bb2.png)

For client side, it is not NO. rpcx supports tcp, udp(quic,kcp). It is a service governance framework which has huge of features, more like alibaba dubbo.

I support you read readme and docs of rpcx to understand the differences.
