### ISSUE TITLE
rpc客户端 client.NewOneClientPool 运行时偶现错误

### ISSUE THREAD

**Issue by yeaze** [smallnest/rpcx#461]
rpc客户端用的是： client.NewOneClientPool
之前一直正常，今天运行中突然出现一个错误：

> runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:199 (0x443a4b)
/usr/local/go/src/runtime/signal_unix.go:394 (0x443888)
/go/pkg/mod/github.com/smallnest/rpcx@v0.0.0-20200428104205-b633eed00350/client/oneclient_pool.go:65 (0xf18d26)
/go/src/kaihu-micro/gateway/rpc/rpc.go:20 (0xf18d1b)
/go/src/kaihu-micro/gateway/handler/broker/broker.go:204 (0xf21bea)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0xa9734a)
/go/src/kaihu-micro/gateway/middleware/intranet.go:31 (0xfae019)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0xa9734a)
/go/src/kaihu-micro/gateway/middleware/aes.go:40 (0xfad947)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0xa9734a)
/go/src/kaihu-micro/gateway/middleware/cross.go:13 (0xfaddce)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0xa9734a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/recovery.go:83 (0xaaade3)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0xa9734a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/logger.go:241 (0xaa9f10)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0xa9734a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:403 (0xaa1379)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364 (0xaa0a6d)
/usr/local/go/src/net/http/server.go:2802 (0x7cac43)
/usr/local/go/src/net/http/server.go:1890 (0x7c64e4)
/usr/local/go/src/runtime/asm_amd64.s:1357 (0x45c0c0)

之后所有的rpc调用，都报这个错误，根据报错信息，定位到源码：
client/oneclient_pool.go:65

>  func (p *OneClientPool) Get() *OneClient {
	i := atomic.AddUint64(&p.index, 1)
	picked := int(i % p.count)
	return p.oneclients[picked]
}

65行就是 i := atomic.AddUint64(&p.index, 1)，应该是就是这一行报错，不知是什么情况下&p.index这个操作会报错。

**Comment by smallnest** [comment]
看错误日志是`p`为nil

**Comment by smallnest** [comment]
看看你的`/go/src/kaihu-micro/gateway/rpc/rpc.go:20`这一行有没有并发问题。 就是`OneClientPool`还没有正式创建出来就使用了

**Comment by yeaze** [comment]
> 文件：/go/src/kaihu-micro/gateway/rpc/rpc.go

```
package rpc

import (
	"sync"
	"time"

	"github.com/smallnest/rpcx/client"
	"github.com/spf13/viper"

)

var (
	once sync.Once
	pool *client.OneClientPool
)


func RpcClient() *client.OneClient {
	once.Do(connect)
	return pool.Get()
}

func connect() {
	discovery := client.NewEtcdV3DiscoveryTemplate(
		viper.GetString("ETCD.BASEPATH"),
		viper.GetStringSlice("ETCD.CLUSTER"), nil)

	option := client.DefaultOption
	option.GenBreaker = func() client.Breaker {
		return client.NewConsecCircuitBreaker(5, 30*time.Second)
	}
	pool = client.NewOneClientPool(100, client.Failtry, client.RandomSelect, discovery, option)
}
```
第20行是：
`	return pool.Get()`

RpcClient()这个方法是存在并发调用的情况的，但是里面利用了sync.Once 确保执行了一次connect()方法生成一个公共的client.OneClientPool

**Comment by smallnest** [comment]
第20行处的pool是nil,会导致这个错误发生。有其它地方会更改全局变量pool的值？

可以在第20行处加个pool == nil 的判断，检查是不是为nil

**Comment by yeaze** [comment]
pool 变量是这个包里私有的，其他地方无法直接访问这个变量

> /go/src/kaihu-micro/gateway/rpc/rpc.go 

整个文件的代码都在上面回复中都贴出来了，没有其他地方会修改这个变量。

程序重启之后就再也没有复现这个问题。
