### ISSUE TITLE
how can i custom err message?

### ISSUE THREAD

**Issue by peachestao** [smallnest/rpcx#463]
i want to custom a err message from server to client ,now only support default err,how can i custom a err object?such as:err{code:1001,msg:'错误' }

**Comment by smallnest** [comment]
You can return your customized error types in your service impletations.

**Comment by peachestao** [comment]
can you  give an example？ thank you.

**Comment by smallnest** [comment]
type MtErr struct {
 Code int
Msg string
}
.......

func (s ...) Add() error{
return MyError{}
}

**Comment by peachestao** [comment]
@smallnest Thank you for your answer. First, MtErr must implement the interface method "Error() string" to be converted into the error interface that comes with the system. Second, even if the Error() string method is implemented in the MtErr structure, it can return the string of code and msg The form, the client gets only the string form, my current requirement is that the client can get the MtErr error object, you can directly call the Code and Msg fields.

**Comment by smallnest** [comment]
The only way that you parse the error into your myerr

**Comment by peachestao** [comment]
Oh, it seems that this method can only be used
