### ISSUE TITLE
How to call MultipleServersDiscovery.Update

### ISSUE THREAD

**Issue by chenjiandongx** [smallnest/rpcx#464]
Hi, @smallnest 

There is something makes me confused, as you described in the docs

![image](https://user-images.githubusercontent.com/19553554/83946768-693c7100-a845-11ea-9350-28dc69225db8.png)

users can use `MultipleServersDiscovery.Update` to update service dynamically. But the fact is that   `NewMultipleServersDiscovery` returns a ServiceDiscovery Interface and it doesn't have the  `Update` method

```golang
// NewMultipleServersDiscovery returns a new MultipleServersDiscovery.
func NewMultipleServersDiscovery(pairs []*KVPair) ServiceDiscovery {
	return &MultipleServersDiscovery{
		pairs: pairs,
	}
}
```

What's more, all fields in  `MultipleServersDiscovery` are private which means that we cannot create a new MultipleServersDiscovery by ourselves.

```
type MultipleServersDiscovery struct {
	pairs []*KVPair
	chans []chan []*KVPair

	mu sync.Mutex
}
```

Hence I want to know what is the proper solution to this question. :)

**Comment by smallnest** [comment]
You can use `d.(*MultipleServersDiscovery ).Update(...)`

**Comment by chenjiandongx** [comment]
Will It be a better design that returns a MultipleServersDiscovery instance in `NewMultipleServersDiscovery` function?

**Comment by smallnest** [comment]
yes. I will enhance it.
