### ISSUE TITLE
是否有支持sidecar模式的计划？

### ISSUE THREAD

**Issue by lintingzhen** [smallnest/rpcx#466]
目前的框架我理解是Chassis模式，rpcx-gateway也仅支持http协议的client端，是否后续考虑让rpcx-gateway支持完整的sidecar模式？

**Comment by smallnest** [comment]
sidecar?

rpcx是一个富客户端的方式，很多服务治理的特性在client sdk中实现。

`sidecar`模式如istio等是以一种通用框架的方式提供服务治理的功能，rpcx不和他们竞争抢市场。你可以使用rpcx.Client + istio的方式实现微服务，在这种情况下，只利用了rpcx的rpc功能，去掉了rpcx服务治理的功能。

**Comment by lintingzhen** [comment]
谢谢 @smallnest 回复！
不好意思笔误。
我起初想的是将rpcx-gateway改造成类似golang版envoy，然后用rpcx.Client + rpcx-envoy来实现sidecar模式微服务。不过现在看envoy的全量实现挺复杂的，不仅复杂，更是一个方向上的大转变。
也许可以用rpcx.Client跟蚂蚁金服出的golang版envoy SOFAMosn对接。

**Comment by lintingzhen** [comment]
谢谢建议！我再考虑考虑。
