### ISSUE TITLE
WatchService

### ISSUE THREAD

**Issue by SSRITW** [smallnest/rpcx#469]

**Comment by smallnest** [comment]
what?

**Comment by SSRITW** [comment]
手误



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"smallnest"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月23日(星期二) 下午4:12
收件人:&nbsp;"smallnest/rpcx"<rpcx@noreply.github.com&gt;;
抄送:&nbsp;"736550258"<736550258@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [smallnest/rpcx] WatchService (#469)





 
what?
