### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by UlricQin** [smallnest/rpcx#47]
```
➜  clientpool git:(master) go run client.go
# github.com/smallnest/rpcx/clientselector
../../clientselector/ping_utils.go:15: p.Network undefined (type *fastping.Pinger has no field or method Network)
```

**Comment by smallnest** [comment]
please see https://github.com/tatsushid/go-fastping/blob/master/fastping.go#L179,
The method exist in latest fastping.
Do you get latest fastping?

**Comment by smallnest** [comment]
see build status and  it is passing: https://camo.githubusercontent.com/08c66cdf0d7540b468e8985615a48d3d8ad1e81a/68747470733a2f2f7472617669732d63692e6f72672f736d616c6c6e6573742f727063782e7376673f6272616e63683d6d6173746572
