### ISSUE TITLE
rpcx 是否支持类似apollo的配置中心 ？

### ISSUE THREAD

**Issue by koolhazz** [smallnest/rpcx#472]
文档中只看到了服务注册中心的相关描述，针对配置中心相关的内容，并没有看到，希望能说明一下。谢谢。

**Comment by smallnest** [comment]
暂时没有，因为没有强烈的需求。

如果你们公司或者有公司考虑使用rpcx+apollo，我会考虑把它加上。
如果是个人项目，暂时不会加上apollo。

目前rpcx支持zookeeper、etcd、consul、 redis、nacos做配置中心。 可以查看代码例子或者官方文档。

**Comment by koolhazz** [comment]
> 目前rpcx支持zookeeper、etcd、consul、 redis、nacos做配置中心。 可以查看代码例子或者官方文档。

这些只是简单的配置项内容的统一存储吧。还不能覆盖配置中心全部功能吧。

**Comment by smallnest** [comment]
rpcx不是一个配置中心的管理工具，而是借助配置中心实现服务发现的功能

**Comment by koolhazz** [comment]
> rpcx不是一个配置中心的管理工具，而是借助配置中心实现服务发现的功能

这个肯定是，但是作为功能更完善的微服务框架，配置内容的管理是需要提供的，通过支持第三方平台实现也是没有问题的。

**Comment by koolhazz** [comment]
> rpcx不是一个配置中心的管理工具，而是借助配置中心实现服务发现的功能

分布式服务的应用场景下，没有完善的配置中心相关功能，起码在控制层面是有很大的缺陷。
