### ISSUE TITLE
关于对ipv6的支持

### ISSUE THREAD

**Issue by jeffdwy** [smallnest/rpcx#474]
请问rpcx是否能支持ipv6？文档中并没有看到相关的说明。如能支持，该如何进行使用？和ipv4环境下的使用是否一致？

**Comment by smallnest** [comment]
没测试过，但是应该支持。因为使用go的net标准库，并没有特殊设置

**Comment by iHDJ** [comment]
go的net支持ipv6

**Comment by smallnest** [comment]
rpcx支持ipv6,看例子:

https://github.com/rpcxio/rpcx-examples/tree/master/ipv6

https://github.com/rpcxio/rpcx-examples/tree/master/ipv6_etcd/etcdv3
