### ISSUE TITLE
etcdv3 使用rpcx报错

### ISSUE THREAD

**Issue by 582727501** [smallnest/rpcx#476]
https://github.com/rpcxio/rpcx-examples/tree/master/registry/etcdv3

操作这个example报错。
etcd：
etcd Version: 3.4.9
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.14.3
Go OS/Arch: darwin/amd64

报错1:
etcd的报错
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"

client端端报错：
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch

server报错3:
server连上后，重新关闭，再开启
2020/07/14 15:42:56 etcdv3.go:66: ERROR: cannot create etcd path /rpcx_test: rpc error: code = Canceled desc = grpc: the client connection is closing
2020/07/14 15:42:56 rpc error: code = Canceled desc = grpc: the client connection is closing
exit status 1

怎么弄，大佬

**Comment by smallnest** [comment]
看看你是否使用最新的`github.com/smallnest/libkv-etcdv3-store`库

![image](https://user-images.githubusercontent.com/865763/87399676-45a9da80-c5ea-11ea-89fd-0ed924a1e8e7.png)

**Comment by 582727501** [comment]
是最新的
![image](https://user-images.githubusercontent.com/34395003/87416178-e73c2680-c600-11ea-8bb2-0f46c627376d.png)


这个是我的mod
module rpcx_v2

go 1.13

require (
	github.com/rpcxio/rpcx-examples v0.0.0-20200713101111-e96cba32d5e8
	github.com/smallnest/rpcx v0.0.0-20200713120749-7bdbc88d036b
)

**Comment by 582727501** [comment]
client代码：
package main

import (
	"context"
	"flag"
	"log"
	"time"

	example "github.com/rpcxio/rpcx-examples"
	"github.com/smallnest/rpcx/client"
)

var (
	etcdAddr1 = flag.String("etcdAddr", "127.0.0.1:2379", "etcd address")
	basePath1 = flag.String("base", "/rpcx_test1", "prefix path")
)

func main() {
	flag.Parse()

	d := client.NewEtcdV3Discovery(*basePath1, "Arith", []string{*etcdAddr1}, nil)
	xclient := client.NewXClient("Arith", client.Failover, client.RoundRobin, d, client.DefaultOption)
	defer xclient.Close()

	args := &example.Args{
		A: 10,
		B: 20,
	}

	for {
		reply := &example.Reply{}
		err := xclient.Call(context.Background(), "Mul", args, reply)
		if err != nil {
			//log.Printf("failed to call: %v\n", err)
			time.Sleep(5 * time.Second)
			continue
		}

		log.Printf("%d * %d = %d", args.A, args.B, reply.C)

		time.Sleep(10 * time.Second)
	}

}

**Comment by 582727501** [comment]
server代码：
_package main

import (
	"flag"
	"log"
	"net/http"
	_ "net/http/pprof"
	"time"

	example "github.com/rpcxio/rpcx-examples"
	"github.com/smallnest/rpcx/server"
	"github.com/smallnest/rpcx/serverplugin"
)

var (
	addr     = flag.String("addr", "localhost:8974", "server address")
	etcdAddr = flag.String("etcdAddr", "127.0.0.1:2379", "etcd address")
	basePath = flag.String("base", "/rpcx_test1", "prefix path")
)

func main() {
	flag.Parse()

	go http.ListenAndServe(":9984", nil)

	s := server.NewServer()
	s.UnregisterAll()
	addRegistryPlugin(s)

	s.RegisterName("Arith", new(example.Arith), "")
	err := s.Serve("tcp", *addr)
	if err != nil {
		panic(err)
	}
	s.UnregisterAll()
}

func addRegistryPlugin(s *server.Server) {

	r := &serverplugin.EtcdV3RegisterPlugin{
		ServiceAddress: "tcp@" + *addr,
		EtcdServers:    []string{"127.0.0.1:2379"},
		BasePath:       *basePath,
		UpdateInterval: time.Minute,
	}
	err := r.Start()
	if err != nil {
		log.Fatal(err)
	}
	s.Plugins.Add(r)
}
_

**Comment by 582727501** [comment]
mac 环境，安装最新的etcd

**Comment by smallnest** [comment]
这应该是我的锅，一个bug

**Comment by 582727501** [comment]
修好了，麻烦告知一下哈，非常感谢

**Comment by smallnest** [comment]
更新一下rpcx和 https://github.com/smallnest/libkv-etcdv3-store, 应该没问题了

**Comment by 582727501** [comment]
可以了，给力，谢谢
