### ISSUE TITLE
希望增加lua写的client端

### ISSUE THREAD

**Issue by ONG-YA** [smallnest/rpcx#477]
目前openresty api网关还是用的挺多的，希望增加rpcx的lua语言client端

**Comment by supermario1990** [comment]
jsonrpc or http

**Comment by smallnest** [comment]
是的。更合适的是通过http或者jsonrpc2.0方式调用rpcx服务，不需要额外的组件，rpcx默认就支持。

https://github.com/rpcxio/rpcx-examples/tree/master/http_invoke

https://github.com/rpcxio/rpcx-examples/tree/master/jsonrpc2
