### ISSUE TITLE
rpcx/codec/codec.go文件报错

### ISSUE THREAD

**Issue by mosesed** [smallnest/rpcx#478]
rpcx/codec/codec.go

func (c ThriftCodec) Decode(data []byte, i interface{}) error {
	t := thrift.NewTMemoryBufferLen(1024)
	p := thrift.NewTBinaryProtocolFactoryDefault().GetProtocol(t)
	d := &thrift.TDeserializer{
		Transport: t,
		Protocol:  p,
	}
	d.Transport.Close()
	return d.Read(i.(thrift.TStruct), data)
}
作者改一下 ,下面是修正的.

func (c ThriftCodec) Decode(data []byte, i interface{}) error {
	t := thrift.NewTMemoryBufferLen(1024)
	p := thrift.NewTBinaryProtocolFactoryDefault().GetProtocol(t)
	d := &thrift.TDeserializer{
		Transport: t,
		Protocol:  p,
	}
	d.Transport.Close()
	return d.Read(context.Background(),i.(thrift.TStruct), data)
}

**Comment by smallnest** [comment]
follow the  thrift version in go.mod
