### ISSUE TITLE
能不能在服务注册时，增加一个bool字段

### ISSUE THREAD

**Issue by Owen-Zhang** [smallnest/rpcx#481]
出发点大概是这样的

服务注册后，我们自己做的后台port会去查看注册中心(etcd. zookeeper)上的节点数据, 有时会想将某个机器排除在外，不让其它服务调用它，但我们又不能将此节点删除，做一些事情后又要将其恢复正常

我们现在port后台想做一个开关，直接操作etcd.zookeeper,
能不能在rpcx服务调用前，验证一下那个开关，假如是关闭的话就换成另一个服务去调用

不知我说清楚没，希望大哥空了考虑一下

**Comment by smallnest** [comment]
rpcx已支持。看注册的时候加元数据state=inactive,看rpcx_ui的处理。

**Comment by Owen-Zhang** [comment]
好的，谢了
