### ISSUE TITLE
有rpcx服务部署指导文档吗？

### ISSUE THREAD

**Issue by charlesgreat** [smallnest/rpcx#482]
有rpcx服务部署指导吗？ 比如需要部署哪些服务， 各个服务的作用，集中或者分布式部署建议

**Comment by smallnest** [comment]
目前没有部署文档。

如果不熟悉微服务的架构，你可能需要先读一些微服务方面的文章，关于微服务的服务划分、服务的治理、服务监控等等，
如果你已经了解了微服务的架构，下面是一个产品级的服务部署模式之一(非service mesh模式)：

1、注册中心

你公司需要有一个服务发现的平台，以便微服务注册和客户端发现。 开源的cp系统比如etcd、consul等，AP系统比如阿里的nacos,如果公司的服务规模不是很大，可以使用redis。 这不是rpcx框架提供的内容，而是贵公司推广微服务必须的一个平台。


2、开发微服务

贵公司的不同业务组开发自己的微服务，并且打包部署。因为使用Go,所以rpcx的微服务最终只是一个二进制文件。依照你使用的注册的类型，需要在服务端设置相应的注册中心的插件，插件主要是注册中心的访问方式以及服务暴露给客户端的IP和端口。

你可以生成一个二进制的文件进行部署，也可以docker化。

3、客户端访问

依照你使用的注册中心的类型，你需要在客户端配置相应注册中心的插件，通过注册中心发现服务端进行调用。

服务端和客户端的代码可以看例子。同时rpcx提供了一堆的服务治理的功能和插件，可以针对自己的微服务的场景选择使用，比如限流、比如容错等。

**Comment by charlesgreat** [comment]
明白了，多谢指导。




在 2020-08-07 14:34:21，"smallnest" <notifications@github.com> 写道：

目前没有部署文档。

如果不熟悉微服务的架构，你可能需要先读一些微服务方面的文章，关于微服务的服务划分、服务的治理、服务监控等等，
如果你已经了解了微服务的架构，下面是一个产品级的服务部署模式之一(非service mesh模式)：

1、注册中心

你公司需要有一个服务发现的平台，以便微服务注册和客户端发现。 开源的cp系统比如etcd、consul等，AP系统比如阿里的nacos,如果公司的服务规模不是很大，可以使用redis。 这不是rpcx框架提供的内容，而是贵公司推广微服务必须的一个平台。

2、开发微服务

贵公司的不同业务组开发自己的微服务，并且打包部署。因为使用Go,所以rpcx的微服务最终只是一个二进制文件。依照你使用的注册的类型，需要在服务端设置相应的注册中心的插件，插件主要是注册中心的访问方式以及服务暴露给客户端的IP和端口。

你可以生成一个二进制的文件进行部署，也可以docker化。

3、客户端访问

依照你使用的注册中心的类型，你需要在客户端配置相应注册中心的插件，通过注册中心发现服务端进行调用。

服务端和客户端的代码可以看例子。同时rpcx提供了一堆的服务治理的功能和插件，可以针对自己的微服务的场景选择使用，比如限流、比如容错等。
