### ISSUE TITLE
example: 101basic-client.go编译报错

### ISSUE THREAD

**Issue by xddai1201** [smallnest/rpcx#484]
go build -v client.go
...
go: downloading gopkg.in/ini.v1 v1.42.0
github.com/coreos/etcd/clientv3
go.etcd.io/etcd/clientv3
# go.etcd.io/etcd/clientv3
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:54:10: undefined: grpc.Address
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:60:18: undefined: grpc.Address
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:137:54: undefined: grpc.BalancerConfig
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:208:41: undefined: grpc.Address
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:383:34: undefined: grpc.Address
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:434:38: undefined: grpc.Address
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:470:56: undefined: grpc.BalancerGetOptions
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:470:82: undefined: grpc.Address
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:518:44: undefined: grpc.Address
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:577:22: undefined: grpc.Address
E:\gospace\pkg\mod\go.etcd.io\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:577:22: too many errors
# github.com/coreos/etcd/clientv3
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:54:10: undefined: grpc.Address
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:60:18: undefined: grpc.Address
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:137:54: undefined: grpc.BalancerConfig
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:208:41: undefined: grpc.Address
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:383:34: undefined: grpc.Address
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:434:38: undefined: grpc.Address
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:470:56: undefined: grpc.BalancerGetOptions
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:470:82: undefined: grpc.Address
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:518:44: undefined: grpc.Address
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:577:22: undefined: grpc.Address
E:\gospace\pkg\mod\github.com\coreos\etcd@v3.3.13+incompatible\clientv3\health_balancer.go:577:22: too many errors

**Comment by smallnest** [comment]
这基本上是etcd和grpc版本冲突导致。你可以尝试在go.mod加入下面一行尝试修复：

```
replace google.golang.org/grpc => google.golang.org/grpc v1.29.0
```

**Comment by xddai1201** [comment]
> 这基本上是etcd和grpc版本冲突导致。你可以尝试在go.mod加入下面一行尝试修复：
> 
> ```
> replace google.golang.org/grpc => google.golang.org/grpc v1.29.0
> ```

编译通过，谢谢。
