### ISSUE TITLE
 consul does not support multiple endpoints

### ISSUE THREAD

**Issue by wenzj-code** [smallnest/rpcx#485]
hello,

I use consul plugin to register server , when start ,catch error this
**2020/08/19 18:17:50 consul.go:58: ERROR: cannot create consul registry: consul does not support multiple endpoints**

code:
`func main() {
	flag.Parse()
	s := server.NewServer()
	addRegistryPlugin(s)
	service.InitAddr(*addr)
	s.RegisterName(*serverName, new(service.Arith), "")
	s.Serve("tcp", *addr)
}

func addRegistryPlugin(s *server.Server) {
	consulAddr := []string{"192.168.2.142:8101", "192.168.2.142:8102", "192.168.2.142:8103"}
	r := &serverplugin.ConsulRegisterPlugin{
		ServiceAddress: "tcp@" + *addr,
		ConsulServers:  consulAddr,
		BasePath:       *basePath,
		Metrics:        metrics.NewRegistry(),
		UpdateInterval: 10 * time.Second,
	}
	err := r.Start()
	if err != nil {
		log.Fatal(err)
	}
	s.Plugins.Add(r)
}`

Does it not support multiple nodes?

**Comment by smallnest** [comment]
No.  Consul doesn't support multiple nodes officially. They suggest you install consul agent in your server.

Maybe you can consider other registries.
