### ISSUE TITLE
"PreWriteResponse"  plugin suggestion

### ISSUE THREAD

**Issue by miaolz123** [smallnest/rpcx#486]
首先感谢作者贡献了这么优秀的开源框架.

**现在的 `PreWriteResponse` 是这样的:**

``` go
type PreWriteResponsePlugin interface {
	PreWriteResponse(context.Context, *protocol.Message, *protocol.Message) error
}
```

**建议的 `PreWriteResponse` 是这样的:**

``` go
type PreWriteResponsePlugin interface {
	PreWriteResponse(context.Context, *protocol.Message, *protocol.Message, error) error
}
```

**为什么这样建议:**

在我这边的使用场景里使用了自定义的服务端 `error` 返回, 具体说就是用了 `github.com/cockroachdb/errors` 把错误进行了封装. 如果按照现有的 `res.Metadata[protocol.ServiceError] = err.Error()` 方式把错误发送给客户端, 错误信息缺失非常严重, 所以我准备用 `rpcx server plugin` 的方式在 `PreWriteResponse` 阶段把自己的完整错误信息 `Encode` 后放到 `res.Metadata["my_error"]` 里面, 这个时候以我的理解现有的插件是无法实现的.

**其他**

另外, 我注意到大部分接口调用阶段的插件 `interface` 都是返回 `error` 的, 但是在具体的 `./server/server.go` 里面调用这些插件的时候, 几乎都选择把 `error` 忽略掉了, 这样设计是出于怎么的考虑呢?

谢谢~

**Comment by smallnest** [comment]
1. 是好的建议，`PreWriteResponse`这个可以把error穿进去。 唯一带来的麻烦就是打破了api的向下兼容性。
2. 很多插件忽略了error是因为大部分的插件的错误不能影响服务的调用。 比如trace出错就出错，最多是这次没有办法trace,但是不能因为此错误不提供服务了

**Comment by miaolz123** [comment]
多谢, 原来 master 分支就是 v6 developing, 非常惊喜.
