### ISSUE TITLE
newConsistentHashSelector 时没有初始化hash，导致 can not found any server

### ISSUE THREAD

**Issue by dhjack** [smallnest/rpcx#489]
在 newConsistentHashSelector里面 ，h没有赋值。
return &consistentHashSelector{servers: ss, h: doublejump.NewHash()}
导致 在Select里面s.h.Get(key).(string)，无法得到地址。

**Comment by supermario1990** [comment]
没看懂。 new操作是创建一个空的selector, UpdateServer 中不是对h进行了更新？确定不是自己的用法不对？

**Comment by supermario1990** [comment]
> 在 newConsistentHashSelector里面 ，h没有赋值。
> return &consistentHashSelector{servers: ss, h: doublejump.NewHash()}
> 导致 在Select里面s.h.Get(key).(string)，无法得到地址。

`go client.watch(ch)` will invoke `UpdateServer(servers)` method to `s.h.Add(k)`.

**Comment by smallnest** [comment]
在UpdateServer(servers)之前调用的话的确会得到空，原因在于构造器中没有初始化doublejump。

已修复，谢谢
