### ISSUE TITLE
当 server 主动返回 err 时，reply 默认为 nil

### ISSUE THREAD

**Issue by CyJaySong** [smallnest/rpcx#502]
如题，，但实际上，reply 有值，而且需要返回给前端。可以 fix 一下吗

**Comment by Lonenso** [comment]
是不是开了oneway?

**Comment by CyJaySong** [comment]
没开啊，直接调用的，不过是用的作者博客中的 grpc 方式

**Comment by Lonenso** [comment]
能不能提供一下代码?

**Comment by CyJaySong** [comment]
哪一部分？

**Comment by Lonenso** [comment]
给一份能够复现出你描述的问题的， 可运行的代码， 帮助别人定位问题。

**Comment by CyJaySong** [comment]
### example/example.go
package example

import (
	"context"
	"errors"
)

type Args struct {
	A int
	B int
}

type Reply struct {
	C int
}

type Arith int

func (t *Arith) Mul(ctx context.Context, args *Args, reply *Reply) error {
	reply.C = args.A * args.B
	return errors.New("test")
}

#### server
package main

import (
	"CollegeCircleServer/test/example"
	"flag"
	"github.com/smallnest/rpcx/server"
)





func main() {
	flag.Parse()
	addr := flag.String("addr", "localhost:8972", "server address")
	s := server.NewServer()
	s.Register(new(example.Arith), "")
	s.Serve("tcp", *addr)
}


##### client
package main

import (
	"CollegeCircleServer/test/example"
	"context"
	"flag"
	"log"

	"github.com/smallnest/rpcx/client"
)

var (
	addr = flag.String("addr", "localhost:8972", "server address")
)

func main() {
	flag.Parse()

	d := client.NewPeer2PeerDiscovery("tcp@"+*addr, "")
	xclient := client.NewXClient("Arith", client.Failtry, client.RandomSelect, d, client.DefaultOption)
	defer xclient.Close()

	args := &example.Args{
		A: 10,
		B: 20,
	}

	reply := &example.Reply{}
	err := xclient.Call(context.Background(), "Mul", args, reply)
	log.Printf("结果: %d \n", reply.C)
	if err != nil {
		log.Fatalf("failed to call: %v", err)
	}

	log.Printf("%d * %d = %d", args.A, args.B, reply.C)

}


打印结果 为 0

**Comment by smallnest** [comment]
在返回错误的情况下再使用reply,因为它是不确定的状态。

anyway，我还是加强了代码，返回了reply,拉最新的代码。

**Comment by CyJaySong** [comment]
我没仔细看源码，rpcx 有类似于 grpc 那种 Status错误码实现计划吗？之前看了B站的源码，他们很巧妙的实现了业务的错误码和 rpc 的错误码合并。
