### ISSUE TITLE
server 重启导致 client 端 failed to dial server

### ISSUE THREAD

**Issue by CyJaySong** [smallnest/rpcx#504]
为了方便部署和多模块调试，我一般server 随机监听一个端口，由于调试的时候经常重启 server,  每次 server 的端口不一样，重启后 client 未及时获取到最新的 server 信息，导致请求偶尔失败。服务发现用的 etcd。 有什么好的办法吗

**Comment by Lonenso** [comment]
我认为这跟rpcx没关系， 关键在etcd动态修改配置，可以去stackoverflow或者etcd的文档看看。

**Comment by smallnest** [comment]
新服务器启动后再关闭老的服务。 正常的微服务你总要保证7*24小时有服务可以用
