### ISSUE TITLE
有计划支持 消息队列 通信方式么， 类似 github.com/nats-rpc/nrpc。

### ISSUE THREAD

**Issue by runner-mei** [smallnest/rpcx#508]
这种在一些场景有很有效

**Comment by smallnest** [comment]
这个QQ群里大家讨论。后来大家普遍认为消息队列的东西还是直接交给消息队列的SDK去处理, 不但性能好，而且还可以实现流式处理。
我业想不出非要经过rpc包装一下的理由。

**Comment by runner-mei** [comment]
我的业务场景下是需要这个了， 对性能的要求反不高。

业务场景是公网上布一个控制节点， 然后各地安装子节点干活， 这些子节点是没有公网IP的。

**Comment by smallnest** [comment]
我觉得你可以实现一个Message服务。服务端使用nats client读取消息，客户端把topic传过去，这个应该不复杂。

**Comment by runner-mei** [comment]
你的方案可行， 但太麻烦。我希望有工具帮我生成 客户端和服务端代码， 这就是为什么我要用 rpc 的原因。
