### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by biter777** [smallnest/rpcx#509]
After clear istallation (on new system, go 1.15.5/gopath):
go get -v github.com/smallnest/rpcx/...

Got errors:

$ go get -v github.com/smallnest/rpcx/...
github.com/smallnest/rpcx (download)
github.com/smallnest/libkv-etcdv3-store (download)
github.com/smallnest/valkeyrie (download)
github.com/rpcxio/go-redis (download)
get "go.opentelemetry.io/otel/api/global": found meta tag get.metaImport{Prefix:"go.opentelemetry.io/otel", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go"} at //go.opentelemetry.io/otel/api/global?go-get=1
get "go.opentelemetry.io/otel/api/global": verifying non-authoritative meta tag
go.opentelemetry.io/otel (download)
package github.com/smallnest/rpcx/client: cannot find package "go.opentelemetry.io/otel/api/global" in any of:
	/usr/local/go/src/go.opentelemetry.io/otel/api/global (from $GOROOT)
	/home/biter/go/src/go.opentelemetry.io/otel/api/global (from $GOPATH)
get "go.opentelemetry.io/otel/api/metric": found meta tag get.metaImport{Prefix:"go.opentelemetry.io/otel", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go"} at //go.opentelemetry.io/otel/api/metric?go-get=1
get "go.opentelemetry.io/otel/api/metric": verifying non-authoritative meta tag
package github.com/smallnest/rpcx/client: cannot find package "go.opentelemetry.io/otel/api/metric" in any of:
	/usr/local/go/src/go.opentelemetry.io/otel/api/metric (from $GOROOT)
	/home/biter/go/src/go.opentelemetry.io/otel/api/metric (from $GOPATH)
get "go.opentelemetry.io/otel/api/trace": found meta tag get.metaImport{Prefix:"go.opentelemetry.io/otel", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go"} at //go.opentelemetry.io/otel/api/trace?go-get=1
get "go.opentelemetry.io/otel/api/trace": verifying non-authoritative meta tag
package github.com/smallnest/rpcx/client: cannot find package "go.opentelemetry.io/otel/api/trace" in any of:
	/usr/local/go/src/go.opentelemetry.io/otel/api/trace (from $GOROOT)

**Comment by biter777** [comment]
I edit some files and it works:
1) util.go
		// trace.SpanFromContext(ctx).RecordError(ctx, err)
		trace.SpanFromContext(ctx).RecordError(err)
2) instruments.go
		// 	meter := metric.Must(metric.Meter("github.com/rpcxio/go-redis"))
		meter := metric.Must(otel.Meter("github.com/rpcxio/go-redis"))

And some others...

**Comment by smallnest** [comment]
use go module

**Comment by smallnest** [comment]
https://pkg.go.dev/go.opentelemetry.io/otel/api

**Comment by biter777** [comment]
> use go module

It fails with etcd

**Comment by Lonenso** [comment]
> > use go module
> 
> It fails with etcd

known issue, see notice in readme, replace etcd version in go.mod

**Comment by smallnest** [comment]
更新了github.com/smallnest/valkeyrie， 使用官方的go-redis.只要go-redis库没有问题，就可以正常下载。
我可以正常下载
