### ISSUE TITLE
move some plugins into independent project

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#517]
make rpcx core slim

**Comment by smallnest** [comment]
also modify examples and documents

**Comment by lesismal** [comment]
我把 [arpc](https://github.com/lesismal/arpc) 的一些扩展放到 [extension](https://github.com/lesismal/arpc/tree/master/extension) 子包了、主要作为示例的方式，如果只使用arpc的默认选项，则只依赖 arpc 和标准库。其他依赖比如使用 kcp、quic、protobuf 、json-iter、服务发现 之类的都取决于应用层

**Comment by smallnest** [comment]
第一阶段： 移出etcd插件到 https://github.com/rpcxio/rpcx-etcd
