### ISSUE TITLE
有个问题想请教哈

### ISSUE THREAD

**Issue by 1046102779** [smallnest/rpcx#52]
如果采用轮询、最小调用次数统计等策略，以达到负载均衡的目的。那是不是已建立好的rpc客户端与rpc服务端连接，都需要断开老连接、建立新连接？

**Comment by smallnest** [comment]
事实上已建好rpc客户端都会保留着以提高性能

**Comment by smallnest** [comment]
一个rpc的客户端可能保持着多个连接

**Comment by 1046102779** [comment]
如果有N个实例，当有N-1个实例down掉后，所有连接都会采用策略连接到第N个rpc server上，当N-1个实例恢复后，那连在第N个上的rpc clients，策略可以把这些客户端均衡到恢复后的rpc server上吗？

**Comment by smallnest** [comment]
会恢复。

**Comment by harlanc** [comment]
客户端保持rpc链接中间会发心跳么？保持多个rpc链接不会消耗服务器资源么？比如有100个server 节点做负载均衡，100万个客户端，那得建立1亿个rpc链接，其中只有100万个连接是活跃的，这么理解有问题么？

**Comment by smallnest** [comment]
客户端和服务端可以发心跳，也可以不发，默认不发。

保持连接会消耗资源。一亿个链接会耗很大的资源，但是这个数字是无意义的。 实际没有微服务节点会保持100万个连接。一般现实中只有手机和消息推送、IOT客户端和服务器、聊天室等才可能有很多的连接，但是每个服务节点10万连接也就足够了，原因在于单个服务节点受限于磁盘、cpu、带宽等限制。

总的一句话，你需要拿一个合理的场景和容量去评估。

**Comment by harlanc** [comment]
非常感谢，就是有10万连接，理论上来讲有大部分连接只是用来做备用连接随时待命，比如：10万客户端，100个server节点做负载均衡，平均下来一个server只有1000一个有效连接，剩下的9900个连接就只做负载，用户体验是好了，但是还是感觉太浪费服务器资源了。
