### ISSUE TITLE
RegisterFunction/RegisterFunctionName Not work

### ISSUE THREAD

**Issue by finishy1995** [smallnest/rpcx#521]
RegisterFunction/RegisterFunctionName Not work when server using InprocessClient Plugin

All code copied from https://doc.rpcx.io/part1/function.html

**Comment by smallnest** [comment]
InprocessClient 会被移除掉。这不是一个很好的插件，因为它根本没走网络传输。

**Comment by finishy1995** [comment]
谢谢，我在开发模式改用了 p2p

**Comment by smallnest** [comment]
removed InprocessClient
