### ISSUE TITLE
如何实现跨平台文件传输

### ISSUE THREAD

**Issue by eddieyyeung** [smallnest/rpcx#527]
请问下用 python 开发的客户端，可以基于 rpcx 实现文件传输吗？

**Comment by smallnest** [comment]
rpcx本身是用来做微服务的，不是专门做文件传输的，不建议使用它做文件传输。

如果你想使用它做文件传输，也仅仅支持go客户端和服务端，部支持其它语言。

https://github.com/rpcxio/rpcx-examples/tree/master/filetransfer

https://github.com/rpcxio/rpcx-examples/tree/master/file_download
