### ISSUE TITLE
协程中调用创建XClient时可能出现data race

### ISSUE THREAD

**Issue by ljyyzss** [smallnest/rpcx#528]
你好，我们在压测过程中发现有可能出现竞争问题，错误如下：
WARNING: DATA RACE
Write at 0x00c0001be170 by goroutine 315:
github.com/smallnest/rpcx/client.(*ConsulDiscovery).watch()
/home/ljy/workspaces/pkg/mod/github.com/smallnest/rpcx@v0.0.0-20200701111749-ed08247be373/client/consul_discovery.go:193 +0x8e4

Previous read at 0x00c0001be170 by goroutine 282:
github.com/smallnest/rpcx/client.(*ConsulDiscovery).GetServices()
/home/ljy/workspaces/pkg/mod/github.com/smallnest/rpcx@v0.0.0-20200701111749-ed08247be373/client/consul_discovery.go:111 +0x3e
github.com/smallnest/rpcx/client.NewXClient()
/home/ljy/workspaces/pkg/mod/github.com/smallnest/rpcx@v0.0.0-20200701111749-ed08247be373/client/xclient.go:116 +0x22c
github.com/smallnest/rpcx/client.(*OneClient).newXClient()
/home/ljy/workspaces/pkg/mod/github.com/smallnest/rpcx@v0.0.0-20200701111749-ed08247be373/client/oneclient.go:144 +0x717
github.com/smallnest/rpcx/client.(*OneClient).SendRaw()
/home/ljy/workspaces/pkg/mod/github.com/smallnest/rpcx@v0.0.0-20200701111749-ed08247be373/client/oneclient.go:204 +0x373
neva3ci.eshore.com/ZJ-CMT-IPOE-AAA/aaa-gateway/app/agent.(*ApiGateway).handleRequest()
/home/ljy/workspaces/src/neva3ci.eshore.com/ZJ-CMT-IPOE-AAA/aaa-gateway-testing/app/agent/gateway.go:211 +0x2da
neva3ci.eshore.com/ZJ-CMT-IPOE-AAA/aaa-gateway/app/agent.(*ApiGateway).React.func1()
/home/ljy/workspaces/src/neva3ci.eshore.com/ZJ-CMT-IPOE-AAA/aaa-gateway-testing/app/agent/gateway.go:124 +0x81a
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
/home/ljy/workspaces/pkg/mod/github.com/panjf2000/ants/v2@v2.4.1/worker.go:68 +0xd9

想问一下有没有解决方案

**Comment by smallnest** [comment]
这个我修改一下，这个和 https://github.com/smallnest/rpcx/issues/494 是同一个问题。 不影响使用，属于"良性race",我使用RWMutex保护一下

**Comment by smallnest** [comment]
fixed
