### ISSUE TITLE
quick start demo Error

### ISSUE THREAD

**Issue by orchie** [smallnest/rpcx#530]
报错如下
```
$ go run main.go 
# go.etcd.io/etcd/clientv3/balancer/picker
D:\gopath\pkg\mod\go.etcd.io\etcd@v0.0.0-20201125193152-8a03d2e9614b\clientv3\balancer\picker\err.go:25:9: cannot use &errPicker literal (type *errPicker) as type Picker in return argument:
        *errPicker does not implement Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)
D:\gopath\pkg\mod\go.etcd.io\etcd@v0.0.0-20201125193152-8a03d2e9614b\clientv3\balancer\picker\roundrobin_balanced.go:33:9: cannot use &rrBalanced literal (type *rrBalanced) as type Picker in return argument:
        *rrBalanced does not implement Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)
```
最初我是比着quick start写 总是报错
后来直接把  rpcx-ecosystem\rpcx-examples3@v1.1.6\102basic 
完整复制运行 ,还是报这个错.
help~~
server没问题 ,就是client编译不过.

**Comment by orchie** [comment]
我在执行 
go get -u 之后 拉下很多库 然后再run是报这些error
```
$ go run main.go 
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
D:\gopath\pkg\mod\github.com\coreos\etcd@v3.3.25+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
D:\gopath\pkg\mod\github.com\coreos\etcd@v3.3.25+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
D:\gopath\pkg\mod\github.com\coreos\etcd@v3.3.25+incompatible\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
D:\gopath\pkg\mod\github.com\coreos\etcd@v3.3.25+incompatible\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
```

**Comment by orchie** [comment]
能看出都是etcd报的错 ,可是demo里用的是 NewPeer2PeerDiscovery
是没用到etcd 的
我在server 下执行过

> 方便起见，我推荐你安装所有的tags，即使你现在并不需要他们：

go get -u -v -tags "reuseport quic kcp zookeeper etcd consul ping" github.com/smallnest/rpcx/...

我想把etcd去掉 该怎么弄呢.

**Comment by AndersonBargas** [comment]
Hello @orchie.
Have you added the replace directive onto your go.mod file?

You have to added the line below:

replace google.golang.org/grpc => google.golang.org/grpc v1.29.0

After that you will be able to compile the program.

Also, i ran go mod vendor on my project. I don´t know if it´s needed.

Best regards.

**Comment by orchie** [comment]
> Hello @orchie.
> Have you added the replace directive onto your go.mod file?
> 
> You have to added the line below:
> 
> replace google.golang.org/grpc => google.golang.org/grpc v1.29.0
> 
> After that you will be able to compile the program.
> 
> Also, i ran go mod vendor on my project. I don´t know if it´s needed.
> 
> Best regards.

Thanks!But I tried thats no birds to use.
I find author and he told me to solved
replace this all to go.sum
```
module rpcx-client

go 1.15

require (
	github.com/rpcx-ecosystem/rpcx-examples3 v1.1.6
	github.com/rpcxio/rpcx-examples v1.1.6
	github.com/smallnest/rpcx v0.0.0-20201211065410-ee13ef5d3696 // indirect
)

replace google.golang.org/grpc => google.golang.org/grpc v1.29.0
```
than it works.(before modify, there are many lines in go.sum)
