### ISSUE TITLE
client.NewEtcdV3Discovery使用问题

### ISSUE THREAD

**Issue by CCYezi** [smallnest/rpcx#531]
问题1、d:=client.NewEtcdV3Discovery 如果没有注册的服务会报错：cannot get services of from registry这样不太友好，希望做个容错处理，可以有err判断
问题2、ss := <-d.WatchService()  获得的chan 和 d.GetServices() 结果一样嘛，无论多久，都获取不到服务关闭，开启的消息， 个人理解，这里应该像clientv3.Client的Watch函数一样才对吧，或者是我哪里搞错了，望作者大大不吝赐教。希望可以提供处理clientv3.EventTypePut和clientv3.EventTypeDelete 这两个消息的接口出来

**Comment by smallnest** [comment]
问题1: 没有服务也不会出错，因为可能服务之后才会注册。这是用户提出的需求
问题2：一样。只不过是通过chan的方式暴露。

暴露其它接口的意义？如果有新的想法或者需要，详细描述一下。

**Comment by CCYezi** [comment]
问题1：d:=NewEtcdDiscovery是没有问题，d:=NewEtcdV3Discovery有问题，我刚才又试了
问题2：这个需求可能是我现在应用场景中的问题，比如我通过client来获取了所有服务节点，然后去链接了所有的服务节点（NewXClient会按select模式去链接d中的服务吧？），如果d的服务节点有新增，我想自动去链接新增节点，如果d的服务节点有掉线，我好通知链接当前应用的所有用户，某服务暂时关闭
