### ISSUE TITLE
github.com/rpcxio/go-redis 与 github.com/go-redis/redis/v8 冲突

### ISSUE THREAD

**Issue by sootma** [smallnest/rpcx#535]
github.com/rpcxio/go-redis 与 github.com/go-redis/redis/v8 都有引用o.opentelemetry.io/otel, 
但版本不同，总是报
go: finding module for package go.opentelemetry.io/otel/api/trace
go: finding module for package go.opentelemetry.io/otel/api/metric
go: finding module for package go.opentelemetry.io/otel/api/global
D:\work_context\go_repo\pkg\mod\github.com\rpcxio\go-redis@v0.8.0\internal\instruments.go:6:2: module go.opentelemetry.io/otel@latest found (v0.15.0), but does not contain package go.opentelemetry.io/otel/api/global
D:\work_context\go_repo\pkg\mod\github.com\rpcxio\go-redis@v0.8.0\internal\instruments.go:7:2: module go.opentelemetry.io/otel@latest found (v0.15.0), but does not contain package go.opentelemetry.io/otel/api/metric
D:\work_context\go_repo\pkg\mod\github.com\rpcxio\go-redis@v0.8.0\internal\util.go:13:2: module go.opentelemetry.io/otel@latest found (v0.15.0), but does not contain package go.opentelemetry.io/otel/api/trace

v8引用的没有/api这个目录。不知大家有没有遇到，都是怎么解决的

**Comment by smallnest** [comment]
新版的rpcx已经不使用rpcxio/go-redis了

**Comment by sootma** [comment]
我是用的 github.com/smallnest/rpcx/v5 v5.7.9， 新版的是未来的v6?

**Comment by smallnest** [comment]
是的，v6将会在一个星期内发布
