### ISSUE TITLE
版本兼容性问题

### ISSUE THREAD

**Issue by firedtoad** [smallnest/rpcx#539]
提交ID 31573493324cefc20b272e156761258f3e2eeb9e
把老版本的 libkv-etcdv3-store 迁移到了rpcxio/rpcx-etcd
新加入的 rpcxio/rpcx-etcd和老版本的 libkv-etcdv3-store 并不兼容
其中 libkv-etcdv3-store 中的List方法在etcdv3.go:336 查找key不存在会返回一个空列表
而新版的 rpcxio/rpcx-etcd中的List方法在etcdv3.go:339 查找key不存在会返回错误
这就导致启动时 rpcx-etcd/client/etcdv3_discovery.go:61 直接panic 
客户端依赖的服务还没启动直接启动客户端会panic这样就会导致服务启动有顺序依赖
希望大佬能考虑一下

**Comment by smallnest** [comment]
fixed, 请使用最新的rpcx-etcd
