### ISSUE TITLE
not enough arguments in call to d.Read

### ISSUE THREAD

**Issue by xiannvdezhu** [smallnest/rpcx#542]
`# github.com/smallnest/rpcx/codec`
`../github.com/smallnest/rpcx/codec/codec.go:133:15: not enough arguments in call to d.Read`
`have (thrift.TStruct, []byte)`
`want (context.Context, thrift.TStruct, []byte)`
`func (c ThriftCodec) Decode(data []byte, i interface{}) error {`
`	t := thrift.NewTMemoryBufferLen(1024)`
`	p := thrift.NewTBinaryProtocolFactoryDefault().GetProtocol(t)`
`	d := &thrift.TDeserializer{`
`		Transport: t,`
`		Protocol:  p,`
`	}`
`	d.Transport.Close()`
`	return d.Read(i.(thrift.TStruct), data) 这里报错`
`}`

**Comment by smallnest** [comment]
使用go module,确保使用正确的thrift版本

**Comment by xiannvdezhu** [comment]
按照教程直接go get的 还要替换一下版本么?

**Comment by smallnest** [comment]
现在gopath要被弃用了，go env看看你的GOMODULE=on吗？不需要额外设置

**Comment by xiannvdezhu** [comment]
我试试 谢谢

**Comment by xiannvdezhu** [comment]
请问我env 开启了 gomodule goland 里gopath 我还需要设置么

**Comment by xiannvdezhu** [comment]
是我开启go module 之后从新go get 么

**Comment by smallnest** [comment]
你看rpcx的集成测试结果就知道库没有问题。
![image](https://user-images.githubusercontent.com/865763/103162974-a2185380-4832-11eb-8cc7-a2aeaf768a7a.png)


确保你的go版本 > 1.15 。GO111MODULE=on, 然后go get -u -v github.com/smallnest/rpcx@master

使用问题请到qq群中询问，会有热心网友及时给出反馈。
