### ISSUE TITLE
rpcx protobuf  bidirectionalXClient

### ISSUE THREAD

**Issue by F88888** [smallnest/rpcx#545]
Environmental Science

    option.SerializeType = protocol.ProtoBuffer
    NewEtcdV3Discovery + NewBidirectionalXClient
    Call(context.Background() 

The following error occurred

2021/01/11 11:20:12 client.go:764: WARN : failed to heartbeat to 192.168.169.137:9461: *int64 is not a proto.Marshaler
2021/01/11 11:20:12 client.go:769: WARN : reply 0 in heartbeat to 192.168.169.137:9461 is different from request 1610335212020624300: %!v(MISSING)

**Comment by smallnest** [comment]
which rpcx version did you use?

This issue has been fixed in current master branch.

**Comment by F88888** [comment]
github.com/smallnest/rpcx v0.0.0-20210107125003-9ec728bdda10
