### ISSUE TITLE
"rpcx: failed to read request"导致双向通讯连接重连

### ISSUE THREAD

**Issue by cairns0214** [smallnest/rpcx#548]
rpcx server 报错日志
![Snipaste_2021-01-27_22-01-57](https://user-images.githubusercontent.com/16733934/106001916-7a473480-60eb-11eb-95e2-506a92f94603.png)
同一时间，客户端与服务端会重连
![Snipaste_2021-01-27_22-02-07](https://user-images.githubusercontent.com/16733934/106001954-83d09c80-60eb-11eb-9849-125adf2e7d92.png)

请问哪些情况会造成rpcx: failed to read request:，是否有避免的方式，当前情况下重连过于频繁，影响使用

**Comment by smallnest** [comment]
是不是你服务端和客户端设置了timeout?重连一般发生在超时，协议解析出错和服务端主动关闭连接的情况

**Comment by smallnest** [comment]
no more info. closed
