### ISSUE TITLE
support kubernetes (k8s)

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#554]
在k8s环境中，rpcx服务端部需要做额外的服务发现配置，部需要设置注册中心。

对于rpcx client，可以通过service (虚拟ip+port)的方式访问rpcx服务，k8s服务服务发现和负载均衡。
但是有用户发现了一些使用的问题，比如
![image](https://user-images.githubusercontent.com/865763/108660890-0f302880-7506-11eb-8b85-ceb143ff3255.png)

如果我们实现自己的K8sDiscovery,不依赖k8s的负载均衡的化，我们可以实现更灵活的负载方式。可以通过k8s client-go获取某个服务的endpoints,实时的watch,以实现服务发现。

https://cloud.tencent.com/developer/news/485720 通过kubectl describe svc xxx也可以获取服务的endpoints:
![image](https://user-images.githubusercontent.com/865763/108661897-f9bbfe00-7507-11eb-9a7b-aa89805c9f5f.png)

**Comment by smallnest** [comment]
获取pod (endpoints)信息
```go
package main

import (
    "flag"
    "fmt"
    "os"
    "path/filepath"
    "time"

    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
    "k8s.io/client-go/kubernetes"
    "k8s.io/client-go/tools/clientcmd"
)

func main() {
    var kubeconfig *string
    if home := homeDir(); home != "" {
        kubeconfig = flag.String("kubeconfig", filepath.Join(home, ".kube", "config"), "(optional) absolute path to the kubeconfig file")
    } else {
        kubeconfig = flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
    }
    flag.Parse()
    // uses the current context in kubeconfig
    config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
    if err != nil {
        panic(err.Error())
    }
    // creates the clientset
    clientset, err := kubernetes.NewForConfig(config)
    if err != nil {
        panic(err.Error())
    }
    for {
        pods, err := clientset.CoreV1().Pods("").List(metav1.ListOptions{})
        if err != nil {
            panic(err.Error())
        }
        fmt.Printf("There are %d pods in the cluster\n", len(pods.Items))
        time.Sleep(10 * time.Second)
    }
}

func homeDir() string {
    if h := os.Getenv("HOME"); h != "" {
        return h
    }
    return os.Getenv("USERPROFILE") // windows
}
```

**Comment by CyJaySong** [comment]
有群？想加进来学习

**Comment by smallnest** [comment]
看readme

**Comment by hunterhug** [comment]
我们生产环境都用了rpcx框架，规模比较大。我们不用k8s的服务发现的功能了，采用rpcx etcd的插件。

我提供一下思路，将pod ip 传进环境变量：

```
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
```

程序里将该ip注册进etcd。

**Comment by smallnest** [comment]
例子：

- 基于环境变量(基于cluster ip)： https://github.com/rpcxio/rpcx-examples/tree/master/k8s
- 基于DNS(clusterIP: None): https://github.com/rpcxio/rpcx-examples/tree/master/k8s_dns
- 第三种: 创建第三方注册中心的集群，把集群的地址通过环境变量传给server和client, 比如创建etcd集群

@hunterhug 
@CyJaySong
