### ISSUE TITLE
使用gzip压缩后在高并发的情况下服务端解析失败导致重连

### ISSUE THREAD

**Issue by cairns0214** [smallnest/rpcx#558]
在设置了option.CompressType = protocol.Gzip选项后
服务端会出现部分数据无法解析的情况，服务端出现以下日志
WARN : rpcx: failed to read request: unexpected EOF
WARN : rpcx: failed to read request: gzip: invalid header
这两种情况都会导致连接需要重新建立

在源码中加了一些日志打印，最终没分析出具体问题所在，帮忙测试排查一下这种情况
另外类似这种几千条数据这中出现一条存在问题的，是否有必要每次都断开连接重新建立？

**Comment by smallnest** [comment]
这是因为客户端主动关闭了链接，为什么这么确定的呢?因为下面的日志出卖了它:
```
WARN : rpcx: failed to read request: unexpected EOF
```

而且是在读取数据的过程中出现，为什么这么肯定呢？因为接下来你又贴了一个日志，说明rpcx server已经读取了这一帧的header,只是在解析payload的时候出错:
```
WARN : rpcx: failed to read request: gzip: invalid header
```

那么问题是，客户端为什么会把connection关闭呢？

1、超时
这个一般不会，除非你设置了timeout,并且传递非常大的payload,导致很长时间读取不到response

2、服务器处理慢，导致客户端context.WithTimeout超时了
这个客户端应该有错误日志


不管怎样，客户端应该会重试再发，不应该对业务又太大影响。这也是微服务架构面临的网络问题。
