### ISSUE TITLE
Xclient *MyService.Request is not a proto.Marshaler

### ISSUE THREAD

**Issue by arigon** [smallnest/rpcx#559]
I updated from v0.0.0-20200729031544-75f1e2894fdb to v0.0.0-20210302003640-3ac62d723635 and I am now getting this error:
*MyService.Request is not a proto.Marshaler

I am creating the XClient and I am using the XClient.Call() function.

**Comment by smallnest** [comment]
if you use protobuf as the encoder/decoder,your request/response must implemented ptoto.marshaler, otherwise you cab use the default encoder (msgpack)

**Comment by arigon** [comment]
I updated protobuf and grpc to the most recent version and now it's working. I am using etcd and your rpcx-etcd is not compatible with newer versions of grpc.
I created a compatible version and uploaded it here: https://github.com/arigon/rpcx-etcd
feel free to update your repo :)

**Comment by smallnest** [comment]
Can you submit a pull request? Thanks

**Comment by arigon** [comment]
Done: https://github.com/rpcxio/rpcx-etcd/pull/7

**Comment by smallnest** [comment]
merged. thanks
