### ISSUE TITLE
运行_examples/zookeeper_registry报error for 127.0.0.1:2181: 7*8, No available service

### ISSUE THREAD

**Issue by Leon2012** [smallnest/rpcx#56]
1，zookeeper已安装
2，已运行server.go,  go run server.go
3，运行client报错

vagrant@vagrant-ubuntu-trusty-64:/go/src/github.com/smallnest/rpcx/_examples/zookeeper_registry$ go run client.go
2016/10/25 17:20:58 Connected to 127.0.0.1:2181
2016/10/25 17:20:58 Authenticated: id=96821782470918149, timeout=40000
error for 127.0.0.1:2181: 7*8, No available service 
error for 127.0.0.1:2181: 7*8, No available service 
error for 127.0.0.1:2181: 7*8, No available service 
error for 127.0.0.1:2181: 7*8, No available service 
error for 127.0.0.1:2181: 7*8, No available service 
error for 127.0.0.1:2181: 7*8, No available service 
error for 127.0.0.1:2181: 7*8, No available service 
error for 127.0.0.1:2181: 7*8, No available service 
error for 127.0.0.1:2181: 7*8, No available service 
error for 127.0.0.1:2181: 7*8, No available service

**Comment by smallnest** [comment]
fixed
