### ISSUE TITLE
心跳包机制小问题，请酌情处理

### ISSUE THREAD

**Issue by DRYGGJS** [smallnest/rpcx#560]
实验代码：https://github.com/rpcxio/rpcx-examples/tree/master/heartbeat
将server端返回心跳response代码注释掉，模拟client未收到心跳返回的场景，发现结果如下：
客户端一直报心跳失败，服务端报客户端socket已关闭，但是客户端与服务端仍然会新建连接继续rpc调用。

个人感觉，当服务端心跳出现问题时，说明服务端出现了问题，客户端应该可以报错提示退出，避免客户端继续新建连接调用服务端。 但是另一方面，可能服务端只是短暂出现问题，可能会自我恢复正常。所以强制客户端报错退出，也不太好。 
如果心跳可以像断路器那样，当持续心跳失败n次，就报错提示客户端退出最好。
另外，服务端好像对心跳没有什么异常处理机制。比如服务端没收到心跳时服务端会如何处理呢？

**Comment by smallnest** [comment]
心跳是和客户端没关系的。

**Comment by smallnest** [comment]
如果heartbeat失败，client会被关闭。
