### ISSUE TITLE
[question]咨询下go-zero和rpcx的区别是什么？

### ISSUE THREAD

**Issue by bingws** [smallnest/rpcx#568]
最近有看鸟窝的《go并发编程实战课》，然后偶然发现[go-zero](https://github.com/tal-tech/go-zero.git)项目，也宣称自己是微服务架构，我想咨询下go-zero和rpcx的区别？如何选择？谢谢。

**Comment by smallnest** [comment]
利益相关者，所以不对其它框架做评价。

对于rpcx,设计哲学就是『简单』，会写hello world的同学就会使用rpcx开发框架。在保持简单的设计哲学下实现了功能丰富，性能强大的特性，并且能被百度、好未来学而思、新浪、马蜂窝等各大公司采用，也足以说明rpcx的过人之处。

我的建议自己做一下框架的调研，写一些简单的例子比较，对性能做些测试，看看哪一款微服务框架更适合你。

**Comment by bingws** [comment]
好的。我都试试。

**Comment by fitlivingmm** [comment]
利益不相关，选择框架的时候go-zero rpcx 都进行了解。
rpcx 性能好是一方面，最重要的是go-zero 使用grpc 新增一个rpc 接口，就需要对proto 文件更新并且rpc client server 服务都需要重启一次，而rpcx 可以不用重启rpc client 服务，只用更新rpc server 方面就可以实现新增一个对外接口功能。由于业务大多使用tcp rpc client 调用方不便多次更新重启。所以采用rpcx，上线半年了，业务很稳定。感谢作者提供这么简洁的rpc 框架。配置真的很简洁。
