### ISSUE TITLE
Plugin 的 PreCall 方法在 HTTP 请求时 context 改为 shared.Context

### ISSUE THREAD

**Issue by whaios** [smallnest/rpcx#569]
在 HTTP 方式请求服务方法时，希望在 Plugin 中处理 Meta 数据并写入到 Context 中。
所以希望 Plugin 的 PreCall 方法中将 context 修改为 shared.Context 。
![QQ图片20210412145054](https://user-images.githubusercontent.com/19703913/114352511-8432ec80-9b9e-11eb-822b-9b3d1ecf8fe6.png)

**Comment by smallnest** [comment]
不清楚你http调用的方式是怎样的。 既然是http调用，那么就是一个http.Client直接访问rpcx service,不会走rpcx client的插件。

**Comment by smallnest** [comment]
另外，如果使用rpcx.XClient, ctx是你自己传入的，你可以传入一个share.Context, 这由你自己决定

**Comment by whaios** [comment]
这里关注 Server Plugin 的 PreCallPlugin 插件，不管是通过http方式调用，还是通过rpcx.XClient调用服务方法，在服务端执行服务方法前都会先执行插件的 PreCall 方法。如果是 http方式调用，在 PreCall 方法中得到的ctx 就是普通的 context.Context，如果是 rpcx.XClient 方式调用的，PreCall 方法中的 ctx 就是 share.Context。

**Comment by whaios** [comment]
![image](https://user-images.githubusercontent.com/19703913/115638766-91da3600-a345-11eb-8cff-ca7cf094cbd4.png)

**Comment by smallnest** [comment]
不确定你使用的rpcx的哪个版本。当前server端的PreCall都属share.Context.
https://github.com/smallnest/rpcx/blob/master/server/gateway.go#L168

![image](https://user-images.githubusercontent.com/865763/116014356-7a61bc80-a667-11eb-9106-b37261dfc091.png)

**Comment by whaios** [comment]
> 不确定你使用的rpcx的哪个版本。当前server端的PreCall都属share.Context.
> https://github.com/smallnest/rpcx/blob/master/server/gateway.go#L168
> 
> ![image](https://user-images.githubusercontent.com/865763/116014356-7a61bc80-a667-11eb-9106-b37261dfc091.png)

使用的是master版本，这里的 newCtx 是 context.Context 类型，而不是 share.Context 类型。
通过 s.handleRequest(newCtx, req) 传递到 PreCall ，所以得到的也是 context.Context 类型。

**Comment by smallnest** [comment]
我明白了

**Comment by smallnest** [comment]
已修改，你可以拉去最新的master试试
