### ISSUE TITLE
已经 go get -u -v -tags "reuseport quic kcp zookeeper etcd consul ping" github.com/smallnest/rpcx/... 但还是找不到EtcdRegisterPlugin

### ISSUE THREAD

**Issue by lihuicms-code-rep** [smallnest/rpcx#570]
![image](https://user-images.githubusercontent.com/50135235/114494892-b5b7c080-9c4f-11eb-987e-47ed9dbc0731.png)

**Comment by lihuicms-code-rep** [comment]
github.com/smallnest/rpcx v1.6.2
serverplugin源码里没看到etcd相关的, ide:goland, 已设置build tags

**Comment by smallnest** [comment]
etcd已经移动到了https://github.com/rpcxio/rpcx-etcd

**Comment by lihuicms-code-rep** [comment]
> etcd已经移动到了https://github.com/rpcxio/rpcx-etcd

好的，感谢
