### ISSUE TITLE
http方式访问服务接口,是这样吗？

### ISSUE THREAD

**Issue by lihuicms-code-rep** [smallnest/rpcx#573]
``func ArithClientHttp() {
	args := &Args{
		A: 10,
		B: 20,
	}

	argsBytes, err := json.Marshal(args)
	if err != nil {
		fmt.Printf("Marshal args error:%v\n", err)
		return
	}

	req, err := http.NewRequest("POST", "http://127.0.0.1:9528", bytes.NewReader(argsBytes))
	if err != nil {
		fmt.Printf("http.NewRequest error:%v\n", err)
		return
	}

	//需要设置的request header
	h := req.Header
	h.Set(client.XMessageID,"10000")
	h.Set(client.XMessageType,"0")
	h.Set(client.XSerializeType,"2")
	h.Set(client.XServicePath,"Arith")
	h.Set(client.XServiceMethod,"Mul")

	//发送http请求
	//http请求===>rpcx请求===>rpcx服务===>返回rpcx结果===>转换为http的response===>输出到client
	res, err := http.DefaultClient.Do(req)
	if err != nil{
		fmt.Printf("failed to call server, err:%v\n", err)
		return
	}
	defer res.Body.Close()

	fmt.Printf("res:%v\n", res)
	// 获取结果
	replyData, err := ioutil.ReadAll(res.Body)
	if err != nil{
		fmt.Printf("failed to read response, err:%v\n", err)
		return
	}

	fmt.Printf("replyData:%v\n", replyData)

	// 反序列化
	reply := &Reply{}
	err = json.Unmarshal(replyData, reply)
	if err != nil {
		fmt.Printf("Unmarshal error:%v\n", err)
		return
	}

	fmt.Printf("ArithClientHttp reply:%+v\n", reply)
}

请求报错: rpcx: failed to handle gateway request: *part1.Args is not a proto.Unmarshaler

**Comment by smallnest** [comment]
序列化格式应该设置成 `1`,代表json, 2是protobuf格式。

```
h.Set(client.XSerializeType,"1")
```

**Comment by smallnest** [comment]
https://github.com/smallnest/rpcx/blob/master/protocol/message.go#L88

**Comment by lihuicms-code-rep** [comment]
好的，看到了，谢谢

**Comment by lihuicms-code-rep** [comment]
![image](https://user-images.githubusercontent.com/50135235/115214237-e6f32d80-a134-11eb-83a7-798d450676a6.png)

json的可以了，刚试了下proto格式的，请求报错: rpcx: failed to handle gateway request: *part1.Args is not a proto.Unmarshaler

**Comment by smallnest** [comment]
我想这个错误提示已经说明了问题。
你的Args没有实现proto.Unmarshaler接口，所以服务端不知道改怎么反序列化它

**Comment by lihuicms-code-rep** [comment]
> 我想这个错误提示已经说明了问题。
> 你的Args没有实现proto.Unmarshaler接口，所以服务端不知道改怎么反序列化它

![image](https://user-images.githubusercontent.com/50135235/115232632-84585c80-a149-11eb-9c0e-cb0ea3491a18.png)
  我是按： protoc --gofast_out 生成的pb.go文件，Marshal,Unmarshal应该是有的。
![image](https://user-images.githubusercontent.com/50135235/115233043-00eb3b00-a14a-11eb-8908-deeca1ef17d5.png)

**Comment by smallnest** [comment]
你可以把你的例子贴上来，方便debug

**Comment by smallnest** [comment]
一个是`*part1.Args`,一个是`*ProtoArgs`,不是同一个类型

**Comment by lihuicms-code-rep** [comment]
> 一个是`*part1.Args`,一个是`*ProtoArgs`,不是同一个类型

是我搞错了，把另一个包的Args引过来了。抱歉，现在没问题了。
