### ISSUE TITLE
cannot find module providing package go.opentelemetry.io/otel/label

### ISSUE THREAD

**Issue by ruziyi** [smallnest/rpcx#574]
``` golang
go get  ./...
crash/cli/client imports
github.com/smallnest/rpcx/client imports
github.com/rpcxio/libkv/store/redis imports
github.com/go-redis/redis/v8 imports
go.opentelemetry.io/otel/label: cannot find module providing package go.opentelemetry.io/otel/label
```

**Comment by smallnest** [comment]
the module exists so you should check whether your go proxy has some issues.

![image](https://user-images.githubusercontent.com/865763/115390501-e16b1580-a210-11eb-9cf6-00cee4393a7b.png)

**Comment by smallnest** [comment]
![image](https://user-images.githubusercontent.com/865763/115391116-ac12f780-a211-11eb-8ef4-163c5c8d72fd.png)

**Comment by smallnest** [comment]
It looks the latest opentelemetry  removed the label lib but opentelemetry dependented by go-redis V8.4.0 had not removed

**Comment by smallnest** [comment]
I have upgrade go-redis in libkv and rpcx. You can get latest rpcx to test.
