### ISSUE TITLE
[ERRO] Unexpected response code: 429 when use Consul

### ISSUE THREAD

**Issue by redwolf2019** [smallnest/rpcx#576]
When my `rpcx server` and `rpcx client` runing for a while, the `rpcx client` show error like:
```
2021/04/30 18:11:57 consul_discovery.go:61: INFO : cannot get services of from registry: user_service/RPC_UserService, err: Unexpected response code: 429
2021-04-30 18:11:57.026 [ERRO] Unexpected response code: 429 
```
and so many duplicate error

![image](https://user-images.githubusercontent.com/54215370/116640270-19a2ee80-a99d-11eb-944d-3241dcc66030.png)

Is this a problem with consul?

consul version: 1.9.5

**Comment by smallnest** [comment]
No. Maybe it is your usage problem or consul. It is a warning. 

I suggest to join the qq 群 to ask questions

**Comment by redwolf2019** [comment]
@smallnest Can you provide QQ group number or Wechat group number? :)

**Comment by smallnest** [comment]
see the readme: 
![image](https://user-images.githubusercontent.com/865763/116649639-54fbe800-a9b2-11eb-98b7-8b96253dfc19.png)
