### ISSUE TITLE
rpcx: failed to handle request: rpcx: can't find method DownloadFile

### ISSUE THREAD

**Issue by edboffical** [smallnest/rpcx#577]
server:
```
		p := server.NewFileTransfer(fileTransferAddr, nil, downloadFilehandler, 1000)
		s.svr.EnableFileTransfer(share.SendFileServiceName, p)

func downloadFilehandler(conn net.Conn, args *share.DownloadFileArgs) {
	f, err := os.Open("abc.txt")
	if err != nil {
		panic(err)
	}
	io.Copy(conn, f)
	conn.Close()
	fmt.Println("send ok")
}
```
client:
```
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	err = c.conn.DownloadFile(context.Background(), filename, f, nil)
	if err != nil {
		return err
	}
	return nil
```

**Comment by smallnest** [comment]
I don't know what is your rpcx version and have no your complete code to run,
But i have run the official example and it is no problem: https://github.com/rpcxio/rpcx-examples/tree/master/file_download.

So you should check and compare your code with offical example, and upgrade rpcx are recommended.

**Comment by edboffical** [comment]
my rpcx version is v1.6.2 and it looks like a syscall.EAGAIN error has occurred

**Comment by edboffical** [comment]
internal/poll.(*FD).Accept at fd_unix.go:393
net.(*netFD).accept at fd_unix.go:172
net.(*TCPListener).accept at tcpsock_posix.go:139
net.(*TCPListener).Accept at tcpsock.go:261
github.com/smallnest/rpcx/server.(*FileTransfer).start at file_transfer.go:135
runtime.goexit at asm_amd64.s:1374

**Comment by edboffical** [comment]
![rpcx](https://user-images.githubusercontent.com/30936981/116663331-892ed300-a9c9-11eb-8fae-f2e20630cb8c.png)

**Comment by edboffical** [comment]
Does s.RegisterName affect this?

**Comment by smallnest** [comment]
you can run rpcx-examples to test. don't change the service name if you don't know  what it means
