### ISSUE TITLE
使用ETCD做服务发现，当服务端没有启动的时候，客户端会造成go程泄露，Close()不管用的。

### ISSUE THREAD

**Issue by Matthew-Zong** [smallnest/rpcx#578]
goroutine profile: total 75
56 @ 0x3c2a5 0xs086af 0x82eb 0xb5d0 0x47da1
  0xbb25cf	github.com/rpcxio/rpcx-etcd/store/etcdv3.New.func1+0x4f	/root/xxx/src/github.com/rpcxio/rpcx-etcd/store/etcdv3/etcdv3.go:71

**Comment by smallnest** [comment]
调用`EtcdV3.Close`会close done,然后返回的，所以如果你自己对EtcdV3做封装，失败的时候记得Close

**Comment by smallnest** [comment]
并且，你的rpcx-etcd和最新的版本不一致了，不清楚你的71#代表什么

**Comment by Matthew-Zong** [comment]
不好意思哈，etcdv3我没修改过什么，之前增加了一行注释，应该是70行，https://github.com/rpcxio/rpcx-etcd/blob/master/store/etcdv3/etcdv3.go 的第70行：
	<-s.startKeepAlive

失败的时候都会调用Close的。

**Comment by Matthew-Zong** [comment]
今天在func (s *EtcdV3) Close() 方法中给startKeepAlive channel 一个空struct会解决此问题（早上到现在没有发生goroutine 积压），不知道我的做法是否有问题哈？^_^

**Comment by smallnest** [comment]
你可以拉取最新的rpcx-etcd试试。我增加了处理，避免goroutine leak

**Comment by Matthew-Zong** [comment]
哈喽，非常感谢修复。
又遇到一种情况，当etcd宕机的情况下也会造成goroutines 泄露。
goroutine profile: total 111
32 @ 0x43c4e5 0x4348fb 0x46c575 0x4e00a5 0x5d2a3c 0x5d2a17 0x5d2a47 0x5ecd68 0x5ec885 0x5e1625 0x5f15c5 0x5f14b7 0x5c82c5 0x5c7692 0x5c6a05 0xa3969b 0xa1f979 0xa1fcde 0xaa45cf 0xaa44c0 0xaa3e8d 0xaa33bf 0x472081
#	0x46c574	internal/poll.runtime_pollWait+0x54					/usr/lib/golang/src/runtime/netpoll.go:222
#	0x4e00a4	internal/poll.(*pollDesc).wait+0x44					/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:87
#	0x5d2a3b	internal/poll.(*pollDesc).waitWrite+0x25b				/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:96
#	0x5d2a16	internal/poll.(*FD).WaitWrite+0x236					/usr/lib/golang/src/internal/poll/fd_unix.go:508
#	0x5d2a46	net.(*netFD).connect+0x266						/usr/lib/golang/src/net/fd_unix.go:141
#	0x5ecd67	net.(*netFD).dial+0x107							/usr/lib/golang/src/net/sock_posix.go:149
#	0x5ec884	net.socket+0x1c4							/usr/lib/golang/src/net/sock_posix.go:70
#	0x5e1624	net.internetSocket+0x144						/usr/lib/golang/src/net/ipsock_posix.go:141
#	0x5f15c4	net.(*sysDialer).doDialTCP+0xc4						/usr/lib/golang/src/net/tcpsock_posix.go:65
#	0x5f14b6	net.(*sysDialer).dialTCP+0xd6						/usr/lib/golang/src/net/tcpsock_posix.go:61
#	0x5c82c4	net.(*sysDialer).dialSingle+0x5e4					/usr/lib/golang/src/net/dial.go:580
#	0x5c7691	net.(*sysDialer).dialSerial+0x151					/usr/lib/golang/src/net/dial.go:548
#	0x5c6a04	net.(*Dialer).DialContext+0x6e4						/usr/lib/golang/src/net/dial.go:425
#	0xa3969a	google.golang.org/grpc/internal/transport.proxyDial+0xfa		/root/iotbot/src/google.golang.org/grpc/internal/transport/proxy.go:125
#	0xa1f978	google.golang.org/grpc/internal/transport.dial+0x358			/root/iotbot/src/google.golang.org/grpc/internal/transport/http2_client.go:159
#	0xa1fcdd	google.golang.org/grpc/internal/transport.newHTTP2Client+0x15d		/root/iotbot/src/google.golang.org/grpc/internal/transport/http2_client.go:192
#	0xaa45ce	google.golang.org/grpc/internal/transport.NewClientTransport+0x40e	/root/iotbot/src/google.golang.org/grpc/internal/transport/transport.go:580
#	0xaa44bf	google.golang.org/grpc.(*addrConn).createTransport+0x2ff		/root/iotbot/src/google.golang.org/grpc/clientconn.go:1322
#	0xaa3e8c	google.golang.org/grpc.(*addrConn).tryAllAddrs+0x38c			/root/iotbot/src/google.golang.org/grpc/clientconn.go:1252
#	0xaa33be	google.golang.org/grpc.(*addrConn).resetTransport+0x23e			/root/iotbot/src/google.golang.org/grpc/clientconn.go:1167

32 @ 0x43c4e5 0x44c64f 0x5fd2c5 0x472081
#	0x5fd2c4	net.(*netFD).connect.func2+0xc4	/usr/lib/golang/src/net/fd_unix.go:118

12 @ 0x43c4e5 0x44c64f 0xa9b068 0x472081
#	0xa9b067	google.golang.org/grpc.(*ccBalancerWrapper).watcher+0xc7	/root/iotbot/src/google.golang.org/grpc/balancer_conn_wrappers.go:69

12 @ 0x43c4e5 0x44c64f 0xbc8665 0x472081
#	0xbc8664	github.com/rpcxio/rpcx-etcd/store/etcdv3.New.func1+0xc4	/root/xxx/src/github.com/rpcxio/rpcx-etcd/store/etcdv3/etcdv3.go:70

4 @ 0x43c4e5 0x44c64f 0xaa35a5 0x472081

**Comment by smallnest** [comment]
> 哈喽，非常感谢修复。
> 又遇到一种情况，当etcd宕机的情况下也会造成goroutine 泄露。

不清楚你的case。

正常情况etcd基础不应该不可用的，否则企业整个服务调用都完蛋了。

**Comment by smallnest** [comment]
另外，如果Discovery有问题了，可以调用Discovery的Close关闭这个Discovery， 避免无谓的re-watch
