### ISSUE TITLE
put 时 就报："v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004c28c0/#initially=[127.0.0.1:2379;127.0.0.1:22379;127.0.0.1:32379]","attempt":99,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing

### ISSUE THREAD

**Issue by jony4096** [smallnest/rpcx#580]
"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004c28c0/#initially=[127.0.0.1:2379;127.0.0.1:22379;127.0.0.1:32379]","attempt":99,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing

求解！

**Comment by smallnest** [comment]
不清楚你的上下文。
建议你提issue的把测试步骤、测试版本描述清楚。

猜测你使用etcdv3当注册中心，在服务注册的时候出错？

我想大概率是etcd版本或者etcd clent库的问题。 你把etcd的版本、etcd client 的version、测试代码贴一下，这样别人才有可能帮你分析问题。

**Comment by jony4096** [comment]
非常感谢你的回复，我再琢磨琢磨
