### ISSUE TITLE
使用msgpack作为序列化方式时，对空数组decode时会出问题

### ISSUE THREAD

**Issue by vosey** [smallnest/rpcx#585]
例如定义参数

type Arg struct {
    St struct {
        St1 string
    }
    Ss string
}

type Reply struct {
	Code    int
	Message string
	Data    interface{}
}

func Test(ctx context.Context, args *Arg, reply *Reply) error { ... }

这个时候如果在php中调用Test ，并且Payload是  msgpack_pack([]),  也就是传一个空数组，那么codec.Decode 会产生一个错误：msgpack: number of fields in array-encoded struct has changed。

期待的情况是即便是不提供接口入参时，仍然可以确保接口是可以被调用的，不知道是否能提供支持  @smallnest

**Comment by smallnest** [comment]
这个需要msgpack库支持

**Comment by vosey** [comment]
> 这个需要msgpack库支持，可以到 https://github.com/vmihailenco/msgpack 提个issue

好的，thanks

**Comment by vosey** [comment]
@smallnest 你可以考虑更新msgpack到 v5.3.3 及以上， 已经解决了空数组参数在decode时的问题了

**Comment by smallnest** [comment]
updated. thanks
