### ISSUE TITLE
使用consul与 etcdV3注册的bug

### ISSUE THREAD

**Issue by mingyunbudui** [smallnest/rpcx#589]
1. 使用consul ，通过 libkv 存储到consul的kv时，UpdateInterval consul 要求至少10s 小于10s时 错误返回非原始，rpcx 内部 UpdateInterval *2 更新，当服务注销时 rpcx 这时间段内 仍然 还会请求到注销的节点上 timeout ，重试也不支持换个节点。
2. 使用 etcd v3 plugin 作为服务发现，依赖服务 后启动时，调用完全找不到 any server
3. 放着consul 好好的服务注册自带健康检查不使用，去使用kv，很奇怪的做法，导致 rpcx服务发现基本不可用

**Comment by smallnest** [comment]
非建设性issue
