### ISSUE TITLE
请教大佬关于XClient.SendRaw使用rpcx.client插件的问题

### ISSUE THREAD

**Issue by vosey** [smallnest/rpcx#591]
最近一直在使用rpcx + rpcx-gateway的方式来搭建自己的服务架构，在假如opentracing的过程中发现gateway中使用了SendRaw方式来进行调用，那么这种情况下并不支持客户端的插件，故会导致在服务端会出现opentracing: SpanContext not found in Extract carrier,  所以这样的话，并不会有任何的span会被记录到tracer了

看了看代码，有个想法，不知道这样做是否正确，打算在xclient中实现一个类似wrapCall的函数，比如

```
func (c *xClient) wrapSendRaw(ctx context.Context, client RPCClient, r *protocol.Message) (map[string]string, []byte, error) {
	if client == nil {
		return nil, nil, ErrServerUnavailable
	}

	ctx = share.NewContext(ctx)
	c.Plugins.DoPreCall(ctx, c.servicePath, r.ServiceMethod, r.Payload)
	m, payload, err := client.SendRaw(ctx, r)
	c.Plugins.DoPostCall(ctx, c.servicePath, r.ServiceMethod, r.Payload, nil, nil)

	return m, payload, err
}
```

然后让SendRaw函数中原有调用方式
```
m, payload, err := client.SendRaw(ctx, r)
```
调整为
```
m, payload, err := c.SendRaw(ctx, client, r)
```

这样一来，使其支持客户端插件，从而让服务端和网关能够正确联动记录span。

如果这个想法不合理的话，那我想到的另外一种思路就是在网关侧SendRaw之前，采用客户端OpenTracingPlugin中PreCall中的方式来创建一个span，并且将ctx传递给SendRaw。

不知道以上这两种实现方式哪个更合理一些，亦或都不正确，请大佬指点一下。  @smallnest

**Comment by smallnest** [comment]
我觉得上面一种方法可以，但是下面的调整应该不是必须的
```
m, payload, err := c.SendRaw(ctx, client, r)
```
因为这里的`client`就是`c`,不确定你要加加client的目的是为何。

你可以提交一个pull request。 谢谢

**Comment by vosey** [comment]
> 我觉得上面一种方法可以，但是下面的调整应该不是必须的
> 
> ```
> m, payload, err := c.SendRaw(ctx, client, r)
> ```
> 
> 因为这里的`client`就是`c`,不确定你要加加client的目的是为何。
> 
> 你可以提交一个pull request。 谢谢

已提PR, 其实昨天这里写错了
```
m, payload, err := c.SendRaw(ctx, client, r)
```
应该是
```
m, payload, err := c.wrapSendRaw(ctx, client, r)
```
这里面的client是指
```
k, client, err := c.selectClient(ctx, r.ServicePath, r.ServiceMethod, r.Payload)
```

大佬看下PR内容是否符合合并要求

**Comment by smallnest** [comment]
merged. thanks

**Comment by cl51287** [comment]
@smallnest 您好，我在https://blog.rpcx.io/posts/use-rpcx-to-transfer-files/这篇文章里看到rpcx以前支持文件传输，但是在最新版看没有了，请问是什么原因导致去掉了呢

**Comment by smallnest** [comment]
没删除，相关例子  https://github.com/rpcxio/rpcx-examples/tree/master/filetransfer
@cl51287

**Comment by cl51287** [comment]
@smallnest 非常感谢
