### ISSUE TITLE
设置熔断器好像没有效果？

### ISSUE THREAD

**Issue by LeechanX** [smallnest/rpcx#593]
我自定义了一个熔断器，并通过这样的方式注册到了client
rpcxOption.GenBreaker = func() client.Breaker {
		return NewClockDriftCircuitBreaker(time.Minute)
}

通过打日志发现 Call(fn func() error, d time.Duration) 没有被调用

**Comment by smallnest** [comment]
只是在连接server失败的时候调用才会标记为断路器失败，在获取连接的时候检查。看看你的测试场景是不是和这个一致？
