### ISSUE TITLE
关于 fileTransfer 的问题

### ISSUE THREAD

**Issue by edboffical** [smallnest/rpcx#595]
云服务器公网 IP 不在网卡上，怎么监听 fileTransfer 在公网 IP 上

https://github.com/rpcxio/rpcx-examples/tree/master/filetransfer

按照这个例子，如果 bind 0.0.0.0:8973

最终 client 取到的地址也是 0.0.0.0:8973

**Comment by smallnest** [comment]
配置AdvertiseAddr字段为外部的公网地址，客户端会连接这个地址

**Comment by edboffical** [comment]
感谢解答

`	if fileTransferAddr, ok := s.opts.Params["fileTransferAddr"]; ok {
		p := server.NewFileTransfer(fileTransferAddr, nil, downloadFilehandler, 1000)
		// 设置外网地址
		if adverFileAddr, ok := s.opts.Params["adverFileAddr"]; ok {
			p.AdvertiseAddr = adverFileAddr
		}
		s.svr.EnableFileTransfer("cprism.file", p)
	}`

不过这样设置了，好像还是返回的 0.0.0.0

**Comment by smallnest** [comment]
你拉取最新的rpcx,或者v1.6.4试一下，先前有些问题

**Comment by edboffical** [comment]
> 你拉取最新的rpcx,或者v1.6.4试一下，先前有些问题

确实可以了 谢谢
