### ISSUE TITLE
自定义时间不能正常传递

### ISSUE THREAD

**Issue by Laotree** [smallnest/rpcx#597]
自定义一个新的time，实现了 UnmarshalJSON、MarshalJSON 接口
在gorm、API的传递是正常的
但是在rpcx里会丢失
客户端拿到的是 CreatedAt:0001-01-01 00:00:00 
是需要实现其他序列化的接口吗？请告知。

**Comment by smallnest** [comment]
编码方式指定为json格式。

默认采用msgpack作为编解码协议，所以你自定义的接口不起作用

**Comment by Laotree** [comment]
能不能告诉我，怎么设置编解码协议？
是否支持指定某个接口使用json，其他保持默认？

**Comment by smallnest** [comment]
https://doc.rpcx.io/part3/codec.html

可以加入qq群寻求使用上的问题。 qq群见readme
