### ISSUE TITLE
java如何用jsonrpc2进行调用，我用jsonrpc4j怎么都调不通，能不能写个简单示例

### ISSUE THREAD

**Issue by sootma** [smallnest/rpcx#606]
java如何用jsonrpc2进行调用，我用jsonrpc4j怎么都调不通，能不能写个简单示例，服务治理，我用的是 redis

**Comment by smallnest** [comment]
各种例子都在 rpcx-examples。 比如jsonrpc2的例子 https://github.com/rpcxio/rpcx-examples/tree/master/jsonrpc2

和服务治理无关。反正是通过http直接访问的服务端地址
