### ISSUE TITLE
请教如何传值能让rpcx自动解析成context

### ISSUE THREAD

**Issue by sootma** [smallnest/rpcx#607]
1. 在go中如此定义：
    func (t *Arith) Mul(ctx context.Context, args Args, reply *Reply) error
2. 在java中用restTemplate调用
    params.put("jsonrpc", "2.0"); 
    params.put("method", "Arith.Mul");
    params.put("id", 99); 
    params.put("params", arg); //arg:
    
   restTemplate.postForEntity(url, httpEntity, String.class)
 // {"headers":{"Content-Type":["application/json"],"X-JSONRPC-2.0":["true"]},"body":{"method":"Arith.Mul","id":99,"jsonrpc":"2.0","params":{"A":8,"B":9}}}
服务端能正常响应，客户端也正常收到消息
{"jsonrpc":"2.0","result":{"C":72},"id":99}

但如何传递ctx，能让rpcx正常解析？因为我用下面的方法，rpcx服务端也取不到值
params.put("__req_metadata", reqMeta);
params.put("__res_metadata", new HashMap<String, String>());

我应该如何传值，才能让rpcx自动解析成context？请有空帮忙解答下，谢谢！

**Comment by smallnest** [comment]
什么叫 `才能让rpcx自动解析成context`？ 你要传递什么信息，希望服务端从context读取什么信息？

**Comment by sootma** [comment]
在golang调用rpcx时，通过context传递了元数据，比如一些user信息之类的
ctx := context.WithValue(context.Background(), share.ReqMetaDataKey, map[string]string{"aaa": "from client"})
ctx = context.WithValue(ctx, share.ResMetaDataKey, make(map[string]string))

我想在java调用时，通过一种方式传递这些元数据过去，能让rpcx自动识别是元数据。
这样在服务端就不用关心是从哪里开始调用的，只用写一套服务代码就行了。

**Comment by sootma** [comment]
在golang调用rpcx时，通过context传递了元数据，比如一些user信息之类的
ctx := context.WithValue(context.Background(), share.ReqMetaDataKey, map[string]string{"aaa": "from client"})
ctx = context.WithValue(ctx, share.ResMetaDataKey, make(map[string]string))

我想在java调用时，通过一种方式传递这些元数据过去，能让rpcx自动识别是元数据。
这样在服务端就不用关心是从哪里开始调用的，只用写一套服务代码就行了。

**Comment by smallnest** [comment]
即使你使用Go做客户端，context也不会被传给server端。client和服务端传递一些额外的数据是通过metadata传递的。

https://github.com/rpcxio/rpcx-examples/tree/master/metadata

**Comment by smallnest** [comment]
因为你使用Java,所以你需要hack,依照rpcx协议的格式，发送请求的时候meta设置到request中
https://github.com/smallnest/rpcx/blob/84200bf9ef25a798924f65d4fff743396352bd8d/client/client.go#L400
