### ISSUE TITLE
support kcp - a full-featured reliable UDP library

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#61]
> kcp-go is a full-featured reliable-UDP library for golang. It provides reliable, ordered, and error-checked delivery of a stream of octets between applications running on hosts communicating over an IP network.

> KCP是一个快速可靠协议，能以比 TCP浪费10%-20%的带宽的代价，换取平均延迟降低 30%-40%，且最大延迟降低三倍的传输效果。纯算法实现，并不负责底层协议（如UDP）的收发，需要使用者自己定义下层数据包的发送方式，以 callback的方式提供给 KCP。 连时钟都需要外部传递进来，内部不会有任何一次系统调用。

see:
https://github.com/xtaci/kcp-go
https://github.com/skywind3000/kcp

**Comment by smallnest** [comment]
the examples is at https://github.com/smallnest/rpcx/tree/master/_examples/kcp

**Comment by smallnest** [comment]
@xtaci @skywind3000

**Comment by skywind3000** [comment]
高端
