### ISSUE TITLE
是否有生成全局错误处理器的建议呢

### ISSUE THREAD

**Issue by LinYKen** [smallnest/rpcx#610]
希望在内部处理业务逻辑的时候 报出err后 能再传回客户端的时候再次对err进行封装成正常的res而不是仅仅将err返回给客户端 不知道这个是否可以实现呢？

**Comment by smallnest** [comment]
to implement the plugin:
```
	PostCallPlugin interface {
		PostCall(ctx context.Context, serviceName, methodName string, args, reply interface{}) (interface{}, error)
	}
```

**Comment by LinYKen** [comment]
I instead implement the the plugin below:
`PreWriteResponsePlugin interface {
		PreWriteResponse(context.Context, *protocol.Message, *protocol.Message, error) error
}`
It works well for the tcp connection. However, when I switch to HTTP connection, it doesn't go through it. Perhaps, mainly because there is a judgement before calling plugins.
`	
if err == nil {
     replyv, err = s.Plugins.DoPostCall(ctx, serviceName, methodName, argv, replyv)
}`
`
if err != nil {
		if s.HandleServiceError != nil {
			s.HandleServiceError(err)
		} else {
			log.Warnf("rpcx:  gateway request: %v", err)
		}
		wh.Set(XMessageStatusType, "Error")
		wh.Set(XErrorMessage, err.Error())
		w.WriteHeader(500)
		return
	}
`
The both are derived from server.go.

And I got one more question. If I am going to build a webapp with rpcx, should I let frontend server call the rpcx with HTTP directly? Or building a client in the middle, for example, gin server, passing and transforming the request?

**Comment by LinYKen** [comment]
> to implement the plugin:
> 
> ```
> 	PostCallPlugin interface {
> 		PostCall(ctx context.Context, serviceName, methodName string, args, reply interface{}) (interface{}, error)
> 	}
> ```

I instead implement the the plugin below:
PreWriteResponsePlugin interface { PreWriteResponse(context.Context, *protocol.Message, *protocol.Message, error) error }
It works well for the tcp connection. However, when I switch to HTTP connection, it doesn't go through it. Perhaps, mainly because there is a judgement before calling plugins.
if err == nil { replyv, err = s.Plugins.DoPostCall(ctx, serviceName, methodName, argv, replyv) }
if err != nil { if s.HandleServiceError != nil { s.HandleServiceError(err) } else { log.Warnf("rpcx: gateway request: %v", err) } wh.Set(XMessageStatusType, "Error") wh.Set(XErrorMessage, err.Error()) w.WriteHeader(500) return }
The both are derived from server.go.

And I got one more question. If I am going to build a webapp with rpcx, should I let frontend server call the rpcx with HTTP directly? Or building a client in the middle, for example, gin server, passing and transforming the request?

**Comment by smallnest** [comment]
No,i suggest you use raw rpcx protocol instead of http directly. Http invoke is used only for those programming languages which have no rpcx raw clients

**Comment by LinYKen** [comment]
> No,i suggest you use raw rpcx protocol instead of http directly. Http invoke is used only for those programming languages which have no rpcx raw clients

Then, according to the situation I mentioned, providing service for some web apps, it will be better to build up some middle routers with gin? If yes, I guess I can set a global error handler in gin, or, is there any solution/architecture simpler or more popular? Since rpc service/framework is new to me, if you can give me some suggestions, I will be very grateful!!

**Comment by smallnest** [comment]
Basically,  if you provides api to the frontend such as angular、vue, you should add gin,echo or others web frameworks  as the business layer, and the business layer uses rpcx to access the backend microservices such ad login, bill services, etcd.

**Comment by LinYKen** [comment]
> Basically, if you provides api to the frontend such as angular、vue, you should add gin,echo or others web frameworks as the business layer, and the business layer uses rpcx to access the backend microservices such ad login, bill services, etcd.

Got it. Thank you so much!!
