### ISSUE TITLE
context的生命周期

### ISSUE THREAD

**Issue by sootma** [smallnest/rpcx#611]
我在拦截器
func (this *rpcxContext) PostReadRequest(ctx context.Context, req *protocol.Message, err error) error {
	//设置操作员
	json := gjson.New(string(req.Payload))
	oper := &xmodel.User{}
	if err := json.GetStruct("user", oper); err == nil {
		customCtx := &xmodel.UserContext{
			// Session: r.Session,
			User: oper,
		}
		xutils.Context.InitRpc(&ctx, customCtx)
	}

	sjson, _ := gjson.Encode(xutils.Context.Get(ctx))
	fmt.Println("=====ctx: ", string(sjson), &ctx)
	return nil
}
中设置了一个context的值 ，在这个方法中可以正确打印出来，但在下一步，真正rpc的调用中却找不到这个值 。
是不是这个方法中的contexg与rpc方法调用中的context不是同一个context?

**Comment by smallnest** [comment]
不清楚你`xutils.Context.InitRpc(&ctx, customCtx)`怎么设置的。 正常go Context是用来读取值，你没有办法设置的。
如果想设置，参考rpcx中插件中其它设置方法，主要利用rpcx自定义的Context

https://github.com/smallnest/rpcx/blob/master/share/context.go

**Comment by sootma** [comment]
xutils.Context.InitRpc(&ctx, customCtx)
是一个很简单的方法，如下：
func (this *contextService) InitRpc(ctx *context.Context, customCtx *xmodel.UserContext) {
	*ctx = context.WithValue(*ctx, _ContextKey_User, customCtx)
}
因为我是对内存地址重新进行赋值，所以它没有改变这个context的地址。
下面是取这个context
func (this *contextService) Get(ctx context.Context) *xmodel.UserContext {
	value := ctx.Value(_ContextKey_User)
	if value == nil {
		return nil
	}
	if localCtx, ok := value.(*xmodel.UserContext); ok {
		return localCtx
	}
	return nil
}

我有3个func,如下
1. plugin
   PostReadRequest(ctx context.Context, req *protocol.Message, err error){
    ...
   xutils.Context.InitRpc(&ctx, &xmodel.UserContext)
  }
  我想在这统一从参数中读取操作员信息，设置到context中
2. api
  FuncA(ctx context.Context, args *Argument, reply *ActionResult){
      ...
     xutils.Context.InitRpc(&ctx, &xmodel.UserContext)
}
3. service
  func (this *Service) ServiceA(ctx context.Context, id int64) error {
	json, _ := gjson.Encode(xutils.Context.Get(ctx))
	fmt.Println("========ReleaseSpu: ", string(json), ", ", versionId)
	return nil
 }

我本想是通过plugin统一从参数中读取用户信息，设置这个初始始，不需要在api的每个方法中设置，并且可以在service的ctx中获取
我试过，在plugin中设置的无效，但在api中设置的，可以在service中获取。但这样比较麻烦，每个api方法都要这样设置一下，最理想的方法是通过plugin统一设置与维护。
我猜想，是不是从plugin到api的过程中，这个context发现在了变化，丢弃了其中的值

**Comment by smallnest** [comment]
Go标准库的Context只是用来传递，context.WithValue只是生成一个新的context,你不可能把这个context传递给外部。

**Comment by smallnest** [comment]
所以我建议你看看仓库中的其它plugin的实现。rpcx使用一个定制的Context,所以你可以通过SetValue的方式设置你的数据，访问这个定制context的方式可以参考

https://github.com/smallnest/rpcx/blob/master/serverplugin/opencensus.go#L57

**Comment by sootma** [comment]
可以的，传地址

**Comment by sootma** [comment]
上面的例子，若在api中设置context的值 ，在service中是可以取值 的，没有问题

**Comment by smallnest** [comment]
你见过地道的Go项目传递Context时使用地址？
