### ISSUE TITLE
context 传值 

### ISSUE THREAD

**Issue by sootma** [smallnest/rpcx#612]
xutils.Context.InitRpc(&ctx, customCtx)
是一个很简单的方法，如下：
func (this *contextService) InitRpc(ctx *context.Context, customCtx *xmodel.UserContext) {
*ctx = context.WithValue(*ctx, _ContextKey_User, customCtx)
}
因为我是对内存地址重新进行赋值，所以它没有改变这个context的地址。
下面是取这个context
func (this *contextService) Get(ctx context.Context) *xmodel.UserContext {
value := ctx.Value(_ContextKey_User)
if value == nil {
return nil
}
if localCtx, ok := value.(*xmodel.UserContext); ok {
return localCtx
}
return nil
}

我有3个func,如下

plugin
PostReadRequest(ctx context.Context, req *protocol.Message, err error){
...
xutils.Context.InitRpc(&ctx, &xmodel.UserContext)
}
我想在这统一从参数中读取操作员信息，设置到context中
api
ApiA(ctx context.Context, args *Argument, reply *ActionResult){
...
xutils.Context.InitRpc(&ctx, &xmodel.UserContext)
}
service
func (this *Service) ServiceA(ctx context.Context, id int64) error {
json, _ := gjson.Encode(xutils.Context.Get(ctx))
fmt.Println( string(json))
return nil
}
我本想是通过plugin统一从参数中读取用户信息，设置这个初始始，不需要在api的每个方法中设置，并且可以在service的ctx中获取
我试过，在plugin中设置的无效，但在api中设置的，可以在service中获取。但这样比较麻烦，每个api方法都要这样设置一下，最理想的方法是通过plugin统一设置与维护。
我猜想，是不是从plugin到api的过程中，这个context发现在了变化，丢弃了其中的值

**Comment by smallnest** [comment]
参考 https://github.com/smallnest/rpcx/blob/master/serverplugin/opencensus.go#L57,  你插件中的context其实是一个rpcx定制的 Context对象，提供了设置Value的方法：

https://github.com/smallnest/rpcx/blob/master/serverplugin/opencensus.go#L57

**Comment by sootma** [comment]
rpcx自带的context解决了我的问题！！！
