### ISSUE TITLE
run example rpcx , panic after kill the service

### ISSUE THREAD

**Issue by fitlivingmm** [smallnest/rpcx#614]
rpcx example 102basic/server 

运行该列子，kill 该进程 panic

`
➜  server git:(master) ✗ pwd
/Users/xxx/working/go/src/github.com/rpcxio/rpcx-examples/102basic/server
➜  server git:(master) ✗ go build .
➜  server git:(master) ✗ ./server
2021/07/19 10:58:49 server.go:184: INFO : server pid:51679
2021/07/19 10:58:56 server.go:827: INFO : shutdown begin
2021/07/19 10:58:56 gateway.go:81: INFO : gateway server closed
2021/07/19 10:58:56 server.go:917: INFO : need handle in-processing msg size:0
panic: http: Server closed

goroutine 1 [running]:
main.main()
	/Users/xxx/working/go/src/github.com/rpcxio/rpcx-examples/102basic/server/server.go:33 +0x158
➜  server git:(master) ✗
`

**Comment by smallnest** [comment]
这里例子故意这样处理的，和框架没关系。 你可以只打印error而不panic, 自由随你

```
func main() {
	flag.Parse()

	s := server.NewServer()
	// s.Register(new(Arith), "")
	s.RegisterName("Arith", new(Arith), "")
	err := s.Serve("tcp", *addr)
	if err != nil {
		panic(err)
	}
}
```

**Comment by fitlivingmm** [comment]
好，谢谢
