### ISSUE TITLE
单次请求最大数据长度

### ISSUE THREAD

**Issue by sirius65535** [smallnest/rpcx#616]
请教大佬，使用msgpack的话，请求的最大数据长度能达到多少？ 我尝试传输1GB的[]byte数据会报错

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by smallnest** [comment]
不建议使用 rpcx传递巨大的数据，毕竟rpc不是用来传输大文件的，而且还会导致内存占用很大。

**Comment by smallnest** [comment]
rpcx默认没有限制消息大小，但是服务端可以通过设置MaxMessageLength进行限制。
https://github.com/smallnest/rpcx/blob/51011c6501d3d360b0e8adcdccfdb152d7104c7f/protocol/message.go#L24
