### ISSUE TITLE
使用两个client去请求同一个RegisterFunction时报锁的错误

### ISSUE THREAD

**Issue by sirius65535** [smallnest/rpcx#618]
在服务端使用RegisterFunction注册了一个function A，在两个终端里分别开启进程a和b，每个进程里有一个client，两个client不停的去向 A 发送获取数据，每次发送的的[]byte数据由32字节开始向上无限递增，步长为16字节。先开启a进程可以正常跑下去，但是再开启b进程几秒钟之后server就报如下错误了。麻烦大佬看看是什么问题，thanks！

`fatal error: sync: unlock of unlocked mutex

goroutine 2125 [running]:
runtime.throw(0x9c9cec, 0x1e)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0002e6a70 sp=0xc0002e6a40 pc=0x43b8f2
sync.throw(0x9c9cec, 0x1e)
        /usr/local/go/src/runtime/panic.go:1103 +0x35 fp=0xc0002e6a90 sp=0xc0002e6a70 pc=0x46d275
sync.(*Mutex).unlockSlow(0xf481f0, 0xc0ffffffff)
        /usr/local/go/src/sync/mutex.go:196 +0xd8 fp=0xc0002e6ab8 sp=0xc0002e6a90 pc=0x47ceb8
sync.(*Mutex).Unlock(0xf481f0)
        /usr/local/go/src/sync/mutex.go:190 +0x48 fp=0xc0002e6ad8 sp=0xc0002e6ab8 pc=0x47cdc8
sync.(*Pool).pinSlow(0xec4ca0, 0xc000204080, 0x1)
        /usr/local/go/src/sync/pool.go:230 +0x167 fp=0xc0002e6b58 sp=0xc0002e6ad8 pc=0x47d627
sync.(*Pool).pin(0xec4ca0, 0xb, 0x0)
        /usr/local/go/src/sync/pool.go:206 +0x65 fp=0xc0002e6b80 sp=0xc0002e6b58 pc=0x47d485
sync.(*Pool).Get(0xec4ca0, 0xc0003048a0, 0xc000028a11)
        /usr/local/go/src/sync/pool.go:128 +0x2f fp=0xc0002e6bc8 sp=0xc0002e6b80 pc=0x47d12f
github.com/smallnest/rpcx/protocol.(*Message).Decode(0xc000305980, 0xa50800, 0xc0003048a0, 0x0, 0x0)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/protocol/message.go:437 +0x12b fp=0xc0002e6ca8 sp=0xc0002e6bc8 pc=0x686a0b
github.com/smallnest/rpcx/server.(*Server).readRequest(0xc00012e000, 0xa5a0e0, 0xc000174408, 0xa50800, 0xc0003048a0, 0xc0001f2000, 0xc000174408, 0x0)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:566 +0xbe fp=0xc0002e6d18 sp=0xc0002e6ca8 pc=0x7991de
github.com/smallnest/rpcx/server.(*Server).serveConn(0xc00012e000, 0xa5e658, 0xc0001f2000)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:400 +0x2bd fp=0xc0002e6fc8 sp=0xc0002e6d18 pc=0x797d5d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0002e6fd0 sp=0xc0002e6fc8 pc=0x4722a1
created by github.com/smallnest/rpcx/server.(*Server).serveListener
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:316 +0x239

goroutine 1 [select]:
github.com/soheilhy/cmux.muxListener.Accept(0xa58db0, 0xc00011e198, 0xc0001102a0, 0xc00010e120, 0xc0000fbd60, 0x18, 0xc000000180, 0x7972f9)
        /home/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:262 +0x85
github.com/smallnest/rpcx/server.(*Server).serveListener(0xc00012e000, 0xa590e0, 0xc000130d80, 0xa58db0, 0xc00011e198)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:262 +0xb7
github.com/smallnest/rpcx/server.(*Server).Serve(0xc00012e000, 0x9bb64c, 0x3, 0xc0001260e0, 0xc, 0x9bfea0, 0xe)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:233 +0x13f
main.main()
        /home/go_test/rpc_server/server.go:221 +0x13d7

goroutine 6 [select]:
database/sql.(*DB).connectionOpener(0xc00021a000, 0xa59e78, 0xc0000825c0)
        /usr/local/go/src/database/sql/sql.go:1133 +0xb5
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:740 +0x12a

goroutine 7 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc0000347e0, 0xc0000b0b40, 0xc00008e240)
        /home/gopath/pkg/mod/github.com/go-sql-driver/mysql@v1.6.0/connection.go:614 +0xa5
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
        /home/gopath/pkg/mod/github.com/go-sql-driver/mysql@v1.6.0/connection.go:611 +0xbe

goroutine 18 [chan receive]:
github.com/smallnest/rpcx/server.(*Server).startShutdownListener.func1(0xc00012e000)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:193 +0x18c
created by github.com/smallnest/rpcx/server.(*Server).startShutdownListener
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:183 +0x3f

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x7fe2769b2dc8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000f0318, 0x72, 0x400, 0x400, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f0300, 0xc0000c0800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0000f0300, 0xc0000c0800, 0x400, 0x400, 0xc0000b4b40, 0x240, 0x220)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0000120b8, 0xc0000c0800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:183 +0x91
github.com/soheilhy/cmux.(*bufferedReader).Read(0xc0001aa630, 0xc0000c0800, 0x400, 0x400, 0xc00006db68, 0xedd580, 0x8)
        /home/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.5/buffer.go:53 +0x12d
github.com/soheilhy/cmux.(*MuxConn).Read(0xc0001aa620, 0xc0000c0800, 0x400, 0x400, 0x203000, 0x203000, 0x20)
        /home/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:297 +0x4f
bufio.(*Reader).Read(0xc000034900, 0xc000028670, 0x1, 0xc, 0x60, 0x60, 0x9a0520)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0xa50800, 0xc000034900, 0xc000028670, 0x1, 0xc, 0x1, 0xc00006dc28, 0x411c58, 0x60)
        /usr/local/go/src/io/io.go:328 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
github.com/smallnest/rpcx/protocol.(*Message).Decode(0xc0000349c0, 0xa50800, 0xc000034900, 0x0, 0x0)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/protocol/message.go:423 +0x7a
github.com/smallnest/rpcx/server.(*Server).readRequest(0xc00012e000, 0xa5a0e0, 0xc000010360, 0xa50800, 0xc000034900, 0xc0001aa620, 0xc000010360, 0x0)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:566 +0xbe
github.com/smallnest/rpcx/server.(*Server).serveConn(0xc00012e000, 0xa5e658, 0xc0001aa620)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:400 +0x2bd
created by github.com/smallnest/rpcx/server.(*Server).serveListener
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:316 +0x239

goroutine 20 [select]:
github.com/soheilhy/cmux.muxListener.Accept(0xa58db0, 0xc00011e198, 0xc000110420, 0xc00010e1e0, 0x411c58, 0x30, 0x970860, 0xc000160101)
        /home/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:262 +0x85
net/http.(*Server).Serve(0xc0001600e0, 0xa590e0, 0xc000130dc0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2981 +0x285
github.com/smallnest/rpcx/server.(*Server).startHTTP1APIGateway(0xc00012e000, 0xa590e0, 0xc000130dc0)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/gateway.go:79 +0x325
created by github.com/smallnest/rpcx/server.(*Server).startGateway
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/gateway.go:43 +0x348

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7fe2769b2eb0, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000128198, 0x72, 0x0, 0x0, 0x9bc8ab)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000128180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc000128180, 0x37e11d600, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00011e198, 0xc00006cf48, 0xc00006cf50, 0x28)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00011e198, 0x9e1210, 0xc0001220f0, 0xa5e760, 0xc0002fe0f0)
        /usr/local/go/src/net/tcpsock.go:261 +0x65
github.com/soheilhy/cmux.(*cMux).Serve(0xc0001220f0, 0x0, 0x0)
        /home/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:170 +0x96
created by github.com/smallnest/rpcx/server.(*Server).startGateway
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/gateway.go:46 +0x1c5

goroutine 8 [select]:
github.com/soheilhy/cmux.muxListener.Accept(0xa58db0, 0xc00011e198, 0xc000110300, 0xc00010e180, 0x411c58, 0x30, 0x970860, 0xc0001a6301)
        /home/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:262 +0x85
net/http.(*Server).Serve(0xc0001a62a0, 0xa590e0, 0xc000130da0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2981 +0x285
created by github.com/smallnest/rpcx/server.(*Server).startJSONRPC2
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/jsonrpc2.go:235 +0x1a9

goroutine 35 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x45

goroutine 50 [IO wait]:
internal/poll.runtime_pollWait(0x7fe2769b2ce0, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000f0418, 0x72, 0x400, 0x400, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f0400, 0xc0002fc000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0000f0400, 0xc0002fc000, 0x400, 0x400, 0x41c733, 0x7fe2769cfee8, 0x0)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000012130, 0xc0002fc000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:183 +0x91
github.com/soheilhy/cmux.(*bufferedReader).Read(0xc0001aa780, 0xc0002fc000, 0x400, 0x400, 0xc0002e5b38, 0x41bed3, 0x8)
        /home/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.5/buffer.go:53 +0x12d
github.com/soheilhy/cmux.(*MuxConn).Read(0xc0001aa770, 0xc0002fc000, 0x400, 0x400, 0x203000, 0x203000, 0x7fe2a08c1a10)
        /home/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:297 +0x4f
bufio.(*Reader).Read(0xc0002e80c0, 0xc00037c030, 0x1, 0xc, 0xc000034a20, 0x60, 0x50)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0xa50800, 0xc0002e80c0, 0xc00037c030, 0x1, 0xc, 0x1, 0xc0002e5c28, 0x411c58, 0x60)
        /usr/local/go/src/io/io.go:328 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
github.com/smallnest/rpcx/protocol.(*Message).Decode(0xc000034a20, 0xa50800, 0xc0002e80c0, 0x0, 0x0)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/protocol/message.go:423 +0x7a
github.com/smallnest/rpcx/server.(*Server).readRequest(0xc00012e000, 0xa5a0e0, 0xc00011e018, 0xa50800, 0xc0002e80c0, 0xc0001aa770, 0xc00011e018, 0x0)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:566 +0xbe
github.com/smallnest/rpcx/server.(*Server).serveConn(0xc00012e000, 0xa5e658, 0xc0001aa770)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:400 +0x2bd
created by github.com/smallnest/rpcx/server.(*Server).serveListener
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:316 +0x239

goroutine 2184 [IO wait]:
internal/poll.runtime_pollWait(0x7fe2769b2bf8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000f0018, 0x72, 0x400, 0x400, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f0000, 0xc0002fc400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0000f0000, 0xc0002fc400, 0x400, 0x400, 0xc0000b4b40, 0x240, 0x220)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000012070, 0xc0002fc400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:183 +0x91
github.com/soheilhy/cmux.(*bufferedReader).Read(0xc0001aa010, 0xc0002fc400, 0x400, 0x400, 0xc0002e0b68, 0x5738c818, 0x8)
        /home/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.5/buffer.go:53 +0x12d
github.com/soheilhy/cmux.(*MuxConn).Read(0xc0001aa000, 0xc0002fc400, 0x400, 0x400, 0x203000, 0x203000, 0xc0002e0bb8)
        /home/gopath/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:297 +0x4f
bufio.(*Reader).Read(0xc000110960, 0xc0003020a0, 0x1, 0xc, 0x60, 0x60, 0x9a0520)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0xa50800, 0xc000110960, 0xc0003020a0, 0x1, 0xc, 0x1, 0xc0002e0c28, 0x411c58, 0x60)
        /usr/local/go/src/io/io.go:328 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
github.com/smallnest/rpcx/protocol.(*Message).Decode(0xc000110ae0, 0xa50800, 0xc000110960, 0x0, 0x0)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/protocol/message.go:423 +0x7a
github.com/smallnest/rpcx/server.(*Server).readRequest(0xc00012e000, 0xa5a0e0, 0xc00011e060, 0xa50800, 0xc000110960, 0xc0001aa000, 0xc00011e060, 0x0)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:566 +0xbe
github.com/smallnest/rpcx/server.(*Server).serveConn(0xc00012e000, 0xa5e658, 0xc0001aa000)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:400 +0x2bd
created by github.com/smallnest/rpcx/server.(*Server).serveListener
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:316 +0x239

goroutine 1934 [runnable]:
sync.(*Map).Load(0xc000099470, 0x940800, 0xc0001af6c0, 0x9a39e0, 0x8e3ae0, 0x8e3ae0)
        /usr/local/go/src/sync/map.go:102 +0x30a
github.com/vmihailenco/msgpack/v5.(*structCache).Fields(0xc000099470, 0xa61730, 0x967600, 0x0, 0x0, 0xf4bda8)
        /home/gopath/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.4/types.go:80 +0x92
github.com/vmihailenco/msgpack/v5.encodeStructValue(0xc0002e8300, 0x967600, 0xc000082000, 0x199, 0xc000082000, 0x199)
        /home/gopath/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.4/encode_map.go:146 +0x87
github.com/vmihailenco/msgpack/v5.ptrEncoderFunc.func1(0xc0002e8300, 0x8e3ae0, 0xc000082000, 0x16, 0x8e3ae0, 0x7fe2769bdc08)
        /home/gopath/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.4/encode_value.go:129 +0xac
github.com/vmihailenco/msgpack/v5.(*Encoder).EncodeValue(0xc0002e8300, 0x8e3ae0, 0xc000082000, 0x16, 0x923580, 0x99bd00)
        /home/gopath/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.4/encode.go:239 +0x8e
github.com/vmihailenco/msgpack/v5.(*Encoder).Encode(0xc0002e8300, 0x8e3ae0, 0xc000082000, 0x7fe2769bdc08, 0xc000210450)
        /home/gopath/pkg/mod/github.com/vmihailenco/msgpack/v5@v5.3.4/encode.go:225 +0x126
github.com/smallnest/rpcx/codec.MsgpackCodec.Encode(0x8e3ae0, 0xc000082000, 0xc000120a40, 0x9e11b8, 0x8e3aa0, 0xc000034b40, 0x16)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/codec/codec.go:96 +0x148
github.com/smallnest/rpcx/server.(*Server).handleRequestForFunction(0xc00012e000, 0xa5a0e0, 0xc000010330, 0xc000111140, 0xc000136d70, 0xc000312060, 0xc00039c04c)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:732 +0x61b
github.com/smallnest/rpcx/server.(*Server).handleRequest(0xc00012e000, 0xa5a0e0, 0xc000010330, 0xc000111140, 0x0, 0x0, 0x0)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:608 +0x126a
github.com/smallnest/rpcx/server.(*Server).serveConn.func2(0xc00012e000, 0xc000111140, 0xc0002fe120, 0xa5e658, 0xc0001aa770)
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:482 +0x270
created by github.com/smallnest/rpcx/server.(*Server).serveConn
        /home/gopath/pkg/mod/github.com/smallnest/rpcx@v1.6.5/server/server.go:454 +0x465
`

**Comment by smallnest** [comment]
这个不应该啊，看错误信息是sync.Pool的错误，但是这个错误不应该出现。

https://github.com/golang/go/blob/0d1280c685c2353a9c982c11e77281ad4d34464a/src/sync/pool.go#L213

```go 
	allPoolsMu.Lock()
	defer allPoolsMu.Unlock()
```

- 你修改过标准库的代码？
- 你是什么环境?
- 问题是否可以重现？

**Comment by sirius65535** [comment]
谢谢大佬答疑！ 这两天排查发现是我自己代码写的有问题。

不过现在我发现，业务上client传送上百兆到1g的[]byte数据流（非文件）到server，通过top命令查看rpcx服务端那边占用的虚拟内存貌似一直不会释放，而且我用过的map也置为nil了，请问大佬这个是什么原因？

**Comment by smallnest** [comment]
这可能是rpcx server pool的问题

**Comment by smallnest** [comment]
fixed.  @sirius65535

**Comment by sirius65535** [comment]
> fixed. @sirius65535

好的大佬
