### ISSUE TITLE
RUnlock of unlocked RWMutex 

### ISSUE THREAD

**Issue by yundmb** [smallnest/rpcx#620]
v1.6.5版本 点对点直连的服务发现，服务端重启，双向通讯 100%复现 会报 sync: RUnlock of unlocked RWMutex 错误
切换到 v1.6.2 版本没有问题

**Comment by aspishk** [comment]
是v1.6.5中 client/client.go line:669的問題

```go
// v1.6.5
client.ServerMessageChanMu.RLock()
if client.ServerMessageChan != nil {
	client.handleServerRequest(res)
	client.ServerMessageChanMu.RUnlock()  //這句的問題
}
client.ServerMessageChanMu.RUnlock()
```

```go
// 可以改回v1.6.2的方法
client.ServerMessageChanMu.RLock()
if client.ServerMessageChan != nil {
	client.ServerMessageChanMu.RUnlock()
	go client.handleServerRequest(res)
} else {
	client.ServerMessageChanMu.RUnlock()
}
```

```go
// 又或直接由最後那句做UNLOCK
client.ServerMessageChanMu.RLock()
f client.ServerMessageChan != nil {
	client.handleServerRequest(res)
	//client.ServerMessageChanMu.RUnlock()  //這句的問題
}
client.ServerMessageChanMu.RUnlock()
```

**Comment by smallnest** [comment]
fixed. thanks

**Comment by yundmb** [comment]
@smallnest 好像没有修复完哦
`
	client.ServerMessageChanMu.RLock()
	if client.ServerMessageChan != nil {
		client.ServerMessageChanMu.RUnlock()
		req := protocol.NewMessage()
		req.SetMessageType(protocol.Request)
		req.SetMessageStatusType(protocol.Error)
		if req.Metadata == nil {
			req.Metadata = make(map[string]string)
			if err != nil {
				req.Metadata[protocol.ServiceError] = err.Error()
			}
		}
		req.Metadata["server"] = client.Conn.RemoteAddr().String()
		client.handleServerRequest(req)
	}
	client.ServerMessageChanMu.RUnlock()
`

**Comment by smallnest** [comment]
yes.fixed
