### ISSUE TITLE
consul、etcd plugin不能自动反注册

### ISSUE THREAD

**Issue by CcccFz** [smallnest/rpcx#621]
使用ConsulRegisterPlugin、EtcdRegisterPlugin
先注册两个服务，如下
![image](https://user-images.githubusercontent.com/11456678/128132804-ea89d254-4e5e-45b8-8708-ac9ff6172269.png)
之后停止其中一个服务，还是和上图一样。（等待、刷新，尝试多次）

-----

但是，ZooKeeperRegisterPlugin可以：
先注册两个服务，如下
![image](https://user-images.githubusercontent.com/11456678/128131825-476ee06b-5778-4eb4-a524-f5030a9e25b4.png)
之后停止其中一个服务，节点能自动删除
![image](https://user-images.githubusercontent.com/11456678/128132097-4f394d44-458c-4577-9341-1cc9c53ee1f6.png)

**Comment by smallnest** [comment]
等待一段较长的时间再观察。etcd/consul需要过期时间自动过期Expire
