### ISSUE TITLE
关于服务端超时时间问题

### ISSUE THREAD

**Issue by sirius65535** [smallnest/rpcx#624]
大佬你好，我在测试超时功能时发现，服务端的超时时间设置好像不生效，不管设置多长都是1分钟超时。不知是否是使用上的问题。

```
	s := server.NewServer(
		server.WithReadTimeout(time.Duration(120)*time.Second),
		server.WithWriteTimeout(time.Duration(120)*time.Second),
	)
```

**Comment by smallnest** [comment]
你需要贴一下你的客户端的设置以及你的报错信息。否则没办法分析问题。

client默认会有heartbeat(30秒)和keepalive(1分钟)保持连接活跃

**Comment by smallnest** [comment]
see the workable example:  https://github.com/rpcxio/rpcx-examples/tree/master/server_timeout

**Comment by sirius65535** [comment]
大佬好！感谢您亲自提供的例程，我的客户端设置如下：
```
    opts := client.DefaultOption
    opts.Heartbeat = true
    opts.HeartbeatInterval = time.Duration(2) * time.Second
    opts.IdleTimeout = time.Duration(90) * time.Second
    opts.ConnectTimeout = time.Duration(90) * time.Second
    opts.MaxWaitForHeartbeat = time.Duration(90) * time.Second
    opts.TCPKeepAlivePeriod = time.Duration(90) * time.Second
```
连接超时后，报错信息如下，属于正常的报错：
```
2021/08/13 12:32:05 server.go:408: WARN : rpcx: failed to read request: read tcp 192.168.11.189:8973->192.168.11.176:33782: i/o timeout
```

服务端使用的是centos，客户端使用的是ubuntu。

测试方法：服务端与客户端正常通信（客户端不断循环向服务端请求某个接口），然后将网络从物理层面直接断开，我的操作是直接关闭客户机的网卡或者拔网线。

经过这几天的测试发现，在centos上，不论服务端超时时间设置多久，在进行断网操作后，服务端几乎都是一分钟左右出现上述报错信息，正常应该是在设置的超时时间到了后出现上述超时报错信息；而在windows上跑服务端并进行上述测试则不存在这个情况，设置多久超时 就是多久报超时错误，可能是各个平台底层的TCP链路设置不同的原因。

**Comment by smallnest** [comment]
可能是tcpkeepalive设置的问题，你尝试设置为0看看。不同的操作系统可能处理不同
