### ISSUE TITLE
如何捕获客户端连接及断开

### ISSUE THREAD

**Issue by ChenMoGe2** [smallnest/rpcx#626]
在双向通信的例子中，并没有写出客户端连接和断开的捕获，如果想主动推送，肯定需要建立一个map对连接进行维护。但是必须要在客户端断开是删除对应的key，否则内存会无限增大，请问如何解决这个问题

**Comment by ChenMoGe2** [comment]
使用插件即可

**Comment by joshuafc** [comment]
> 使用插件即可

请问你使用的什么插件

**Comment by smallnest** [comment]
实现 PostConnClosePlugin interface 
https://github.com/smallnest/rpcx/blob/master/server/plugin.go#L67

**Comment by smallnest** [comment]
@joshuafc
