### ISSUE TITLE
rpc 服务端自动重启

### ISSUE THREAD

**Issue by nanyounanyounan** [smallnest/rpcx#643]
liunx command nohup ./xxx &
result:

2021/10/02 21:57:00 server.go:198: INFO : server pid:11502
2021/10/02 21:58:22 server.go:958: INFO : restart a new rpcx server: 11713
2021/10/02 21:58:25 server.go:900: INFO : shutdown begin
2021/10/02 21:58:25 gateway.go:81: INFO : gateway server closed
2021/10/02 21:58:25 server.go:990: INFO : need handle in-processing msg size:0
2021/10/02 22:29:40 server.go:198: INFO : server pid:15902
2021/10/02 22:43:00 server.go:958: INFO : restart a new rpcx server: 17567
2021/10/02 22:43:00 server.go:198: INFO : server pid:17567
listen tcp 127.0.0.1:8972: bind: address already in use
2021/10/02 22:43:03 server.go:900: INFO : shutdown begin
2021/10/02 22:43:03 gateway.go:81: INFO : gateway server closed
2021/10/02 22:43:03 server.go:990: INFO : need handle in-processing msg size:0
http: Server closed

**Comment by nanyounanyounan** [comment]
![image](https://user-images.githubusercontent.com/32302366/135742907-d83abef7-0a21-482a-8606-9b7d3edb70fc.png)

- [ ]

**Comment by smallnest** [comment]
问题？

看到你日志有这么一句：

```
listen tcp 127.0.0.1:8972: bind: address already in use
```
你必须使用`reuseport`。


我测试rpcx-examples,没问题。

![image](https://user-images.githubusercontent.com/865763/136171263-f9d85341-aaad-4c96-9318-8549eba90839.png)

**Comment by nanyounanyounan** [comment]
我用的是tcp,tcp也是会这样,还是要开启reuseport

**Comment by smallnest** [comment]
对，而且不需要自己调用Restart
