### ISSUE TITLE
Support wasm clients written in golang

### ISSUE THREAD

**Issue by gedw99** [smallnest/rpcx#654]
I have not tried to compile the client to wasm yet 

i think that go build tags for “ wasm “. 

https://github.com/nhooyr/websocket Supports wasm . Been working for me

**Comment by smallnest** [comment]
I do not get your problem. If you want to visit rpcx services, you can use websocket. rpcx supports websocket

**Comment by gedw99** [comment]
yeah sorry, i was tired and did not explain it well....

I am using a golang wasm client, and i know that the current web socket wont work with wasm.
been through it many times. https://github.com/nhooyr/websocket  does works

then i can code gen the front end golang code to talk to the backend rpcx code.
the ability to generate golang structs from json you already have too.
