### ISSUE TITLE
startShutdownListener 问题

### ISSUE THREAD

**Issue by qiannianshaonian** [smallnest/rpcx#657]
func (s *Server) Serve(network, address string) (err error) {
	s.startShutdownListener() // TODO 我在启动rpcx服务时候，服务的停止不需要重启链接的监听，目前docker stop 时候，会restart链接
	var ln net.Listener
	ln, err = s.makeListener(network, address)
	if err != nil {
		return
	}

	if network == "http" {
		s.serveByHTTP(ln, "")
		return nil
	}

	if network == "ws" || network == "wss" {
		s.serveByWS(ln, "")
		return nil
	}

	// try to start gateway
	ln = s.startGateway(network, ln)

	return s.serveListener(ln)
}

**Comment by smallnest** [comment]
fixed. Removed configured restart functions
