### ISSUE TITLE
RemoveWatcher方法的作用

### ISSUE THREAD

**Issue by Jun10ng** [smallnest/rpcx#658]
hi master，
由于公司项目内使用了历史版本的RPCX，我正在对照老版本的bug修复commit，我看到了以下这个新增RemoveWatcher方法的issue，
我不是很明白在什么情况下会触发这个bug，已经新增的RemoveWatcher方法是如何解决问题的。
https://github.com/smallnest/rpcx/issues/186

十分感谢！

**Comment by Jun10ng** [comment]
@smallnest

**Comment by smallnest** [comment]
bug已经描述了。在Discovery共享的情况下， 某个client close不再使用的时候应该把自己从Discovery移出

https://github.com/smallnest/rpcx/commit/454b64a51a455382d6652293357a50c3209725a5#diff-b107d948e2b395c2f9eca398733517e29af92082c426f2d3e2cebbea125afe7cR560
