### ISSUE TITLE
Avoid lazy init of client.pending

### ISSUE THREAD

**Issue by SericaLaw** [smallnest/rpcx#666]
The lazy init appears in 2 send methods of `Client`. While being user-friendly, I think it's hurting the performance since the CPU's branch operation is expensive.

https://github.com/smallnest/rpcx/blob/fff4bc1fd6337a6b3aa288c1185b4b961a82ccee/client/client.go#L410-L412

https://github.com/smallnest/rpcx/blob/fff4bc1fd6337a6b3aa288c1185b4b961a82ccee/client/client.go#L534-L536

However, removing the lazy init by asking users to create `Client` using `client.New` will change the way of how users are using the `Client`, and also introduce the need to modify the document.

So you can decide whether or not to make the change.

**Comment by smallnest** [comment]
暂不修改
