### ISSUE TITLE
go 1.6 兼容性问题

### ISSUE THREAD

**Issue by tangjiemian** [smallnest/rpcx#669]
\pkg\mod\github.com\smallnest\rpcx@v1.6.11\server\gateway.go:67:22: cannot convert *s.corsOptions (type CORSOptions) to type cors.Options
\pkg\mod\github.com\smallnest\rpcx@v1.6.11\server\jsonrpc2.go:227:22: cannot convert *s.corsOptions (type CORSOptions) to type cors.Options

**Comment by smallnest** [comment]
贴一下你的go.mod中是不是指定了cors库，版本是多少

**Comment by tangjiemian** [comment]
就第一次运行 go get -u -v -tags "reuseport quic kcp zookeeper etcd consul ping" github.com/smallnest/rpcx/... 没有指定库的版本

**Comment by tangjiemian** [comment]
我的go 版本是 1.16

**Comment by tangjiemian** [comment]
![image](https://user-images.githubusercontent.com/15653245/147776484-60054593-0f3c-4355-ad7b-68472f3fbcc8.png)

**Comment by tangjiemian** [comment]
![image](https://user-images.githubusercontent.com/15653245/147776672-9a02004b-1449-4b7d-8660-b603ebd62df2.png)

**Comment by smallnest** [comment]
可以推断你没有启用go module导致。现在go111module=on已经是标配了。

rpcx v1.6.11使用的cors1.7.x，和corsv1.8.2不兼容，如果你使用go module就没有问题。

自rpcx v1.7.1之后cors的版本已经提升到了v1.8.2
