### ISSUE TITLE
how install rpcx？

### ISSUE THREAD

**Issue by xjjrocker** [smallnest/rpcx#67]
$ go get github.com/smallnest/rpcx
不成功，只有空 文件夹rpcx！案例没法跑！
从grpc和rpcx对比，想尝试两者在使用上的区别和自己测试性能，无奈，文档很不完善，用不了。
你也没提供安装方法。

**Comment by smallnest** [comment]
go get -u github.com/smsllnest/rpcx/...

raad the readme and the ebook.

make sure you can visit golang.org without GFW issue.

see examples and benchmark directories
