### ISSUE TITLE
rpcx 如何做为一个普通的tcp服务器使用。

### ISSUE THREAD

**Issue by tangjiemian** [smallnest/rpcx#670]
看完文档后，我不知道如何做一个承载其它语言的client端的使用。比如：一个承载其它语言的网关

**Comment by smallnest** [comment]
它不是一个类似java/netty一样的网络框架，
而是一个rpc/微服务框架，用来为微服务之间进行调用的框架。
如果其他语言作为client,可以通过http/invoke方式调用微服务，只需要设置相应的header
