### ISSUE TITLE
cannot get services of from registry: %v, err: %v

### ISSUE THREAD

**Issue by ha666** [smallnest/rpcx#682]
os：macOS
rpcx version：v1.7.1

![3](https://user-images.githubusercontent.com/4374328/151537177-1c94e29a-61c9-487c-b4cb-42497c1b0b93.jpg)
![4](https://user-images.githubusercontent.com/4374328/151537213-76b700ba-9354-4e3b-abb7-e9fe27140b3f.jpg)
![5](https://user-images.githubusercontent.com/4374328/151537229-064f19ac-a965-4e74-8f28-9792934b31e0.jpg)

**Comment by smallnest** [comment]
fixed at https://github.com/rpcxio/rpcx-etcd
