### ISSUE TITLE
rpcx如何返回给客户端nil并且客户端接收时也为nil

### ISSUE THREAD

**Issue by ChenMoGe2** [smallnest/rpcx#686]
比如简单的数据库查询后返回结果，如根据ID查询user时，user没有查到，在server端返回nil。怎么让client端获取时为nil而不是&User{}

**Comment by supermario1990** [comment]
能贴下您的代码吗？

**Comment by smallnest** [comment]
这个并不太好实现。rpcx service端使用reflect去调用注册的函数，所以会生成一个零值。如果你没有设置，最终会把这个零值返回。

目前你可以使用下面两种方法让client知晓服务端未设置replay:
1. 在元数据中加一个标志
2. 更改reply的定义，增加一个flag

**Comment by ChenMoGe2** [comment]
@smallnest @supermario1990 谢谢已经实现了
目前的方式是通过在err里添加一个固定字符串实现
