### ISSUE TITLE
New a RPC Server 既可以单例，又可以NewServer?

### ISSUE THREAD

**Issue by 1046102779** [smallnest/rpcx#69]
![image](https://cloud.githubusercontent.com/assets/20457624/20776565/4c901dc4-b79c-11e6-9f87-66ef82ae6bed.png)

看源代码，既提供了一套采用defaultServer的调用方法列表，又给出了rpcx.Server的公开方法列表，其目的是什么？我想是不是直接server单实例，把rpcx.Server的公开方法列表变私有方法列表？

**Comment by 1046102779** [comment]
![image](https://cloud.githubusercontent.com/assets/20457624/20776609/9f576486-b79c-11e6-8a21-d8dc21855812.png)

然后rpcx/server.go 文件中存在大量的RCP, 是不是RPC？嘿嘿

**Comment by smallnest** [comment]
rcp写错了，应该是RPC. typo issue.

defaultServer为了提供一个简便的方法。类似官方库http的实现一样。
