### ISSUE TITLE
server gracefully shutdown 的读关闭会导致连接直接关闭退出

### ISSUE THREAD

**Issue by xiaoshi100086** [smallnest/rpcx#696]
是看代码发现的问题，还未测试证实

server shutdown是 gracefully stop 的，即先进行读关闭，然后等待接受的请求处理完毕再完全关闭连接。 可见：https://github.com/smallnest/rpcx/blob/f781e94c5a90924454e249f7c04ef920a9136f77/server/server.go#L903
但读关闭会导致 read 返回 eof 错误，进而导致server的read loop退出
https://github.com/smallnest/rpcx/blob/f781e94c5a90924454e249f7c04ef920a9136f77/server/server.go#L393
该loop退出会触发连接完全关闭，根本不会等待请求是否处理完毕
https://github.com/smallnest/rpcx/blob/f781e94c5a90924454e249f7c04ef920a9136f77/server/server.go#L354

**Comment by xiaoshi100086** [comment]
参考dubbo优雅停机的实现，https://dubbo.apache.org/zh/docs/v2.7/user/examples/graceful-shutdown/#%E5%8E%9F%E7%90%86
可以在优雅停止前先设置请求“挡板”，新的请求会直接拒绝并返回错误，然后在等待已接受请求完成处理并返回，最后关闭连接。
这样做的好处：
* 可以解决server read loop 因为EOF关闭连接的问题
* 相比于读关闭（读关闭并不会通知client，client发送的请求会等待超时或者等待server关闭连接报错），请求“挡板”可以及时告知client实际的错误，client可以重试其他服务实例。

**Comment by xiaoshi100086** [comment]
参考dubbo优雅停机的实现，https://dubbo.apache.org/zh/docs/v2.7/user/examples/graceful-shutdown/#%E5%8E%9F%E7%90%86
可以在优雅停止前先设置请求“挡板”，新的请求会直接拒绝并返回错误，然后在等待已接受请求完成处理并返回，最后关闭连接。
这样做的好处：
* 可以解决server read loop 因为EOF关闭连接的问题
* 相比于读关闭（读关闭并不会通知client，client发送的请求会等待超时或者等待server关闭连接报错），请求“挡板”可以及时告知client实际的错误，client可以重试其他服务实例。

**Comment by smallnest** [comment]
修改了。退出的时候确保已收到的已经被处理之后conn才会被关闭
