### ISSUE TITLE
Previous K/V pair exists

### ISSUE THREAD

**Issue by 15074072862** [smallnest/rpcx#697]
1.7版本rpcx 使用zk 作为注册发现中心，当快速重启服务时候，注册服务的时候会报错然后导致注册失败
 zookeeper.go:214: ERROR: cannot create zk path xxxx@xxxx:9001: Previous K/V pair exists, cannot complete Atomic operation
register err [Previous K/V pair exists, cannot complete Atomic operation

**Comment by smallnest** [comment]
thanks @supermario1990 for pullrequests
