### ISSUE TITLE
rpcx中的reply和args

### ISSUE THREAD

**Issue by yingyi666** [smallnest/rpcx#698]
官方文档中提到注册方法：
> 接受3个参数，第一个是 context.Context类型，其他2个都是可导出（或内置）的类型。

但是在我实际使用时我发现只能使用可导出的结构体，如果我使用内置类型会出现报错
```bash
#客户端爆出错误
2022/03/11 22:26:21 client.go:690: ERROR: rpcx: client protocol error:json: Unmarshal(nil *int)
```
![image](https://user-images.githubusercontent.com/41784264/157887209-3123f672-9b84-43cd-8c20-6a1ce9b87d72.png)

所以我现在很迷惑究竟是文档出问题还是我的代码书写有问题。。。。

**Comment by supermario1990** [comment]
I have tried it worked when reply is *int, below is my code:
server: 
```
package main

import (
	"flag"

	example "github.com/rpcxio/rpcx-examples"
	"github.com/smallnest/rpcx/server"
)

var addr = flag.String("addr", "localhost:8972", "server address")

func main() {
	flag.Parse()

	s := server.NewServer()
	// s.RegisterName("Arith", new(example.Arith), "")
	s.Register(new(example.Arith), "")
	s.Serve("tcp", *addr)
}

```

client: 
```
package main

import (
	"context"
	"flag"
	"log"
	"time"

	example "github.com/rpcxio/rpcx-examples"
	"github.com/smallnest/rpcx/client"
)

var (
	addr = flag.String("addr", "localhost:8972", "server address")
)

func main() {
	flag.Parse()

	d, _ := client.NewPeer2PeerDiscovery("tcp@"+*addr, "")
	xclient := client.NewXClient("Arith", client.Failtry, client.RandomSelect, d, client.DefaultOption)
	defer xclient.Close()

	args := &example.Args{
		A: 10,
		B: 20,
	}

	for {
		var reply int
		err := xclient.Call(context.Background(), "Mul", args, &reply)
		if err != nil {
			log.Fatalf("failed to call: %v", err)
		}

		log.Printf("%d * %d = %d", args.A, args.B, reply)
		time.Sleep(1e9)
	}

}

```


```
type Arith int

func (t *Arith) Mul(ctx context.Context, args *Args, reply *int) error {
	*reply = args.A * args.B
	fmt.Printf("call: %d * %d = %d\n", args.A, args.B, *reply)
	return nil
}
```

**Comment by yingyi666** [comment]
> I have tried it worked when reply is *int, below is my code: server:
> 
> ```
> package main
> 
> import (
> 	"flag"
> 
> 	example "github.com/rpcxio/rpcx-examples"
> 	"github.com/smallnest/rpcx/server"
> )
> 
> var addr = flag.String("addr", "localhost:8972", "server address")
> 
> func main() {
> 	flag.Parse()
> 
> 	s := server.NewServer()
> 	// s.RegisterName("Arith", new(example.Arith), "")
> 	s.Register(new(example.Arith), "")
> 	s.Serve("tcp", *addr)
> }
> ```
> 
> client:
> 
> ```
> package main
> 
> import (
> 	"context"
> 	"flag"
> 	"log"
> 	"time"
> 
> 	example "github.com/rpcxio/rpcx-examples"
> 	"github.com/smallnest/rpcx/client"
> )
> 
> var (
> 	addr = flag.String("addr", "localhost:8972", "server address")
> )
> 
> func main() {
> 	flag.Parse()
> 
> 	d, _ := client.NewPeer2PeerDiscovery("tcp@"+*addr, "")
> 	xclient := client.NewXClient("Arith", client.Failtry, client.RandomSelect, d, client.DefaultOption)
> 	defer xclient.Close()
> 
> 	args := &example.Args{
> 		A: 10,
> 		B: 20,
> 	}
> 
> 	for {
> 		var reply int
> 		err := xclient.Call(context.Background(), "Mul", args, &reply)
> 		if err != nil {
> 			log.Fatalf("failed to call: %v", err)
> 		}
> 
> 		log.Printf("%d * %d = %d", args.A, args.B, reply)
> 		time.Sleep(1e9)
> 	}
> 
> }
> ```
> 
> ```
> type Arith int
> 
> func (t *Arith) Mul(ctx context.Context, args *Args, reply *int) error {
> 	*reply = args.A * args.B
> 	fmt.Printf("call: %d * %d = %d\n", args.A, args.B, *reply)
> 	return nil
> }
> ```

Thank you. Now the problem that  I know it's my code, I'm going to fix it

**Comment by yingyi666** [comment]
> I have tried it worked when reply is *int, below is my code: server:
> 
> ```
> package main
> 
> import (
> 	"flag"
> 
> 	example "github.com/rpcxio/rpcx-examples"
> 	"github.com/smallnest/rpcx/server"
> )
> 
> var addr = flag.String("addr", "localhost:8972", "server address")
> 
> func main() {
> 	flag.Parse()
> 
> 	s := server.NewServer()
> 	// s.RegisterName("Arith", new(example.Arith), "")
> 	s.Register(new(example.Arith), "")
> 	s.Serve("tcp", *addr)
> }
> ```
> 
> client:
> 
> ```
> package main
> 
> import (
> 	"context"
> 	"flag"
> 	"log"
> 	"time"
> 
> 	example "github.com/rpcxio/rpcx-examples"
> 	"github.com/smallnest/rpcx/client"
> )
> 
> var (
> 	addr = flag.String("addr", "localhost:8972", "server address")
> )
> 
> func main() {
> 	flag.Parse()
> 
> 	d, _ := client.NewPeer2PeerDiscovery("tcp@"+*addr, "")
> 	xclient := client.NewXClient("Arith", client.Failtry, client.RandomSelect, d, client.DefaultOption)
> 	defer xclient.Close()
> 
> 	args := &example.Args{
> 		A: 10,
> 		B: 20,
> 	}
> 
> 	for {
> 		var reply int
> 		err := xclient.Call(context.Background(), "Mul", args, &reply)
> 		if err != nil {
> 			log.Fatalf("failed to call: %v", err)
> 		}
> 
> 		log.Printf("%d * %d = %d", args.A, args.B, reply)
> 		time.Sleep(1e9)
> 	}
> 
> }
> ```
> 
> ```
> type Arith int
> 
> func (t *Arith) Mul(ctx context.Context, args *Args, reply *int) error {
> 	*reply = args.A * args.B
> 	fmt.Printf("call: %d * %d = %d\n", args.A, args.B, *reply)
> 	return nil
> }
> ```

i have fix it
How stupid of me to use an empty int pointer instead of the address of int🤐
