### ISSUE TITLE
rpcx使用过程中，容易出问题的地方

### ISSUE THREAD

**Issue by 1046102779** [smallnest/rpcx#70]
![image](https://cloud.githubusercontent.com/assets/20457624/20776810/d1ce53ce-b79d-11e6-9484-d652db0eadfc.png)

在rpc server提供的服务列表中，返回参数error，如果服务是用的多实例，如果error返回不为空，则rpc client连接容易出现shutdown，所以我每次都要在服务方法体第一行中写“ var err error ;  defer err =nil”, 感觉怪怪的

**Comment by smallnest** [comment]
因为rpcx基于官方库net/rpc,所以要求服务的方法必须遵循一定的规则。我考虑以后fork这个官方库以便扩展功能，或者提供一些辅助办法绕过去。 Thanks.

> Only methods that satisfy these criteria will be made available for remote access;
> 	other methods will be ignored:
> 		- the method's type is exported.
> 		- the method is exported.
> 		- the method has two arguments, both exported (or builtin) types.
> 		- the method's second argument is a pointer.
> 		- the method has return type error.
> 	In effect, the method must look schematically like
> 		func (t *T) MethodName(argType T1, replyType *T2) error
