### ISSUE TITLE
双向通讯问题

### ISSUE THREAD

**Issue by hydaizd** [smallnest/rpcx#702]
```go
for i := 0; i < 100; i++ {
    logger.Debugf("start to send messages %d to %s\n", i, tools.ClientConn.RemoteAddr().String())
    err := s.SendMessage(tools.ClientConn, "SpiderPlugin", "Entry", nil, []byte("abcde"))
    if err != nil {
	    logger.Errorf("failed to send messsage to %s: %v\n", tools.ClientConn.RemoteAddr().String(), err)
	    tools.ClientConn = nil
    }
    time.Sleep(time.Second)
}
```
如果将代码行：time.Sleep(time.Second) 去掉的话，则会报错：
ServerMessageChan may be full so the server request 2 has been dropped
加上time.Sleep(time.Second) 则获取消息正常，这个休眠时间是必须加的么？有没有什么办法规避这个问题，因为大批量发送消息时，如果加上这个休眠时间，效率太低了。

**Comment by hydaizd** [comment]
没来得及消费的消息，再次发送的话不应该会阻塞么，现在是直接给出这个提示信息，并将消息丢弃了。

**Comment by hydaizd** [comment]
后续有计划用什么好的方案解决这个问题吗？因为增大容量的话也不知道增大多少合适，因为消息的量也是一个不确定因素。如果消息的量超过设置的最大容量则会产生消息丢弃，无法保证数据的一致性。

**Comment by supermario1990** [comment]
> 后续有计划用什么好的方案解决这个问题吗？因为增大容量的话也不知道增大多少合适，因为消息的量也是一个不确定因素。如果消息的量超过设置的最大容量则会产生消息丢弃，无法保证数据的一致性。

可以增加一个设置，当channel满了生产者阻塞。这两天我来实现这个feature，好了我通知你，谢谢

**Comment by supermario1990** [comment]
set BidirectionalBlock true to ensure massage not be dropped
```
defaultOption := client.DefaultOption
defaultOption.BidirectionalBlock = true
```

**Comment by hydaizd** [comment]
好的，我试下，非常感谢
