### ISSUE TITLE
如何在发起连接的时候监听连接失败的情况

### ISSUE THREAD

**Issue by BigCatGit** [smallnest/rpcx#704]
**### 如何在发起连接的时候监听连接失败的情况**
    // ConnCreatedPlugin is invoked when the client connection has created.
    func (_this *Client) ConnCreated(conn net.Conn) (net.Conn, error) 
    
    // ClientConnectedPlugin is invoked when the client has connected the server.
    func (_this *Client) ClientConnected(conn net.Conn) (net.Conn, error) 
    
    // ClientConnectionClosePlugin is invoked when the connection is closing.
    func (_this *Client) ClientConnectionClose(conn net.Conn) error 
测试了，只有连接成功会有回调，但是连接失败的情况下没找到相关的回调函数，除了通过发送消息来确认失败的结果，请问还有别的办法吗?

**Comment by supermario1990** [comment]
客户端连接失败会返回error，你直接判断error进行处理就行了。有什么场景是一定要在回调函数中处理的吗？

**Comment by smallnest** [comment]
dial一个节点的时候,如果有failover,错误信息可能暴露不出来。增加了一个插件，如果你关注client连接情况，可以实现这个插件

**Comment by super-l** [comment]
端口被占用或者无效，无法抛出错误信息，这种情况如何处理？
