### ISSUE TITLE
功能建议：能否让rpcx支持apisix网关呢

### ISSUE THREAD

**Issue by flash520** [smallnest/rpcx#709]
rpcx是一个很棒的框架，我现在正在学习使用它，并且尝试在我们自己的系统上进行验证，但就目前而言，我们团队开发的服务通常有多种语言组成，对于网关apisix是一个错的选择，但是apisix现在提供的transcode只支持grpc，如果也能支持rpcx那就太棒了。 @smallnest

**Comment by smallnest** [comment]
我不了解lua，所以不会去实现apisix的rpcx插件，我非常欢迎你能实现apisix的rpcx插件,或者熟悉lua的同学实现一个，类似grpc。

即使没有lua实现的rpcx插件，我认为你也可以实现通过apisix访问rpcx,因为rpcx支持http访问，你只需在apisix网关上配置http服务即可

**Comment by flash520** [comment]
@smallnest 是的，目前就要转一次 @supermario1990 太好了，期待中
