### ISSUE TITLE
如何捕获当前服务协程的panic

### ISSUE THREAD

**Issue by ChenMoGe2** [smallnest/rpcx#711]
在main中写
```
defer func() {
        if err := recover(); err != nil {
            fmt.Println("is panic")
        }
}()
```
只能捕获到main里的panic，无法捕获到当前调用接口所在协程的panic。请问rpcx有什么方法可以捕获到当前协程的任意panic并输出到zap的log模块中吗

**Comment by ChenMoGe2** [comment]
@supermario1990 
谢谢，我看到打印到日志框架了，但是这个并不会输出到文件中，我是使用zap的日志框架，希望能用zap拦截到panic信息。程序没有直接崩溃。

**Comment by supermario1990** [comment]
你把zap包装一下，实现rpcx中的Logger接口，然后使用log.SetLogger()方法就能使用zap打日志了

**Comment by ChenMoGe2** [comment]
@supermario1990 好的谢谢
