### ISSUE TITLE
Why not DoPreWriteResponse() and DoPostWriteResponse()?

### ISSUE THREAD

**Issue by zltl** [smallnest/rpcx#713]
I notice that s.Plugins.DoPreWriteResponse() and s.Plugins.DoPostWriteResponse() appear before most return statement, but not before s.auth() call. Can anyone explain why?

https://github.com/smallnest/rpcx/blob/e264d94076a9e626a10c56075715bd059de4f340/server/gateway.go#L151-L154

I want to census rpcx errors on my plugin.

**Comment by smallnest** [comment]
It is a bug. This plugins should keep consistent.
