### ISSUE TITLE
普通的tcp客户端要访问服务需要怎么处理

### ISSUE THREAD

**Issue by hydaizd** [smallnest/rpcx#714]
由于之前的tcp服务是用的原生的方式自己实现的，给外部tcp客户端调用，外部tcp客户端是用c++实现的。现在想把tcp服务端改用rpcx框架实现，但这样一来，如何在不修改客户端的情况下，能够调用到rpcx的tcp服务呢？有没有相应的解决方案可供参考？

**Comment by smallnest** [comment]
那没太大意义，因为客户端还是老的客户端，协议也不是rpcx的协议。没法享受服务治理的红利。

**Comment by hydaizd** [comment]
如果可以修改c++客户端代码，那c++客户端如何调用rpcx服务呢，有没有相关文档可供参考，示例代码都是用go做客户端来调用的。

**Comment by smallnest** [comment]
rpcx主要还是go语言的，其它语言部分实现了rpcx功能。 我所知道的rpcx-java已废弃，rpcx-rs并没有实现双向流，还有一些php的实现。

如果你用C++实现，可以参考 https://doc.rpcx.io/part5/protocol.html ，这是 rpcx的协议

**Comment by fitlivingmm** [comment]
我理解的是需要实现类似于tcp版本rpcx-gateway，其他可以参考https://github.com/rpcxio/rpcx-gateway http版本。我们也是有需要，所以实现tcp 版本rpcx-gateway，参考http版本rpcx-gateway很小改动就实现了。
