### ISSUE TITLE
discuss: does distributed transactions needed in rpcx?

### ISSUE THREAD

**Issue by supermario1990** [smallnest/rpcx#715]

**Comment by smallnest** [comment]
虽然分布式事务并不是微服务框架中的内容，但是在实际产品开发中，微服务框架经常会和分布式事务框架结合。

我建议无侵入的提供和分布式事务框架的例子，比如 [dtm](https://github.com/dtm-labs/dtm), go-zero等框架都提供结合。

如果没有办法做到无侵入，那么可以尽量已插件的方式提供结合，尤其是dtm框架。

总结一下，rpcx提供分布式事务的能力是很有必要的

**Comment by supermario1990** [comment]
感谢回复。我一直在想把dtm引入到rpcx框架中来

**Comment by smallnest** [comment]
感谢你一直以来对rpcx的贡献。
欢迎你有时间能提供rpcx和dtm的结合的能力。

**Comment by supermario1990** [comment]
> 感谢你一直以来对rpcx的贡献。 欢迎你有时间能提供rpcx和dtm的结合的能力。

ok，最近我想下怎么实现

**Comment by smallnest** [comment]
缺乏强烈需求，暂时关闭
