### ISSUE TITLE
rpcx 如何监听客户端加入和离线？

### ISSUE THREAD

**Issue by sairson** [smallnest/rpcx#719]
我在服务端启动了rpcx的服务端并注册一些方法，现在，我想在客户端连接我的时候存储加入的客户端，在客户端离线的时候告知其他服务，客户端离线了，就像聊天室一样，我该怎么做？谢谢

**Comment by smallnest** [comment]
实现下面的插件

https://github.com/smallnest/rpcx/blob/master/server/plugin.go#L23
