### ISSUE TITLE
心跳请求能自定义参数和返回值吗？

### ISSUE THREAD

**Issue by hydaizd** [smallnest/rpcx#720]
看源码，客户端发送心跳的时候，请求参数和返回值是固定的，如果我想要自定义请求参数和返回值，要如何做？
```go
request := time.Now().UnixNano()
reply := int64(0)
ctx, cancel := context.WithTimeout(context.Background(), client.option.MaxWaitForHeartbeat)
err := client.Call(ctx, "", "", &request, &reply)
```

**Comment by smallnest** [comment]
不能。你为什么要通过heartbeat自定义呢，要实现什么需求？为什么不自己实现一个心跳服务呢？

**Comment by hydaizd** [comment]
因为对特定客户端有些特殊处理，我需要使用字符串来区别标识这个特别的客户端连接（不用ip来区别，因为ip是变动的），以便服务端处理。

**Comment by hydaizd** [comment]
其实就是想通过在心跳中设置元数据，用来区分不同的客户端连接，因为用ip的话无法区分，我需要一些有意义的字符串标识来区分不同的客户端连接。

**Comment by smallnest** [comment]
自己实现一个AgentService即可，定时的发送你自己的信息，不一定非要通过heartbeat传递。

或者client调用的时候，在元数据中增加client的信息
