### ISSUE TITLE
请教有关于xclient的问题

### ISSUE THREAD

**Issue by m40Jc001** [smallnest/rpcx#721]
请问我的单个服务 `RegisterName("A", &ServiceA{}) RegisterName("B", &ServiceB{})`

我在实作client端调用是否必须建立两个 `XClient`, 我是否能使用一个 XClient 实例来达到 rpc 源码 `client.Call("A.Hello", "hello", &reply) `, `client.Call("B.Hello", "hello", &reply)` 用同一个连线呼叫呢?  还是example里有我没注意的细节.

如果不行, 我是否该建立多个xclient 直到客户端退出? 

我该往哪下手呢？谢谢

**Comment by supermario1990** [comment]
目前好像是不行的，xclient必须和一个服务绑定。所以两个服务要两个xclient

**Comment by smallnest** [comment]
使用`OneClient`

**Comment by m40Jc001** [comment]
是我看的不够仔细, 谢谢大佬！
