### ISSUE TITLE
WeightedICMP 不生效

### ISSUE THREAD

**Issue by wydcocos** [smallnest/rpcx#724]
![image](https://user-images.githubusercontent.com/16483465/164675036-09a4847f-a36e-4586-8781-b98b3713cb72.png)
rtt计算出来的值一直为0，导致无效连接和有效连接都是最高权重

**Comment by supermario1990** [comment]
host 地址是什么？

**Comment by wydcocos** [comment]
在windows下测试的，就是随便输入的一个无效地址，我看ping的库，说是得调用pinger.run()，才能有时间。

**Comment by wydcocos** [comment]
在windows下测试的，就是随便输入的一个无效地址，我看ping的库，说是得调用pinger.run()，才能有时间。
