### ISSUE TITLE
resMetadata concurrent map writes

### ISSUE THREAD

**Issue by CaoPengflying** [smallnest/rpcx#728]
服务端返回错误时会向resMetaData中写入map，也就是说并发调用rpc服务并且出现error时会出现此问题
**client/client.go 300行**
[https://github.com/smallnest/rpcx/pull/723/files](url)

**Comment by smallnest** [comment]
一次调用只会处理一次，为什么会有并发问题。能提供一个测试场景么？

**Comment by CaoPengflying** [comment]
我们的业务场景是A服务 依赖B,C,D服务。没有顺序关系。会启用协程并发调用BCD，如果刚好BCD都返回了error，就会有并发写入的问题

**Comment by CaoPengflying** [comment]
简单复现  A循环调用B
当然这种情况最好B提供一个批量的处理接口，但是B已经有单个处理的接口，A不想等，并且循环次数不多，采用协程并发调用B的单个处理，刚好B都返回了error， 并发写入map,A发生 panic

**Comment by smallnest** [comment]
这是问题你的A如果调用B、C、D时，使用不同的ctx应该就能避免。

但是如果你因为某些原因，不是新生成的 ctx，这是时候就得加锁了。但是使用client级别的锁会严重影响性能，应该实现context级别的锁。比如放一把锁在context中。

**Comment by CaoPengflying** [comment]
ctx作为全链路上下文，不能用新的ctx
这个写入resMetaData我只发现了在返回error的时候会写入其他情况下并不会写入，是不是对性能不会有大的影响？如果有影响
那这里不推荐使用client的锁，直接创建一个新的锁？

**Comment by smallnest** [comment]
嗯，创建一个ctx scope级别的锁更合适

**Comment by CaoPengflying** [comment]
我目前的解决是 在client 里面新增了一个 `resMetaMutex sync.Mutex // ctx resMeta lock` 的属性，然后在ctx中的resMetadata写入的时候用这把锁
您觉得这种修改方式可以吗？有具体的修改方案吗？
您在使用过程中没有这种并发调用场景吗？我个人认为，一个请求对应一个ctx是合理的 ，然后这个请求里面并发调用多个rpc接口也是正常的场景呀

**Comment by smallnest** [comment]
我提交一个基于context的Locker, 基于client的Locker锁的粒度太大。你看看是否解决了你的问题
