### ISSUE TITLE
心跳机制如何触发重连

### ISSUE THREAD

**Issue by hydaizd** [smallnest/rpcx#731]
查看了源码，发现心跳机制只是检测连接是否关闭，并没有触发重连 ；如果服务端某个时间段异常再恢复时，客户端要在调用服务端方法的时候才会触发重连。在双向通信时，如果客户端一直没有调用服务端的方法，服务端还在往客户端吐数据，这时候客户端是收不到数据的，因为此时客户端并未与服务端连接。

**Comment by smallnest** [comment]
容我想想

**Comment by smallnest** [comment]
双向通讯时，如果客户端已经宕机或者关掉了连接，服务端是能够发现连接已断掉，如果再放客户端发送数据会失败的，发送不过去
