### ISSUE TITLE
高负载运行时，报错：requested lease not found

### ISSUE THREAD

**Issue by helisong427** [smallnest/rpcx#734]
服务发现方式使用的是etcdv3，当服务高负载运行时，报如下错：
"2022-05-18T02:45:06.341Z","{""level"":""warn"",""ts"":""2022-05-18T10:45:06.341+0800"",""logger"":""etcd-client"",""caller"":""v3@v3.5.2/retry_interceptor.go:62"",""msg"":""retrying of unary invoker failed"",""target"":""etcd-endpoints://0xc00162a000/192.168.18.115:2379"",""attempt"":0,""error"":""rpc error: code = NotFound desc = etcdserver: requested lease not found""}"
"2022-05-18T02:45:06.340Z","2022/05/18 10:45:06 etcdv3.go:92: WARN : can't get data of node: /services/match/tcp@192.168.18.169:19401, because of Key not found in store"

相关依赖库：
	github.com/smallnest/rpcx v1.7.3
	go.etcd.io/etcd/api/v3 v3.5.2
	go.etcd.io/etcd/client/v3 v3.5.2

是网络原因吗？还是续租不及时？又或者需要调整参数？ 望解答~~

**Comment by smallnest** [comment]
应该是续租不及时导致这个服务器节点从etcd中注销了。
延迟超过1秒就会注销，这个有点苛刻。

当前解决方案你可以改一下etcdv3的库，把time.Second改大一点,比如10秒，或者一分钟。

明天我会改造一下，把time.Second抽取成可配置的参数。

<img width="790" alt="image" src="https://user-images.githubusercontent.com/865763/169017790-2f30f7b8-4cdc-4172-8683-9ec7a436cfcc.png">

**Comment by helisong427** [comment]
非常感谢

> 应该是续租不及时导致这个服务器节点从etcd中注销了。 延迟超过1秒就会注销，这个有点苛刻。
> 
> 当前解决方案你可以改一下etcdv3的库，把time.Second改大一点,比如10秒，或者一分钟。
> 
> 明天我会改造一下，把time.Second抽取成可配置的参数。
> 
> <img alt="image" width="790" src="https://user-images.githubusercontent.com/865763/169017790-2f30f7b8-4cdc-4172-8683-9ec7a436cfcc.png">

非常感谢解答~~
