### ISSUE TITLE
share.Context Locker 未解决ctx ResMetaDataKey 的concurrent map write

### ISSUE THREAD

**Issue by CaoPengflying** [smallnest/rpcx#736]
由于 context.WithValue 修改了context树
`locker, ok := ctx.(sync.Locker)`
这里的ok永远都是false

**Comment by smallnest** [comment]
默认ctx 是shared.Context。 你代码中使用context.WithValue更改了ctx? 还是rpcx自己更改了？

**Comment by CaoPengflying** [comment]
rpcx自己改了
client/client.go:271

**Comment by smallnest** [comment]
fixed. 往context放入了一把锁

**Comment by CaoPengflying** [comment]
这样加锁，不行，没锁住
context 每次请求都是new出来的share.context，没有锁住这个resMetaData的这个map

**Comment by smallnest** [comment]
[汗]

**Comment by CaoPengflying** [comment]
是不是只能用client中的锁？

**Comment by smallnest** [comment]
再想想办法

**Comment by smallnest** [comment]
因为不清楚你具体的场景，盲猜是下面一行出现的问题：
https://github.com/smallnest/rpcx/blob/master/client/client.go#L239

如果你还有问题，建议你在下面的代码中补充一个你的类似的case:
https://github.com/rpcxio/rpcx-examples/tree/master/context_lock

**Comment by CaoPengflying** [comment]
上次在share.context中修改了 tagsLock 为指针后，会有空指针报错
https://github.com/rpcxio/rpcx-examples/tree/master/context_lock/server/server.go#L21
我在本地增加了tagsLock的初始化后，使用下述代码，并发调用还是会有并发问题
https://github.com/rpcxio/rpcx-examples/pull/32

**Comment by CaoPengflying** [comment]
xclient: 814行
进行wrapCall调用时将ctx 转换为了share.Context
但是在client：287行 又将ctx 转换为了Context
我理解是不是应该在wrapCall转为了share.Context后，在整个调用的生命周期内都是share.Context呢？
向context写入内容是不是也应该向share.Context 的tags写入尤其是share.ResMetaDataKey
在ctx 操作share.ResMetaDataKey这个map是怎么锁都锁不住的

**Comment by smallnest** [comment]
嗯。 在client中我已修改为如果是sharedContext,那么就保持使用这个sharedContext
