### ISSUE TITLE
refactor to improve performance

### ISSUE THREAD

**Issue by smallnest** [smallnest/rpcx#743]
rpcx一直在做着性能优化。
今年又到了一个新阶段，需要进一步的做性能提升

**Comment by niconical** [comment]
Maybe changing the send function to an asynchronous call can improve some performance
https://github.com/smallnest/rpcx/blob/adafbb9fa94827236ef9cb1f4dfd4f5c409970ff/client/client.go#L271
```go
client.send -> go client send
```
