### ISSUE TITLE
端口被占用或者无效，无法抛出错误信息，这种情况如何处理？

### ISSUE THREAD

**Issue by super-l** [smallnest/rpcx#744]
端口被占用或者无效，无法抛出错误信息，这种情况如何处理？

func runServer() error {
	flag.Parse()
	s := server.NewServer()
	s.RegisterName("DataRepeat", new(service.DataRepeat), "")
	s.AuthFunc = auth
	err := s.Serve("tcp", *addr)
	return err
}

比如端口号是1 , err 是 nil。不会显示错误信息

**Comment by supermario1990** [comment]
我这边在mac下测试，端口为1会报错，请问你是在什么环境下测试的？

**Comment by smallnest** [comment]
缺乏信息。正常如果端口被占用会抛出错误信息的
