### ISSUE TITLE
cannot convert *s.corsOptions (type CORSOptions) to type cors.Options

### ISSUE THREAD

**Issue by qinjinze** [smallnest/rpcx#746]
https://doc.rpcx.io/part1/server.html
Sample code for the server

# github.com/smallnest/rpcx/server
..\..\..\github.com\smallnest\rpcx\server\gateway.go:67:22: cannot convert *s.corsOptions (type CORSOptions) to type cors.Options
..\..\..\github.com\smallnest\rpcx\server\jsonrpc2.go:227:22: cannot convert *s.corsOptions (type CORSOptions) to type cors.Options

**Comment by smallnest** [comment]
看起来你使用的是老版本的rpcx和cors。
请确保使用最新的rpcx和相应的cors版本。 请检查你的go.mod中的版本
