### ISSUE TITLE
rpcx 支持mq协议吗？

### ISSUE THREAD

**Issue by xwinie** [smallnest/rpcx#75]
rpcx 是否有支持mq协议的例子？

**Comment by smallnest** [comment]
我的理解是MQ是消费-生产者模型，而RPC是Client-Server远程调用模型，两者的模型之间还是有很大的差异。可能你碰到了这样的需求，可以详细说说这个需求，看看能否实现你的需求？

**Comment by 1046102779** [comment]
![image](https://cloud.githubusercontent.com/assets/20457624/21044488/3a4b87ce-be37-11e6-9b33-82dc0dedd9cb.png)

**Comment by smallnest** [comment]
目前不支持。你可以考虑NSQ或者Kafka等MQ系统实现MQ的功能
