### ISSUE TITLE
getCachedClient 锁粒度问题

### ISSUE THREAD

**Issue by eaglc** [smallnest/rpcx#754]
c.mu.Lock()
generatedClient, err, _ := c.slGroup.Do(k, func() (interface{}, error) {
	return c.generateClient(k, servicePath, serviceMethod)
})
c.mu.Unlock()

generateClient默认超时时间是1s，如果服务器重启了，且在重启过程中有大量的客户端请求，那么会导致大量goroutine等待获取锁，时间会很久，在我们生产环境中甚至达到了10分钟。

另外，希望当一个client连续创建失败达到指定次数时，提供在selector中丢弃该client的功能（即条件满足后不再选择这个client），以提高系统的容错及快速恢复。

**Comment by lk-j** [comment]
遇到同样的问题

**Comment by smallnest** [comment]
修复了。 先前代码不合理。本来使用singleflight就好了，没必要再加锁。
这样不会有大量的goroutine都在抢这把锁。服务器异常情况下应该1秒就返回了。

第二个是个优化项，尝试实现了一下，还没有优雅的实现。现在要实现的话会破坏Selector接口向下兼容性，暂时不实现了。

anyway, 不会再有等待锁的问题
