### ISSUE TITLE
concurrent map read and map write on DownloadFileArgs.Meta[]

### ISSUE THREAD

**Issue by momiji** [smallnest/rpcx#755]
hi,

Got this error when my software based on rpcxio is under heavy load (not sure how to define heavy however...).

```
Aug 25 18:42:11 drproxy[47347]: fatal error: concurrent map read and map write
Aug 25 18:42:11 drproxy[47347]: goroutine 1611 [running]:
Aug 25 18:42:11 drproxy[47347]: runtime.throw({0x9ac422?, 0x0?})
Aug 25 18:42:11 drproxy[47347]: /opt/go/go1.18.5/src/runtime/panic.go:992 +0x71 fp=0xc000e8cc10 sp=0xc000e8cbe0 pc=0x435b71
Aug 25 18:42:11 drproxy[47347]: runtime.mapaccess1_faststr(0xc0022aa280?, 0xc0022aa280?, {0x9a07ed, 0xe})
Aug 25 18:42:11 drproxy[47347]: /opt/go/go1.18.5/src/runtime/map_faststr.go:22 +0x3a5 fp=0xc000e8cc78 sp=0xc000e8cc10 pc=0x414305
Aug 25 18:42:11 drproxy[47347]: main.(*FindService).DownloadHandler(0x0?, {0xa68370?, 0xc001248020}, 0xc00164a1e0)
Aug 25 18:42:11 drproxy[47347]: /home/xtian/drproxy.new.rpcx/rpc_find.go:42 +0x265 fp=0xc000e8cf88 sp=0xc000e8cc78 pc=0x88f705
Aug 25 18:42:11 drproxy[47347]: main.(*FindService).DownloadHandler-fm({0xa68370?, 0xc001248020?}, 0x0?)
Aug 25 18:42:11 drproxy[47347]: <autogenerated>:1 +0x3c fp=0xc000e8cfb8 sp=0xc000e8cf88 pc=0x89f69c
Aug 25 18:42:11 drproxy[47347]: github.com/smallnest/rpcx/server.(*FileTransfer).start.func2()
Aug 25 18:42:11 drproxy[47347]: /home/xtian/go/pkg/mod/github.com/smallnest/rpcx@v1.7.8/server/file_transfer.go:197 +0x32 fp=0xc000e8cfe0 sp=0xc000e8cfb8 pc=0x86cf32
Aug 25 18:42:11 drproxy[47347]: runtime.goexit()
Aug 25 18:42:11 drproxy[47347]: /opt/go/go1.18.5/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000e8cfe8 sp=0xc000e8cfe0 pc=0x465141
Aug 25 18:42:11 drproxy[47347]: created by github.com/smallnest/rpcx/server.(*FileTransfer).start
Aug 25 18:42:11 drproxy[47347]: /home/xtian/go/pkg/mod/github.com/smallnest/rpcx@v1.7.8/server/file_transfer.go:197 +0x4db
Aug 25 18:42:11 drproxy[47347]: goroutine 1 [select (no cases)]:
Aug 25 18:42:11 drproxy[47347]: main.doRun()
Aug 25 18:42:11 drproxy[47347]: /home/xtian/drproxy.new.rpcx/main.go:174 +0x65
Aug 25 18:42:11 drproxy[47347]: main.main()
Aug 25 18:42:11 drproxy[47347]: /home/xtian/drproxy.new.rpcx/main.go:102 +0x6aa
```

I'm simply read the DownloadFileArgs.Meta map, which is only used:
- server side: in download Handler, to read values from the map (rpc_find.go:42)
- server side: in PostCall to read one value from the map (does not appear here)
- client side: in WrapSelect to write the value used in PostCall (does not appear here)

I debugged, checked the code (including rpcx), ... and could not find anything or any idea, except this one:
- the map used for Meta "may be" shared by several calls, maybe coming from https://github.com/smallnest/rpcx/blob/master/server/server.go#L696 and later, where argv is get then put in the reflectTypePools
- the downloading feature is working by saving the argv in a token map, to be retrived later (after the put) by a second call, hence the argv may have be re-get by another request and shared.

Any thoughts or ideas?

**Comment by momiji** [comment]
I changed a little bit th serve.go file, to :
- copy argv into original_argv, to put back original_argv and not argv
- add a precall plugin on my code to clone (create a new one and copy content) when it is a download, to have argv!=original_argv
- redo my tests
No more concurrent map, no more issues.

I still have more tests to confirm this, but I think to have located the issue.

Of course the patch I made is... ugly at least, and requires a precall, but the idea was to test and not have a real solution.
I didn't figure yet of a good way to solve this, unless storing in the cachedTokens something else than the object, maybe it is possible to do a clone by reflaction, but this is far from my (newbie) golang knowledge.

I'll keep informed and confirm this once I have reviewed all the things, as I've made a lot of changes to track this issue since one week.

**Comment by momiji** [comment]
Line 395:
```
	// get a argv object from object pool
	argv := reflectTypePools.Get(mtype.ArgType)
	oargv := argv
```

Line 730:
```
	// return argc to object pool
	reflectTypePools.Put(mtype.ArgType, original_argv)
```

**Comment by momiji** [comment]
I finally applied a temporary fix, which consists in commenting the Line 731 to prevent to put back argv in the pool.
Even if it applies to all calls and not only file transfer/downloads, it works.

**Comment by smallnest** [comment]
Thanks. I will fix it.

**Comment by momiji** [comment]
Great!
Let me know when you have a first vesion of this fix, I'll be happy to test it.

**Comment by smallnest** [comment]
@momiji I have fixed it. You can check the v1.9.10

**Comment by momiji** [comment]
Nice, I love the way it's fixed!
Issue may be closed now.
