### ISSUE TITLE
中文官方文档中的一个单词拼写错误

### ISSUE THREAD

**Issue by sober-wang** [smallnest/rpcx#758]
### 文档链接
[docs_link](https://books.studygolang.com/go-rpc-programming-guide/part1/server.html)

<img width="1251" alt="图片" src="https://user-images.githubusercontent.com/35804630/192424115-c3f225dc-5910-4158-9ea3-2fbdb5cce97b.png">

我很想协助修改，但是我在页面上没有找到文档修改的 github 或其他仓库地址。所以只能来这里提一个 issue ，反馈一下。

**Comment by smallnest** [comment]
项目在 smallnest/go-rpc-programming-guide: gitbook Go RPC开发指南 [中文文档]
(github.com) <https://github.com/smallnest/go-rpc-programming-guide>

尚墨 ***@***.***> 于2022年9月27日周二 11:20写道：

**Comment by fitlivingmm** [comment]
https://rpcx.io/  大佬，显示证书无效

**Comment by smallnest** [comment]
renewed
