### ISSUE TITLE
服务高可用问题怎样解决？

### ISSUE THREAD

**Issue by liangsen** [smallnest/rpcx#76]
我在同一台机器上分别起了两个服务端（端口号不同），用客户端循环调用该服务，接下来我停掉其中的某个服务，客户端开始报connection is shut down，请问failover为什么未生效呢？

**服务端：**
  server2 := rpcx.NewServer()
  server2.RegisterName("Arith", new(Arith))
  server2.Serve("tcp", *address)

**客户端：**
server1 := clientselector.ServerPeer{Network: "tcp", Address: "127.0.0.1:8972"}
server2 := clientselector.ServerPeer{Network: "tcp", Address: "127.0.0.1:8973"}
servers := []*clientselector.ServerPeer{&server1, &server2}
s := clientselector.NewMultiClientSelector(servers, rpcx.RoundRobin, 1*time.Second)
for i := 0;; i++ {
     callServerSync(s)
}

func callServerSync(s rpcx.ClientSelector) {
	client := rpcx.NewClient(s)
	client.FailMode = rpcx.Failover
	args := &Args{9, 9}
	var reply Reply
	err := client.Call("Arith.Mul", args, &reply)
	if err != nil {
		fmt.Printf("error for Arith: %d*%d, %v \n", args.A, args.B, err)
	} else {
		fmt.Printf("Arith: %d*%d=%d \n", args.A, args.B, reply.C)
	}
	client.Close()
}

**Comment by smallnest** [comment]
停掉一台服务器没问题，它会调用另外一台。
但是当这台服务器重新起来的时候，client确没有把它加入到备选服务器中，这时候如果把另外一台服务器关掉，机会出现 “connection is shut down”的问题。

**Comment by smallnest** [comment]
fixed.

测试可用。

测试步骤,代码如描述中的服务器和客户端代码, FailMode同样是Failover:
1. 启动server1
2. 启动server2
3. 启动客户端，一直在调用
4. 关闭server2,发现客户端一直在调用server1
5. 重启server2,发现客户端通过RoundRobin轮询

**Comment by liangsen** [comment]
👍👍👍👍👍
