### ISSUE TITLE
应用退出后，注册中心etcd 不会自动注销，必须待租约到期

### ISSUE THREAD

**Issue by wzhsh90** [smallnest/rpcx#764]
应用退出后，注册中心etcd 不会自动注销，必须待租约到期

这个要怎么处理？

**Comment by smallnest** [comment]
应用退出的时候调用server.UnregisterAll

**Comment by wzhsh90** [comment]
不是调用ShutDown ?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smallnest/rpcx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 中午11:34
***@***.***&gt;;
抄送:&nbsp;"@***@***.******@***.***&gt;;
主题:&nbsp;Re: [smallnest/rpcx] 应用退出后，注册中心etcd 不会自动注销，必须待租约到期 (Issue #764)





 
应用退出的时候调用server.UnregisterAll

**Comment by smallnest** [comment]
不是

**Comment by wzhsh90** [comment]
现在用UnregisterAll 报错了
2022/11/15 11:48:42 Upgrade start: hangup
2022/11/15 11:48:45 tcp server: listen tcp :19190: bind: address already in use
2022/11/15 11:48:45 Upgrade succeeded


用shutdown 不会出现
19190: bind: address already in use









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smallnest/rpcx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 中午11:42
***@***.***&gt;;
抄送:&nbsp;"@***@***.******@***.***&gt;;
主题:&nbsp;Re: [smallnest/rpcx] 应用退出后，注册中心etcd 不会自动注销，必须待租约到期 (Issue #764)





 
不是
