### ISSUE TITLE
RegisterOnShutdown not work

### ISSUE THREAD

**Issue by wzhsh90** [smallnest/rpcx#765]
RegisterOnShutdown the code is not used.

**Comment by smallnest** [comment]
需要更多的信息或者例子

**Comment by wzhsh90** [comment]
RegisterOnShutdown&nbsp; 里面onShutdown slice 代码里面没有地方调用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smallnest/rpcx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 中午11:35
***@***.***&gt;;
抄送:&nbsp;"@***@***.******@***.***&gt;;
主题:&nbsp;Re: [smallnest/rpcx] RegisterOnShutdown not work (Issue #765)





 
需要更多的信息或者例子

**Comment by smallnest** [comment]
这是提供给用户用来注册退出的调用
