### ISSUE TITLE
关于typePools的疑问

### ISSUE THREAD

**Issue by supermario1990** [smallnest/rpcx#770]
https://github.com/smallnest/rpcx/blob/a6502f15435ef013eeeaf4227107bdcf5437833a/server/pool.go#L45
现在调用 typePools.Put，元素必须实现接口 Reset, 这样很多以前的使用typePools的地方其实是无法Put成功的，这样做是OK的吗？
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/8428531/205446913-069eca21-40c8-4cf1-a8d2-f311f5af897d.png">

**Comment by smallnest** [comment]
是的，设计是这样。原先都是使用pool,后来有用户使用有问题才改成这样。

因为request/response如果直接放回pool,可能会有问题。有可能相关的字段被设置了没有被清理，如果直接重用数据不对。
所以显示的要求用户实现Reset方法，负责清理这些对象

**Comment by supermario1990** [comment]
> 是的，设计是这样。原先都是使用pool,后来有用户使用有问题才改成这样。
> 
> 因为request/response如果直接放回pool,可能会有问题。有可能相关的字段被设置了没有被清理，如果直接重用数据不对。 所以显示的要求用户实现Reset方法，负责清理这些对象

谢谢鸟哥解答
