### ISSUE TITLE
getCachedClient 存在并发bug

### ISSUE THREAD

**Issue by mini-bix** [smallnest/rpcx#772]
https://github.com/smallnest/rpcx/blob/6d27bc7e40cf7ffdec0d9b2b4dac715b3dc1bdbd/client/xclient.go#L282-L338
上面这段代码存在并发问题，锁的使用存在问题，可能多个线程都拿到了nil的client， c.slGroup.Do似乎只能保证同时创建一个连接,但是c.slGroup.Forget之后可能创建出多个连接，导致连接泄露，创建一些不被使用的连接

**Comment by smallnest** [comment]
fixed. only forget k when the client is cached.

**Comment by supermario1990** [comment]
> fixed. only forget k when the client is cached.

我觉得改了之后还是有点问题，当 c.slGroup.Do() 中调用的函数返回后，还没缓存client前，这里仍然会创建一些不被使用的链接。 这里应该直接使用mutex来控制并发就行了

**Comment by smallnest** [comment]
> > fixed. only forget k when the client is cached.
> 
> 我觉得改了之后还是有点问题，当 c.slGroup.Do() 中调用的函数返回后，还没缓存client前，这里仍然会创建一些不被使用的链接。 这里应该直接使用mutex来控制并发就行了

这个应该修复了。
或者使用同一个singleflight key的结果，或者从cache中获取

**Comment by lk-j** [comment]
还是存在问题，当网络延时的时候    c.slGroup.Do(k, func() (interface{}, error) { 
 			return c.generateClient(k, servicePath, serviceMethod) 
 		})    k不一样，还是会生成大量连接

**Comment by smallnest** [comment]
> 还是存在问题，当网络延时的时候 c.slGroup.Do(k, func() (interface{}, error) { return c.generateClient(k, servicePath, serviceMethod) }) k不一样，还是会生成大量连接 直接使用mutex来控制并发更合理

你的rpcx的版本是？

**Comment by lk-j** [comment]
> > 还是存在问题，当网络延时的时候 c.slGroup.Do(k, func() (interface{}, error) { return c.generateClient(k, servicePath, serviceMethod) }) k不一样，还是会生成大量连接 直接使用mutex来控制并发更合理
> 
> 你的rpcx的版本是？

1.7.15
