### ISSUE TITLE
A question about the memory usage of rpcx framework

### ISSUE THREAD

**Issue by xiaolongz007** [smallnest/rpcx#775]
currently, with pprof, lots of memory is observed to be used by rpcx network IO which lies in the method of server.serveConn? I wonder if there is a way to optimize it? with QPS more than 15K, the application package is not large maybe 200 bytes, with msgPack encoding, the memory it used is 30G, which really is disgusting and unusable.

**Comment by xiaolongz007** [comment]
the running environment is K8s pod.

**Comment by smallnest** [comment]
Since you has pprof, you should watched which line took the large memory, can you attach the pprof result?
