### ISSUE TITLE
客户端如何等待进行中的请求都执行完成再安全关闭？

### ISSUE THREAD

**Issue by zhmm** [smallnest/rpcx#781]
场景：
程序a中消费mq中数据，再rpc远程调用服务b，
程序a在重启时候需要等xclient.call的所有都请求都执行完成再关闭，现在a程序a中已经监听信号，收到停止信号执行一系列操作，但是如何确保xclient.call正在进行中的这些请求都处理完成再停止服务？

**Comment by smallnest** [comment]
你可以使用一个计数器，调用前+1， 调用完减1. 
a收到停止信号检查计数器，等计数器变为0后可以安全退出
