### ISSUE TITLE
服务节点下线，注册中心未剔除，导致大量客户端超时

### ISSUE THREAD

**Issue by szlmbella** [smallnest/rpcx#784]
- 版本：v1.7.15
- 服务发现组件：consul 1.15 
- 问题
   服务节点下线，注册中心未剔除，导致大量客户端超时，且期间客户端设置的超时时间不起作用，手动剔除节点后服务才恢复正常。

**Comment by smallnest** [comment]
我部署一套环境测试下，在超过两倍的超时间后还没有反注册？

我更新了一下rpcx,让它正常退出的时候自动反注册，你也可以调用`UnregisterAll()`保证退出的时候反注册

**Comment by szlmbella** [comment]
设置了 200 ms 的超时时间，正常请求是生效的，上面这种情况有很多超过 1 s 的请求。

我更新下 rpcx，感谢大佬！

**Comment by szlmbella** [comment]
设置了 200 ms 的超时时间，正常请求是生效的，上面这种情况有很多超过 1 s 的请求。

我更新下 rpcx，感谢大佬！

**Comment by szlmbella** [comment]
设置了 200 ms 的超时时间，正常请求是生效的，上面这种情况有很多超过 1 s 的请求。

我更新下 rpcx，感谢大佬！

**Comment by szlmbella** [comment]
设置了 200 ms 的超时时间，正常请求是生效的，上面这种情况有很多超过 1 s 的请求。

我更新下 rpcx，感谢大佬！

**Comment by szlmbella** [comment]
设置了 200 ms 的超时时间，正常请求是生效的，上面这种情况有很多超过 1 s 的请求。

我更新下 rpcx，感谢大佬！
