### ISSUE TITLE
server start error

### ISSUE THREAD

**Issue by fate-zx** [smallnest/rpcx#785]
D:\sys\go\pkg\mod\github.com\smallnest\rpcx@v1.8.2\server\gateway.go:67:23: cannot convert *s.corsOptions (variable of type CORSOptions) to type cors.Options
D:\sys\go\pkg\mod\github.com\smallnest\rpcx@v1.8.2\server\jsonrpc2.go:232:23: cannot convert *s.corsOptions (variable of type CORSOptions) to type cors.Options

**Comment by smallnest** [comment]
nidgo.mod中cors的版本是多少

**Comment by fate-zx** [comment]
github.com/rs/cors v1.8.3 // indirect

**Comment by fate-zx** [comment]
> nidgo.mod中cors的版本是多少

github.com/rs/cors v1.8.3 // indirect

**Comment by ArkerX** [comment]
use: go get -u github.com/rs/cors@v1.8.2

**Comment by fate-zx** [comment]
> 使用：获取 -u github.com/rs/cors@v1.8.2

可以了，谢谢
