### ISSUE TITLE
同时调用同一个接口多次，会出现 rpcx: can't find service xxx 的错误

### ISSUE THREAD

**Issue by lixh00** [smallnest/rpcx#788]
问题如标题所示。
下面这两个请求都是页面加载的时候同时调的，只有一个成功返回了数据。请问是我参数设置的有问题还是一个BUG啊？
失败:
![image](https://user-images.githubusercontent.com/72033265/224946447-bd28bb21-7316-4f02-ae72-1bcb89ebb445.png)
成功: 
![image](https://user-images.githubusercontent.com/72033265/224946494-93ba189d-2632-40c0-befa-d4d82671a6e1.png)

rpcx版本: `v1.8.4`
Go版本: `1.20.2`

**Comment by smallnest** [comment]
我认为是你程序中的问题。你需要使用debug技术去分析。我怀疑是你参数设置错误，没有设置正确的服务名

**Comment by lixh00** [comment]
> 我认为是你程序中的问题。你需要使用debug技术去分析。我怀疑是你参数设置错误，没有设置正确的服务名

不应该啊，如果是服务名错了，那就不应该有成功的请求嘛，我追debug，没追到哪儿错了，很绝望

**Comment by lixh00** [comment]
rpcx调用失败，提示找不到服务
![image](https://user-images.githubusercontent.com/72033265/225181356-a9044b8f-0c1c-4bdd-bed8-5f551712f818.png)
nacos里面注册的服务详情，它是在线的
![image](https://user-images.githubusercontent.com/72033265/225181502-62490201-597e-4af2-9b9a-18482d5408b6.png)

**Comment by lixh00** [comment]
对不起，我的错！！
复制代码的时候有一个东西忘了改，变量名长得太像了，导致不同的client用了同一个Discovery。
非常抱歉，打扰您了！！！！！！
