### ISSUE TITLE
win下使用reuseport提供提示

### ISSUE THREAD

**Issue by summer-boythink** [smallnest/rpcx#798]
https://github.com/rpcxio/rpcx-examples/blob/master/reuseport/server/server.go

对于在windows下直接使用`reuseport`通信方式，会直接退出server

是否应该加一个提示，然后把`reuseport`方式，默认的改成普通`tcp`方式，保持其不退出

**Comment by smallnest** [comment]
这个不会。 如果用户使用`resuseport`应该了解resuseport的北京。 替换成tcp设置和运行就不一致了

**Comment by summer-boythink** [comment]
> 这个不会。 如果用户使用`resuseport`应该了解resuseport的北京。 替换成tcp设置和运行就不一致了

好的，感谢
