### ISSUE TITLE
EtcdRegisterPlugin 示例

### ISSUE THREAD

**Issue by leonardyp** [smallnest/rpcx#80]
rpcx/_examples/etcd_registry  的demo 为什么跑不起来呢？

提示:No Available Service     本地 etcd  有跑起来   单个实例2379端口

环境 mac pro

**Comment by smallnest** [comment]
以前版本的例子中有问题，最新的版本应该没有这个问题了。
我的测试版本也是mac pro,brew 重新安装了一个全新的etcd版本。

首先运行server: `go run server.go`,
再运行client: `go run client.go`, 运行正常：

```
Arith: 7*8=56
Arith: 7*8=56
Arith: 7*8=56
Arith: 7*8=56
Arith: 7*8=56
Arith: 7*8=56
Arith: 7*8=56
Arith: 7*8=56
Arith: 7*8=56
Arith: 7*8=56
Arith: 7*8=56
➜  etcd_registry git:(master)
```

**Comment by smallnest** [comment]
所以你go get -u github.com/smallnest/rpcx拉取最新的版本试一下

**Comment by leonardyp** [comment]
我找到问题了  etcd 问题 https://github.com/coreos/etcd/pull/7095
