### ISSUE TITLE
failed to dial server: dial tcp: missing address

### ISSUE THREAD

**Issue by mylxy** [smallnest/rpcx#802]
采用k8s做服务发现，做集群，比如A 服务扩展三个副本，A1,A2,A3 每个副本都是rpc Server及client，比如A1 client连接 A2,A3 server
client的初始化代码如下

c.xclient = client.NewXClient(surface.FishServerPath, c.config.FailMode, client.SelectByUser, c.discovery, client.DefaultOption)
c.xclient.SetSelector(NewFishSelector(c.event))

没有配置心跳，采用tcp协议传输，目前集群正，但  failed to dial server: dial tcp: missing address 这个warn告警日志特别多，请问为什么，告警日志期间，服务器也未发生重启，服务也未重新部署![image](https://user-images.githubusercontent.com/8554595/237026667-f81365b4-04e0-4c0f-9be9-c9d74ff21168.png)

**Comment by smallnest** [comment]
注册的node节点不对就会报这个问题。你是自己实现的注册discovery 和selector,看看你拼装的格式是啥
