### ISSUE TITLE
rpcx结合service mesh的案例

### ISSUE THREAD

**Issue by someview** [smallnest/rpcx#803]
有没有rpcx结合service mesh的案例
另外，rpcx的bidistream在做负载均衡的时候，怎么确保所有的消息都是传递到同一个serviceendpoint上呢

**Comment by fengyeall111** [comment]
另外，是否可以考虑proxyless这样的方案呢，对接envoy这样的反向代理，实现xds协议。
有个交流群更好

**Comment by smallnest** [comment]
交流群可以看readme的qq群。
目前没有实现xds协议的插件，我感觉在k8s上grpc更有优势，但是也非常欢迎大家能提供支持xds协议的插件
