### ISSUE TITLE
如何处理自定义error

### ISSUE THREAD

**Issue by westwin** [smallnest/rpcx#805]
假定自定义error类型为
type BizErr struct ｛
     Code, Message string
｝

rpcx服务端，业务代码实现时会抛出BizError，
那么客户端调用时怎么能够得到BizErr类型的error呢？

有没有类似于自定义error handler之类的机制？ 谢谢

**Comment by smallnest** [comment]
https://github.com/rpcxio/rpcx-examples/tree/master/error_customized
