### ISSUE TITLE
RPC Service主动抛非strErr错误

### ISSUE THREAD

**Issue by marslabtron** [smallnest/rpcx#806]
smallnest你好，

我使用rpcx开发了一主多从的raft服务，client采用MultipleTcpServersDiscovery，以及Failover失败模式，我希望client在访问到从节点时触发Failover；

目前service端返回错误都被作为strErr处理掉了，不会触发Failover，针对以上需求请教有何官方的解决方案?

**Comment by smallnest** [comment]
客户端实现 `ClientErrorFunc `,请参照 https://github.com/smallnest/rpcx/commit/0f372c4f24bac89e6f72a75039e636ba2b56cd8f#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09

**Comment by marslabtron** [comment]
> 客户端实现 `ClientErrorFunc `,请参照 [0f372c4#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09](https://github.com/smallnest/rpcx/commit/0f372c4f24bac89e6f72a75039e636ba2b56cd8f#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09)

`type ServiceError interface {
	Error() string
	IsServiceError() bool
}`

该接口定义的IsServiceError()并没有在任何地方用到，xclient.Call中在判断失败模式中`if _, ok := err.(ServiceError); ok { return error }` 是否需要判断一下IsServiceError()再renturn

**Comment by smallnest** [comment]
rpcx client默认把服务端返回的error包装成strErr, 它实现了ServiceError。

如果你的ClientErrorFunc返回你自定义的Err请记得实现ServiceError接口。

BTW, 我会在rpcx-examples增加一个使用定制err的例子。

**Comment by smallnest** [comment]
rpcx需要扩展下,待我想想

**Comment by marslabtron** [comment]
> rpcx需要扩展下,待我想想

多谢回复。以下是我的一些理解：

服务端错误大致可分为“通用服务错误类型” 和 “服务错误类型”：
- 通用服务错误类型（ServiceError）：即代码中已定义的ServiceError接口，这类错误不被client捕获，延续当前逻辑直接交给用户逻辑处理，允许用户代码中自行实现接口，比如之前有issue提到是否可以类似 ErrorCode 这样的错误，完全可以自行定义；
- 服务错误类型（ServerError）：定义一系列官方的错误类型，比如ServerUnexpectedError、ServerAccessDenied、ServerAuthorizeError；这些错误类型不被当作ServiceError直接交给用户代码，而是直接被client捕获，并执行相应逻辑，比如failover

以上观点如有理解有误的地方，还请指点。

**Comment by smallnest** [comment]
我应该fix,如果还没有修复，请reopen它
