### ISSUE TITLE
编码方式为 protocol.SerializeNone时调用异常

### ISSUE THREAD

**Issue by shinxiang** [smallnest/rpcx#809]
我想实现的目的是， 不使用序列化，直接传递 []byte 数据流，代码如下：
server.go
```
type Arith struct{}

func (t *Arith) Echo(ctx context.Context, args []byte, reply *[]byte) error {
	copy(*reply, args)
	log.Printf("%v, %v", args, reply)
	return nil
}

func main() {
	s := server.NewServer()
	s.RegisterName("Arith", new(Arith), "weight=3")
	s.Serve("tcp", "localhost:8972")
}
```

client.go
```
func main() {
	d, _ := client.NewPeer2PeerDiscovery("tcp@localhost:8972", "")
	option := client.DefaultOption
	option.SerializeType = protocol.SerializeNone
	xclient := client.NewXClient("Arith", client.Failtry, client.RandomSelect, d, option)
	defer xclient.Close()
	
	args := []byte{0x00, 0x01, 0x02}
	reply := make([]byte, 0)
	xclient.Call(context.Background(), "Echo", args, &reply)
	log.Printf("%v, %v", args, reply)
}
```

server.go代码调试时 Echo函数参数reply 为nil

**Comment by smallnest** [comment]
copy内建函数使用时，要求dst必须预分配足够的容量，比如：
![d2618ff47476f4541345b5e7af9c61c4](https://github.com/smallnest/rpcx/assets/865763/e4add18e-80a8-4e2f-8994-91b2488ea55f)

**Comment by shinxiang** [comment]
按你的建议，更正server.go代码
func (t *Arith) Echo(ctx context.Context, args []byte, reply *[]byte) error {
	*reply = make([]byte, 1024)
	n := copy(*reply, args)
	*reply = (*reply)[:n]
	return nil
}

依然报错，信息如下：
panic: reflect: reflect.Value.SetBytes using unaddressable value

goroutine 66 [running]:
reflect.flag.mustBeAssignableSlow(0x97)
        C:/Program Files/Go/src/reflect/value.go:262 +0xbd
reflect.flag.mustBeAssignable(0x97)
        C:/Program Files/Go/src/reflect/value.go:249 +0x4e
reflect.Value.SetBytes({0xe71a20, 0xc0000a8ea0, 0x97}, {0xc00008c438, 0x3, 0x3})
        C:/Program Files/Go/src/reflect/value.go:2259 +0x3e
github.com/smallnest/rpcx/codec.ByteCodec.Decode({}, {0xc00008c438, 0x3, 0x3}, {0xe71a20, 0xc0000a8ea0})
        C:/Users/ZHANG/go/pkg/mod/github.com/smallnest/rpcx@v1.8.10/codec/codec.go:42 +0x9b
github.com/smallnest/rpcx/client.(*Client).input(0xc0000ce2a0)
        C:/Users/ZHANG/go/pkg/mod/github.com/smallnest/rpcx@v1.8.10/client/client.go:694 +0xbc4
created by github.com/smallnest/rpcx/client.(*Client).Connect
        C:/Users/ZHANG/go/pkg/mod/github.com/smallnest/rpcx@v1.8.10/client/connection.go:70 +0x94c

**Comment by smallnest** [comment]
看日志是你的client端代码调用的时候使用unaddressable值

**Comment by smallnest** [comment]
如果你是按照你最开始代码修改的，是没问题的，我测试过

**Comment by shinxiang** [comment]
问题已经解决了，谢谢！
