### ISSUE TITLE
plugins print all request log

### ISSUE THREAD

**Issue by BlackSinny** [smallnest/rpcx#818]
1. plugins receive request,get request begin time(t1)
2. run service code ...
3. plugins return request(t2)

## how i want to do
**rpcx** framework can print log contain duration[t2-t1],request body、url and so on...

## my guess
i used to achieve it in **gin middleware**,and i want to do it in rpcx plugins

**Comment by smallnest** [comment]
Maybe you should see https://github.com/smallnest/rpcx/blob/master/server/plugin.go and implement your plugins.

see some examples: 
https://github.com/rpcxio/rpcx-examples/tree/master/plugin
https://github.com/rpcxio/rpcx-examples/tree/master/plugin_blacklist
