### ISSUE TITLE
gogo/protobuf已经声明Deprecated了，是否可以考虑其它替代实现？

### ISSUE THREAD

**Issue by bmfmsd** [smallnest/rpcx#819]
还有go-ping也是相同情况

**Comment by bmfmsd** [comment]
还有go-ping

**Comment by smallnest** [comment]
rpcx并没有限定使用的pb的库，官方库、goog都可以，第三方的库也可以。

**Comment by smallnest** [comment]
go-ping刻录替换成 https://github.com/prometheus-community/pro-bing， 或者rpcx自己实现一个ping latency的库
