### ISSUE TITLE
server状态变更client无法感知

### ISSUE THREAD

**Issue by 275861756** [smallnest/rpcx#820]
option := client.DefaultOption
	option.Heartbeat = true
	option.HeartbeatInterval = time.Second
	d, _ := cclient.NewZookeeperDiscovery(*basePath, "Arith", []string{*zkAddr}, nil)
	xclient := client.NewXClient("Arith", client.Failover, client.RandomSelect, d, option)
	defer xclient.Close()

客户端启动后， 修改注册中心某个服务的 state为inactive后仍能一直受到请求。粗略看了代码，修改后，是没有重新加载注册中心的元数据的。
	github.com/rpcxio/libkv v0.5.1 // indirect
	github.com/rpcxio/rpcx-zookeeper v0.0.0-20220730061732-d20531677676 // indirect
		github.com/smallnest/rpcx v1.8.11
![image](https://github.com/smallnest/rpcx/assets/38198980/4814bc67-df99-4033-941c-66aee64fc874)

**Comment by smallnest** [comment]
rpcx-ui废弃了。
