### ISSUE TITLE
Method to add field

### ISSUE THREAD

**Issue by LeaklessGfy** [smallnest/rpcx#83]
Hello,

I would like to know if there's a function to add field on request of client already here or is it possible to have this feature ?

Because for now the call is exactly the same as rpc package =>
```
{ method: {method}, params: [ {args} ], id: {int} }
```

Thanks !

**Comment by smallnest** [comment]
simply to say, No.  Because we use the same requst to official rpc lib.

But you can hack it as I do it to implement Auth plugin.
Method is string type and you can marshal/unmarshal any types to set it as method field.
