### ISSUE TITLE
请问作者，如果在其它协程理出现错误，如何让serveConn循环结束，进而让server从activeConn删除此Conn 

### ISSUE THREAD

**Issue by blueskydata** [smallnest/rpcx#834]
如果在别的协程中执行processOneRequest出现错误，如对端已关闭，那么写操作肯定报错，您的代码中对写好像没做特殊处理，请问：
1、如果让serveConn函数感知到错误，并跳出循环；
2、如何让server，从容地从activeConn中删除conn；
3、如果防止conn多次关闭，比如出现一次错误关闭了，后面的协程执行再关闭怎么办。
谢谢作者。

**Comment by smallnest** [comment]
看serveConn, 处理连接异常。
可以加入QQ群，及时获得rpcx用户和开发者的支持

**Comment by blueskydata** [comment]
昨天已经申请加群了，请您通过一下啊
