### ISSUE TITLE
碰到空指针时， 服务会直接挂掉， 这个如何处理？

### ISSUE THREAD

**Issue by giter** [smallnest/rpcx#84]

**Comment by smallnest** [comment]
需要详细信息，或者简单的例子描述这个问题

**Comment by giter** [comment]
比如一般我们做webservice时， 碰到空指针的话， 服务端会返回500.
但如果用rpcx， 碰到空指针时会直接导致服务挂掉。

**Comment by smallnest** [comment]
你说的空指针是业务代码的空指针panic吧，你可以在服务的实现中通过cover避免。当然rpcx如果能提供统一的处理最好了，这个需要加强

**Comment by smallnest** [comment]
目前这一块的捕获逻辑还在官方net/rpc库中，所以这个特性需要在抽取官方库完成后才能实现。
