### ISSUE TITLE
C或C++怎么实现与rpcx客户端或服务端交互? 

### ISSUE THREAD

**Issue by holiray** [smallnest/rpcx#842]
项目介绍中有描述:
Theoretically it can be used with java, php, python, c/c++, node.js, c# and other platforms

实际应用中C或C++怎么实现与rpcx客户端或服务端交互,  是否有例程参考? 谢谢.

**Comment by smallnest** [comment]
目前其他语言还是主要通过http调用的方式访问rpcx 服务。

可以参考
https://doc.rpcx.io/part6/http_invoke.html
https://github.com/rpcxio/rpcx-examples/tree/master/http_invoke
