### ISSUE TITLE
关于go get tags的疑问

### ISSUE THREAD

**Issue by 369guang** [smallnest/rpcx#857]
版本: v1.8.31
指令：go get -u -v -tags "reuseport quic kcp zookeeper etcd consul ping" github.com/smallnest/rpcx/...
当我查看源码时发现并没有支持kcp或者quic，请问是我哪里搞错了吗？

文件路径：vendor/github.com/smallnest/rpcx/server/listener.go
![screenshot-20240531-143938](https://github.com/smallnest/rpcx/assets/17714241/8f710826-1560-4208-9251-f0fe8e156df5)

**Comment by smallnest** [comment]
在这个。你搜一下代码应该就搜出来啊
https://github.com/smallnest/rpcx/blob/master/server/kcp.go
