### ISSUE TITLE
Replace juju/ratelimit with time/rate

### ISSUE THREAD

**Issue by yfwz100** [smallnest/rpcx#860]
`juju/ratelimit` is LGPL and requires dynamically-linked for commercial products. It's better to replace `juju/ratelimit` with `golang.org/x/time/rate` (which is licensed under BSD license).

**Comment by smallnest** [comment]
juju/ratelimit is licensed with [LGPL v3 License](https://github.com/juju/ratelimit/commit/3e8ea27cbb171e619c6a88ca2c39ee8c5356b621) with the below exceptions:

> As a special exception to the GNU Lesser General Public License version 3
("LGPL3"), the copyright holders of this Library give you permission to
convey to a third party a Combined Work that links statically or dynamically
to this Library without providing any Minimal Corresponding Source or
Minimal Application Code as set out in 4d or providing the installation
information set out in section 4e, provided that you comply with the other
provisions of LGPL3 and provided that you meet, for the Application the
terms and conditions of the license(s) which apply to the Application.

Except as stated in this special exception, the provisions of LGPL3 will
continue to comply in full to this Library. If you modify this Library, you
may apply this exception to your version of this Library, but you are not
obliged to do so. If you do not wish to do so, delete this exception
statement from your version. This exception does not (and cannot) modify any
license terms which apply to the Application, with which you must still
comply.

So,  using it in Go programs is no problem

**Comment by yfwz100** [comment]
Ok, thanks for the reply!
