### ISSUE TITLE
Can we have error constants?

### ISSUE THREAD

**Issue by mikekonan** [smallnest/rpcx#871]
Hello,

As a user of the framework, I would like to perform type-checking on errors similar to how it's done in Go 1.13.

```
if errors.Is(err, ErrRPCService) {
}
```

Could we have error constants for scenarios like this? 

https://github.com/smallnest/rpcx/blob/master/server/service.go#L355
https://github.com/smallnest/rpcx/blob/master/server/service.go#L381
Thanks!

**Comment by smallnest** [comment]
defined a error type:
```go
type RpcServiceInternalError struct {
	Err    string
	Method string
	Argv   interface{}
	stack  string
}
```
