### ISSUE TITLE
是否考虑新增一个只关闭当前 Client 的方法

### ISSUE THREAD

**Issue by frankyzhu** [smallnest/rpcx#89]
目前 rpcx.Client 中的 [Close](https://github.com/smallnest/rpcx/blob/master/client.go#L149) 方法，每次都会关闭该 ClientSelector 下的全部 Client 。

**Comment by smallnest** [comment]
CloseCurrentClient的需求的目的是什么？想应用在什么场景下？

**Comment by frankyzhu** [comment]
最典型的应用场景就是 Client 端做了连接池：
如果当前 Client 调用失败了（比如 Server 不可用），那么就需要关闭这个 Client 。
另外，如果连接池已经满了，再放入 Client 时，需要扔掉这个 Client , 在这之前也需要做关闭处理。

**Comment by smallnest** [comment]
连接池中放入的是rpcx.Client，而不是底层的连接对象, 所以rpcx.Client调用失败后关闭的是它本身。
rpcx本身会处理单个连接失败的情况，每个ClientSelector都有HandleFailedClient方法，用来处理底层的rpc.Client失败的情况，典型地，会关闭这个连接，并且从池中删除这个连接。

所以说，rpcx本身会close底层的连接。

**Comment by frankyzhu** [comment]
是的，我之前可能没描述清楚，我所指的 Client 都是 rpcx.Client 。
我的应用场景大致如下：

```go
pool, err := NewClientPool(config, clientSelector) // create the *rpcx.Client pool

client := pool.Borrow() // get a *rpcx.Client from the pool

err = client.Call("Service.Api", args, &reply)
if err != nil {
	client.CloseSelf() // or call clientSelector.Close(client) whatever to close current client
} else {
    pool.Return(client) // returns a client to the pool, if the pool is filled up I also need to close the client before I throw it away
}
```

**Comment by smallnest** [comment]
1. 我觉得你不必考虑关闭底层的rpc.Client，因为rpcx.Client隐藏了底层rpc.Client的调用,以及失败处理。 

2. 如果底层的rpc.Client调用失败，它会自动关闭, 而它隶属的rpcx.Client依然保持着对其它服务节点的连接，所以你只管把rpcx.Client返回对象池中即可。

see:

https://github.com/smallnest/rpcx/blob/master/client.go#L178

3. 只有在你不想再使用rpcx.Client,才调用它的 Close方法，并且从对象池中移除即可。

4. rpcx.Client并没有current client的概念，因为一个底层的rpc.client可以被多个goroutine共享,同一时刻可能多个rpc.Client被多个goroutine使用
