### ISSUE TITLE
is there any plans to support other languages?

### ISSUE THREAD

**Issue by celeskyking** [smallnest/rpcx#9]

**Comment by smallnest** [comment]
so far it is NO. 
As introduced in the overview. there are two rpc styles：one is supporting crossing languages such as thrift and the other is for service governance such as Dubbo.

rpcx is based on go/rpc so it is more like Dubbo and Motan.

If there are some eager requirements in other companies, please tell me which language and client support or server support, I will consider implement it.

**Comment by celeskyking** [comment]
thanks for your answer.  
Now i am solving some problems that need cross language,  i'm very interested in your project because it can solve some of my problems, i wanna to extend myself about java implementation, thanks for your contribution.
