### ISSUE TITLE
提供服务编排的功能

### ISSUE THREAD

**Issue by zyanho** [smallnest/rpcx#91]
https://github.com/go-kit/kit  
也是一个golang的standard library for microservices
也是类似finagle、dubbo
也带服务发现，也带负载均衡

不知道rpcx跟gokit的区别或者性能上的对比如何？

**Comment by smallnest** [comment]
我觉得go-kit/kit为了实现一个服务要做的额外工作太多了，过于复杂，我不太欣赏这种风格，如果有人愿意提交相应的测试代码，我很乐意merge。测试代码可以参考 https://github.com/smallnest/rpcx/tree/master/_benchmarks 中实现的一些框架的测试代码。

从实现上看，go-kit/kit的transport可以为http，grpc和thrift。 从这种实现上看，它的性能基本类似grpc、thrift的性能。 http的transport可能性能会比较差。

**Comment by zyanho** [comment]
请问一下 rpcx有做服务编排，服务降级，服务治理的打算吗？

**Comment by smallnest** [comment]
目前rpcx已经支持。如果有特殊的编排和降级可以提需求。
可以看readme中的features,比如：
* Service dicovery. support ZooKeeper、Etcd.
* Fault tolerance：Failover、Failfast、Failtry.
* Load banlancer：support randomSelecter, RoundRobin, consistent hashing, etc.

服务降级支持两种:
1. 限速ratelimiting
2. 暂时不可用：通过rpcx-ui可以操作，或者调用api

**Comment by zyanho** [comment]
感谢你的工作，也就是说目前负载均衡，路由编排，失效切换都已经有了

再深入一步的，我所讲的服务编排类似这样的一个想法，请见谅 ：）

假设，我们做的service都是一个细颗粒的功能，现在有
A：查询库存
B：写入订单信息
C：写入账单信息
D：付款

而A、B、C、D组合起来是一个“下单”业务，他是一个粗颗粒的，类似一个API网关，可被客户端直接调用的，客户端不感知里面有A、B、C、D四件事情的发生。

这4件事情如果要避免硬编码，就会涉及到一些入参出参，顺序，分支，异常，并行，幂等，等行为的规定，匹配，整个过程应该是动态的，拖动的，可直接操作调整的。
也会涉及到一些补偿机制，去保障最终一致性。

不知道rpcx有没考虑往这个方向去扩展的可能？

**Comment by smallnest** [comment]
这看起来是一个复杂的服务编排的功能。 将各种微服务(A,B,C,D)基于定义的规则进行编排提供一个"下单"服务。

这看起来很有趣，我会关注这个功能，目前看起来似乎单独创建一个服务编排的项目更合适。

**Comment by smallnest** [comment]
目前没雨计划去实现
