### ISSUE TITLE
rpcx的异步通信机制是否支持failover方式？

### ISSUE THREAD

**Issue by thou** [smallnest/rpcx#94]
异步方式，client通过client.Go()访问2台server；
同步方式，client通过client.Call()访问2台server；

设置：client.FailMode = rpcx.Failover

当一台server当掉后，同步方式可以切换到另外一台，而异步不能。

**Comment by smallnest** [comment]
目前异步不支持其他的重试方式。

不过这个可以作为待实现的特性。

如果一台Server当掉，目前异步模式下客户端只能依赖服务发现的方式知晓服务器宕机。

**Comment by thou** [comment]
就是说目前rpcx的异步工作方式，还不支持failover的自动切换，依赖于使用rpcx的应用程序去发现服务是否可用？

**Comment by smallnest** [comment]
对，和你理解的一样。
